<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\War.Shared\War.Shared.csproj" />
    <ProjectReference Include="..\War.Persistence\War.Persistence.csproj" />
    <ProjectReference Include="..\War.Infrastructure\War.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
