"""Source evidence inventory; action references do not imply implementation."""
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
ASSETS=ROOT/'Clients/ExportedProject/Assets'
GAME=ASSETS/'Scripts/Assembly-CSharp'
OUT=ROOT/'Server/docs'
OUT.mkdir(exist_ok=True)
sources={p:p.read_text(encoding='utf-8-sig') for p in GAME.rglob('*.cs')}
actions={name:int(value) for name,value in re.findall(r'^\s*(\w+)\s*=\s*(\d+)',sources[GAME/'DatabaseAction.cs'],re.M)}
calls={name:[] for name in actions}
rpcs=[];rpc_calls=[];serialize=[];photon_files=[];http_fields=[]
for path,text in sources.items():
    rel=path.relative_to(ROOT).as_posix()
    if re.search(r'\b(?:PhotonNetwork|PhotonView|PhotonStream|PhotonPlayer|PhotonMessageInfo|PhotonTargets)\b',text):photon_files.append(rel)
    for match in re.finditer(r'\bDatabaseAction\.(\w+)',text):
        if match[1] in calls:calls[match[1]].append({'file':rel,'line':text.count('\n',0,match.start())+1})
    for match in re.finditer(r'\[(?:PunRPC|RPC)\]\s*((?:(?:public|private|protected|internal|virtual|override|static|sealed)\s+)*[\w<>\[\],]+\s+(\w+)\s*\([^)]*\))',text):
        rpcs.append({'file':rel,'line':text.count('\n',0,match.start())+1,'name':match[2],'signature':match[1]})
    for match in re.finditer(r'\.RPC\(\s*"([^"]+)"',text):rpc_calls.append({'file':rel,'line':text.count('\n',0,match.start())+1,'name':match[1]})
    for match in re.finditer(r'\bOnPhotonSerializeView\s*\(',text):serialize.append({'file':rel,'line':text.count('\n',0,match.start())+1})
    if path.name=='BeanstalkServerManager.cs':
        for match in re.finditer(r'new Tuple<string, string>\("([^"]+)"|\.AddField\("([^"]+)"',text):http_fields.append({'field':match[1] or match[2],'line':text.count('\n',0,match.start())+1})
response_keys=sorted(set(re.findall(r'mResponse\["([^"]+)"\]',sources[GAME/'ServerResponseHandler.cs'])))
guid=re.search(r'guid: (\w+)',(ASSETS/'Plugins/Assembly-CSharp-firstpass/PhotonView.cs.meta').read_text())[1]
attachments=[]
for path in ASSETS.rglob('*'):
    if path.suffix not in {'.unity','.prefab'}:continue
    count=path.read_text(encoding='utf-8-sig').count('guid: '+guid)
    if count:attachments.append({'file':path.relative_to(ROOT).as_posix(),'count':count})
def methods(text):
    pattern=r'^\t(?:(?:public|private|protected|internal|static|override|virtual|sealed|async)\s+)+[\w<>,.?\[\]]+\s+(\w+)\([^\n]*\)'
    matches=list(re.finditer(pattern,text,re.M))
    return [(m[1],text.count('\n',0,m.start())+1,text[m.start():matches[i+1].start() if i+1<len(matches) else len(text)]) for i,m in enumerate(matches)]
builders=[]
for name,line,body in methods(sources[GAME/'BeanstalkServerManager.cs']):
    sent=sorted(set(re.findall(r'CreateServerRequest\(DatabaseAction\.(\w+)',body)))
    if sent:
        builders.append(dict(method=name,line=line,actions=sent,fieldCandidates=sorted(set(re.findall(r'new Tuple<string, string>\("([^"]+)"',body)))))
handlers=[]
for name,line,body in methods(sources[GAME/'ServerResponseHandler.cs']):
    keys=sorted(set(re.findall(r'mResponse\["([^"]+)"\]',body)))
    if keys:handlers.append(dict(method=name,line=line,directResponseKeys=keys))
report={'client':'1.4.0','actionCount':len(actions),'actions':[dict(name=n,id=i,references=calls[n]) for n,i in sorted(actions.items(),key=lambda x:x[1])],
        'directRequestBuilders':builders,'responseHandlerMethods':handlers,
        'httpFieldOccurrences':http_fields,'responseKeys':response_keys,'rpcDefinitions':rpcs,'rpcLiteralCalls':rpc_calls,'serializeOccurrences':serialize,'photonGameplayFiles':photon_files,'photonViewAttachments':attachments,
        'sourceDigests':{p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in [GAME/'DatabaseAction.cs',GAME/'BeanstalkServerManager.cs',GAME/'ServerResponseHandler.cs',GAME/'PhotonConnectionManager.cs',GAME/'RequestBuffer.cs',GAME/'CustomTypes.cs']}}
(OUT/'client-communication-inventory.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
lines=['# Recovered 1.4.0 action inventory','', 'Generated by `python Server/tools/inventory_client.py`. References include consumers and enum comparisons; they do not prove server implementation.','', '| ID | Recovered name | Source references |','|---:|---|---:|']
lines += [f'| {i} | {n} | {len(calls[n])} |' for n,i in sorted(actions.items(),key=lambda x:x[1])]
(OUT/'LEGACY_ACTIONS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps(dict(actions=len(actions),rpcDefinitions=len(rpcs),rpcLiteralCalls=len(rpc_calls),serializationOccurrences=len(serialize),photonGameplayFiles=len(photon_files),photonViewAttachments=sum(x['count'] for x in attachments),responseKeys=len(response_keys)),indent=2))
