using UnityEngine;

public class ActiveUnitsCategoriesIndicator : Core_BaseScript
{
	[Header("Left Side")]
	public UISprite NKJLNMGKAFL;

	public UISprite OAHNFICFNFK;

	public UISprite BCBLCNOKGAP;

	[Header("Center")]
	public UISprite PADFLEPAOAK;

	[Header("Right Side")]
	public UISprite AIDOOKGKCBF;

	public UISprite FIKHDGOCBLK;

	public UISprite KEEFMICIDNI;

	private LevelBehaviour.UnitType BCBKHONHNJE;

	public void KOEBOGHPHIA(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 1979f, PADFLEPAOAK.transform.localScale.y * 1708f, 220f);
		EDAHNEHMNDN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		BOEPNABLAIK(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	public void BJKFEJNAMGK(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HCLGJAIEFLB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			ALFJLCCHMBF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			JCDGFLCFHJB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			MJFHAEIFKLN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JIFEFBILDKC(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GKGCINPJIHI(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void NDIJBPIDGOF(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 527f, PADFLEPAOAK.transform.localScale.y * 6f, 1791f);
		MJFHAEIFKLN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		BOEPNABLAIK(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	public void KCJFKOKGAMO(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 168f, PADFLEPAOAK.transform.localScale.y * 869f, 1206f);
		HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		BKIHMKELADJ(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void GKGCINPJIHI(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void NIAPHKPJKMP(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void NJPBFJFKAPE(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void MIFGOKPFDAN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void KCGOHFDFCEO(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void GLDADDPEHFP(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void MJFHAEIFKLN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void ACBHGJCMCPG(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 772f, PADFLEPAOAK.transform.localScale.y * 255f, 40f);
		PBCDMACJADG(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		BKIHMKELADJ(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void HHFKGOJKDKO(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void FHAHOJCHLPL(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void GJIIMJDFCNO(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			PMGPDEOJGFL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			MIFGOKPFDAN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			BHJFBCBAGPN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			OGDMJKAIGDO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JIFEFBILDKC(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			FHAHOJCHLPL(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void PBCDMACJADG(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void LIMIFKFNNLA(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 1761f, PADFLEPAOAK.transform.localScale.y * 209f, 630f);
		PBCDMACJADG(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		HHFKGOJKDKO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void AHCANGMCAOA(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void NFKAHPJOPAI(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			BKIHMKELADJ(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			GLDADDPEHFP(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			NIAPHKPJKMP(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			AHCANGMCAOA(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JELOLBFENOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GDLOGAFHGDF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void JIFEFBILDKC(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void EKBICJIINJP(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HCLGJAIEFLB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			MIFGOKPFDAN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			EIPCJCMMKAL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			KCGOHFDFCEO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			ALFJLCCHMBF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			BHJFBCBAGPN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void MDEPEPPBKJN(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			PMGPDEOJGFL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			JIFEFBILDKC(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			FHAHOJCHLPL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			PBCDMACJADG(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			ALFJLCCHMBF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GDLOGAFHGDF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void AJEGOKKKLOL(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 1290f, PADFLEPAOAK.transform.localScale.y * 1466f, 139f);
		BOEPNABLAIK(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		AHCANGMCAOA(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void EIPCJCMMKAL(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void GHFHNLNHCFC(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 997f, PADFLEPAOAK.transform.localScale.y * 160f, 1096f);
		BOEPNABLAIK(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		KCGOHFDFCEO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void PMGPDEOJGFL(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void GPIIHMKONIE(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			BOEPNABLAIK(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			JIFEFBILDKC(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			EIPCJCMMKAL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			MJFHAEIFKLN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			MIFGOKPFDAN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			EMAODCIJAOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void EDAHNEHMNDN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void IOJFOPCOKAF(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void AGJHKFMMCIA(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			MFNMPIEIBLN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			JCDGFLCFHJB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			KCGOHFDFCEO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			GLDADDPEHFP(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GDLOGAFHGDF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void BHJFBCBAGPN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void DCKOKFJNOPN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void ONMBGACBEND(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void DKCNBOACONG(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			DLBHADMACFM(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			GLDADDPEHFP(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			FHAHOJCHLPL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			ONMBGACBEND(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			MIFGOKPFDAN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			BHJFBCBAGPN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void JOMAEDAGMKN(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			DLBHADMACFM(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			GLDADDPEHFP(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			GDLOGAFHGDF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			AHCANGMCAOA(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			MFNMPIEIBLN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			EMAODCIJAOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void FEFKMMJEHJM(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void GDLOGAFHGDF(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void OABBPAMLADC(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void OGDMJKAIGDO(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	private void ALFJLCCHMBF(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void HCFPABNMHMJ(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			BKIHMKELADJ(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			MIFGOKPFDAN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			FHAHOJCHLPL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			BOEPNABLAIK(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JELOLBFENOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			JKFFLLJOMPH(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void Initialize(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 0.5f, PADFLEPAOAK.transform.localScale.y * 0.5f, 1f);
		PMGPDEOJGFL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		PMGPDEOJGFL(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	private void BOEPNABLAIK(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void NOFPGNOFMMD(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			BKIHMKELADJ(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			JIFEFBILDKC(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			NIAPHKPJKMP(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			ONMBGACBEND(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JIFEFBILDKC(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			BHJFBCBAGPN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void EMAODCIJAOO(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void HNNPLBKAPAK(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			KCGOHFDFCEO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			ALFJLCCHMBF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			EMAODCIJAOO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			HHFKGOJKDKO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JIFEFBILDKC(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			JCDGFLCFHJB(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void JELOLBFENOO(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void AIHNDOIMPGA(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HCLGJAIEFLB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			ALFJLCCHMBF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			DCKOKFJNOPN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			HCLGJAIEFLB(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			GLDADDPEHFP(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			BHJFBCBAGPN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void BKIHMKELADJ(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void MMKEEBKDKLG(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 163f, PADFLEPAOAK.transform.localScale.y * 969f, 1500f);
		DLBHADMACFM(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		HCLGJAIEFLB(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	public void JLOCEJAIHIA(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			ALFJLCCHMBF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			DCKOKFJNOPN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			HCLGJAIEFLB(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JELOLBFENOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GDLOGAFHGDF(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void MKJEIOOINBP(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HCLGJAIEFLB(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			NJPBFJFKAPE(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			JKFFLLJOMPH(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			ONMBGACBEND(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			NJPBFJFKAPE(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			BHJFBCBAGPN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void DGBLPBDDKJM(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void MADKFJMELKO(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			MFNMPIEIBLN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			DCKOKFJNOPN(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			MJFHAEIFKLN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JELOLBFENOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			GKGCINPJIHI(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void JKFFLLJOMPH(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void MFNMPIEIBLN(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(true);
	}

	public void IGPOLIPPGBP(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 1788f, PADFLEPAOAK.transform.localScale.y * 379f, 1888f);
		DLBHADMACFM(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		AHCANGMCAOA(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}

	public void CCJPOJLIJPD(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			JIFEFBILDKC(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			JKFFLLJOMPH(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			BKIHMKELADJ(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			NJPBFJFKAPE(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			FHAHOJCHLPL(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void DLBHADMACFM(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	private void JCDGFLCFHJB(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		MBMIOELEAND.color = Color.white;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void BMPDGNBAAFO(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			HHFKGOJKDKO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			ALFJLCCHMBF(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			EMAODCIJAOO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			MJFHAEIFKLN(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			GLDADDPEHFP(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			JKFFLLJOMPH(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	private void HCLGJAIEFLB(UISprite KMFGCJEGJJK, UISprite MBMIOELEAND, UISprite LBBHCGDEBCE)
	{
		KMFGCJEGJJK.color = Color.black;
		MBMIOELEAND.color = GameVariables.CNFFEIMLDNP[BCBKHONHNJE].Value2;
		LBBHCGDEBCE.gameObject.SetActive(false);
	}

	public void SetUnits(LevelBehaviour INGHMGFIJBL, LevelBehaviour AEGKHCMGFNH)
	{
		if (INGHMGFIJBL == null)
		{
			PMGPDEOJGFL(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else if (INGHMGFIJBL.isSoldier)
		{
			JELOLBFENOO(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		else
		{
			DGBLPBDDKJM(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		}
		if (AEGKHCMGFNH == null)
		{
			PMGPDEOJGFL(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else if (AEGKHCMGFNH.isSoldier)
		{
			JELOLBFENOO(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
		else
		{
			DGBLPBDDKJM(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
		}
	}

	public void MFMJPBCIHEH(LevelBehaviour.UnitType PMKOFALJMOP)
	{
		BCBKHONHNJE = PMKOFALJMOP;
		PADFLEPAOAK.spriteName = GameVariables.CNFFEIMLDNP[PMKOFALJMOP].Value1;
		PADFLEPAOAK.MakePixelPerfect();
		PADFLEPAOAK.transform.localScale = new Vector3(PADFLEPAOAK.transform.localScale.x * 1831f, PADFLEPAOAK.transform.localScale.y * 1775f, 527f);
		PBCDMACJADG(NKJLNMGKAFL, OAHNFICFNFK, BCBLCNOKGAP);
		BKIHMKELADJ(AIDOOKGKCBF, FIKHDGOCBLK, KEEFMICIDNI);
	}
}
