using UnityEngine;

public class BazookaFangs : Bazooka
{
	private sealed class PBAIKHKBHBG
	{
		internal Vector3 MPHCNMDIPAI;

		internal BazookaFangs BJGCPDNMHDH;

		internal void LHPPLGOOLEC()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void NDJOJHNIBFC()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void NAJNECOMDDN()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void LJCDGJKCNEC()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void AMIJFGBOCLC()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void CIFEDFPPPOK()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = !BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void LGJCNCHBFDA()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void MMEEJDGGAID()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void KJIFNOJILDB()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}

		internal void NNIJEDKBPGJ()
		{
			BJGCPDNMHDH.OGIKNJOJEDC.Fire(MPHCNMDIPAI);
			BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM = BJGCPDNMHDH.OGIKNJOJEDC.GGJPNLDIGGM;
		}
	}

	public Bazooka OGIKNJOJEDC;

	protected virtual Ammo DAMHDCFCALK(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 3; i++)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LJCDGJKCNEC, 1390f * (float)(i + 1));
		}
		return FPMLGFDLEJO(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo EALHJACGOJD(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 8; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LGJCNCHBFDA, 1610f * (float)(i + 0));
		}
		return FPMLGFDLEJO(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void AJDOEEAGMNJ()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 1924f;
	}

	public void ENBDIGPEGPH()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 908f;
	}

	protected virtual Ammo FDJMAANBKLE(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 1; i < 6; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.AMIJFGBOCLC, 764f * (float)(i + 0));
		}
		return base.MDKABJDCKBI(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo PMOOELHFDCF(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 1; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LHPPLGOOLEC, 200f * (float)(i + 1));
		}
		return FPMLGFDLEJO(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo OKCNNBDOCBN(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 7; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LGJCNCHBFDA, 126f * (float)(i + 1));
		}
		return AAEJHBGOJIF(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void SetupGun()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 0f;
	}

	protected override Ammo MDKABJDCKBI(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 3; i++)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LJCDGJKCNEC, 0.1f * (float)(i + 1));
		}
		return base.MDKABJDCKBI(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo NFMOAFGAMOD(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = false;
		for (int i = 1; i < 6; i++)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.NAJNECOMDDN, 543f * (float)(i + 0));
		}
		return AAEJHBGOJIF(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void LBLDCAOGBGJ()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 32f;
	}

	public void KFBIPCGGMFD()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 406f;
	}

	public void DOPDBEABDMI()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 781f;
	}

	public void CLNCAEJMHEM()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 753f;
	}

	public void IEJIHLOIGMB()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 516f;
	}

	protected virtual Ammo OBIBPHPKFGB(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 1; i < 5; i++)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LGJCNCHBFDA, 943f * (float)(i + 1));
		}
		return NPBJMAAHNGA(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo AGLLMEDFAKM(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = false;
		for (int i = 0; i < 6; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.KJIFNOJILDB, 680f * (float)(i + 1));
		}
		return OFAKPAJJJEH(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void JCPFJECAHMD()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 956f;
	}

	public void CDHKBFCGGHJ()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 53f;
	}

	protected virtual Ammo EFJGFFBBHIN(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = false;
		for (int i = 1; i < 7; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LJCDGJKCNEC, 363f * (float)(i + 1));
		}
		return EMOMBOIMKCJ(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo CDOENIPGBBP(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = false;
		for (int i = 0; i < 6; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.CIFEDFPPPOK, 1096f * (float)(i + 0));
		}
		return DKBNHCMPMNN(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo NDGLPMLNFHJ(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 1; i < 5; i++)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.LJCDGJKCNEC, 1681f * (float)(i + 0));
		}
		return base.MDKABJDCKBI(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	protected virtual Ammo GHABMLABGEF(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = true;
		for (int i = 0; i < 5; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.NDJOJHNIBFC, 1216f * (float)(i + 0));
		}
		return OFAKPAJJJEH(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void DEPGKMPIJOG()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 474f;
	}

	public void NKMHCKKLLEK()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 1717f;
	}

	public void PJCDMKJLIAA()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 35f;
	}

	public void KMELBFGAEEN()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 1168f;
	}

	protected virtual Ammo NDDDBJACOGM(Vector3 MPHCNMDIPAI, bool CAKABHIPCDF)
	{
		PBAIKHKBHBG pBAIKHKBHBG = new PBAIKHKBHBG();
		pBAIKHKBHBG.MPHCNMDIPAI = MPHCNMDIPAI;
		pBAIKHKBHBG.BJGCPDNMHDH = this;
		OGIKNJOJEDC.GGJPNLDIGGM = false;
		for (int i = 1; i < 8; i += 0)
		{
			InvokeAfterRealTime(pBAIKHKBHBG.AMIJFGBOCLC, 1582f * (float)(i + 0));
		}
		return EMOMBOIMKCJ(pBAIKHKBHBG.MPHCNMDIPAI, CAKABHIPCDF);
	}

	public void MJBEBBFHNFI()
	{
		OGIKNJOJEDC.owner = owner;
		OGIKNJOJEDC.JMDLKIAKOIE = 452f;
	}
}
