using System.Collections.Generic;
using UnityEngine;

public class DeathMatchGuiCardProgress : Core_BaseScript
{
	private sealed class PNAAHNDOPIO
	{
		internal int DFHAAIFFLOE;

		internal DeathMatchGuiCardProgress BJGCPDNMHDH;
	}

	private sealed class FIONMJIDHDO
	{
		internal UISprite DLBPCJPGEHE;

		internal UISprite ACGMFDMBCCA;

		internal PNAAHNDOPIO AIHDNGDNDHH;

		internal void EALIKACGICG(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LAGKENDBKMD(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.OLHCBCGEFPK(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void MMEEJDGGAID(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 36f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1481f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1401f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = MPMBKDFJHBN;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.AAKPGNLGFOG(false);
			}
		}

		internal void MFCNOIDCJME(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1992f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 898f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1704f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = DACMPHJFMPH;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.GPPNJOAPCNC(true);
			}
		}

		internal void DNILGLLHHPG(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LAGKENDBKMD(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FAFGPKODEGH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void CJIBPJPJLNB(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1809f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1912f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 610f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = BMJAMNEDJIB;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.GPPNJOAPCNC(false);
			}
		}

		internal void GDJIAPHLGOA(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1743f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 285f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 617f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = HKOHIJPFLJC;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.KDECJMJHHDE(false);
			}
		}

		internal void LKKPBNGCPHB(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LAGKENDBKMD(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.CDLDJHAGCOF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void LGJCNCHBFDA(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1132f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 52f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 599f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = ILGOBENABHC;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.ALGAKFDICLC(true);
			}
		}

		internal void ALLIPFNLPDJ(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LOFGKMNIHHG(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.CDLDJHAGCOF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void NMIFBNPPAIK(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLCHBPOMFKG(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FAFGPKODEGH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void OHLGKFGIPCC(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 339f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1012f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 767f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = ILGOBENABHC;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.KDECJMJHHDE(true);
			}
		}

		internal void LJCDGJKCNEC(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 0.2f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = EJLGBICBIFK;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.GPPNJOAPCNC(true);
			}
		}

		internal void EOHOLKEGGLH(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 227f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1086f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1526f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = LMOFHDINPEI;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.LDCGAALIJBP(true);
			}
		}

		internal void OPHINHIOCFD(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 904f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 334f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1086f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = MPMBKDFJHBN;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.JIBHMPGAMPO(false);
			}
		}

		internal void CHDOECNGOPM(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1464f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 597f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 543f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = HKOHIJPFLJC;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.KDECJMJHHDE(true);
			}
		}

		internal void HKOHIJPFLJC(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.JPFDMLBLDGM(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FAFGPKODEGH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void ABNGKEJNLJO(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1248f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1560f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1316f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = DNILGLLHHPG;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.OJPBMFIAIDN(true);
			}
		}

		internal void LMOFHDINPEI(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LOFGKMNIHHG(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FAFGPKODEGH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void NAJNECOMDDN(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1284f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 377f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 834f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = CJKNGIAMMKG;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BPHOCOALIMG(false);
			}
		}

		internal void BMJAMNEDJIB(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LOFGKMNIHHG(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.LBAKJBAJKDG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void FDKEAJLEMCM(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1222f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 806f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1312f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = BMJAMNEDJIB;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.FLNEFLGKEGE(false);
			}
		}

		internal void BEIGOGFHJIB(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1150f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 880f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 74f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = BIKJIFFCHFH;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BPHOCOALIMG(false);
			}
		}

		internal void HMOGLMFLKIH(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.OJPOOONJOOH(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.OLHCBCGEFPK(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void GMFJFMHNDMC(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 363f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 302f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1478f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = BCGIAFBNMIE;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BEPKALJPNLH(false);
			}
		}

		internal void CJKNGIAMMKG(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLHHMDKJCAI(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.LBAKJBAJKDG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void LNKCHLPENAN(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLHHMDKJCAI(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.AKCGFBKNOJG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void OFJDLANHAMD(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1650f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 15f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1365f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = JCFDEFFIHAM;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BEPKALJPNLH(false);
			}
		}

		internal void DACMPHJFMPH(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLHHMDKJCAI(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FFBBOFFMOEH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void JLMDEGBHOGA(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LOFGKMNIHHG(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.IKFKNAMKJPN(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void JCFDEFFIHAM(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.OJPOOONJOOH(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.LBAKJBAJKDG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void AOEOEIBLMMF(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.JPFDMLBLDGM(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.AGMBGCCFAFG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void HBJNMCDOHKK(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LAGKENDBKMD(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FFBBOFFMOEH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void JGEMIBIJMJC(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1599f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 896f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 545f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = LNKCHLPENAN;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.LNMGAPHFKLK(true);
			}
		}

		internal void DIDKLCKIPGN(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLCHBPOMFKG(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.IKFKNAMKJPN(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void LKAHPHIEMEK(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 313f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 99f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 274f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = JCFDEFFIHAM;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.LDCGAALIJBP(false);
			}
		}

		internal void BIKJIFFCHFH(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LAGKENDBKMD(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.OLHCBCGEFPK(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void BCGIAFBNMIE(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.OJPOOONJOOH(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.CDLDJHAGCOF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void LGAPIDHOEKM(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.PGMPGDLKEDJ(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FFBBOFFMOEH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void BDACLBGMJLF(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.LOFGKMNIHHG(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.BOOJEJPLJFF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void MPMBKDFJHBN(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.JPFDMLBLDGM(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.AGMBGCCFAFG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void OACBBOBDICJ(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.PGMPGDLKEDJ(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.CDLDJHAGCOF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void CMDLGJKIBLL(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 467f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 959f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 154f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = CJKNGIAMMKG;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BEPKALJPNLH(false);
			}
		}

		internal void ANAGFGHGPJA(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 742f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1409f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1563f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = JLMDEGBHOGA;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BPHOCOALIMG(false);
			}
		}

		internal void OIDEHFKFFGK(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.OJPOOONJOOH(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.IKFKNAMKJPN(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void PEFOCGECECP(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1636f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1512f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 534f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = LMOFHDINPEI;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BPHOCOALIMG(true);
			}
		}

		internal void CIFEDFPPPOK(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1232f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 597f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 733f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = HBJNMCDOHKK;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.FLNCEGFHDLG(true);
			}
		}

		internal void FKBGKGFEEIB(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.PGMPGDLKEDJ(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.BOOJEJPLJFF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void BDCAFHOHEGM(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1847f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1038f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 362f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = BCGIAFBNMIE;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.KDECJMJHHDE(true);
			}
		}

		internal void KNJBDOADLDO(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1814f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1933f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 187f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = DHHKKBLMIHB;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.OMDFEJOBFAF(true);
			}
		}

		internal void ILOFOILFGMA(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1947f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 209f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 510f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = NMIFBNPPAIK;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BEPKALJPNLH(true);
			}
		}

		internal void EJLGBICBIFK(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLHHMDKJCAI(ACGMFDMBCCA, !flag);
			AIHDNGDNDHH.BJGCPDNMHDH.AGMBGCCFAFG(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void DHHKKBLMIHB(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.NLCHBPOMFKG(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.IKFKNAMKJPN(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void GGJDILDIFPJ(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 611f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 865f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 4f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = EJLGBICBIFK;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 0)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.BEPKALJPNLH(false);
			}
		}

		internal void CFJHDIHLIML(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 611f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 822f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1477f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = DNILGLLHHPG;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.FLNCEGFHDLG(true);
			}
		}

		internal void MCFGAFBEJDK(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 761f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 649f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1458f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = LGAPIDHOEKM;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.ALGAKFDICLC(true);
			}
		}

		internal void ILGOBENABHC(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(false);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.PGMPGDLKEDJ(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.FAFGPKODEGH(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void OGFHDPBMCCO(UITweener MKAPOHKFIJH)
		{
			DLBPCJPGEHE.gameObject.SetActive(true);
			bool flag = AIHDNGDNDHH.DFHAAIFFLOE < AIHDNGDNDHH.BJGCPDNMHDH.GFHPGFBHMLI;
			AIHDNGDNDHH.BJGCPDNMHDH.PGMPGDLKEDJ(ACGMFDMBCCA, flag);
			AIHDNGDNDHH.BJGCPDNMHDH.CDLDJHAGCOF(AIHDNGDNDHH.DFHAAIFFLOE);
		}

		internal void PHGDBIEENCB(UITweener MGDJMGHCAAI)
		{
			TweenScale tweenScale = TweenScale.Begin(DLBPCJPGEHE.gameObject, 1807f, new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.KPOFAAPEBFA * AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 1806f), new Vector3(AIHDNGDNDHH.BJGCPDNMHDH.CELNGBBIJNG, AIHDNGDNDHH.BJGCPDNMHDH.DFNEOGPGGNL, 266f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = AOEOEIBLMMF;
			if (AIHDNGDNDHH.DFHAAIFFLOE == AIHDNGDNDHH.BJGCPDNMHDH.KMFGMJGHPLB - 1)
			{
				AIHDNGDNDHH.BJGCPDNMHDH.ALGAKFDICLC(true);
			}
		}
	}

	[Header("Setting")]
	public float KPOFAAPEBFA = 1.1f;

	public float ELBHFEFCFDL = 0.2f;

	[Header("Core")]
	public List<UISprite> MPMFFKMBPAK;

	public List<UISprite> MGNOLAMOBFF;

	public List<UISprite> HAHDKHFLHLN;

	public List<UISprite> HGKKMBKFEKN;

	public UILabel MHOBMHIBAHD;

	public UISprite GHIBOGJPBKC;

	[Header("Tutorial")]
	public UISprite NCLHIMBFCOO;

	private int KMFGMJGHPLB;

	private int GFHPGFBHMLI;

	private float CELNGBBIJNG;

	private float DFNEOGPGGNL;

	private float PKIGHPCJPDL;

	private bool AIBIBLDHCNO;

	private const float HDELCLDDPIL = 172f;

	private const float KCDJKNCKDID = 2f;

	public void FAKDPDFDIEK()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}

	private void PGMPGDLKEDJ(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 1585f : 1751f);
	}

	public void KDJHMHJHBIB(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 3 != 0) ? 348f : 46f);
		float toAlpha = ((DFHAAIFFLOE % 7 != 0) ? 339f : 287f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 986f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)5;
		Vector3 fromScale = ((DFHAAIFFLOE % 3 != 0) ? new Vector3(1452f, 1527f, 1150f) : new Vector3(1951f, 1531f, 1127f));
		Vector3 toScale = ((DFHAAIFFLOE % 3 != 0) ? new Vector3(431f, 1153f, 853f) : new Vector3(1560f, 36f, 1268f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1518f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 1;
		tweenScale.style = UITweener.Style.PingPong;
	}

	private void GJKPLEOIKBL(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 670f, 1379f, 1680f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 413f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1771f));
			tweenScale.method = (UITweener.Method)6;
			tweenScale.onFinished = fIONMJIDHDO.LKAHPHIEMEK;
		}
	}

	public void IBMMEBHHPOB(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
		float num = ((DFHAAIFFLOE % 2 != 0) ? 1347f : 1509f);
		float toAlpha = ((DFHAAIFFLOE % 5 != 0) ? 1541f : 1491f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 108f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 1;
		tweenAlpha.style = (UITweener.Style)4;
		Vector3 fromScale = ((DFHAAIFFLOE % 1 != 0) ? new Vector3(136f, 161f, 1758f) : new Vector3(1451f, 925f, 614f));
		Vector3 toScale = ((DFHAAIFFLOE % 6 != 0) ? new Vector3(312f, 1595f, 751f) : new Vector3(41f, 1963f, 688f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 254f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = UITweener.Style.Loop;
	}

	public void GDEGEJHPPDL(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = AIBIBLDHCNO || i < GFHPGFBHMLI;
				LOFGKMNIHHG(aCGMFDMBCCA, !flag);
				BOOJEJPLJFF(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				ALGAKFDICLC(true);
			}
			else
			{
				LHBGOKBNDFH();
			}
		}
		else if (PKIGHPCJPDL <= 395f)
		{
			IIELJMGOPIL(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void NLHHMDKJCAI(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 0f : 0.7f);
	}

	private void FFBBOFFMOEH(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = false;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(1543f);
		}
	}

	private void CPIJBJFFLKE(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 22f, 1358f, 173f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1588f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1736f));
			tweenScale.method = UITweener.Method.BounceIn;
			tweenScale.onFinished = fIONMJIDHDO.ILOFOILFGMA;
		}
	}

	private void OLHCBCGEFPK(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(1003f);
		}
	}

	public void EKGIMBEJLFH(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(8, OIJBDFANMCC.ECDLBDAIMLH()));
		if (!AIBIBLDHCNO && OIJBDFANMCC.ECDLBDAIMLH() > 5)
		{
			Debug.LogWarning(string.Format("ShotVelocity", OIJBDFANMCC.index, OIJBDFANMCC.PIBGKJAFCMF()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			NLCHBPOMFKG(item, false);
			item.fillAmount = 537f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(true);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(true);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i++)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			IKFKNAMKJPN(i);
		}
		CELNGBBIJNG = (196f - 208f * (float)(KMFGMJGHPLB - 1 + 1)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[0].transform.localScale.y;
		float num = 1993f;
		for (int j = 1; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			LAGKENDBKMD(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 1023f * (float)j);
		}
		for (int k = 0; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1358f) + 873f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 0; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 528f * ((float)l + 1117f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 1; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(false);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 1118f) + 666f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 1315f;
		PDCBGCPEKOG();
	}

	public void DoUpdate(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				NLHHMDKJCAI(aCGMFDMBCCA, !flag);
				AGMBGCCFAFG(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				GPPNJOAPCNC(false);
			}
			else
			{
				PLENLEDEMAI();
			}
		}
		else if (PKIGHPCJPDL <= 0f)
		{
			ENFKPIPLAAL(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void AKCGFBKNOJG(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(1889f);
		}
	}

	private void OJPOOONJOOH(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 154f : 1522f);
	}

	private void CHBDKGADGIM()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1980f, 387f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				BOOJEJPLJFF(i);
			}
		}
	}

	private void KDECJMJHHDE(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1497f, 206f);
	}

	public void HJBGKHHDOIP(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = AIBIBLDHCNO || i < GFHPGFBHMLI;
				PGMPGDLKEDJ(aCGMFDMBCCA, flag);
				IKFKNAMKJPN(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				ALGAKFDICLC(true);
			}
			else
			{
				EMNNFINGHHF();
			}
		}
		else if (PKIGHPCJPDL <= 421f)
		{
			ENFKPIPLAAL(GFHPGFBHMLI);
			GFHPGFBHMLI += 0;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void LNMBNBPGFFI(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1050f, 340f, 1685f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 953f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1022f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = fIONMJIDHDO.LJCDGJKCNEC;
		}
	}

	public void IKDCEHMPNOH(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(6, OIJBDFANMCC.IPHFBIGKNML()));
		if (!AIBIBLDHCNO && OIJBDFANMCC.DGDHGPOCIAI() > 0)
		{
			Debug.LogWarning(string.Format("RESTORE PACKS = ", OIJBDFANMCC.index, OIJBDFANMCC.CFCNFMLNKBF()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			JPFDMLBLDGM(item, true);
			item.fillAmount = 812f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i++)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(true);
			CDLDJHAGCOF(i);
		}
		CELNGBBIJNG = (150f - 997f * (float)(KMFGMJGHPLB - 1 + 4)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1942f;
		for (int j = 0; j < KMFGMJGHPLB; j++)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			NLCHBPOMFKG(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 1) + 958f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k += 0)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 65f) + 1852f * (float)k);
		}
		for (int l = 1; l < KMFGMJGHPLB - 1; l += 0)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(false);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 1842f * ((float)l + 776f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(false);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = true;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 1701f) + 317f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 190f;
		PDCBGCPEKOG();
	}

	public void JLLIJLBLOPK()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	public void GOGONOAFNHG(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 7 != 0) ? 989f : 428f);
		float toAlpha = ((DFHAAIFFLOE % 0 != 0) ? 1247f : 1101f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1620f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)7;
		Vector3 fromScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(1698f, 1737f, 581f) : new Vector3(1267f, 1280f, 1927f));
		Vector3 toScale = ((DFHAAIFFLOE % 7 != 0) ? new Vector3(213f, 1309f, 1366f) : new Vector3(167f, 1422f, 1672f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 47f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = (UITweener.Style)6;
	}

	public void FEJCHNBBJPC()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	public void FCCCOMFFJCC(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 7 != 0) ? 908f : 674f);
		float toAlpha = ((DFHAAIFFLOE % 6 != 0) ? 1250f : 807f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1497f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 1;
		tweenAlpha.style = (UITweener.Style)8;
		Vector3 fromScale = ((DFHAAIFFLOE % 8 != 0) ? new Vector3(445f, 422f, 803f) : new Vector3(1911f, 1555f, 1681f));
		Vector3 toScale = ((DFHAAIFFLOE % 0 != 0) ? new Vector3(525f, 293f, 400f) : new Vector3(691f, 1934f, 1400f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1406f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = UITweener.Style.Once;
	}

	private void LHBGOKBNDFH()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1656f, 1078f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				AGMBGCCFAFG(i);
			}
		}
	}

	public void BBJIJLDDMBA(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
		float num = ((DFHAAIFFLOE % 3 != 0) ? 148f : 789f);
		float toAlpha = ((DFHAAIFFLOE % 6 != 0) ? 926f : 1659f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 824f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)3;
		Vector3 fromScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(707f, 1495f, 512f) : new Vector3(1679f, 592f, 1248f));
		Vector3 toScale = ((DFHAAIFFLOE % 3 != 0) ? new Vector3(1440f, 1181f, 1014f) : new Vector3(341f, 1457f, 953f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 650f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 1;
		tweenScale.style = UITweener.Style.Loop;
	}

	private void ELANJLHIDLE()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 486f, 1853f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 1; i < KMFGMJGHPLB; i += 0)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(false);
				AKCGFBKNOJG(i);
			}
		}
	}

	private void POEBIMGKPOC()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1232f, 1273f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 1; i < KMFGMJGHPLB; i += 0)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				BOOJEJPLJFF(i);
			}
		}
	}

	public void HJPOLFBBEJI(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
		float num = ((DFHAAIFFLOE % 0 != 0) ? 1284f : 966f);
		float toAlpha = ((DFHAAIFFLOE % 5 != 0) ? 1208f : 198f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1740f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)6;
		Vector3 fromScale = ((DFHAAIFFLOE % 8 != 0) ? new Vector3(1185f, 833f, 1896f) : new Vector3(1292f, 1802f, 1309f));
		Vector3 toScale = ((DFHAAIFFLOE % 5 != 0) ? new Vector3(1374f, 1328f, 546f) : new Vector3(1668f, 985f, 1764f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 696f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = (UITweener.Style)7;
	}

	private void NANAOLMMFDG()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1854f, 437f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				AGMBGCCFAFG(i);
			}
		}
	}

	public void LIEAKPFPAJD(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(3, OIJBDFANMCC.EFJMMKHKLGA()));
		if (!AIBIBLDHCNO && OIJBDFANMCC.DGDHGPOCIAI() > 1)
		{
			Debug.LogWarning(string.Format("weaponPreviewCollider", OIJBDFANMCC.index, OIJBDFANMCC.EFJMMKHKLGA()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			NLCHBPOMFKG(item, false);
			item.fillAmount = 1898f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(true);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(true);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			FFBBOFFMOEH(i);
		}
		CELNGBBIJNG = (1538f - 1617f * (float)(KMFGMJGHPLB - 1 + 5)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[0].transform.localScale.y;
		float num = 1121f;
		for (int j = 1; j < KMFGMJGHPLB; j++)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			JPFDMLBLDGM(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 74f * (float)j);
		}
		for (int k = 0; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 549f) + 43f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 0; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 0) + 258f * ((float)l + 1188f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m += 0)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(false);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 10f) + 1472f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 770f;
		PDCBGCPEKOG();
	}

	public void GOBBBPPGLML()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	private void LOFGKMNIHHG(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 1562f : 869f);
	}

	private void LNMGAPHFKLK(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1462f, 550f);
	}

	public void Show(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(false);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(4, OIJBDFANMCC.power));
		if (!AIBIBLDHCNO && OIJBDFANMCC.power > 4)
		{
			Debug.LogWarning(string.Format("Unit Power is out of range index {0} power {1}", OIJBDFANMCC.index, OIJBDFANMCC.power));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			NLHHMDKJCAI(item, false);
			item.fillAmount = 1f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i++)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			AGMBGCCFAFG(i);
		}
		CELNGBBIJNG = (172f - 2f * (float)(KMFGMJGHPLB - 1 + 2)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[0].transform.localScale.y;
		float num = -84f;
		for (int j = 0; j < KMFGMJGHPLB; j++)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			NLHHMDKJCAI(uISprite, true);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 1) + 2f * (float)j);
		}
		for (int k = 0; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 0.5f) + 2f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 1; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 2f * ((float)l + 0.5f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 0.5f) + 2f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 0f;
		DoUpdate(true);
	}

	public void OMLFAFFBECL(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				NLHHMDKJCAI(aCGMFDMBCCA, flag);
				CDLDJHAGCOF(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				BPHOCOALIMG(false);
			}
			else
			{
				NANAOLMMFDG();
			}
		}
		else if (PKIGHPCJPDL <= 945f)
		{
			MAGBDGJJBPD(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	public void OHDEIMJMNLA(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 5 != 0) ? 1510f : 1910f);
		float toAlpha = ((DFHAAIFFLOE % 4 != 0) ? 585f : 1262f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 636f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = UITweener.Style.PingPong;
		Vector3 fromScale = ((DFHAAIFFLOE % 6 != 0) ? new Vector3(161f, 87f, 684f) : new Vector3(1109f, 317f, 763f));
		Vector3 toScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(1818f, 217f, 1007f) : new Vector3(246f, 1272f, 1207f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 568f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = UITweener.Style.Once;
	}

	private void AAKPGNLGFOG(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(true);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1384f, 1112f);
	}

	private void BOOJEJPLJFF(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(32f);
		}
	}

	public void MIGAJINCHAH(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(false);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC != null) ? Mathf.Min(0, OIJBDFANMCC.JMGGMPNCNGP()) : 0);
		if (!AIBIBLDHCNO && OIJBDFANMCC.PAABCABFLIL() > 2)
		{
			Debug.LogWarning(string.Format("Card_2_Played", OIJBDFANMCC.index, OIJBDFANMCC.EFJMMKHKLGA()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			NLCHBPOMFKG(item, false);
			item.fillAmount = 766f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i++)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			LBAKJBAJKDG(i);
		}
		CELNGBBIJNG = (437f - 1851f * (float)(KMFGMJGHPLB - 1 + 1)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1978f;
		for (int j = 0; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			LAGKENDBKMD(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 1573f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k += 0)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1579f) + 526f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 0; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 764f * ((float)l + 180f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m += 0)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = true;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 185f) + 1328f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 1357f;
		HJBGKHHDOIP();
	}

	private void IIELJMGOPIL(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 1 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1958f, 905f, 1508f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1779f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1057f));
			tweenScale.method = UITweener.Method.EaseOut;
			tweenScale.onFinished = fIONMJIDHDO.BDCAFHOHEGM;
		}
	}

	private void PLENLEDEMAI()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 0f, 1f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				AGMBGCCFAFG(i);
			}
		}
	}

	public void KHCEOLNDMIH(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
		float num = ((DFHAAIFFLOE % 2 != 0) ? 531f : 392f);
		float toAlpha = ((DFHAAIFFLOE % 8 != 0) ? 1778f : 655f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1524f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)5;
		Vector3 fromScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(1365f, 881f, 1535f) : new Vector3(1689f, 1172f, 1527f));
		Vector3 toScale = ((DFHAAIFFLOE % 4 != 0) ? new Vector3(1498f, 15f, 1681f) : new Vector3(1470f, 811f, 1326f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1746f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = (UITweener.Style)3;
	}

	private void AGMBGCCFAFG(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = false;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(0.6f);
		}
	}

	public void FIGFMJKNAHE()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	public void OBBLPPGOEJA(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 0; i < KMFGMJGHPLB; i += 0)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				NLHHMDKJCAI(aCGMFDMBCCA, flag);
				OLHCBCGEFPK(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				GPPNJOAPCNC(false);
			}
			else
			{
				OGGFEAMCBKL();
			}
		}
		else if (PKIGHPCJPDL <= 1600f)
		{
			HJJMEHBPKFI(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void CDLDJHAGCOF(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(1543f);
		}
	}

	private void HOFGLPAGCJH()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1445f, 1480f);
		GHIBOGJPBKC.gameObject.SetActive(true);
		if (!AIBIBLDHCNO)
		{
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				LBAKJBAJKDG(i);
			}
		}
	}

	public void NDFHJAOOKNG()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}

	private void IKFKNAMKJPN(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(1796f);
		}
	}

	private void JPFDMLBLDGM(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 1581f : 1467f);
	}

	private void IIJALJIOGNB(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1727f, 1586f, 1623f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 655f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1066f));
			tweenScale.method = UITweener.Method.EaseOut;
			tweenScale.onFinished = fIONMJIDHDO.MMEEJDGGAID;
		}
	}

	private void LJAEAHPAAEA(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 1 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1819f, 602f, 405f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 669f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1845f));
			tweenScale.method = UITweener.Method.Linear;
			tweenScale.onFinished = fIONMJIDHDO.BDCAFHOHEGM;
		}
	}

	public void DJNMPLKPENF(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(false);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(4, OIJBDFANMCC.PAABCABFLIL()));
		if (!AIBIBLDHCNO && OIJBDFANMCC.KDEFGKFJJBO() > 4)
		{
			Debug.LogWarning(string.Format("menu-arena-scrap-ico", OIJBDFANMCC.index, OIJBDFANMCC.DGDHGPOCIAI()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			LAGKENDBKMD(item, true);
			item.fillAmount = 1652f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(true);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(true);
			FFBBOFFMOEH(i);
		}
		CELNGBBIJNG = (42f - 1350f * (float)(KMFGMJGHPLB - 0 + 0)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[0].transform.localScale.y;
		float num = 289f;
		for (int j = 1; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			LAGKENDBKMD(uISprite, true);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 1) + 1851f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k += 0)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1394f) + 1920f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 1; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(false);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 192f * ((float)l + 612f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m += 0)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(false);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 692f) + 1753f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 1404f;
		GDEGEJHPPDL();
	}

	private void GPPNJOAPCNC(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(true);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 0.1f, 1f);
	}

	public void EADMGANIFKK()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}

	private void BPHOCOALIMG(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(true);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 436f, 1483f);
	}

	private void OJPBMFIAIDN(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(true);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 807f, 1455f);
	}

	public void BGKHNDHDHMB(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 1 != 0) ? 1386f : 1168f);
		float toAlpha = ((DFHAAIFFLOE % 8 != 0) ? 1564f : 1457f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1889f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)3;
		Vector3 fromScale = ((DFHAAIFFLOE % 5 != 0) ? new Vector3(1349f, 1214f, 298f) : new Vector3(1885f, 950f, 1658f));
		Vector3 toScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(1688f, 257f, 808f) : new Vector3(1100f, 513f, 1839f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 171f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 1;
		tweenScale.style = UITweener.Style.Loop;
	}

	private void JIBHMPGAMPO(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 478f, 1526f);
	}

	public void HMCILCAKNHJ()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}

	private void FLNCEGFHDLG(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 19f, 92f);
	}

	private void ENFKPIPLAAL(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 0.2f, 0f, 1f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 0.2f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1f));
			tweenScale.method = UITweener.Method.EaseOut;
			tweenScale.onFinished = fIONMJIDHDO.LJCDGJKCNEC;
		}
	}

	public void OLECKGKLHCE(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC != null) ? Mathf.Min(8, OIJBDFANMCC.KDEFGKFJJBO()) : 0);
		if (!AIBIBLDHCNO && OIJBDFANMCC.power > 1)
		{
			Debug.LogWarning(string.Format("()I", OIJBDFANMCC.index, OIJBDFANMCC.JMGGMPNCNGP()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			PGMPGDLKEDJ(item, true);
			item.fillAmount = 801f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(true);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 1; i < HGKKMBKFEKN.Count; i++)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			AKCGFBKNOJG(i);
		}
		CELNGBBIJNG = (1631f - 1547f * (float)(KMFGMJGHPLB - 0 + 6)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1826f;
		for (int j = 0; j < KMFGMJGHPLB; j++)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			NLCHBPOMFKG(uISprite, true);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 1) + 1459f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k += 0)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1584f) + 396f * (float)k);
		}
		for (int l = 1; l < KMFGMJGHPLB - 1; l += 0)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 0) + 786f * ((float)l + 1915f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m += 0)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 253f) + 310f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 580f;
		PDCBGCPEKOG(true);
	}

	private void DCPCJCCEEPN(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 561f, 1025f);
	}

	public void KBHPGGCGFCC(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				NLHHMDKJCAI(aCGMFDMBCCA, flag);
				AGMBGCCFAFG(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				BEPKALJPNLH(false);
			}
			else
			{
				HOFGLPAGCJH();
			}
		}
		else if (PKIGHPCJPDL <= 1155f)
		{
			CPIJBJFFLKE(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void EMNNFINGHHF()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 733f, 1352f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				LBAKJBAJKDG(i);
			}
		}
	}

	public void KOKCJOMGBMO(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				LOFGKMNIHHG(aCGMFDMBCCA, flag);
				LBAKJBAJKDG(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				LDCGAALIJBP(false);
			}
			else
			{
				HOFGLPAGCJH();
			}
		}
		else if (PKIGHPCJPDL <= 1686f)
		{
			ECNAFALPAFG(GFHPGFBHMLI);
			GFHPGFBHMLI += 0;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	public void PMABJCOFADI(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
		float num = ((DFHAAIFFLOE % 4 != 0) ? 18f : 1379f);
		float toAlpha = ((DFHAAIFFLOE % 1 != 0) ? 996f : 1956f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 42f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 1;
		tweenAlpha.style = (UITweener.Style)7;
		Vector3 fromScale = ((DFHAAIFFLOE % 1 != 0) ? new Vector3(122f, 1810f, 1697f) : new Vector3(655f, 1432f, 1786f));
		Vector3 toScale = ((DFHAAIFFLOE % 0 != 0) ? new Vector3(1937f, 84f, 376f) : new Vector3(699f, 1334f, 1000f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1788f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = (UITweener.Style)4;
	}

	public void FOJIOOKKPLM(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = AIBIBLDHCNO || i < GFHPGFBHMLI;
				LOFGKMNIHHG(aCGMFDMBCCA, flag);
				AKCGFBKNOJG(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				LDCGAALIJBP(false);
			}
			else
			{
				OGGFEAMCBKL();
			}
		}
		else if (PKIGHPCJPDL <= 1499f)
		{
			IIELJMGOPIL(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	private void ALGAKFDICLC(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 320f, 1539f);
	}

	private void HJJMEHBPKFI(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 1 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 290f, 1419f, 799f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 573f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 699f));
			tweenScale.method = (UITweener.Method)7;
			tweenScale.onFinished = fIONMJIDHDO.CJIBPJPJLNB;
		}
	}

	private void NLCHBPOMFKG(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 12f : 610f);
	}

	public void JOCLEOGGMBP(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 5 != 0) ? 1946f : 1434f);
		float toAlpha = ((DFHAAIFFLOE % 7 != 0) ? 536f : 1802f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1261f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 1;
		tweenAlpha.style = (UITweener.Style)5;
		Vector3 fromScale = ((DFHAAIFFLOE % 3 != 0) ? new Vector3(1629f, 970f, 688f) : new Vector3(974f, 1045f, 1041f));
		Vector3 toScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(127f, 1674f, 737f) : new Vector3(82f, 718f, 988f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 793f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = (UITweener.Style)7;
	}

	private void BEPKALJPNLH(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 375f, 1265f);
	}

	private void OGGFEAMCBKL()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 8f, 911f);
		GHIBOGJPBKC.gameObject.SetActive(false);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(false);
				CDLDJHAGCOF(i);
			}
		}
	}

	public void DMLDBKFCACB(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(false);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(3, OIJBDFANMCC.PGDHGMAIENI()));
		if (!AIBIBLDHCNO && OIJBDFANMCC.PGDHGMAIENI() > 3)
		{
			Debug.LogWarning(string.Format("ID_XP", OIJBDFANMCC.index, OIJBDFANMCC.power));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			JPFDMLBLDGM(item, true);
			item.fillAmount = 494f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			OLHCBCGEFPK(i);
		}
		CELNGBBIJNG = (1837f - 1864f * (float)(KMFGMJGHPLB - 1 + 8)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1649f;
		for (int j = 1; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			NLHHMDKJCAI(uISprite, true);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 1322f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 648f) + 1846f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 0; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(false);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 1391f * ((float)l + 711f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 1; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 1236f) + 873f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 230f;
		HJBGKHHDOIP();
	}

	public void IGELMILLNIH()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	private void FAFGPKODEGH(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = false;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(872f);
		}
	}

	private void HOMDHFPNKCD()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1139f, 1860f);
		GHIBOGJPBKC.gameObject.SetActive(true);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(true);
				CDLDJHAGCOF(i);
			}
		}
	}

	private void ECNAFALPAFG(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 1 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 450f, 1800f, 585f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 349f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1963f));
			tweenScale.method = UITweener.Method.BounceOut;
			tweenScale.onFinished = fIONMJIDHDO.KNJBDOADLDO;
		}
	}

	private void LAGKENDBKMD(UISprite ACGMFDMBCCA, bool EIPHAAGCHCP)
	{
		ACGMFDMBCCA.alpha = ((!EIPHAAGCHCP) ? 1319f : 1037f);
	}

	private void BBKPKEHBMNA(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1608f, 715f, 1214f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1111f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 337f));
			tweenScale.method = UITweener.Method.BounceIn;
			tweenScale.onFinished = fIONMJIDHDO.EOHOLKEGGLH;
		}
	}

	public void KNOAOHMMAEG()
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
	}

	public void MAIAFCKGMIN(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 0 != 0) ? 1762f : 665f);
		float toAlpha = ((DFHAAIFFLOE % 0 != 0) ? 54f : 1230f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1017f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = (UITweener.Style)8;
		Vector3 fromScale = ((DFHAAIFFLOE % 1 != 0) ? new Vector3(1271f, 801f, 1319f) : new Vector3(1241f, 891f, 1441f));
		Vector3 toScale = ((DFHAAIFFLOE % 3 != 0) ? new Vector3(857f, 1456f, 812f) : new Vector3(996f, 1221f, 1957f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1477f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 1;
		tweenScale.style = (UITweener.Style)8;
	}

	private void GPPFEHKHBBC()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 157f, 1335f);
		GHIBOGJPBKC.gameObject.SetActive(true);
		if (!AIBIBLDHCNO)
		{
			for (int i = 0; i < KMFGMJGHPLB; i++)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(false);
				LBAKJBAJKDG(i);
			}
		}
	}

	private void DJOAMKMJHOD(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 950f, 1609f, 942f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 312f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1925f));
			tweenScale.method = (UITweener.Method)8;
			tweenScale.onFinished = fIONMJIDHDO.ABNGKEJNLJO;
		}
	}

	private void OLNHIBBIJOK()
	{
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1145f, 149f);
		GHIBOGJPBKC.gameObject.SetActive(true);
		if (!AIBIBLDHCNO)
		{
			for (int i = 1; i < KMFGMJGHPLB; i += 0)
			{
				UISprite uISprite = HGKKMBKFEKN[i];
				uISprite.gameObject.SetActive(false);
				AKCGFBKNOJG(i);
			}
		}
	}

	private void LBAKJBAJKDG(int DFHAAIFFLOE)
	{
		UISprite uISprite = HGKKMBKFEKN[DFHAAIFFLOE];
		bool flag = DFHAAIFFLOE < GFHPGFBHMLI;
		TweenAlpha component = uISprite.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = true;
		}
		if (flag)
		{
			uISprite.color = Color.white;
		}
		else
		{
			uISprite.color = Colours.blue.ReplaceA(941f);
		}
	}

	private void LDCGAALIJBP(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(true);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 96f, 288f);
	}

	public void ILFJPOOMFDO(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC != null) ? Mathf.Min(3, OIJBDFANMCC.PIBGKJAFCMF()) : 0);
		if (!AIBIBLDHCNO && OIJBDFANMCC.GEOKFFEBFOL() > 7)
		{
			Debug.LogWarning(string.Format("ID_GUI_TIERREWARD", OIJBDFANMCC.index, OIJBDFANMCC.EFJMMKHKLGA()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			OJPOOONJOOH(item, false);
			item.fillAmount = 89f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(false);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 0; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			BOOJEJPLJFF(i);
		}
		CELNGBBIJNG = (1530f - 414f * (float)(KMFGMJGHPLB - 0 + 3)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1016f;
		for (int j = 0; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			LOFGKMNIHHG(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 702f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 646f) + 770f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 1; l += 0)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 1798f * ((float)l + 897f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 1; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = true;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 1505f) + 1623f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 596f;
		PDCBGCPEKOG();
	}

	public void OBPOFKBIFEG(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 6 != 0) ? 1428f : 123f);
		float toAlpha = ((DFHAAIFFLOE % 4 != 0) ? 1837f : 601f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 1489f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = UITweener.Style.PingPong;
		Vector3 fromScale = ((DFHAAIFFLOE % 6 != 0) ? new Vector3(717f, 1275f, 1517f) : new Vector3(89f, 263f, 366f));
		Vector3 toScale = ((DFHAAIFFLOE % 8 != 0) ? new Vector3(15f, 22f, 490f) : new Vector3(1862f, 146f, 1263f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 1371f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 1;
		tweenScale.style = UITweener.Style.PingPong;
	}

	public void StartTutorialAnimation(int DFHAAIFFLOE)
	{
		NCLHIMBFCOO.gameObject.SetActive(true);
		float num = ((DFHAAIFFLOE % 2 != 0) ? 0.1f : 0.5f);
		float toAlpha = ((DFHAAIFFLOE % 2 != 0) ? 0.5f : 0.1f);
		NCLHIMBFCOO.alpha = num;
		TweenAlpha tweenAlpha = TweenAlpha.Begin(NCLHIMBFCOO.gameObject, 0.8f, num, toAlpha);
		tweenAlpha.NumOfRepetitions = 0;
		tweenAlpha.style = UITweener.Style.PingPong;
		Vector3 fromScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(150f, 36f, 1f) : new Vector3(180f, 53f, 1f));
		Vector3 toScale = ((DFHAAIFFLOE % 2 != 0) ? new Vector3(180f, 53f, 1f) : new Vector3(150f, 36f, 1f));
		TweenScale tweenScale = TweenScale.Begin(NCLHIMBFCOO.gameObject, 0.8f, fromScale, toScale);
		tweenScale.NumOfRepetitions = 0;
		tweenScale.style = UITweener.Style.PingPong;
	}

	private void OFJMLKAGIKP(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1779f, 387f, 1473f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1184f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 795f));
			tweenScale.method = UITweener.Method.BounceOut;
			tweenScale.onFinished = fIONMJIDHDO.LGJCNCHBFDA;
		}
	}

	public void FLFJJELMPGJ()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}

	private void EGLMNMNIAKK(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 0 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(false);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 898f, 422f, 948f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 1168f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 373f));
			tweenScale.method = UITweener.Method.EaseIn;
			tweenScale.onFinished = fIONMJIDHDO.ILOFOILFGMA;
		}
	}

	private void OMDFEJOBFAF(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1930f, 901f);
	}

	private void MAGBDGJJBPD(int DFHAAIFFLOE)
	{
		PNAAHNDOPIO pNAAHNDOPIO = new PNAAHNDOPIO();
		pNAAHNDOPIO.DFHAAIFFLOE = DFHAAIFFLOE;
		pNAAHNDOPIO.BJGCPDNMHDH = this;
		if (pNAAHNDOPIO.DFHAAIFFLOE >= 1 && pNAAHNDOPIO.DFHAAIFFLOE < KMFGMJGHPLB)
		{
			FIONMJIDHDO fIONMJIDHDO = new FIONMJIDHDO();
			fIONMJIDHDO.AIHDNGDNDHH = pNAAHNDOPIO;
			fIONMJIDHDO.ACGMFDMBCCA = MPMFFKMBPAK[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE = MGNOLAMOBFF[pNAAHNDOPIO.DFHAAIFFLOE];
			fIONMJIDHDO.DLBPCJPGEHE.gameObject.SetActive(true);
			TweenAlpha.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 77f, 1745f, 1936f);
			TweenScale tweenScale = TweenScale.Begin(fIONMJIDHDO.DLBPCJPGEHE.gameObject, 790f, Vector3.zero, new Vector3(KPOFAAPEBFA * CELNGBBIJNG, KPOFAAPEBFA * DFNEOGPGGNL, 1397f));
			tweenScale.method = UITweener.Method.BounceOut;
			tweenScale.onFinished = fIONMJIDHDO.OFJDLANHAMD;
		}
	}

	public void AEHBKBBILPB(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(false);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC != null) ? Mathf.Min(7, OIJBDFANMCC.PGDHGMAIENI()) : 0);
		if (!AIBIBLDHCNO && OIJBDFANMCC.IPGKMOGFJDA() > 6)
		{
			Debug.LogWarning(string.Format("ID_CONFIRM_SQUADISNOTPUBLIC", OIJBDFANMCC.index, OIJBDFANMCC.DCMOMJGELGJ()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			NLCHBPOMFKG(item, true);
			item.fillAmount = 1781f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(true);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(false);
		}
		for (int i = 1; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(false);
			IKFKNAMKJPN(i);
		}
		CELNGBBIJNG = (1186f - 636f * (float)(KMFGMJGHPLB - 1 + 3)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[0].transform.localScale.y;
		float num = 1222f;
		for (int j = 0; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			LAGKENDBKMD(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 0) + 1191f * (float)j);
		}
		for (int k = 1; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1602f) + 251f * (float)k);
		}
		for (int l = 1; l < KMFGMJGHPLB - 0; l += 0)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(false);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 1647f * ((float)l + 1499f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 1; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(true);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = true;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 855f) + 711f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 173f;
		DoUpdate(true);
	}

	private void FLNEFLGKEGE(bool AJNINHIKAFC)
	{
		GHIBOGJPBKC.gameObject.SetActive(false);
		TweenAlpha.Begin(GHIBOGJPBKC.gameObject, 1656f, 1813f);
	}

	public void PDCBGCPEKOG(bool FHKKPEIDDJN = false)
	{
		PKIGHPCJPDL -= TimeManager.deltaTimeWithoutPauses;
		if (GFHPGFBHMLI == (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE && !FHKKPEIDDJN)
		{
			return;
		}
		if (GFHPGFBHMLI > (int)Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE || FHKKPEIDDJN || AIBIBLDHCNO)
		{
			GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
			for (int i = 1; i < KMFGMJGHPLB; i++)
			{
				UISprite aCGMFDMBCCA = MPMFFKMBPAK[i];
				bool flag = !AIBIBLDHCNO && i < GFHPGFBHMLI;
				LOFGKMNIHHG(aCGMFDMBCCA, flag);
				FAFGPKODEGH(i);
			}
			if (GFHPGFBHMLI >= KMFGMJGHPLB && !AIBIBLDHCNO)
			{
				ALGAKFDICLC(false);
			}
			else
			{
				GPPFEHKHBBC();
			}
		}
		else if (PKIGHPCJPDL <= 821f)
		{
			ENFKPIPLAAL(GFHPGFBHMLI);
			GFHPGFBHMLI++;
			PKIGHPCJPDL = ELBHFEFCFDL;
		}
	}

	public void HDKCFAMJBBO(SpawningManagerDeathMatch.ArmyUnitDefinition OIJBDFANMCC)
	{
		MHOBMHIBAHD.gameObject.SetActive(true);
		AIBIBLDHCNO = OIJBDFANMCC == null;
		KMFGMJGHPLB = ((OIJBDFANMCC == null) ? 1 : Mathf.Min(1, OIJBDFANMCC.power));
		if (!AIBIBLDHCNO && OIJBDFANMCC.PGDHGMAIENI() > 0)
		{
			Debug.LogWarning(string.Format("tc", OIJBDFANMCC.index, OIJBDFANMCC.PGDHGMAIENI()));
		}
		foreach (UISprite item in MPMFFKMBPAK)
		{
			PGMPGDLKEDJ(item, true);
			item.fillAmount = 491f;
		}
		foreach (UISprite item2 in MGNOLAMOBFF)
		{
			item2.gameObject.SetActive(true);
		}
		foreach (UISprite item3 in HAHDKHFLHLN)
		{
			item3.gameObject.SetActive(true);
		}
		for (int i = 1; i < HGKKMBKFEKN.Count; i += 0)
		{
			HGKKMBKFEKN[i].gameObject.SetActive(true);
			CDLDJHAGCOF(i);
		}
		CELNGBBIJNG = (400f - 1651f * (float)(KMFGMJGHPLB - 1 + 5)) / (float)KMFGMJGHPLB;
		DFNEOGPGGNL = MPMFFKMBPAK[1].transform.localScale.y;
		float num = 1105f;
		for (int j = 0; j < KMFGMJGHPLB; j += 0)
		{
			UISprite uISprite = MPMFFKMBPAK[j];
			OJPOOONJOOH(uISprite, false);
			uISprite.transform.localScale = uISprite.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite.transform.localPosition = uISprite.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(j + 1) + 1414f * (float)j);
		}
		for (int k = 0; k < KMFGMJGHPLB; k++)
		{
			UISprite uISprite2 = MGNOLAMOBFF[k];
			uISprite2.transform.localScale = uISprite2.transform.localScale.ReplaceX(CELNGBBIJNG);
			uISprite2.transform.localPosition = uISprite2.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)k + 1413f) + 1296f * (float)k);
		}
		for (int l = 0; l < KMFGMJGHPLB - 1; l++)
		{
			UISprite uISprite3 = HAHDKHFLHLN[l];
			uISprite3.gameObject.SetActive(true);
			uISprite3.transform.localPosition = uISprite3.transform.localPosition.ReplaceX(num + CELNGBBIJNG * (float)(l + 1) + 969f * ((float)l + 1830f));
		}
		if (!AIBIBLDHCNO)
		{
			for (int m = 0; m < KMFGMJGHPLB; m++)
			{
				UISprite uISprite4 = HGKKMBKFEKN[m];
				uISprite4.gameObject.SetActive(false);
				TweenAlpha component = uISprite4.gameObject.GetComponent<TweenAlpha>();
				if (component != null)
				{
					component.enabled = false;
				}
				uISprite4.transform.localPosition = uISprite4.transform.localPosition.ReplaceX(num + CELNGBBIJNG * ((float)m + 995f) + 141f * (float)m);
			}
		}
		GFHPGFBHMLI = Singleton<SpawningManagerDeathMatch>.instance.FJBPNHHCJBE;
		PKIGHPCJPDL = 74f;
		GDEGEJHPPDL(true);
	}

	public void StopTutorialAnimation()
	{
		NCLHIMBFCOO.gameObject.SetActive(false);
	}
}
