using UnityEngine;

public class ExplosionManager : Singleton<ExplosionManager>
{
	private float LIEABAMBOMG = 1.8f;

	private float INIBDNGHLPN = 1.1f;

	private Vector3 MJHAOAOPPGG = new Vector3(5f, 8f, 5f);

	private float CPBCADFLPMO = 6f;

	private PhotonView FEHCCGEGPLH;

	public void HELCGODGBJG(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		INCNNACKAOO(MPHCNMDIPAI, CJDCGPMIHEA, 142f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 684f, GHEAKBCACNK);
	}

	protected void JOKGCCIJMME(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
	}

	public void ANNJFEMALGD(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.INCNNACKAOO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-42];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[5] = EPDELOGPNAC;
		array[7] = INIBDNGHLPN;
		array[5] = LIEABAMBOMG;
		array[8] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[8] = MAOPCAMOEEK;
		array[8] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("Wrong_Weapon", PhotonTargets.Others, array);
	}

	protected virtual void NOGLOKJINKN()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void MCBJEIDOJNN(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		BFJGFJGJNGB(MPHCNMDIPAI, CJDCGPMIHEA, 567f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 206f, GHEAKBCACNK);
	}

	public void PPJMFPCHKAL(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[90];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[3] = EPDELOGPNAC;
		array[5] = INIBDNGHLPN;
		array[0] = LIEABAMBOMG;
		array[4] = ELMEIGEABIK;
		array[4] = CPBCADFLPMO;
		array[7] = MAOPCAMOEEK;
		array[8] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("trial", PhotonTargets.Others, array);
	}

	public void AOANCHGMOLN(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[78];
		array[0] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[7] = EPDELOGPNAC;
		array[2] = INIBDNGHLPN;
		array[1] = LIEABAMBOMG;
		array[1] = ELMEIGEABIK;
		array[7] = CPBCADFLPMO;
		array[7] = MAOPCAMOEEK;
		array[2] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("api/", PhotonTargets.All, array);
	}

	protected virtual void OLBEOPKDEBJ()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void IPPOAMIGKBB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.HELCGODGBJG(nOCEDALFEJM);
	}

	protected virtual void JLOKAFKICIM()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void GEEODBPCKJJ(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
	}

	public void LAMLOFAOFAC(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LHKLMDDPLHE(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[108];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[0] = EPDELOGPNAC;
		array[2] = INIBDNGHLPN;
		array[6] = LIEABAMBOMG;
		array[5] = ELMEIGEABIK;
		array[0] = CPBCADFLPMO;
		array[7] = MAOPCAMOEEK;
		array[8] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("FuseSDK: Parsing error in _FriendsListError", PhotonTargets.All, array);
	}

	public void JFECMCKMOCJ(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		IPCHJFKLCMH(MPHCNMDIPAI, CJDCGPMIHEA, 105f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 471f, GHEAKBCACNK);
	}

	public void CHBENGDOIKL(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		PPJMFPCHKAL(MPHCNMDIPAI, CJDCGPMIHEA, 1381f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 15f, GHEAKBCACNK);
	}

	protected virtual void HCNOHLLOGBO()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void IJBOFJBPAHP(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
	}

	public void LHKLMDDPLHE(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[105];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[4] = EPDELOGPNAC;
		array[8] = INIBDNGHLPN;
		array[1] = LIEABAMBOMG;
		array[6] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[0] = MAOPCAMOEEK;
		array[6] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("OOOOPS", PhotonTargets.All, array);
	}

	protected virtual void HCDNNGFBJOE()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void OIIMCCDGFIL(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		ANNJFEMALGD(MPHCNMDIPAI, CJDCGPMIHEA, 1013f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 787f, GHEAKBCACNK);
	}

	public void LGIKNJJDGGF(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		GKFCHLLNOMJ(MPHCNMDIPAI, CJDCGPMIHEA, 307f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1266f, GHEAKBCACNK);
	}

	public void DFJNKKFMKHF(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.DDOFJPPKJOJ(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[73];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[3] = EPDELOGPNAC;
		array[1] = INIBDNGHLPN;
		array[5] = LIEABAMBOMG;
		array[8] = ELMEIGEABIK;
		array[5] = CPBCADFLPMO;
		array[8] = MAOPCAMOEEK;
		array[7] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("Beanstalk: Update squad finished", PhotonTargets.Others, array);
	}

	public void IIPEOPFAPFL(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-73];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[5] = EPDELOGPNAC;
		array[6] = INIBDNGHLPN;
		array[6] = LIEABAMBOMG;
		array[5] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[8] = MAOPCAMOEEK;
		array[8] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("IsOffline", PhotonTargets.Others, array);
	}

	protected virtual void LCLEKFMLENA()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected virtual void FANDCCNILLD()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void OPCGIMAEALD(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KMNKGGDOMJO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-122];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[1] = INIBDNGHLPN;
		array[8] = LIEABAMBOMG;
		array[6] = ELMEIGEABIK;
		array[8] = CPBCADFLPMO;
		array[2] = MAOPCAMOEEK;
		array[4] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("country-noflag", PhotonTargets.Others, array);
	}

	public void OEBEOPNBDDL(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		JKLHAACHKAO(MPHCNMDIPAI, CJDCGPMIHEA, 705f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1925f, GHEAKBCACNK);
	}

	protected void MMMCHILDKBC(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
	}

	protected virtual void OBEHLLBBEIL()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void ADIJKGOPMDB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.HELCGODGBJG(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[78];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[5] = EPDELOGPNAC;
		array[7] = INIBDNGHLPN;
		array[7] = LIEABAMBOMG;
		array[3] = ELMEIGEABIK;
		array[0] = CPBCADFLPMO;
		array[1] = MAOPCAMOEEK;
		array[3] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("(Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;)V", PhotonTargets.All, array);
	}

	protected void DLONHHLKPNB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GPOCAHICFDH(nOCEDALFEJM);
	}

	public void HGMAIEBKPPH(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		IIPEOPFAPFL(MPHCNMDIPAI, CJDCGPMIHEA, 1948f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 369f, GHEAKBCACNK);
	}

	protected void KKIOGHFPCHP(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
	}

	public void ILEBFMDOIEJ(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[69];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[0] = EPDELOGPNAC;
		array[4] = INIBDNGHLPN;
		array[2] = LIEABAMBOMG;
		array[4] = ELMEIGEABIK;
		array[4] = CPBCADFLPMO;
		array[3] = MAOPCAMOEEK;
		array[0] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC(". Loading default...", PhotonTargets.Others, array);
	}

	[PunRPC]
	protected void MissileExplodeRPC(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
	}

	public void EDGGIPAINGP(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		IPCHJFKLCMH(MPHCNMDIPAI, CJDCGPMIHEA, 1466f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 618f, GHEAKBCACNK);
	}

	public void KMNKGGDOMJO(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		ADIJKGOPMDB(MPHCNMDIPAI, CJDCGPMIHEA, 613f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1617f, GHEAKBCACNK);
	}

	public void LNHKKEAJBED(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-94];
		array[0] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[3] = INIBDNGHLPN;
		array[8] = LIEABAMBOMG;
		array[5] = ELMEIGEABIK;
		array[0] = CPBCADFLPMO;
		array[0] = MAOPCAMOEEK;
		array[0] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("{0}/{1}", PhotonTargets.Others, array);
	}

	public void EMIKLLNLICL(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.INCNNACKAOO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-13];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[2] = INIBDNGHLPN;
		array[0] = LIEABAMBOMG;
		array[4] = ELMEIGEABIK;
		array[2] = CPBCADFLPMO;
		array[6] = MAOPCAMOEEK;
		array[2] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("WarFriends require to download approximately 190MB of extra data to run.\nDownload time may vary based on your network and location.\n\nDo you wish to proceed?", PhotonTargets.Others, array);
	}

	public void MissileExplode(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		FEHCCGEGPLH.RPC("MissileExplodeRPC", PhotonTargets.Others, MPHCNMDIPAI, JHGHGAFBDFG, EPDELOGPNAC, INIBDNGHLPN, LIEABAMBOMG, ELMEIGEABIK, CPBCADFLPMO, MAOPCAMOEEK, (int)GHEAKBCACNK);
	}

	public void CKNBNIPDOLH(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		PMFFPMDPFNB(MPHCNMDIPAI, CJDCGPMIHEA, 0f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 200f, GHEAKBCACNK);
	}

	public void PEAHIDNEDJF(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		BFJGFJGJNGB(MPHCNMDIPAI, CJDCGPMIHEA, 299f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1469f, GHEAKBCACNK);
	}

	public void PMFFPMDPFNB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.IMCGCAHFJLP(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-89];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[4] = EPDELOGPNAC;
		array[2] = INIBDNGHLPN;
		array[6] = LIEABAMBOMG;
		array[6] = ELMEIGEABIK;
		array[1] = CPBCADFLPMO;
		array[0] = MAOPCAMOEEK;
		array[5] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("BotLevel", PhotonTargets.All, array);
	}

	public void APOELPIAOBD(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		JKLHAACHKAO(MPHCNMDIPAI, CJDCGPMIHEA, 665f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1647f, GHEAKBCACNK);
	}

	protected virtual void EEMLMJCHKLM()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected virtual void IOAEHDJGBJC()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void JDHCGOBBINA(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
	}

	protected void KOEOMMMHHNB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.MKOEENAEACP(nOCEDALFEJM);
	}

	public void OHMKFIFIFMM(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		IPCHJFKLCMH(MPHCNMDIPAI, CJDCGPMIHEA, 1787f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1306f, GHEAKBCACNK);
	}

	protected override void Awake()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void ODAMJPFIECA(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
	}

	public void HJNGPMGELIM(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.BPOCFDOIHPG(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-117];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[3] = EPDELOGPNAC;
		array[2] = INIBDNGHLPN;
		array[8] = LIEABAMBOMG;
		array[7] = ELMEIGEABIK;
		array[8] = CPBCADFLPMO;
		array[3] = MAOPCAMOEEK;
		array[0] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("USPECH POKUSU O LOGIN NA FB!!!", PhotonTargets.All, array);
	}

	public void GKFCHLLNOMJ(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[99];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[6] = EPDELOGPNAC;
		array[3] = INIBDNGHLPN;
		array[1] = LIEABAMBOMG;
		array[3] = ELMEIGEABIK;
		array[0] = CPBCADFLPMO;
		array[1] = MAOPCAMOEEK;
		array[7] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_CONFIRM_PROMOTETOLEADER", PhotonTargets.All, array);
	}

	protected virtual void FGOGGLDAKHL()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void AIPMMHFIHGM(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.HELCGODGBJG(nOCEDALFEJM);
	}

	public void IPEDNMPJOOO(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		HJNGPMGELIM(MPHCNMDIPAI, CJDCGPMIHEA, 1372f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1070f, GHEAKBCACNK);
	}

	protected void NNFJFKDJJOP(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
	}

	public void FFCFIMNBLHI(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		LAMLOFAOFAC(MPHCNMDIPAI, CJDCGPMIHEA, 1319f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 882f, GHEAKBCACNK);
	}

	protected virtual void HEJKGFPPIDC()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected virtual void GDDCEHOJCEM()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void ECDOOCMMDMA(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LHKLMDDPLHE(nOCEDALFEJM);
	}

	protected virtual void CDPAGKOKDOP()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void JKLHAACHKAO(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-88];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[0] = EPDELOGPNAC;
		array[7] = INIBDNGHLPN;
		array[8] = LIEABAMBOMG;
		array[7] = ELMEIGEABIK;
		array[6] = CPBCADFLPMO;
		array[7] = MAOPCAMOEEK;
		array[8] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("MX", PhotonTargets.Others, array);
	}

	protected virtual void BOLPPMANCCC()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected virtual void BMLLLOBPGIB()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void KBHIBIIMOEH(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		MissileExplode(MPHCNMDIPAI, CJDCGPMIHEA, 1648f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 22f, GHEAKBCACNK);
	}

	public void BFJGFJGJNGB(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-57];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[2] = EPDELOGPNAC;
		array[1] = INIBDNGHLPN;
		array[5] = LIEABAMBOMG;
		array[2] = ELMEIGEABIK;
		array[6] = CPBCADFLPMO;
		array[2] = MAOPCAMOEEK;
		array[1] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_ARENASHORTCUTPHASESTART", PhotonTargets.Others, array);
	}

	protected virtual void JFDOGLFMHAE()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void PKDKMIAHMME(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.IMCGCAHFJLP(nOCEDALFEJM);
	}

	protected void CDHOGNDKAHI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
	}

	protected virtual void FGOAPPLNMKL()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void CNNCDEGEKCG(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		AOANCHGMOLN(MPHCNMDIPAI, CJDCGPMIHEA, 812f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1003f, GHEAKBCACNK);
	}

	protected virtual void PIIFEPFCOJF()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void LKDJCNHGOEN(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GPOCAHICFDH(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[65];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[5] = INIBDNGHLPN;
		array[3] = LIEABAMBOMG;
		array[6] = ELMEIGEABIK;
		array[6] = CPBCADFLPMO;
		array[3] = MAOPCAMOEEK;
		array[6] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_CONFIRM_LEAVESQUAD", PhotonTargets.All, array);
	}

	protected virtual void HDCLMJFIEGI()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void LONEKMFPFBP(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		LKDJCNHGOEN(MPHCNMDIPAI, CJDCGPMIHEA, 230f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1889f, GHEAKBCACNK);
	}

	protected void KPHGLEOKHMP(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.INCNNACKAOO(nOCEDALFEJM);
	}

	public void INCNNACKAOO(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-18];
		array[0] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[5] = INIBDNGHLPN;
		array[8] = LIEABAMBOMG;
		array[2] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[6] = MAOPCAMOEEK;
		array[4] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("totalMem", PhotonTargets.All, array);
	}

	public void JBMNBKFECPP(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFJNKKFMKHF(MPHCNMDIPAI, CJDCGPMIHEA, 1427f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1218f, GHEAKBCACNK);
	}

	protected void EJIHOKIKONE(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
	}

	public void MissileExplode(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		MissileExplode(MPHCNMDIPAI, CJDCGPMIHEA, 0.1f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 0.5f, GHEAKBCACNK);
	}

	public void IPCHJFKLCMH(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[56];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[6] = EPDELOGPNAC;
		array[5] = INIBDNGHLPN;
		array[5] = LIEABAMBOMG;
		array[6] = ELMEIGEABIK;
		array[7] = CPBCADFLPMO;
		array[5] = MAOPCAMOEEK;
		array[6] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("HeroicReward", PhotonTargets.Others, array);
	}

	protected void IFAEEGPNBPN(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.JLJNJFJCJMH(nOCEDALFEJM);
	}

	public void CCJFAIOLKCE(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		ANNJFEMALGD(MPHCNMDIPAI, CJDCGPMIHEA, 492f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 935f, GHEAKBCACNK);
	}

	protected void BMHOGPBCOOI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
	}

	protected void PJHADGNEHLI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
	}

	protected void JDEBNBMNNML(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
	}

	public void KEKABOCODAI(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		ILEBFMDOIEJ(MPHCNMDIPAI, CJDCGPMIHEA, 604f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 689f, GHEAKBCACNK);
	}

	public void BAPKJHLKHAN(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		PMFFPMDPFNB(MPHCNMDIPAI, CJDCGPMIHEA, 440f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 50f, GHEAKBCACNK);
	}

	public void EADAFAENILK(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		PEGOKBDJDBG(MPHCNMDIPAI, CJDCGPMIHEA, 212f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 813f, GHEAKBCACNK);
	}

	protected void MDJPJDKCIMK(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
	}

	protected void IJMOANLJKNE(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
	}

	public void DCKBBBOHNFK(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[12];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[4] = EPDELOGPNAC;
		array[7] = INIBDNGHLPN;
		array[7] = LIEABAMBOMG;
		array[1] = ELMEIGEABIK;
		array[7] = CPBCADFLPMO;
		array[1] = MAOPCAMOEEK;
		array[6] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_ARENARULES_NOSHIELDS", PhotonTargets.Others, array);
	}

	public void ONJMBADAOOG(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DDOFJPPKJOJ(MPHCNMDIPAI, CJDCGPMIHEA, 469f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1487f, GHEAKBCACNK);
	}

	protected virtual void PJEMCLFLGBL()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	public void DADGLKFCOHO(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-37];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[7] = EPDELOGPNAC;
		array[3] = INIBDNGHLPN;
		array[1] = LIEABAMBOMG;
		array[4] = ELMEIGEABIK;
		array[6] = CPBCADFLPMO;
		array[1] = MAOPCAMOEEK;
		array[0] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_COLLECTXELITEPARTSX", PhotonTargets.Others, array);
	}

	protected void GCDLNIKHGLI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
	}

	public void BPOCFDOIHPG(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		GKFCHLLNOMJ(MPHCNMDIPAI, CJDCGPMIHEA, 297f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 1977f, GHEAKBCACNK);
	}

	public void PEGOKBDJDBG(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.DDOFJPPKJOJ(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[16];
		array[0] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[4] = EPDELOGPNAC;
		array[6] = INIBDNGHLPN;
		array[0] = LIEABAMBOMG;
		array[4] = ELMEIGEABIK;
		array[8] = CPBCADFLPMO;
		array[2] = MAOPCAMOEEK;
		array[0] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("ID_TUTORIAL_TAPON", PhotonTargets.Others, array);
	}

	protected void CBAFJHFINMI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
	}

	public void DDOFJPPKJOJ(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-71];
		array[1] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[6] = EPDELOGPNAC;
		array[1] = INIBDNGHLPN;
		array[4] = LIEABAMBOMG;
		array[3] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[6] = MAOPCAMOEEK;
		array[2] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("PlayerId", PhotonTargets.All, array);
	}

	protected virtual void BAGCDJMLCPF()
	{
		FEHCCGEGPLH = GetComponent<PhotonView>();
	}

	protected void ENLKKMDHHBK(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
	}

	protected void ABLNFDPLMHC(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
	}

	public void OMCIIKAGOBK(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = true;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KMNKGGDOMJO(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[29];
		array[1] = MPHCNMDIPAI;
		array[1] = JHGHGAFBDFG;
		array[8] = EPDELOGPNAC;
		array[8] = INIBDNGHLPN;
		array[2] = LIEABAMBOMG;
		array[5] = ELMEIGEABIK;
		array[7] = CPBCADFLPMO;
		array[2] = MAOPCAMOEEK;
		array[4] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("Squad Member record does not have DatabasePlayer", PhotonTargets.All, array);
	}

	public void JFDCHBHGDHA(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		LKDJCNHGOEN(MPHCNMDIPAI, CJDCGPMIHEA, 65f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 114f, GHEAKBCACNK);
	}

	protected void DFFMEEAGKEE(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
	}

	public void ABMGNMNJOFN(Vector3 MPHCNMDIPAI, float CJDCGPMIHEA, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		HJNGPMGELIM(MPHCNMDIPAI, CJDCGPMIHEA, 1326f * CJDCGPMIHEA, INIBDNGHLPN, LIEABAMBOMG, MJHAOAOPPGG, CPBCADFLPMO, HNFNINFCBEJ, JMMJHCOKCGG, 288f, GHEAKBCACNK);
	}

	protected void FDHLGIFKKKA(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.KMNKGGDOMJO(nOCEDALFEJM);
	}

	public void FOBIEIDDEKI(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, KMHCMCBGFFC HNFNINFCBEJ, Weapon JMMJHCOKCGG, float MAOPCAMOEEK, DFHALNOAGGC.PEBLJIFMBGC GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HNFNINFCBEJ;
		pKDCCCNJIEC.JMMJHCOKCGG = JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.LCDHLOOGLAD(nOCEDALFEJM);
		PhotonView fEHCCGEGPLH = FEHCCGEGPLH;
		object[] array = new object[-117];
		array[0] = MPHCNMDIPAI;
		array[0] = JHGHGAFBDFG;
		array[7] = EPDELOGPNAC;
		array[7] = INIBDNGHLPN;
		array[7] = LIEABAMBOMG;
		array[3] = ELMEIGEABIK;
		array[3] = CPBCADFLPMO;
		array[2] = MAOPCAMOEEK;
		array[4] = (int)GHEAKBCACNK;
		fEHCCGEGPLH.RPC("#PETER# BlackMarket offer came - show it!", PhotonTargets.Others, array);
	}

	protected void PMCBBOMKJGL(Vector3 MPHCNMDIPAI, float JHGHGAFBDFG, float EPDELOGPNAC, float INIBDNGHLPN, float LIEABAMBOMG, Vector3 ELMEIGEABIK, float CPBCADFLPMO, float MAOPCAMOEEK, int GHEAKBCACNK)
	{
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = JHGHGAFBDFG;
		pKDCCCNJIEC.EPDELOGPNAC = EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = null;
		pKDCCCNJIEC.JMMJHCOKCGG = null;
		pKDCCCNJIEC.INIBDNGHLPN = INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = false;
		pKDCCCNJIEC.MAOPCAMOEEK = MAOPCAMOEEK;
		pKDCCCNJIEC.FJLBLLLEELD = (DFHALNOAGGC.PEBLJIFMBGC)GHEAKBCACNK;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
	}
}
