using UnityEngine;
using UnityStandardAssets.ImageEffects;

public class FogSettings : MonoBehaviour
{
	public bool MJBKNJBOKDI;

	public Color LADMOMJBEII;

	public float HOCADCCOKBH;

	public FogMode HJINPFPEOEH;

	public float KIFAFIFHCNE;

	public float EBJOMHODDJI;

	public bool LGKHCDAELJI;

	public bool LFDAOGMOIPK;

	public bool NFJAJFKAOBK;

	public float FBMIFHHEOBO;

	public float NNBDAJABIIC;

	public float LIJCAIJIDMD;

	private GlobalFog IBICHIPAJDA;

	private void OBNOHPKPNBG()
	{
		BPPIFOADHBN();
	}

	private void DONOCHMMMDG()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void OHHLOAKBKFK()
	{
		GCCJGAFNJIK();
	}

	private void BPKLLAIPEGF()
	{
		CBHAPDNNNCM();
	}

	private void CJLBKFMJBAN()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JDGAENDKCJO()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void LCCLOEDCGOP()
	{
		BPPIFOADHBN();
	}

	private void IEOENHMCBNP()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void CJAPKAIJAAH()
	{
		ECBIDJFDNPD();
	}

	private void OOPDIAHJKPJ()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void HDNPECCNIAK()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void ACGNKACNAOE()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void CMLJPOCFIIG()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void PFAAHEPCNCP()
	{
		EKIPMOPKJKJ();
	}

	private void OABEHNOPIEE()
	{
		LKOEKKDJFEA();
	}

	private void HGAJCDHEECN()
	{
		LLCIFFCAPNN();
	}

	private void EGPIGGJIOMP()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void CDEIAEFBBAF()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JJGHGOMKKIP()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void GBIBKBNBBKI()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void BKGFAHFGGAA()
	{
		GCCJGAFNJIK();
	}

	private void BIIEAFMDJJM()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void DMEKJGPNDMA()
	{
		KIDFIMOMEHJ();
	}

	private void CFHILPHMOOG()
	{
		NEMLPALPEHA();
	}

	private void BBDMAMKGFAE()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void HFEIGJPACHC()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void NMDBBDBKBBP()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void GIEHNCKABOF()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void CBHAPDNNNCM()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void HDFHPMNEAMB()
	{
		ACGNKACNAOE();
	}

	private void GLEDKIMGOKP()
	{
		CKDLBENMDIC();
	}

	private void GMGLOIFNGIO()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void OnDestroy()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void KIDFIMOMEHJ()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JCELFGKLJBH()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void Start()
	{
		BPPIFOADHBN();
	}

	private void PBFNGLAENEA()
	{
		KIDFIMOMEHJ();
	}

	private void CLICFGKKGBG()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void PGEDLBBPCDC()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void NJNBJAPDFGC()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void FOBOGAOLNGK()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void OKPEKAJDEDD()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void DNAMBMBGDLM()
	{
		JJGHGOMKKIP();
	}

	private void CCMDIJAIPEM()
	{
		CBHAPDNNNCM();
	}

	private void ODIBABNNECL()
	{
		CBHAPDNNNCM();
	}

	private void OLLGBDFCGFL()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void MLPGCEFJLOK()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void IGLCCOCGFPJ()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void ECBIDJFDNPD()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void KEDOACMGCED()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void NNFHLNDHOJF()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void LKOEKKDJFEA()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void DHJONAEGDNM()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void OBBHECACANB()
	{
		CMLJPOCFIIG();
	}

	private void KCJGDLOGJNF()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void ADFPJLHEGFJ()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void EKIPMOPKJKJ()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void KCMDGOGJKEP()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void EKIEGINBAOC()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JCLABHIBIGK()
	{
		CBHAPDNNNCM();
	}

	private void KELNFODGEAO()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void HFKIAIEGNGI()
	{
		CJLBKFMJBAN();
	}

	private void BKPJIIBCOPF()
	{
		EGPIGGJIOMP();
	}

	private void KGMNFAIFNCB()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void KKMANEFGPIL()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void LLCIFFCAPNN()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void HFFEELCNDOE()
	{
		LBJLHLLEFAD();
	}

	private void EAFAKALHKLM()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void PPBPNEHFFKA()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void PIEOPFLGPHC()
	{
		EGPIGGJIOMP();
	}

	private void GCCJGAFNJIK()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void DABGGMNKMOL()
	{
		GCCJGAFNJIK();
	}

	private void HHGGAIHMIII()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void GPPPLKJCLBN()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void CKDLBENMDIC()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JKJNFFLBKJC()
	{
		ECBIDJFDNPD();
	}

	private void LJKLFLJOCFF()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void LBJLHLLEFAD()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void NEMLPALPEHA()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void JPJNMFLDBCE()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void PAEAMOGAJEL()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void JFDLOPCEENO()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	private void KHPDEJJPECO()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void NAJPLAADGEG()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = false;
			IBICHIPAJDA = null;
		}
	}

	[ContextMenu("Set Fog Parameters")]
	private void BPPIFOADHBN()
	{
		IBICHIPAJDA = Camera.main.GetComponent<GlobalFog>();
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = MJBKNJBOKDI;
			IBICHIPAJDA.LADMOMJBEII = LADMOMJBEII;
			IBICHIPAJDA.HOCADCCOKBH = HOCADCCOKBH;
			IBICHIPAJDA.EBJOMHODDJI = EBJOMHODDJI;
			IBICHIPAJDA.HJINPFPEOEH = HJINPFPEOEH;
			IBICHIPAJDA.KIFAFIFHCNE = KIFAFIFHCNE;
			IBICHIPAJDA.LGKHCDAELJI = LGKHCDAELJI;
			IBICHIPAJDA.LFDAOGMOIPK = LFDAOGMOIPK;
			IBICHIPAJDA.NFJAJFKAOBK = NFJAJFKAOBK;
			IBICHIPAJDA.FBMIFHHEOBO = FBMIFHHEOBO;
			IBICHIPAJDA.NNBDAJABIIC = NNBDAJABIIC;
			IBICHIPAJDA.LIJCAIJIDMD = LIJCAIJIDMD;
		}
	}

	private void DFBCIKFOGAL()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}

	private void FMGDJJDEIML()
	{
		NNFHLNDHOJF();
	}

	private void FNEHFNLDGNP()
	{
		if (IBICHIPAJDA != null)
		{
			IBICHIPAJDA.enabled = true;
			IBICHIPAJDA = null;
		}
	}
}
