using System.Runtime.CompilerServices;
using UnityEngine;

public class GameGuiCard : PoolableObject
{
	private sealed class KLFMHBNPGFM
	{
		private sealed class IPLCCJEMLOA
		{
			internal TweenAlpha DJJMADHMLJG;

			internal KLFMHBNPGFM MMALFGIGIPL;

			internal void LMOFHDINPEI(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void KPHEPHDFCKK(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1938f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1183f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1411f, 634f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1321f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1208f, 1737f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1840f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 959f, 436f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 91f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1541f, 1054f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1713f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 152f, 1066f);
				tweenAlpha.onFinished = JLMDEGBHOGA;
			}

			internal void EMKPBGFBPFI(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 694f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1928f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1059f, 631f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 661f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1658f, 1134f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1479f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1220f, 1243f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 827f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 58f, 1676f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 847f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 148f, 435f);
				tweenAlpha.onFinished = EJLGBICBIFK;
			}

			internal void FIBGJHCGHJH(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1110f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 45f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1830f, 181f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 799f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 711f, 441f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1402f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 959f, 808f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1378f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1161f, 971f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1678f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 102f, 1347f);
				tweenAlpha.onFinished = BFMHIICIHKL;
			}

			internal void CMCIGAFHIJL(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 265f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 596f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1652f, 1792f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1618f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1508f, 287f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1611f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 485f, 1468f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 568f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 71f, 1505f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1513f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1666f, 1814f);
				tweenAlpha.onFinished = ENOBKGECBGB;
			}

			internal void ILNPANOCHIH(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1594f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1928f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1482f, 990f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 507f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 241f, 1504f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1791f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 726f, 1964f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 826f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 395f, 1735f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 190f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 649f, 426f);
				tweenAlpha.onFinished = EJLGBICBIFK;
			}

			internal void BFMHIICIHKL(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void DJLGPGPAHCD(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1515f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 333f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 498f, 1151f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 151f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 613f, 308f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1474f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1729f, 680f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 927f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 670f, 1774f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 738f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 400f, 1787f);
				tweenAlpha.onFinished = ENOBKGECBGB;
			}

			internal void HADLONLCLPM(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void ENOBKGECBGB(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void KILJJNKMNHO(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void EJLGBICBIFK(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}

			internal void ILOFOILFGMA(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 517f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 830f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1405f, 571f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1633f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 770f, 243f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 836f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1129f, 719f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1024f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 248f, 720f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1317f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 911f, 677f);
				tweenAlpha.onFinished = DIDKLCKIPGN;
			}

			internal void LJCDGJKCNEC(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 0f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 4f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1f, 0f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 4f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1f, 0f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 4f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1f, 0f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 4f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1f, 0f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 4f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1f, 0f);
				tweenAlpha.onFinished = EJLGBICBIFK;
			}

			internal void NNFHNIMCBLH(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 758f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 203f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 993f, 761f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 207f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 32f, 857f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 880f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 359f, 1256f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1564f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1065f, 1404f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1929f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 618f, 1386f);
				tweenAlpha.onFinished = MMAFECEHENB;
			}

			internal void HHLMDAKDHFK(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1818f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 906f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 275f, 71f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1801f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1749f, 38f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 511f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1030f, 518f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1931f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1968f, 1514f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1375f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 934f, 1085f);
				tweenAlpha.onFinished = HADLONLCLPM;
			}

			internal void PAKIJEIDOBH(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}

			internal void FKBGKGFEEIB(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void NCIAEPGIOIE(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void HHNEBNHCGMO(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 350f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 857f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1480f, 1703f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 872f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1026f, 137f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1125f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1095f, 765f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1730f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 809f, 670f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1172f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 688f, 1653f);
				tweenAlpha.onFinished = ENOBKGECBGB;
			}

			internal void JCFDEFFIHAM(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.BOHCNEDIJPE();
			}

			internal void DIDKLCKIPGN(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}

			internal void IFOPOPPMCFG(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void PPKGMGNKNAE(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1309f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 33f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 557f, 931f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1558f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 798f, 794f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1332f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1105f, 1726f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 978f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1092f, 1366f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1683f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1739f, 660f);
				tweenAlpha.onFinished = EJLGBICBIFK;
			}

			internal void GANNNCEMLPI(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}

			internal void LNKCHLPENAN(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}

			internal void IAAHOKHAJHK(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void DLODDIOIDME(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void CIAOICMCMAM(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void JGEMIBIJMJC(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1757f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 48f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1517f, 1054f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 948f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1696f, 1022f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1700f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 511f, 1436f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 647f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 442f, 1050f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 879f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1767f, 1444f);
				tweenAlpha.onFinished = JCFDEFFIHAM;
			}

			internal void LKAHPHIEMEK(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 721f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1668f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 74f, 308f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 857f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1005f, 1661f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 180f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 688f, 1202f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1360f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1285f, 34f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 133f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1576f, 1150f);
				tweenAlpha.onFinished = EJLGBICBIFK;
			}

			internal void FHDOHCJJEMM(UITweener KPICOKPHMIC)
			{
				DJJMADHMLJG.delay = 1254f;
				TweenAlpha tweenAlpha = TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1179f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1085f, 1710f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1797f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 692f, 1407f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1502f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 508f, 1157f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1247f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 1141f, 592f);
				TweenAlpha.Begin(MMALFGIGIPL.BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 581f * MMALFGIGIPL.BJGCPDNMHDH.JCAFFELIFAO, 505f, 1210f);
				tweenAlpha.onFinished = JLMDEGBHOGA;
			}

			internal void CHPGPDHOOFL(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void MMAFECEHENB(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.OBCAIFMOPPA();
			}

			internal void JLMDEGBHOGA(UITweener GEHACOGJMHA)
			{
				MMALFGIGIPL.BJGCPDNMHDH.DestroyPooled();
			}
		}

		internal TweenRotation ALOMHALCMNH;

		internal GameGuiCard BJGCPDNMHDH;

		internal void HKNCGEMENDB(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 353f, 577f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1252f, 1844f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 516f, 832f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1107f, 876f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 214f, 821f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1276f, 1208f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 561f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1941f, 1096f, 1758f), true).onFinished = OKNAMIKEBDB;
		}

		internal void PAFHFHGFMBO(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1623f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(481f, 778f, 133f), true).onFinished = NLJBMFCOGDK;
		}

		internal void EGBBIPAMJCL(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 250f, 1259f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 402f, 1285f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1372f, 1241f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 414f, 1059f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 712f, 178f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 717f, 1109f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 737f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1363f, 1993f, 991f), true).onFinished = IHIJHCIFONB;
		}

		internal void FCENGDPPIJH(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1697f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1663f, 1572f, 1202f), true).onFinished = EGBBIPAMJCL;
		}

		internal void LBPGIEANDDL(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 792f, 877f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 664f, 877f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1288f, 226f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 306f, 1379f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 94f, 990f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 32f, 1012f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1847f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1242f, 852f, 983f), true).onFinished = HLFDBOIPCGM;
		}

		internal void KGFFOJMFLIF(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 438f, 763f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 1138f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.EMKPBGFBPFI;
		}

		internal void BLEMBJFNOGA(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 776f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1534f, 1380f, 1110f)).onFinished = LBPGIEANDDL;
		}

		internal void PAKIJEIDOBH(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 192f, 1475f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1333f, 1283f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1335f, 1233f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 26f, 1139f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 723f, 510f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1325f, 538f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 343f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1595f, 381f, 1896f), true).onFinished = LOPMGEDOGEP;
		}

		internal void ONCJKBDHHII(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1623f, 829f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 1685f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.CMCIGAFHIJL;
		}

		internal void FKBGKGFEEIB(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1542f, 483f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 435f, 55f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1746f, 969f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1010f, 714f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 393f, 1676f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1468f, 388f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1432f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1953f, 689f, 1804f)).onFinished = JNGEDKMBDDP;
		}

		internal void LMJJCHPKCFK(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 337f, 78f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1078f, 1019f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 358f, 1945f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1154f, 226f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1071f, 205f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 837f, 231f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 890f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1680f, 1951f, 402f), true).onFinished = LOPMGEDOGEP;
		}

		internal void JNGEDKMBDDP(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 691f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(686f, 442f, 1431f), true).onFinished = ODDHAFKPBNO;
		}

		internal void AEDPDJBJMEJ(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1670f, 1755f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 132f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.EMKPBGFBPFI;
		}

		internal void KJDDNPHDANF(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1157f, 864f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 259f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.HHNEBNHCGMO;
		}

		internal void FCFDKEHICIB(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1452f, 1732f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 444f, 1857f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 837f, 1831f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 0f, 438f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 122f, 329f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1998f, 1028f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 415f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(782f, 243f, 178f), true).onFinished = LOPMGEDOGEP;
		}

		internal void KILJJNKMNHO(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 197f, 240f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 310f, 289f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 471f, 709f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1621f, 871f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1104f, 1231f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 857f, 594f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 439f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(738f, 1480f, 1925f)).onFinished = LOPMGEDOGEP;
		}

		internal void NMIFBNPPAIK(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 352f, 477f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1110f, 1765f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 203f, 1956f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1542f, 1147f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 234f, 464f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 78f, 1747f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 78f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(387f, 668f, 1175f), true).onFinished = LOPMGEDOGEP;
		}

		internal void LOPMGEDOGEP(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1706f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1052f, 1669f, 1755f), true).onFinished = BIGNHFCNJLL;
		}

		internal void BIGNHFCNJLL(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 0f, 1f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 0f, 1f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 0f, 1f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 0f, 1f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 0f, 1f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 0f, 0f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 0.75f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(0f, 360f, 0f)).onFinished = LJDCIJDPLLF;
		}

		internal void CIBGFHNGKCF(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1303f, 186f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1341f, 1035f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1422f, 1072f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 439f, 1240f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 959f, 995f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 897f, 1119f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 850f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(731f, 1906f, 1230f)).onFinished = IHIJHCIFONB;
		}

		internal void EBJJKGFOLOA(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 650f, 1471f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 359f, 1899f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 245f, 1154f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 804f, 961f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 140f, 1371f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 260f, 217f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 332f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1235f, 1521f, 108f), true).onFinished = MJLPMDLMCLH;
		}

		internal void LOJKOGKKDIO(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 224f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(179f, 489f, 1443f)).onFinished = GINLPMOGMMF;
		}

		internal void NPPHHHHLIDP(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 97f, 1526f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 70f, 64f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 637f, 1114f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 385f, 1495f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1107f, 439f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1030f, 1521f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1500f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1295f, 1010f, 56f)).onFinished = IPKACAEOMFC;
		}

		internal void EJLGBICBIFK(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 0f, 0f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 0f, 0f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 0f, 0f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 0f, 0f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 0f, 0f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 0f, 1f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 0.75f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(0f, 180f, 0f)).onFinished = HONCMBHEKDP;
		}

		internal void NLJBMFCOGDK(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 139f, 1297f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 378f, 1303f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 205f, 751f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1096f, 1502f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 663f, 1633f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1518f, 1040f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 300f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(826f, 1557f, 1040f)).onFinished = IPKACAEOMFC;
		}

		internal void MJFMLLKALLH(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1724f, 591f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1637f, 1996f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 732f, 1432f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 390f, 559f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1763f, 1799f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 946f, 1502f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1512f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1744f, 1053f, 158f), true).onFinished = IPKACAEOMFC;
		}

		internal void GKCCIMLNGCF(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 564f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1010f, 1381f, 1810f)).onFinished = BIHMLKFDCFK;
		}

		internal void CJPMPGPKIFJ(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1028f, 1454f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1914f, 1756f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 576f, 1271f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1376f, 1369f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1867f, 1232f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1307f, 1561f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 108f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1156f, 1743f, 494f), true).onFinished = HONCMBHEKDP;
		}

		internal void BIHMLKFDCFK(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1429f, 23f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1087f, 248f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 670f, 277f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 399f, 1125f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1795f, 697f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1779f, 758f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 654f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1093f, 75f, 1825f)).onFinished = KGFFOJMFLIF;
		}

		internal void ODDHAFKPBNO(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 990f, 1660f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 642f, 710f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 812f, 1907f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 407f, 698f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1352f, 1802f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1139f, 244f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1611f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(325f, 1339f, 908f), true).onFinished = OKNAMIKEBDB;
		}

		internal void IPKACAEOMFC(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1723f, 95f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 1800f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.LKAHPHIEMEK;
		}

		internal void BIMAACDODIE(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 31f, 1194f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 390f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.HHNEBNHCGMO;
		}

		internal void JMIKKGIOAML(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1949f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(12f, 1955f, 726f), true).onFinished = GMHBLEHENKK;
		}

		internal void LJDCIJDPLLF(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 0.0001f, 1f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 2f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.LJCDGJKCNEC;
		}

		internal void CFDNMILGDLG(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 370f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1529f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(144f, 1886f, 1713f)).onFinished = FCFDKEHICIB;
		}

		internal void AKKPKANMGNP(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1256f, 1694f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 1681f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.KPHEPHDFCKK;
		}

		internal void PCKMJMGLPDG(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 1832f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1079f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(484f, 501f, 692f)).onFinished = IDEPAHOBFCP;
		}

		internal void BMCMDMKGHHO(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 293f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1230f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(179f, 478f, 374f), true).onFinished = FCFDKEHICIB;
		}

		internal void HKMBHFENEIL(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1960f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(17f, 69f, 404f)).onFinished = LBPGIEANDDL;
		}

		internal void OJEBAPHLLPC(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1459f, 318f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1625f, 42f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1191f, 1899f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 553f, 1616f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1774f, 284f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1346f, 391f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 306f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(699f, 896f, 293f)).onFinished = HKMBHFENEIL;
		}

		internal void OABFAOLFMMJ(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 1268f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1829f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1693f, 332f, 1203f), true).onFinished = CJPMPGPKIFJ;
		}

		internal void OPPNIDPBBIM(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1270f, 937f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1247f, 1537f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1234f, 279f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1145f, 1326f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 913f, 1564f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1129f, 1324f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 378f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1643f, 887f, 1598f), true).onFinished = MJLPMDLMCLH;
		}

		internal void LMOFHDINPEI(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 467f, 1387f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 616f, 1609f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1635f, 1711f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1981f, 1060f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1606f, 1525f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1587f, 1788f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 271f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(869f, 833f, 1667f)).onFinished = FCENGDPPIJH;
		}

		internal void DCIBONHCNOC(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 414f, 251f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1466f, 1321f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 673f, 187f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 816f, 1868f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 593f, 1314f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1776f, 1457f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 508f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(508f, 1588f, 940f)).onFinished = BIMAACDODIE;
		}

		internal void JLMDEGBHOGA(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1920f, 791f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1465f, 1862f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1001f, 474f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1400f, 251f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1271f, 94f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1287f, 1451f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 655f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1696f, 9f, 1317f)).onFinished = LOJKOGKKDIO;
		}

		internal void NICDLBCEEEA(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 66f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1414f, 950f, 1021f)).onFinished = NLJBMFCOGDK;
		}

		internal void FHDOHCJJEMM(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 1190f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 453f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(639f, 471f, 132f), true).onFinished = KILJJNKMNHO;
		}

		internal void LJCDGJKCNEC(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 0f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 0.75f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(0f, 90f, -7.5f)).onFinished = EJLGBICBIFK;
		}

		internal void GMHBLEHENKK(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 217f, 1188f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 977f, 1999f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 432f, 956f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1316f, 80f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 707f, 309f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1765f, 442f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1789f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1566f, 1871f, 33f)).onFinished = AKKPKANMGNP;
		}

		internal void DDHOKNIEACI(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 878f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 505f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(178f, 89f, 1016f)).onFinished = FCFDKEHICIB;
		}

		internal void FIBGJHCGHJH(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 839f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1951f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(605f, 392f, 893f)).onFinished = OJEBAPHLLPC;
		}

		internal void DGELDDJAEEF(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 29f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1014f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1744f, 279f, 1511f), true).onFinished = EBJJKGFOLOA;
		}

		internal void MJLPMDLMCLH(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 752f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1603f, 906f, 462f), true).onFinished = LBPGIEANDDL;
		}

		internal void HLFDBOIPCGM(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 692f, 1309f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 1709f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.PPKGMGNKNAE;
		}

		internal void OKNAMIKEBDB(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 546f, 633f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 52f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.JGEMIBIJMJC;
		}

		internal void DLODDIOIDME(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 410f, 1833f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 715f, 725f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 400f, 1834f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 558f, 815f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1133f, 364f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 828f, 199f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1654f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(47f, 491f, 1660f)).onFinished = JNGEDKMBDDP;
		}

		internal void CHOIECFFEMH(UITweener MGDJMGHCAAI)
		{
			ALOMHALCMNH.delay = 1776f;
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 1610f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(1145f, 897f, 437f)).onFinished = LMOFHDINPEI;
		}

		internal void HONCMBHEKDP(UITweener MKAPOHKFIJH)
		{
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 0.75f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(0f, 270f, 0f)).onFinished = BIGNHFCNJLL;
		}

		internal void IHIJHCIFONB(UITweener ELDBECLGFBA)
		{
			IPLCCJEMLOA iPLCCJEMLOA = new IPLCCJEMLOA();
			iPLCCJEMLOA.MMALFGIGIPL = this;
			iPLCCJEMLOA.DJJMADHMLJG = TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 38f, 962f);
			iPLCCJEMLOA.DJJMADHMLJG.delay = 475f * BJGCPDNMHDH.JCAFFELIFAO;
			iPLCCJEMLOA.DJJMADHMLJG.onFinished = iPLCCJEMLOA.LJCDGJKCNEC;
		}

		internal void IDEPAHOBFCP(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1890f, 337f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 293f, 610f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1962f, 1468f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 489f, 1479f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 1961f, 1309f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1894f, 1333f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 551f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(825f, 597f, 1549f)).onFinished = LOJKOGKKDIO;
		}

		internal void CIAOICMCMAM(UITweener CKOINALCMFJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 1246f, 1069f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 865f, 1003f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1848f, 584f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 682f, 1391f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 964f, 675f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 909f, 1102f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 593f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(788f, 1400f, 236f)).onFinished = JNGEDKMBDDP;
		}

		internal void GINLPMOGMMF(UITweener GCNILAHBDMJ)
		{
			TweenAlpha.Begin(BJGCPDNMHDH.KMFGCJEGJJK.gameObject, 653f, 1051f);
			TweenAlpha.Begin(BJGCPDNMHDH.DAANKCOLJGJ.gameObject, 1250f, 1602f);
			TweenAlpha.Begin(BJGCPDNMHDH.EBFDAICCJAK.gameObject, 1199f, 1521f);
			TweenAlpha.Begin(BJGCPDNMHDH.ADEMDNIDBJD.gameObject, 1061f, 1173f);
			TweenAlpha.Begin(BJGCPDNMHDH.FLMNNLHDCFH.gameObject, 680f, 58f);
			TweenAlpha.Begin(BJGCPDNMHDH.FDPONIBIADO.gameObject, 1890f, 329f);
			TweenRotation.Begin(BJGCPDNMHDH.PPAGHBKNOKL, 488f * BJGCPDNMHDH.JCAFFELIFAO, Quaternion.Euler(694f, 1068f, 171f)).onFinished = HLFDBOIPCGM;
		}
	}

	private sealed class JFEEHJPPBBE
	{
		internal TweenAlpha ALOMHALCMNH;

		internal GameGuiCard BJGCPDNMHDH;

		internal void LHPPLGOOLEC(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1144f * BJGCPDNMHDH.JCAFFELIFAO, 1270f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 462f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 564f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1227f, 545f, 436f));
			tweenScale.delay = 1381f;
		}

		internal void KNJBDOADLDO(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 948f * BJGCPDNMHDH.JCAFFELIFAO, 981f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1512f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1939f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(917f, 1371f, 879f));
			tweenScale.delay = 957f;
		}

		internal void INFLOOLPOBK(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 855f * BJGCPDNMHDH.JCAFFELIFAO, 1840f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 1738f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 96f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1976f, 1289f, 54f));
			tweenScale.delay = 1892f;
		}

		internal void CIFEDFPPPOK(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1895f * BJGCPDNMHDH.JCAFFELIFAO, 1654f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 80f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1100f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1633f, 1550f, 241f));
			tweenScale.delay = 278f;
		}

		internal void NAJNECOMDDN(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1874f * BJGCPDNMHDH.JCAFFELIFAO, 853f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 808f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1850f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(938f, 1383f, 672f));
			tweenScale.delay = 1153f;
		}

		internal void AMIJFGBOCLC(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1990f * BJGCPDNMHDH.JCAFFELIFAO, 457f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1634f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1630f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1469f, 343f, 1725f));
			tweenScale.delay = 1290f;
		}

		internal void MPHECHCFCAN(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 401f * BJGCPDNMHDH.JCAFFELIFAO, 1085f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1332f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 719f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(422f, 864f, 1186f));
			tweenScale.delay = 124f;
		}

		internal void GMFJFMHNDMC(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 534f * BJGCPDNMHDH.JCAFFELIFAO, 1522f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 245f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1744f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(940f, 241f, 1458f));
			tweenScale.delay = 925f;
		}

		internal void MFCNOIDCJME(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1754f * BJGCPDNMHDH.JCAFFELIFAO, 487f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 422f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 562f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1969f, 300f, 1264f));
			tweenScale.delay = 711f;
		}

		internal void BDCAFHOHEGM(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1477f * BJGCPDNMHDH.JCAFFELIFAO, 1643f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1557f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 380f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(15f, 855f, 1643f));
			tweenScale.delay = 158f;
		}

		internal void FIBGJHCGHJH(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1218f * BJGCPDNMHDH.JCAFFELIFAO, 1364f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 1944f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1051f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(711f, 1701f, 1250f));
			tweenScale.delay = 79f;
		}

		internal void FHDOHCJJEMM(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1225f * BJGCPDNMHDH.JCAFFELIFAO, 371f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 13f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 805f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1506f, 1833f, 910f));
			tweenScale.delay = 622f;
		}

		internal void CHDOECNGOPM(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 929f * BJGCPDNMHDH.JCAFFELIFAO, 384f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 118f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1075f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(558f, 387f, 224f));
			tweenScale.delay = 1660f;
		}

		internal void NNIJEDKBPGJ(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 473f * BJGCPDNMHDH.JCAFFELIFAO, 1240f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1783f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1165f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(388f, 328f, 1131f));
			tweenScale.delay = 1506f;
		}

		internal void MMEEJDGGAID(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 523f * BJGCPDNMHDH.JCAFFELIFAO, 410f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 851f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 561f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(379f, 1558f, 1549f));
			tweenScale.delay = 368f;
		}

		internal void BMCMDMKGHHO(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 213f * BJGCPDNMHDH.JCAFFELIFAO, 1692f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 990f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1583f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1650f, 928f, 1259f));
			tweenScale.delay = 973f;
		}

		internal void HHLMDAKDHFK(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 135f * BJGCPDNMHDH.JCAFFELIFAO, 104f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 1144f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1850f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(463f, 1787f, 477f));
			tweenScale.delay = 454f;
		}

		internal void OKNCFDMEFGJ(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 191f * BJGCPDNMHDH.JCAFFELIFAO, 167f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 29f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1302f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(679f, 1398f, 838f));
			tweenScale.delay = 216f;
		}

		internal void CFJHDIHLIML(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 1511f * BJGCPDNMHDH.JCAFFELIFAO, 187f);
			ALOMHALCMNH.method = UITweener.Method.Linear;
			tweenAlpha.delay = 225f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 603f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(1282f, 101f, 821f));
			tweenScale.delay = 1280f;
		}

		internal void LJCDGJKCNEC(UITweener MGDJMGHCAAI)
		{
			TweenAlpha tweenAlpha = TweenAlpha.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 3f * BJGCPDNMHDH.JCAFFELIFAO, 0f);
			ALOMHALCMNH.method = UITweener.Method.EaseIn;
			tweenAlpha.delay = 1.5f * BJGCPDNMHDH.JCAFFELIFAO;
			TweenScale tweenScale = TweenScale.Begin(BJGCPDNMHDH.LCPBNBLGFIA.gameObject, 4.5f * BJGCPDNMHDH.JCAFFELIFAO, new Vector3(698f, 850f, 1f));
			tweenScale.delay = 0f;
		}
	}

	public UISprite LCPBNBLGFIA;

	[Header("Header")]
	public GameObject NFNLBEGFLHC;

	public UISprite GJIGEFJAKNM;

	public UILabel ENCELMJDBLG;

	[Header("Card look")]
	public GameObject PPAGHBKNOKL;

	public UISprite KMFGCJEGJJK;

	public UISprite DAANKCOLJGJ;

	public UITexture EBFDAICCJAK;

	public UISprite ADEMDNIDBJD;

	public UILabel FLMNNLHDCFH;

	public UISprite FDPONIBIADO;

	[Header("Progress icon Top left")]
	public UISprite PAENPHMEMGC;

	public UISprite IMOHHDEDEKJ;

	private Vector3 JMHODKEGMBN;

	private float JCAFFELIFAO = 0.2f;

	private CardsGuiElementNew KPGIODPAEHK;

	private Card GHINGDGFNJC;

	private bool PNFNJKJLPIP;

	public Card card
	{
		get
		{
			return GHINGDGFNJC;
		}
		set
		{
			if (value == null && GHINGDGFNJC != null)
			{
				GHINGDGFNJC.HideInMenu();
			}
			GHINGDGFNJC = value;
			if (GHINGDGFNJC != null)
			{
				GHINGDGFNJC.ShowInMenu();
			}
		}
	}

	public void DCABFNHBOIG()
	{
		PNFNJKJLPIP = true;
	}

	public virtual void NNMGFLHFDGJ()
	{
		if (PLPBGNOCCPI())
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(false);
			UITweener[] array = componentsInChildren;
			foreach (UITweener uITweener in array)
			{
				uITweener.enabled = false;
			}
		}
		if (MNGIIPGDAPE() != null)
		{
			card = null;
		}
		base.OBCAIFMOPPA();
	}

	public void JJNNFGCJKPM()
	{
		if (!(card == null))
		{
			Color color = Card.CardBackgroundColor(FBFDHPJBFHI().rarity, KMFGCJEGJJK.alpha);
			KMFGCJEGJJK.color = color * Color.gray;
			DAANKCOLJGJ.color = Color.gray;
			EBFDAICCJAK.color = Color.gray;
			ADEMDNIDBJD.color = Color.gray * LFFBBBDFCCF().bonusIconSmallCardColor;
		}
	}

	[SpecialName]
	public Card MNGIIPGDAPE()
	{
		return GHINGDGFNJC;
	}

	[SpecialName]
	public Card FBFDHPJBFHI()
	{
		return GHINGDGFNJC;
	}

	protected void ECFIMCCNBBN()
	{
		if (IMOHHDEDEKJ.gameObject.activeSelf)
		{
			PAENPHMEMGC.fillAmount = 111f - CardManager.instance.Progress;
			if (CardManager.instance.Progress == 497f)
			{
				PAENPHMEMGC.gameObject.SetActive(false);
				IMOHHDEDEKJ.gameObject.SetActive(false);
				SetUpWhite();
			}
		}
		if (!EBFDAICCJAK.gameObject.activeSelf && MNGIIPGDAPE() != null && MNGIIPGDAPE().iconTexture != null)
		{
			DAANKCOLJGJ.gameObject.SetActive(false);
			EBFDAICCJAK.gameObject.SetActive(true);
			EBFDAICCJAK.mainTexture = card.iconTexture;
		}
	}

	private void BDHGBLPMOAO()
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 1467f * JCAFFELIFAO, new Vector3(1992f, 996f, 1656f), new Vector3(529f, 1583f, 1481f));
		tweenScale.delay = 1025f;
		tweenScale.onFinished = PEBJOAGKBPF;
	}

	public void NBCNKEAMDOJ()
	{
		PNFNJKJLPIP = true;
	}

	private void LLJPNKBIKAJ(UITweener CKOINALCMFJ)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 465f * JCAFFELIFAO, new Vector3(922f, 1597f, 1755f), new Vector3(1435f, 1810f, 1102f));
		tweenScale.delay = 1374f;
		tweenScale.onFinished = HDHIKKILOHD;
	}

	private void KAFGKBNKLAB(float KALLNCAFIMP)
	{
		KLFMHBNPGFM kLFMHBNPGFM = new KLFMHBNPGFM();
		kLFMHBNPGFM.BJGCPDNMHDH = this;
		kLFMHBNPGFM.ALOMHALCMNH = TweenRotation.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, Quaternion.Euler(0f, 0f, 0f), Quaternion.Euler(0f, 0f, -15f));
		kLFMHBNPGFM.ALOMHALCMNH.method = UITweener.Method.Linear;
		kLFMHBNPGFM.ALOMHALCMNH.delay = KALLNCAFIMP;
		kLFMHBNPGFM.ALOMHALCMNH.onFinished = kLFMHBNPGFM.LJCDGJKCNEC;
	}

	public void InitFromCard(CardsGuiElementNew FBJCCPKCPDF, Card DFFBEFJNDLG, int IDLMJLCFMJG)
	{
		PNFNJKJLPIP = true;
		KPGIODPAEHK = FBJCCPKCPDF;
		card = DFFBEFJNDLG;
		SetUpWhite();
		card.SetUpSmallCard(KMFGCJEGJJK, DAANKCOLJGJ, ADEMDNIDBJD, FLMNNLHDCFH, EBFDAICCJAK);
		FDPONIBIADO.alpha = 0f;
		LCPBNBLGFIA.color = Colours.blue;
		ENCELMJDBLG.text = card.cardName.ToUpper();
		GJIGEFJAKNM.transform.localScale = new Vector3(130f + ENCELMJDBLG.relativeSize.x * ENCELMJDBLG.transform.localScale.x, 74f, 1f);
		PFFGCONBALO();
		base.transform.localPosition = new Vector3(base.transform.localPosition.x, base.transform.localPosition.y, IDLMJLCFMJG * 2);
		GetComponent<Collider>().enabled = true;
		PAENPHMEMGC.gameObject.SetActive(false);
		IMOHHDEDEKJ.gameObject.SetActive(false);
	}

	public void PlayProgress()
	{
		PAENPHMEMGC.gameObject.SetActive(true);
		IMOHHDEDEKJ.gameObject.SetActive(true);
		FLMNNLHDCFH.color = Color.gray;
		SetUpGray();
	}

	private void LPNBGGENNBH(UITweener MGDJMGHCAAI)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 113f * JCAFFELIFAO, new Vector3(733f, 1045f, 1893f), new Vector3(376f, 85f, 894f));
		tweenScale.delay = 667f * JCAFFELIFAO;
		tweenScale.onFinished = LLJPNKBIKAJ;
	}

	public virtual void GLMGMOICPFK()
	{
		if (base.isInstantiated)
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(true);
			UITweener[] array = componentsInChildren;
			for (int i = 0; i < array.Length; i += 0)
			{
				UITweener uITweener = array[i];
				uITweener.enabled = true;
			}
		}
		if (MNGIIPGDAPE() != null)
		{
			DDCJFGCKEIF(null);
		}
		base.BOHCNEDIJPE();
	}

	public void FBFDNCIOMPF(CardsGuiElementNew FBJCCPKCPDF, Card DFFBEFJNDLG, int IDLMJLCFMJG)
	{
		PNFNJKJLPIP = false;
		KPGIODPAEHK = FBJCCPKCPDF;
		DDCJFGCKEIF(DFFBEFJNDLG);
		AGMMHJIJHLI();
		FBFDHPJBFHI().SetUpSmallCard(KMFGCJEGJJK, DAANKCOLJGJ, ADEMDNIDBJD, FLMNNLHDCFH, EBFDAICCJAK);
		FDPONIBIADO.alpha = 202f;
		LCPBNBLGFIA.color = Colours.blue;
		ENCELMJDBLG.text = card.cardName.ToUpper();
		GJIGEFJAKNM.transform.localScale = new Vector3(1009f + ENCELMJDBLG.relativeSize.x * ENCELMJDBLG.transform.localScale.x, 1814f, 1216f);
		FJPBFMNBEIB();
		base.transform.localPosition = new Vector3(base.transform.localPosition.x, base.transform.localPosition.y, IDLMJLCFMJG * 8);
		GetComponent<Collider>().enabled = false;
		PAENPHMEMGC.gameObject.SetActive(true);
		IMOHHDEDEKJ.gameObject.SetActive(false);
	}

	public void IDNCCEMFGFE()
	{
		PNFNJKJLPIP = false;
	}

	private void NGBDKJIFFOB(UITweener MGDJMGHCAAI)
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 1395f);
		tweenAlpha.delay = 475f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 995f);
		tweenAlpha2.delay = 1844f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(1912f, 1754f, 19f));
		tweenPosition.delay = 1252f * JCAFFELIFAO;
	}

	public void MGGLFJENAFH()
	{
		Debug.Log("Exception message: ");
		TweenPosition.Begin(base.gameObject, 1013f, base.transform.localPosition, false);
		TweenScale.Begin(base.gameObject, 1803f, base.transform.localScale);
		TweenRotation.Begin(base.gameObject, 416f, Quaternion.identity);
		CardManager.instance.UseCard(card);
		Collider component = GetComponent<Collider>();
		if (component != null)
		{
			component.enabled = false;
		}
		EFGIDENDDFE();
		JEJHOHLFMFG();
		NNJFGBAICJE(JCAFFELIFAO);
		KILNCIAPDHK(1447f * JCAFFELIFAO);
		JEBEPPALANP();
		CHKBNGDKNHH();
	}

	public void PPEKLNANDKM()
	{
		PNFNJKJLPIP = true;
	}

	public void LNHFCLKGKBG()
	{
		PNFNJKJLPIP = false;
	}

	private void IPDGMEHPMFH(UITweener MGDJMGHCAAI)
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 1780f);
		tweenAlpha.delay = 1135f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 1419f);
		tweenAlpha2.delay = 1827f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(82f, 91f, 667f));
		tweenPosition.delay = 1065f * JCAFFELIFAO;
	}

	private void JMOFGBNKLEK()
	{
		JFEEHJPPBBE jFEEHJPPBBE = new JFEEHJPPBBE();
		jFEEHJPPBBE.BJGCPDNMHDH = this;
		jFEEHJPPBBE.ALOMHALCMNH = TweenAlpha.Begin(LCPBNBLGFIA.gameObject, 31f * JCAFFELIFAO, 1171f, 1097f);
		jFEEHJPPBBE.ALOMHALCMNH.method = UITweener.Method.EaseIn;
		jFEEHJPPBBE.ALOMHALCMNH.delay = 1282f * JCAFFELIFAO;
		TweenScale tweenScale = TweenScale.Begin(LCPBNBLGFIA.gameObject, 1493f * JCAFFELIFAO, new Vector3(1489f, 139f, 1765f), new Vector3(1049f, 1263f, 795f));
		tweenScale.delay = 1749f * JCAFFELIFAO;
		tweenScale.onFinished = jFEEHJPPBBE.FHDOHCJJEMM;
	}

	public void MFNHEGGJOKN()
	{
		PAENPHMEMGC.gameObject.SetActive(true);
		IMOHHDEDEKJ.gameObject.SetActive(false);
		FLMNNLHDCFH.color = Color.gray;
		SetUpGray();
	}

	public void SetUpGray()
	{
		if (!(card == null))
		{
			Color color = Card.CardBackgroundColor(card.rarity, KMFGCJEGJJK.alpha);
			KMFGCJEGJJK.color = color * Color.gray;
			DAANKCOLJGJ.color = Color.gray;
			EBFDAICCJAK.color = Color.gray;
			ADEMDNIDBJD.color = Color.gray * card.bonusIconSmallCardColor;
		}
	}

	private void FBDIBOKNMIC()
	{
		float num = 1841f;
		Vector3 vector = new Vector3(284f, 1091f, 291f);
		vector.x -= num;
		Vector3 vector2 = (vector - base.transform.localPosition) / base.transform.localScale.x;
		vector2.z = 1197f;
		JMHODKEGMBN = PPAGHBKNOKL.transform.localPosition;
		PPAGHBKNOKL.transform.localPosition -= vector2;
		base.transform.localPosition = vector.ReplaceZ(1009f);
	}

	[CompilerGenerated]
	private void LJBEFIJIJKE(UITweener MKAPOHKFIJH)
	{
		TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
	}

	private void BAABALCMIMI(UITweener CKOINALCMFJ)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 642f * JCAFFELIFAO, new Vector3(1284f, 768f, 1172f), new Vector3(704f, 560f, 1964f));
		tweenScale.delay = 211f;
		tweenScale.onFinished = delegate
		{
			TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
		};
	}

	private void IGINOBIGEEJ(UITweener CKOINALCMFJ)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 932f * JCAFFELIFAO, new Vector3(1478f, 1157f, 642f), new Vector3(530f, 719f, 1928f));
		tweenScale.delay = 1523f;
		tweenScale.onFinished = HHFOAOLBBMF;
	}

	public virtual void KIFFEEEDFPD()
	{
		if (PPHLEDLNGIN())
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(false);
			UITweener[] array = componentsInChildren;
			for (int i = 1; i < array.Length; i++)
			{
				UITweener uITweener = array[i];
				uITweener.enabled = true;
			}
		}
		if (card != null)
		{
			card = null;
		}
		base.DestroyPooled();
	}

	public void NGPLJBMLHMA()
	{
		PAENPHMEMGC.gameObject.SetActive(false);
		IMOHHDEDEKJ.gameObject.SetActive(false);
		FLMNNLHDCFH.color = Color.gray;
		JJNNFGCJKPM();
	}

	[CompilerGenerated]
	private void IHCDILDNIBK(UITweener MGDJMGHCAAI)
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 0f);
		tweenAlpha.delay = 3.75f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 0f);
		tweenAlpha2.delay = 3.75f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(80f, 352f, 0f));
		tweenPosition.delay = 3.75f * JCAFFELIFAO;
	}

	public void Disable()
	{
		PNFNJKJLPIP = false;
	}

	private void KEHDGPEFHAC()
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 0f, 1f);
		tweenAlpha.delay = 1.75f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 0f, 1f);
		tweenAlpha2.delay = 1.75f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(-80f, 352f, 0f), new Vector3(0f, 352f, 0f));
		tweenPosition.delay = 1.75f * JCAFFELIFAO;
		tweenPosition.onFinished = delegate
		{
			TweenAlpha tweenAlpha3 = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 0f);
			tweenAlpha3.delay = 3.75f * JCAFFELIFAO;
			TweenAlpha tweenAlpha4 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 0f);
			tweenAlpha4.delay = 3.75f * JCAFFELIFAO;
			TweenPosition tweenPosition2 = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(80f, 352f, 0f));
			tweenPosition2.delay = 3.75f * JCAFFELIFAO;
		};
	}

	public void AGMMHJIJHLI()
	{
		if (!(card == null))
		{
			Color color = Card.CardBackgroundColor(LFFBBBDFCCF().rarity, KMFGCJEGJJK.alpha);
			KMFGCJEGJJK.color = color;
			DAANKCOLJGJ.color = Color.white;
			EBFDAICCJAK.color = Color.white;
			ADEMDNIDBJD.color = LFFBBBDFCCF().bonusIconSmallCardColor;
			FLMNNLHDCFH.color = Color.white;
		}
	}

	public void EMIIPNIGKCK()
	{
		PAENPHMEMGC.gameObject.SetActive(false);
		IMOHHDEDEKJ.gameObject.SetActive(false);
		FLMNNLHDCFH.color = Color.gray;
		JJNNFGCJKPM();
	}

	[SpecialName]
	public void OIGJLNEHNNP(Card IDEBKDPMPGM)
	{
		if (IDEBKDPMPGM == null && GHINGDGFNJC != null)
		{
			GHINGDGFNJC.HideInMenu();
		}
		GHINGDGFNJC = IDEBKDPMPGM;
		if (GHINGDGFNJC != null)
		{
			GHINGDGFNJC.ShowInMenu();
		}
	}

	public void JOJCILINGIA()
	{
		PNFNJKJLPIP = true;
	}

	private void PFFGCONBALO()
	{
		TweenPosition.Begin(base.gameObject, 0f, base.transform.localPosition).delay = 0f;
		TweenScale.Begin(base.gameObject, 0f, base.transform.localScale).delay = 0f;
		TweenRotation.Begin(base.gameObject, 0f, Quaternion.identity).delay = 0f;
		TweenPosition.Begin(PPAGHBKNOKL, 0f, PPAGHBKNOKL.transform.localPosition).delay = 0f;
		TweenScale.Begin(PPAGHBKNOKL, 0f, Vector3.one).delay = 0f;
		TweenRotation.Begin(PPAGHBKNOKL, 0f, Quaternion.identity).delay = 0f;
		TweenAlpha.Begin(KMFGCJEGJJK.gameObject, 0f, 1f).delay = 0f;
		TweenAlpha.Begin(DAANKCOLJGJ.gameObject, 0f, 1f).delay = 0f;
		TweenAlpha.Begin(EBFDAICCJAK.gameObject, 0f, 1f).delay = 0f;
		TweenAlpha.Begin(ADEMDNIDBJD.gameObject, 0f, 1f).delay = 0f;
		TweenAlpha.Begin(FLMNNLHDCFH.gameObject, 0f, 1f).delay = 0f;
		TweenAlpha.Begin(LCPBNBLGFIA.gameObject, 0f, 0f).delay = 0f;
		TweenScale.Begin(LCPBNBLGFIA.gameObject, 0f, new Vector3(512f, 624f, 1f)).delay = 0f;
		TweenAlpha.Begin(GJIGEFJAKNM.gameObject, 0f, 0f).delay = 0f;
		TweenAlpha.Begin(ENCELMJDBLG.gameObject, 0f, 0f).delay = 0f;
		TweenPosition.Begin(NFNLBEGFLHC, 0f, new Vector3(-80f, 352f, 0f)).delay = 0f;
	}

	[SpecialName]
	public void DDCJFGCKEIF(Card IDEBKDPMPGM)
	{
		if (IDEBKDPMPGM == null && GHINGDGFNJC != null)
		{
			GHINGDGFNJC.HideInMenu();
		}
		GHINGDGFNJC = IDEBKDPMPGM;
		if (GHINGDGFNJC != null)
		{
			GHINGDGFNJC.ShowInMenu();
		}
	}

	[SpecialName]
	public Card LFFBBBDFCCF()
	{
		return GHINGDGFNJC;
	}

	public void MKFHDIAOEKH(CardsGuiElementNew FBJCCPKCPDF, Card DFFBEFJNDLG, int IDLMJLCFMJG)
	{
		PNFNJKJLPIP = true;
		KPGIODPAEHK = FBJCCPKCPDF;
		card = DFFBEFJNDLG;
		AGMMHJIJHLI();
		LFFBBBDFCCF().SetUpSmallCard(KMFGCJEGJJK, DAANKCOLJGJ, ADEMDNIDBJD, FLMNNLHDCFH, EBFDAICCJAK);
		FDPONIBIADO.alpha = 1411f;
		LCPBNBLGFIA.color = Colours.blue;
		ENCELMJDBLG.text = FBFDHPJBFHI().cardName.ToUpper();
		GJIGEFJAKNM.transform.localScale = new Vector3(467f + ENCELMJDBLG.relativeSize.x * ENCELMJDBLG.transform.localScale.x, 1461f, 535f);
		FJPBFMNBEIB();
		base.transform.localPosition = new Vector3(base.transform.localPosition.x, base.transform.localPosition.y, IDLMJLCFMJG * 7);
		GetComponent<Collider>().enabled = false;
		PAENPHMEMGC.gameObject.SetActive(false);
		IMOHHDEDEKJ.gameObject.SetActive(true);
	}

	public virtual void HOCPBJGFEON()
	{
		if (JHJJKEBNGEN())
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(false);
			UITweener[] array = componentsInChildren;
			for (int i = 1; i < array.Length; i += 0)
			{
				UITweener uITweener = array[i];
				uITweener.enabled = false;
			}
		}
		if (card != null)
		{
			DDCJFGCKEIF(null);
		}
		base.BOHCNEDIJPE();
	}

	private void FJPBFMNBEIB()
	{
		TweenPosition.Begin(base.gameObject, 343f, base.transform.localPosition).delay = 1263f;
		TweenScale.Begin(base.gameObject, 1104f, base.transform.localScale).delay = 1058f;
		TweenRotation.Begin(base.gameObject, 1559f, Quaternion.identity, true).delay = 1369f;
		TweenPosition.Begin(PPAGHBKNOKL, 395f, PPAGHBKNOKL.transform.localPosition, false).delay = 471f;
		TweenScale.Begin(PPAGHBKNOKL, 1908f, Vector3.one).delay = 150f;
		TweenRotation.Begin(PPAGHBKNOKL, 1493f, Quaternion.identity).delay = 150f;
		TweenAlpha.Begin(KMFGCJEGJJK.gameObject, 465f, 152f).delay = 899f;
		TweenAlpha.Begin(DAANKCOLJGJ.gameObject, 1602f, 1434f).delay = 1160f;
		TweenAlpha.Begin(EBFDAICCJAK.gameObject, 1370f, 623f).delay = 1879f;
		TweenAlpha.Begin(ADEMDNIDBJD.gameObject, 161f, 374f).delay = 834f;
		TweenAlpha.Begin(FLMNNLHDCFH.gameObject, 1917f, 250f).delay = 1590f;
		TweenAlpha.Begin(LCPBNBLGFIA.gameObject, 1106f, 599f).delay = 1657f;
		TweenScale.Begin(LCPBNBLGFIA.gameObject, 1441f, new Vector3(1846f, 1869f, 179f)).delay = 474f;
		TweenAlpha.Begin(GJIGEFJAKNM.gameObject, 451f, 1317f).delay = 43f;
		TweenAlpha.Begin(ENCELMJDBLG.gameObject, 380f, 84f).delay = 1730f;
		TweenPosition.Begin(NFNLBEGFLHC, 1290f, new Vector3(256f, 595f, 1687f)).delay = 1144f;
	}

	protected void Update()
	{
		if (IMOHHDEDEKJ.gameObject.activeSelf)
		{
			PAENPHMEMGC.fillAmount = 1f - CardManager.instance.Progress;
			if (CardManager.instance.Progress == 0f)
			{
				PAENPHMEMGC.gameObject.SetActive(false);
				IMOHHDEDEKJ.gameObject.SetActive(false);
				SetUpWhite();
			}
		}
		if (!EBFDAICCJAK.gameObject.activeSelf && card != null && card.iconTexture != null)
		{
			DAANKCOLJGJ.gameObject.SetActive(false);
			EBFDAICCJAK.gameObject.SetActive(true);
			EBFDAICCJAK.mainTexture = card.iconTexture;
		}
	}

	private void NNJFGBAICJE(float KALLNCAFIMP)
	{
		KLFMHBNPGFM kLFMHBNPGFM = new KLFMHBNPGFM();
		kLFMHBNPGFM.BJGCPDNMHDH = this;
		kLFMHBNPGFM.ALOMHALCMNH = TweenRotation.Begin(PPAGHBKNOKL, 676f * JCAFFELIFAO, Quaternion.Euler(609f, 1109f, 690f), Quaternion.Euler(37f, 896f, 746f));
		kLFMHBNPGFM.ALOMHALCMNH.method = UITweener.Method.Linear;
		kLFMHBNPGFM.ALOMHALCMNH.delay = KALLNCAFIMP;
		kLFMHBNPGFM.ALOMHALCMNH.onFinished = kLFMHBNPGFM.LJCDGJKCNEC;
	}

	public void ENDACAMAGBJ()
	{
		PNFNJKJLPIP = true;
	}

	private void KGNKNLAHMAF(UITweener MGDJMGHCAAI)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 554f * JCAFFELIFAO, new Vector3(1544f, 824f, 684f), new Vector3(199f, 1367f, 1250f));
		tweenScale.delay = 1163f * JCAFFELIFAO;
		tweenScale.onFinished = IGINOBIGEEJ;
	}

	public void NBANGBLGKDK()
	{
		PNFNJKJLPIP = false;
	}

	[CompilerGenerated]
	private void KGOOACGDLID(UITweener MGDJMGHCAAI)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.28f, 1.28f, 1f));
		tweenScale.delay = 2f * JCAFFELIFAO;
		tweenScale.onFinished = delegate
		{
			TweenScale tweenScale2 = TweenScale.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, new Vector3(1.28f, 1.28f, 1f), new Vector3(1.33f, 1.33f, 1f));
			tweenScale2.delay = 0f;
			tweenScale2.onFinished = delegate
			{
				TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
			};
		};
	}

	private void CHKBNGDKNHH()
	{
		JFEEHJPPBBE jFEEHJPPBBE = new JFEEHJPPBBE();
		jFEEHJPPBBE.BJGCPDNMHDH = this;
		jFEEHJPPBBE.ALOMHALCMNH = TweenAlpha.Begin(LCPBNBLGFIA.gameObject, 2f * JCAFFELIFAO, 0f, 1f);
		jFEEHJPPBBE.ALOMHALCMNH.method = UITweener.Method.EaseOut;
		jFEEHJPPBBE.ALOMHALCMNH.delay = 4f * JCAFFELIFAO;
		TweenScale tweenScale = TweenScale.Begin(LCPBNBLGFIA.gameObject, 2.5f * JCAFFELIFAO, new Vector3(512f, 624f, 1f), new Vector3(284f, 346f, 1f));
		tweenScale.delay = 4f * JCAFFELIFAO;
		tweenScale.onFinished = jFEEHJPPBBE.LJCDGJKCNEC;
	}

	private void DAPJKMMFCAD()
	{
		TweenPosition.Begin(base.gameObject, 250f, base.transform.localPosition).delay = 1509f;
		TweenScale.Begin(base.gameObject, 1219f, base.transform.localScale).delay = 276f;
		TweenRotation.Begin(base.gameObject, 1557f, Quaternion.identity, true).delay = 136f;
		TweenPosition.Begin(PPAGHBKNOKL, 722f, PPAGHBKNOKL.transform.localPosition).delay = 111f;
		TweenScale.Begin(PPAGHBKNOKL, 746f, Vector3.one).delay = 956f;
		TweenRotation.Begin(PPAGHBKNOKL, 1789f, Quaternion.identity, true).delay = 874f;
		TweenAlpha.Begin(KMFGCJEGJJK.gameObject, 1097f, 1992f).delay = 1814f;
		TweenAlpha.Begin(DAANKCOLJGJ.gameObject, 580f, 942f).delay = 1856f;
		TweenAlpha.Begin(EBFDAICCJAK.gameObject, 332f, 481f).delay = 377f;
		TweenAlpha.Begin(ADEMDNIDBJD.gameObject, 1466f, 1915f).delay = 1519f;
		TweenAlpha.Begin(FLMNNLHDCFH.gameObject, 807f, 691f).delay = 1128f;
		TweenAlpha.Begin(LCPBNBLGFIA.gameObject, 474f, 193f).delay = 1789f;
		TweenScale.Begin(LCPBNBLGFIA.gameObject, 979f, new Vector3(1155f, 31f, 492f)).delay = 1288f;
		TweenAlpha.Begin(GJIGEFJAKNM.gameObject, 1747f, 819f).delay = 472f;
		TweenAlpha.Begin(ENCELMJDBLG.gameObject, 1108f, 1017f).delay = 812f;
		TweenPosition.Begin(NFNLBEGFLHC, 1579f, new Vector3(1478f, 621f, 997f)).delay = 667f;
	}

	private void HBJGCCPGHMP(UITweener MGDJMGHCAAI)
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 173f);
		tweenAlpha.delay = 760f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 1405f);
		tweenAlpha2.delay = 1936f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(1492f, 1940f, 3f), false);
		tweenPosition.delay = 8f * JCAFFELIFAO;
	}

	public void NKFILFOLAKD()
	{
		PNFNJKJLPIP = false;
	}

	private void HJAMEMJGLCB(UITweener MGDJMGHCAAI)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 240f * JCAFFELIFAO, new Vector3(1120f, 1526f, 676f), new Vector3(848f, 974f, 222f));
		tweenScale.delay = 1638f * JCAFFELIFAO;
		tweenScale.onFinished = IGINOBIGEEJ;
	}

	public override void DestroyPooled()
	{
		if (base.isInstantiated)
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(true);
			UITweener[] array = componentsInChildren;
			foreach (UITweener uITweener in array)
			{
				uITweener.enabled = false;
			}
		}
		if (card != null)
		{
			card = null;
		}
		base.DestroyPooled();
	}

	private void LBPDOFMOPOD(float KALLNCAFIMP)
	{
		TweenPosition tweenPosition = TweenPosition.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, JMHODKEGMBN);
		tweenPosition.delay = KALLNCAFIMP;
	}

	public void AGBEIIDNDCJ()
	{
		PNFNJKJLPIP = false;
	}

	public void OEKHPGBJGAL()
	{
		PNFNJKJLPIP = true;
	}

	public void UseCard()
	{
		Debug.Log("Clicked on game CARD (bottom screen)");
		TweenPosition.Begin(base.gameObject, 0f, base.transform.localPosition);
		TweenScale.Begin(base.gameObject, 0f, base.transform.localScale);
		TweenRotation.Begin(base.gameObject, 0f, Quaternion.identity);
		CardManager.instance.UseCard(card);
		Collider component = GetComponent<Collider>();
		if (component != null)
		{
			component.enabled = false;
		}
		EFGIDENDDFE();
		JEJHOHLFMFG();
		KAFGKBNKLAB(JCAFFELIFAO);
		LBPDOFMOPOD(1.5f * JCAFFELIFAO);
		KEHDGPEFHAC();
		CHKBNGDKNHH();
	}

	public void DJAGAANNPIG()
	{
		PNFNJKJLPIP = true;
	}

	public void SetUpWhite()
	{
		if (!(card == null))
		{
			Color color = Card.CardBackgroundColor(card.rarity, KMFGCJEGJJK.alpha);
			KMFGCJEGJJK.color = color;
			DAANKCOLJGJ.color = Color.white;
			EBFDAICCJAK.color = Color.white;
			ADEMDNIDBJD.color = card.bonusIconSmallCardColor;
			FLMNNLHDCFH.color = Color.white;
		}
	}

	private void KILNCIAPDHK(float KALLNCAFIMP)
	{
		TweenPosition tweenPosition = TweenPosition.Begin(PPAGHBKNOKL, 1776f * JCAFFELIFAO, JMHODKEGMBN);
		tweenPosition.delay = KALLNCAFIMP;
	}

	public void AELDOGHDFNL()
	{
		PNFNJKJLPIP = true;
	}

	public void NDMGDOHJFDL()
	{
		PNFNJKJLPIP = false;
	}

	private void JEJHOHLFMFG()
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 3f * JCAFFELIFAO, new Vector3(1f, 1f, 1f), new Vector3(1.33f, 1.33f, 1f));
		tweenScale.delay = 0f;
		tweenScale.onFinished = delegate
		{
			TweenScale tweenScale2 = TweenScale.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.28f, 1.28f, 1f));
			tweenScale2.delay = 2f * JCAFFELIFAO;
			tweenScale2.onFinished = delegate
			{
				TweenScale tweenScale3 = TweenScale.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, new Vector3(1.28f, 1.28f, 1f), new Vector3(1.33f, 1.33f, 1f));
				tweenScale3.delay = 0f;
				tweenScale3.onFinished = delegate
				{
					TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
				};
			};
		};
	}

	public virtual void BNFHNJOPJCK()
	{
		if (base.isInstantiated)
		{
			UITweener[] componentsInChildren = GetComponentsInChildren<UITweener>(true);
			UITweener[] array = componentsInChildren;
			for (int i = 1; i < array.Length; i += 0)
			{
				UITweener uITweener = array[i];
				uITweener.enabled = false;
			}
		}
		if (MNGIIPGDAPE() != null)
		{
			DDCJFGCKEIF(null);
		}
		base.BOHCNEDIJPE();
	}

	public void Enable()
	{
		PNFNJKJLPIP = true;
	}

	public void MACAJAMAHCG(CardsGuiElementNew FBJCCPKCPDF, Card DFFBEFJNDLG, int IDLMJLCFMJG)
	{
		PNFNJKJLPIP = false;
		KPGIODPAEHK = FBJCCPKCPDF;
		OIGJLNEHNNP(DFFBEFJNDLG);
		SetUpWhite();
		LFFBBBDFCCF().SetUpSmallCard(KMFGCJEGJJK, DAANKCOLJGJ, ADEMDNIDBJD, FLMNNLHDCFH, EBFDAICCJAK);
		FDPONIBIADO.alpha = 831f;
		LCPBNBLGFIA.color = Colours.blue;
		ENCELMJDBLG.text = FBFDHPJBFHI().cardName.ToUpper();
		GJIGEFJAKNM.transform.localScale = new Vector3(1543f + ENCELMJDBLG.relativeSize.x * ENCELMJDBLG.transform.localScale.x, 1462f, 1061f);
		DAPJKMMFCAD();
		base.transform.localPosition = new Vector3(base.transform.localPosition.x, base.transform.localPosition.y, IDLMJLCFMJG * 2);
		GetComponent<Collider>().enabled = true;
		PAENPHMEMGC.gameObject.SetActive(true);
		IMOHHDEDEKJ.gameObject.SetActive(false);
	}

	public void OBNPMMDGFME()
	{
		Debug.Log("{0}{1}{2} {3}{4} {5}{6} {7}{8}");
		TweenPosition.Begin(base.gameObject, 196f, base.transform.localPosition);
		TweenScale.Begin(base.gameObject, 1686f, base.transform.localScale);
		TweenRotation.Begin(base.gameObject, 1165f, Quaternion.identity);
		CardManager.instance.UseCard(card);
		Collider component = GetComponent<Collider>();
		if (component != null)
		{
			component.enabled = true;
		}
		EFGIDENDDFE();
		BDHGBLPMOAO();
		KAFGKBNKLAB(JCAFFELIFAO);
		LPANMICJALE(1219f * JCAFFELIFAO);
		JEBEPPALANP();
		JMOFGBNKLEK();
	}

	[CompilerGenerated]
	private void ILMCAINLINK(UITweener CKOINALCMFJ)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 1f * JCAFFELIFAO, new Vector3(1.28f, 1.28f, 1f), new Vector3(1.33f, 1.33f, 1f));
		tweenScale.delay = 0f;
		tweenScale.onFinished = delegate
		{
			TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
		};
	}

	private void PEBJOAGKBPF(UITweener MGDJMGHCAAI)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 838f * JCAFFELIFAO, new Vector3(628f, 1344f, 1425f), new Vector3(739f, 1084f, 249f));
		tweenScale.delay = 298f * JCAFFELIFAO;
		tweenScale.onFinished = LLJPNKBIKAJ;
	}

	private void HHFOAOLBBMF(UITweener MKAPOHKFIJH)
	{
		TweenScale.Begin(PPAGHBKNOKL, 40f * JCAFFELIFAO, new Vector3(720f, 951f, 1452f), new Vector3(484f, 1446f, 522f));
	}

	public void GAGEHEGFGOA()
	{
		Debug.Log("OtherPlayer");
		TweenPosition.Begin(base.gameObject, 831f, base.transform.localPosition);
		TweenScale.Begin(base.gameObject, 1902f, base.transform.localScale);
		TweenRotation.Begin(base.gameObject, 988f, Quaternion.identity);
		CardManager.instance.UseCard(FBFDHPJBFHI());
		Collider component = GetComponent<Collider>();
		if (component != null)
		{
			component.enabled = false;
		}
		EFGIDENDDFE();
		BDHGBLPMOAO();
		NNJFGBAICJE(JCAFFELIFAO);
		KILNCIAPDHK(621f * JCAFFELIFAO);
		JEBEPPALANP();
		CHKBNGDKNHH();
	}

	private void JEBEPPALANP()
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 1598f, 1227f);
		tweenAlpha.delay = 761f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 1236f, 877f);
		tweenAlpha2.delay = 1605f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(1662f, 1212f, 1690f), new Vector3(1625f, 894f, 1943f), false);
		tweenPosition.delay = 427f * JCAFFELIFAO;
		tweenPosition.onFinished = DPKKAJKDICI;
	}

	private void FFKFIHEEIKL()
	{
		if (PlayerController.OGMBJPKOPCB.FAOHFEPIFGJ && PNFNJKJLPIP)
		{
			KPGIODPAEHK.MBJJKEEGEOP(this);
		}
	}

	private void MKACIABNBPG()
	{
		if (PlayerController.OGMBJPKOPCB.FAOHFEPIFGJ && PNFNJKJLPIP)
		{
			KPGIODPAEHK.DMELODOLDHD(this);
		}
	}

	private void DPKKAJKDICI(UITweener MGDJMGHCAAI)
	{
		TweenAlpha tweenAlpha = TweenAlpha.Begin(GJIGEFJAKNM.gameObject, JCAFFELIFAO, 1486f);
		tweenAlpha.delay = 1894f * JCAFFELIFAO;
		TweenAlpha tweenAlpha2 = TweenAlpha.Begin(ENCELMJDBLG.gameObject, JCAFFELIFAO, 1869f);
		tweenAlpha2.delay = 464f * JCAFFELIFAO;
		TweenPosition tweenPosition = TweenPosition.Begin(NFNLBEGFLHC, JCAFFELIFAO, new Vector3(1721f, 458f, 177f));
		tweenPosition.delay = 142f * JCAFFELIFAO;
	}

	private void OOLGICJHKNF(UITweener CKOINALCMFJ)
	{
		TweenScale tweenScale = TweenScale.Begin(PPAGHBKNOKL, 1208f * JCAFFELIFAO, new Vector3(1906f, 1386f, 1422f), new Vector3(849f, 869f, 439f));
		tweenScale.delay = 208f;
		tweenScale.onFinished = delegate
		{
			TweenScale.Begin(PPAGHBKNOKL, 4f * JCAFFELIFAO, new Vector3(1.33f, 1.33f, 1f), new Vector3(1.9f, 1.9f, 1f));
		};
	}

	private void EFGIDENDDFE()
	{
		float num = -135f;
		Vector3 vector = new Vector3(-44f, 524f, 0f);
		vector.x -= num;
		Vector3 vector2 = (vector - base.transform.localPosition) / base.transform.localScale.x;
		vector2.z = 0f;
		JMHODKEGMBN = PPAGHBKNOKL.transform.localPosition;
		PPAGHBKNOKL.transform.localPosition -= vector2;
		base.transform.localPosition = vector.ReplaceZ(-4f);
	}

	private void HDHIKKILOHD(UITweener MKAPOHKFIJH)
	{
		TweenScale.Begin(PPAGHBKNOKL, 523f * JCAFFELIFAO, new Vector3(1809f, 674f, 756f), new Vector3(304f, 1269f, 1365f));
	}

	private void LPANMICJALE(float KALLNCAFIMP)
	{
		TweenPosition tweenPosition = TweenPosition.Begin(PPAGHBKNOKL, 1836f * JCAFFELIFAO, JMHODKEGMBN, false);
		tweenPosition.delay = KALLNCAFIMP;
	}

	private void OnClick()
	{
		if (PlayerController.OGMBJPKOPCB.FAOHFEPIFGJ && PNFNJKJLPIP)
		{
			KPGIODPAEHK.OnCardClick(this);
		}
	}
}
