using UnityEngine;

public static class HADLIENNCEA
{
	private sealed class ILMIFBEGMDB
	{
		internal string KIFBICENDHM;

		internal double PAENPHMEMGC;

		internal void ABNGKEJNLJO(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void LHPPLGOOLEC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void KPHEPHDFCKK(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void HHNEBNHCGMO(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void LJCDGJKCNEC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void ILNPANOCHIH(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void NAJNECOMDDN(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void BBPKDMPNEDG(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void HHLMDAKDHFK(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void CHOIECFFEMH(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void POGDLLFCOKO(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void NDJOJHNIBFC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void DDHOKNIEACI(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void MMEEJDGGAID(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void BDCAFHOHEGM(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void CFJHDIHLIML(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void GMFJFMHNDMC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void NCLMPCCHDAM(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void CIFEDFPPPOK(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void DJLGPGPAHCD(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void PANKBNOCEAM(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void DGELDDJAEEF(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void JDEJHLLIONG(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void EMKPBGFBPFI(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void LKKLABBEOAG(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void ECPMEMNKMCB(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void NNFHNIMCBLH(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void PPKGMGNKNAE(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void OHLGKFGIPCC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}

		internal void AGFEDJAKLAC(bool NOCIMJBMOCB)
		{
			DFEFFEMFANO(NOCIMJBMOCB, KIFBICENDHM, PAENPHMEMGC);
		}
	}

	public static void IJAOGNHHEPK(AchievementsManager.CHIDHGCKCIK DPKMJALJPIP, double PAENPHMEMGC)
	{
		string kIFBICENDHM = DPKMJALJPIP.INFLHPGMEOB;
		DJAMKKDFCJG(kIFBICENDHM, PAENPHMEMGC);
	}

	private static void DJAMKKDFCJG(string KIFBICENDHM, double PAENPHMEMGC)
	{
		ILMIFBEGMDB iLMIFBEGMDB = new ILMIFBEGMDB();
		iLMIFBEGMDB.KIFBICENDHM = KIFBICENDHM;
		iLMIFBEGMDB.PAENPHMEMGC = PAENPHMEMGC;
		Singleton<GooglePlayGameService>.instance.ReportAchievement(iLMIFBEGMDB.KIFBICENDHM, iLMIFBEGMDB.PAENPHMEMGC, iLMIFBEGMDB.LJCDGJKCNEC);
	}

	private static void DFEFFEMFANO(bool NOCIMJBMOCB, string KIFBICENDHM, double PAENPHMEMGC)
	{
		if (DebugSettings.debugEnabled)
		{
			if (NOCIMJBMOCB)
			{
				Debug.LogFormat("Achievement '{0}' progress '{1}' successfully reported.", KIFBICENDHM, PAENPHMEMGC);
			}
			else
			{
				Debug.LogFormat("#STEPAN# Achievement '{0}' progress '{1}' could not be reported.", KIFBICENDHM, PAENPHMEMGC);
			}
		}
	}
}
