using UnityEngine;

public class KillStreakBonusAddHealth : KillStreakBonus
{
	public virtual bool MMDCAEFEFNA(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.GONLNEJFBKH(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 384f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return true;
	}

	public override bool CKMPBKMOIAF(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.ActivateBonus(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 206f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return true;
	}

	public virtual bool IPLELGEMLDD(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.DAECMMEPAHL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1267f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}

	public override bool LGJMNEKMDEO(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.HHOBEJGPLMO(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 393f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public virtual bool JIBCBLKGAFD(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.MCDFGACAGCG(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 754f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}

	public override bool ActivateBonus(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.ActivateBonus(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 0.1f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public override bool HHOBEJGPLMO(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.BCDFEBKGHCN(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 948f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool EEHNJBMIKAN(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.ActivateBonus(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 98f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public virtual bool LHOMNBABMFD(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.OHHOJEJKLBB(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1431f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool IEGHLKIJPDB(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.CMPIFPBJDLM(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 830f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return true;
	}

	public virtual bool INKGAAOPMGK(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.LKJMDKHFMDL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 117f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}

	public virtual bool DFPGPKIIHFA(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.DAECMMEPAHL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1741f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public virtual bool JJOOCBLMFFH(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.OHHOJEJKLBB(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 442f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}

	public virtual bool GAJCNNKKNMN(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.MCDFGACAGCG(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 897f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool AFBFEIPAEOG(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.LKJMDKHFMDL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 857f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}

	public override bool CMPIFPBJDLM(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.LKJMDKHFMDL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1329f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool NFCAGIHGEAF(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.ActivateBonus(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1502f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return true;
	}

	public virtual bool AIFHKFOGBAL(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.BCDFEBKGHCN(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1365f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return true;
	}

	public override bool CKMJBNEMDIG(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.FJAJKEBLFOE(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 949f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public override bool FJAJKEBLFOE(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.CMPIFPBJDLM(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 705f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public virtual bool KECLAGIBNLE(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.LKJMDKHFMDL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1988f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool JNMBAGKGIAM(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.MCDFGACAGCG(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1929f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool DJAMPKIBNDH(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.GCHILNJMFPD(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1782f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool MMHOKAHLIIK(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.ActivateBonus(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.LNPKAAGJIGO(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 682f, false);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return false;
	}

	public virtual bool AKACKBCIHAG(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.LJBDCGFBAHE(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 658f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.Sync();
		return true;
	}

	public virtual bool AFNCLMOHLCF(GameObject NPNGCEJFAOP, PlayerController KHLGDCHJJPB)
	{
		base.DAECMMEPAHL(NPNGCEJFAOP, KHLGDCHJJPB);
		KHLGDCHJJPB.FOCIOKMPCAG.Heal(KHLGDCHJJPB.FOCIOKMPCAG.maxHealth * 1689f, true);
		KHLGDCHJJPB.FOCIOKMPCAG.EHFOHNLMJOH();
		return false;
	}
}
