using UnityEngine;

public class MolotovGrenadeAmmo : GrenadeAmmoContent
{
	public virtual void GCKPAEAEKLO(Vector3 MPHCNMDIPAI)
	{
		base.NLCMFKBPCGJ(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1437f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)118, 1805f);
		DFHALNOAGGC.BPOCFDOIHPG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1466f);
	}

	public virtual void BAHNPKAHGFA(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1031f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-36), 59f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1709f);
	}

	public virtual void PFDDHEMBHEL(AmmoSetup MBNLFKHLDBH)
	{
		base.KGPPGHKFNEC(MBNLFKHLDBH);
	}

	public virtual void KDKBMIJECPJ(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1777f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)(-25), 206f);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(638f);
	}

	public virtual void JDKDEJGFMOD(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 703f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-75), 940f);
		DFHALNOAGGC.IMCGCAHFJLP(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1894f, true);
	}

	public virtual void ABLKNCLKJDG(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeRPCImplementation(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1718f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, HINJJOAJAOA.RELOAD_ASSAULT, 1399f);
		DFHALNOAGGC.DCKBBBOHNFK(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(602f);
	}

	public virtual void IGNCJLAEFEP(Vector3 MPHCNMDIPAI)
	{
		base.NLCMFKBPCGJ(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 159f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-18), 1891f);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1067f);
	}

	public override void FPNEPAFOGCK(AmmoSetup MBNLFKHLDBH)
	{
		base.LIFANJAGJJC(MBNLFKHLDBH);
	}

	public virtual void CJFDJHLGDGD(AmmoSetup MBNLFKHLDBH)
	{
		base.EMAIHAALNDP(MBNLFKHLDBH);
	}

	public virtual void KBPMAGHOOKH(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1789f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-124), 85f);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(508f, true);
	}

	public virtual void EEKDNJPPBEB(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1941f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)113, 1717f);
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(622f);
	}

	public virtual void HAFMIKKFJCC(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 860f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, HINJJOAJAOA.MedkitPickup, 520f);
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1520f);
	}

	public virtual void APPPEICJAHA(AmmoSetup MBNLFKHLDBH)
	{
		base.AKMBBJILJMF(MBNLFKHLDBH);
	}

	public virtual void NAAEJLKDCMF(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1665f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-60), 1070f);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(479f, true);
	}

	public virtual void KMBBDFAPDHP(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 512f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-80), 752f);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(776f, true);
	}

	public override void ExplodeImplementation(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 0.7f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, HINJJOAJAOA.MolotovImpact);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(0.3f);
	}

	public override void NPALDDDEBIC(Vector3 MPHCNMDIPAI)
	{
		base.NPALDDDEBIC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1276f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-44), 1891f);
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1568f, true);
	}

	public virtual void CCHINPKCNFN(Vector3 MPHCNMDIPAI)
	{
		base.NPALDDDEBIC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = KNLBEJDDGML() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 653f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-85), 1301f);
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1397f, true);
	}

	public override void JFMGNLPFEGM(AmmoSetup MBNLFKHLDBH)
	{
		base.PMBGEMJABBF(MBNLFKHLDBH);
	}

	public virtual void HFHCIDDIHFL(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 524f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)121, 640f);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(117f, true);
	}

	public virtual void KFNMNPEJHIK(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = OMGJCJKFKHJ() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1457f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, HINJJOAJAOA.SHOT_PISTOL_1, 802f);
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1392f);
	}

	public virtual void AOFJCJNOEEN(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 323f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)99, 396f);
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1737f, true);
	}

	public virtual void IPNFDEDGFBD(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 602f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-50), 1750f);
		DFHALNOAGGC.BPOCFDOIHPG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1770f, true);
	}

	public virtual void PKMFMKOPLJF(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 36f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)(-23), 542f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1590f, true);
	}

	public virtual void KNJKIKKNAOA(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1555f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-12), 662f);
		DFHALNOAGGC.IPEDNMPJOOO(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1324f);
	}

	public virtual void CGCHBCJKKOB(AmmoSetup MBNLFKHLDBH)
	{
		base.NCPMKDGNGMD(MBNLFKHLDBH);
	}

	public virtual void ECEGOOLDPGO(AmmoSetup MBNLFKHLDBH)
	{
		base.NCPMKDGNGMD(MBNLFKHLDBH);
	}

	public virtual void GKKDLPAIIIC(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1924f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-73), 348f);
		DFHALNOAGGC.INCNNACKAOO(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(471f, true);
	}

	public virtual void KKONANJNNBP(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 945f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-123), 1911f);
		DFHALNOAGGC.IPEDNMPJOOO(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(651f);
	}

	public virtual void PCECEEJGCNB(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1899f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, HINJJOAJAOA.SHOT_PISTOL_4, 877f);
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1442f, true);
	}

	public virtual void BIACKPAIJAH(AmmoSetup MBNLFKHLDBH)
	{
		base.FPNEPAFOGCK(MBNLFKHLDBH);
	}

	public override void KGPPGHKFNEC(AmmoSetup MBNLFKHLDBH)
	{
		base.JFMGNLPFEGM(MBNLFKHLDBH);
	}

	public virtual void KGIEEIGALMG(AmmoSetup MBNLFKHLDBH)
	{
		base.PMBGEMJABBF(MBNLFKHLDBH);
	}

	public virtual void FBNJLDNAOIO(AmmoSetup MBNLFKHLDBH)
	{
		base.NHMKPJGCKKN(MBNLFKHLDBH);
	}

	public virtual void EOFNMNLADKK(AmmoSetup MBNLFKHLDBH)
	{
		base.LIFANJAGJJC(MBNLFKHLDBH);
	}

	public virtual void JLBHPCHGEIG(AmmoSetup MBNLFKHLDBH)
	{
		base.JFMGNLPFEGM(MBNLFKHLDBH);
	}

	public virtual void CBKAFECJMDJ(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1220f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-104), 1805f);
		DFHALNOAGGC.NNKPEIEABPA(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(858f);
	}

	public virtual void HMAOMIDBAGM(AmmoSetup MBNLFKHLDBH)
	{
		base.NCPMKDGNGMD(MBNLFKHLDBH);
	}

	public virtual void BFKPDNJEKHI(Vector3 MPHCNMDIPAI)
	{
		base.ECBPMJGHHAJ(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = KNLBEJDDGML() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1696f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, HINJJOAJAOA.DroneEngineStart, 932f);
		DFHALNOAGGC.BPOCFDOIHPG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1210f);
	}

	public virtual void NNJKKKHMNOC(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 844f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)97, 1866f);
		DFHALNOAGGC.NNKPEIEABPA(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1284f, true);
	}

	public virtual void LBCKECONMNJ(AmmoSetup MBNLFKHLDBH)
	{
		base.PHDBJMJIPOL(MBNLFKHLDBH);
	}

	public virtual void GPMHPDOKHIH(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1963f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-14), 1009f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1397f, true);
	}

	public virtual void MMKLGOAMGKL(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = OMGJCJKFKHJ() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 600f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-95), 1701f);
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(52f);
	}

	public virtual void EJFDPOLGBNA(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1609f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)103, 881f);
		DFHALNOAGGC.KMNKGGDOMJO(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(645f, true);
	}

	public virtual void IEBOCPEIHBH(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1715f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-114), 635f);
		DFHALNOAGGC.LHKLMDDPLHE(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1903f);
	}

	public virtual void DBJKLHGNDPJ(Vector3 MPHCNMDIPAI)
	{
		base.NPALDDDEBIC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 669f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-87), 411f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1053f, true);
	}

	public override void PMBGEMJABBF(AmmoSetup MBNLFKHLDBH)
	{
		base.FPNEPAFOGCK(MBNLFKHLDBH);
	}

	public virtual void JFBFBJMKCBN(AmmoSetup MBNLFKHLDBH)
	{
		base.NCPMKDGNGMD(MBNLFKHLDBH);
	}

	public virtual void DJBBJANFKEP(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 122f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)111, 697f);
		DFHALNOAGGC.IMCGCAHFJLP(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1815f);
	}

	public virtual void NJKKBPPIHIE(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1685f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)(-25), 1675f);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(170f, true);
	}

	public virtual void BCCEMCOPEEB(AmmoSetup MBNLFKHLDBH)
	{
		base.PHDBJMJIPOL(MBNLFKHLDBH);
	}

	public virtual void JOOHIBHNDPE(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1593f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)93, 606f);
		DFHALNOAGGC.JLJNJFJCJMH(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(164f);
	}

	public virtual void MEFEFEDLNEK(AmmoSetup MBNLFKHLDBH)
	{
		base.GNIDNNGIIOH(MBNLFKHLDBH);
	}

	public virtual void JLDLGFNLKDK(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 966f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-27), 883f);
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1611f);
	}

	public virtual void MDFLGJMKJHH(AmmoSetup MBNLFKHLDBH)
	{
		base.JFMGNLPFEGM(MBNLFKHLDBH);
	}

	public virtual void ILNOPFHIANA(AmmoSetup MBNLFKHLDBH)
	{
		base.AKMBBJILJMF(MBNLFKHLDBH);
	}

	public virtual void BNNAJCEBPBP(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1275f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-66), 633f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(72f);
	}

	public virtual void HFCLICFACNG(AmmoSetup MBNLFKHLDBH)
	{
		base.LIFANJAGJJC(MBNLFKHLDBH);
	}

	public virtual void PDHGFNFOEKK(AmmoSetup MBNLFKHLDBH)
	{
		base.GNIDNNGIIOH(MBNLFKHLDBH);
	}

	public virtual void KJFECNBLLFI(AmmoSetup MBNLFKHLDBH)
	{
		base.NHMKPJGCKKN(MBNLFKHLDBH);
	}

	public virtual void KODNJMPNEKO(AmmoSetup MBNLFKHLDBH)
	{
		base.NCPMKDGNGMD(MBNLFKHLDBH);
	}

	public virtual void EPPDPJBNJHP(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1376f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.KDFJDBLLCFL(base.gameObject, (HINJJOAJAOA)(-102), 1261f);
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(849f, true);
	}

	public virtual void BPOKLNLNLAE(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 202f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)92, 941f);
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(22f, true);
	}

	public override void ExplodeRPCImplementation(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeRPCImplementation(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 0.7f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, HINJJOAJAOA.MolotovImpact);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(0.3f);
	}

	public override void LoadAmmoSetup(AmmoSetup MBNLFKHLDBH)
	{
		base.LoadAmmoSetup(MBNLFKHLDBH);
	}

	public virtual void NHOCLHCHMLH(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = OMGJCJKFKHJ() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1139f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)(-93), 921f);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1941f);
	}

	public virtual void BIFMMLCIHLE(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = OMGJCJKFKHJ() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 520f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, HINJJOAJAOA.MechSound, 820f);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1516f, true);
	}

	public virtual void NCHGDGBHDKA(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = EFGNPJONPCN() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1765f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PHGHNHAAPOK(base.gameObject, (HINJJOAJAOA)90, 1155f);
		DFHALNOAGGC.KMNKGGDOMJO(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(823f, true);
	}

	public virtual void ALHEEFNPNMJ(AmmoSetup MBNLFKHLDBH)
	{
		base.GNIDNNGIIOH(MBNLFKHLDBH);
	}

	public virtual void CBFJAINHEMB(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 281f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.BPPFAOLKEOO(base.gameObject, (HINJJOAJAOA)(-68), 1385f);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1055f, true);
	}

	public virtual void CKOMABNMJPE(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = base.transform.position;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1267f;
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = pKDCCCNJIEC;
		Singleton<SoundsManager3D>.instance.PlayOneShot(base.gameObject, (HINJJOAJAOA)90, 822f);
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1878f, true);
	}
}
