using UnityEngine;

public class PlayerStatsScreenRecord : PoolableObject
{
	[Header("Header")]
	public UILabel NFHEAEKGHNJ;

	[Header("Content")]
	public UILabel EFNFNKIIOEK;

	[Header("Left Part")]
	public UISprite OPMFPPJNEGC;

	public UISprite NNMCKEECNFK;

	public UISprite LEJHANGDGGK;

	public GameObject JOKEIPPNCMF;

	public UISprite LKFCODGKCKG;

	public UISprite INOLIBMAEAN;

	public UISprite ADONBKGNGCG;

	public void OEIKEEBDLFF(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 391f, 380f, -136);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-67)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-89)) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "GPGS: Logged Out, Logged: ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 981f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_SALEPERCENTLINE");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_CONFIRM_ERROR");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("App installed", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 798f : 849f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "D3");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)21);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)35);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)15);
	}

	public void FOCIMFPHDLP(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1251f, 1447f, -61);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-78)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)75) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "D6");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 786f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "^\\D*");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "Sniper_Tutorial_Played");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("Xp", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 830f : 1871f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "{0} 2 / 3");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)126);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-56));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-106));
	}

	public void OEJODDBHLDO(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1088f, 16f, 198);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-28)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-57)) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_VISUALCATEGORY2");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 214f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_READYTIME");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "PromotedPlayerId");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("withUnitPrice", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 986f : 1505f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "Null");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-46));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)39);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)45);
	}

	public void LDPFPPBNCMF(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 941f, 83f, -131);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-9)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-31)) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "{0} \t\t");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 670f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "placement");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : " ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("nonEliteUnits", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 308f : 1240f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "reloadTime");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.League);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-99));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)123);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-45));
	}

	public void GMDPHEGEDPL(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 748f, 1640f, 157);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)42) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)82) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "menu-assignments-type-score");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 313f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_TUTORIAL_GRENADE_DOWN");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_SALEPERCENT");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("ID_CLAIM", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 976f : 264f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "1\u00a0{0}");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-121));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-124));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-71));
	}

	public void FLCHMKHNLPO(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1763f, 328f, 64);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)75) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)125) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : " AND ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 1659f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "banana");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "EventDefinition");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("Texture z:{0}\t\"{1}\"    with depth:{2}", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1508f : 1358f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "game-label-you-blue");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)118);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)63);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)13);
	}

	public void Init(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 37f, 20f, 500);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "-");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 0f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "-");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "-");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("{0} {1}/ {2}", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1f : 0f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "-");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.League);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints);
	}

	public void ONACINBKALP(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 774f, 1908f, 152);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)53) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-49)) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_UPGRADED");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 1783f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "BattleRewards");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "qbz_run");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("MapName", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 445f : 1752f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "ReSyncDisabledRPC");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-27));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-119));
	}

	public void LILOECCIHFG(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1121f, 1476f, 177);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-83)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)33) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "hiding dialog............");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 1331f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_TRYFORFREE");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_CONFIRM_EXITINGMATCH");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("Client has no suitable init configs, RESETING, configs stored for: {0} and new version is {1} init sheet config {2}, curent bundle version {3}", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1194f : 1108f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "BR");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-112));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)71);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-26));
	}

	public void OPPKNICNNHF(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 634f, 1090f, 119);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)65) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)92) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "ShotFrequencyMax");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 1775f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "-");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "\n\nDEBUG STATE: ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("NO Video Feed found!", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1215f : 1608f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "#VAVRO# Trying to finish Tutorial, which is not currently running ");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)109);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-7));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)110);
	}

	public void MDMDKMGCNGE(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1677f, 78f, 52);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)16) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "mortar_down");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 728f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_STAT_SQUADPOINTSBEST");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "Yes_Clicked");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("DogTagCap", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 245f : 1709f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "PlayerData");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)111);
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-98));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)100);
	}

	public void CAPLIILLLNI(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 1168f, 118f, 164);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)48) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-87)) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "ID_HOU");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 1967f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "\"");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "Player with id {0} doesnt exists ! ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("getDaysSinceLastPlayed", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1898f : 187f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "FriendsPushNotification(");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-35));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-85));
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)47);
	}

	public void BEGONDBHMOG(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 62f, 238f, 24);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-25)) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)63) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "_Metallic");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 878f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "GPGS: Logged In (user action), Logged: ");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 1) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "210 GAME END");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("_DistanceParams", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1541f : 533f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 0) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "http://localhost:8081/");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-45));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-80));
	}

	public void NDAJNMAOHHA(OverallStats.OAADFICHNJP ODKJAFDLFKP)
	{
		NFHEAEKGHNJ.text = ODKJAFDLFKP.GAFCFHLBDCO;
		MEJMLNDFDBP.COCBCFKJOJE(NFHEAEKGHNJ, 277f, 731f, -189);
		EFNFNKIIOEK.color = ((ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)116) ? Colours.greenArmyPower : ((ODKJAFDLFKP.DGKAELKJAED != (OverallStats.OAADFICHNJP.AAICHFHEIGB)28) ? Colours.blue : Colours.goldWar));
		switch (ODKJAFDLFKP.DGKAELKJAED)
		{
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleInt:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Medals:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Missions:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Coop:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.Heroic:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.ArmyPower:
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SquadPoints:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE) : "1");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat:
			EFNFNKIIOEK.text = ((!(ODKJAFDLFKP.AIDOBNPKBHI < 696f)) ? MEJMLNDFDBP.CNLFNIHHHAA(ODKJAFDLFKP.AIDOBNPKBHI) : "ID_CONFIRM_ERROR");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimplePercent:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.NIOKDCOKEFE >= 0) ? MEJMLNDFDBP.IIHHLGANLGP(ODKJAFDLFKP.NIOKDCOKEFE) : "#AccoutCheck# Account exist check result NOT contain result message");
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime:
			EFNFNKIIOEK.text = MEJMLNDFDBP.ACBPLBAHMEF(ODKJAFDLFKP.NIOKDCOKEFE, false);
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt:
			EFNFNKIIOEK.text = string.Format("OnInputChanged", MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.NIOKDCOKEFE), Colours.stringGrayLight, MEJMLNDFDBP.GMIPFLIEOHD(ODKJAFDLFKP.OCNJFEFAPJE));
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.League:
			EFNFNKIIOEK.text = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value1;
			NNMCKEECNFK.alpha = ((ODKJAFDLFKP.NBGHILICPKO != League.NoLeague) ? 1226f : 901f);
			NNMCKEECNFK.spriteName = GameVariables.CAOGFCFGFPD[ODKJAFDLFKP.NBGHILICPKO].Value2;
			NNMCKEECNFK.MakePixelPerfect();
			break;
		case OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleLong:
			EFNFNKIIOEK.text = ((ODKJAFDLFKP.POFEJHBLFPJ >= 1) ? MEJMLNDFDBP.PGJPABFJDGG(ODKJAFDLFKP.POFEJHBLFPJ) : "opponent attack = true");
			break;
		}
		OPMFPPJNEGC.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleFloat);
		NNMCKEECNFK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		LEJHANGDGGK.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleIntInt);
		JOKEIPPNCMF.SetActive(ODKJAFDLFKP.DGKAELKJAED == OverallStats.OAADFICHNJP.AAICHFHEIGB.SimpleTime);
		LKFCODGKCKG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-16));
		INOLIBMAEAN.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)112);
		ADONBKGNGCG.gameObject.SetActive(ODKJAFDLFKP.DGKAELKJAED == (OverallStats.OAADFICHNJP.AAICHFHEIGB)(-109));
	}
}
