using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class SquadEventContent : Core_BaseScript
{
	public class HJIHBPDIPMA
	{
		public bool JAHGCGMPCKP;

		public int MOEMPHPNBLM;

		public int FPCCEPIAEKG;

		public Assignment EFEIDBFDDBE;

		public float PAENPHMEMGC;

		public float IOIPJCICLFH;

		public bool EIPHAAGCHCP;

		public static HJIHBPDIPMA GENNOJGJDLI(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA CDMDGPOKPCK(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA GOEGPLDNIBF(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA LFGPGPJMPBE(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KGHEFBKNMGH(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA JDLHOIHKMNJ(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA ELHHONOGMKK(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA ELCCPIGFNLN(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA IECPPLFPBNL(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA HALPMFAMPLJ(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA CFCJKBMGKPM(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA BOCGNENPCCJ(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KBKADNNBNNC(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA CBGDBAFHNFI(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA PFAMCJFJBCM(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA BCOENAIOLIH(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA GBAPCDNGJKG(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KGHHLJHAONC(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA EJLGBLFDLMM(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA MAJEMNBDKBO(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA HKGLNMPHILA(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA JOEHMCLMKPP(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA MMAPAPAACPP(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA MNILIBCPNAF(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA ADLKLKNFHDM(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA EOJCANPDOJJ(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA HLKBPOHHDCL(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA JDDPHPMGFIN(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KIJPBELHFLK(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA OPJGGODJICJ(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA PJNBNGNPDPM(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA NAKEEPEOELH(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KPGKIMIAEBJ(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA IMDJBEKMIBF(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA DKAPBIJACPI(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA KBELFPFKDID(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA BHAFBCMOBAJ(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA GLJMEHGBPJI(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA CCDCFPNOPNG(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA BOFNPDNEGEA(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA MPJHINPELEF(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), true, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA ADFOIEONFCD(int MOEMPHPNBLM, int PDKIAALFDNG, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = true;
			hJIHBPDIPMA.MOEMPHPNBLM = MOEMPHPNBLM;
			hJIHBPDIPMA.FPCCEPIAEKG = PDKIAALFDNG;
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			hJIHBPDIPMA.EFEIDBFDDBE = null;
			return hJIHBPDIPMA;
		}

		public static HJIHBPDIPMA FNAKPMHOBNG(int INFLHPGMEOB, float PAENPHMEMGC, float IOIPJCICLFH, bool EIPHAAGCHCP, string EFCLKFBGDAG, int MKIPAEDAADL, float BDDPCPKHILL)
		{
			HJIHBPDIPMA hJIHBPDIPMA = new HJIHBPDIPMA();
			hJIHBPDIPMA.JAHGCGMPCKP = false;
			hJIHBPDIPMA.EFEIDBFDDBE = Assignment.CreateAssignment(new AssignmentsManager.DatabaseAssignment(INFLHPGMEOB, MKIPAEDAADL), false, EFCLKFBGDAG, BDDPCPKHILL);
			hJIHBPDIPMA.PAENPHMEMGC = PAENPHMEMGC;
			hJIHBPDIPMA.IOIPJCICLFH = IOIPJCICLFH;
			hJIHBPDIPMA.EIPHAAGCHCP = EIPHAAGCHCP;
			return hJIHBPDIPMA;
		}
	}

	public UIPanel JAEJGOEPOKM;

	[Header("Joining Wait")]
	public GameObject GFIMEFHEPKO;

	[Header("Join Event")]
	public GameObject KIDECBDHOKP;

	public UIButton PHPLNMAGPFN;

	public UILabel GDEJLOFELOD;

	public UISprite FFMDLFCOKBP;

	[Header("No Event At The Moment")]
	public GameObject GILNALHJFME;

	public UILabel EEOCJGLNMJA;

	public UISprite FJFELNBBPFD;

	[Header("Event Progress")]
	public GameObject HAIDFBGPILC;

	[Header("-Header")]
	public UILabel IJDMGCMGMAB;

	public GameObject LOPKDMAKJMJ;

	public UITable JJEPOPCDAAP;

	public WinStreakCounter NOFEEBBFNFM;

	public GameObject OKIEMKPIEJE;

	[Header("-List of Assignments")]
	public UIPanel CFFKHHJKBMJ;

	public UIDraggablePanel NFLPPGKCOBL;

	public SquadEventRecord HGOMGJIJPJA;

	public UIPooledGrid OLGLAGDAOJH;

	[Header("-Bottom")]
	public GameObject BFEAHCKKLMO;

	private bool IHEPLEBDJCB;

	private PFPAMNODNPF DFFIJNCKJAA;

	private JMHLHIIMNIG FLJHEGNHMGD;

	private List<HJIHBPDIPMA> KBLNIKLNHEL = new List<HJIHBPDIPMA>();

	public void Animate(bool PJIEFMBDLBE, bool PDPDGCNHCFN)
	{
		IHEPLEBDJCB = PJIEFMBDLBE;
		if (IHEPLEBDJCB && !base.gameObject.activeSelf)
		{
			base.gameObject.SetActive(true);
			PMBPAOLBLFA();
		}
		if (base.gameObject.activeSelf)
		{
			TweenAlpha.Begin(JAEJGOEPOKM.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 2f) : 0.01f, (!IHEPLEBDJCB) ? 0f : 1f);
			TweenAlpha.Begin(GFIMEFHEPKO.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 2f) : 0.01f, (!IHEPLEBDJCB) ? 0f : 1f);
			TweenAlpha.Begin(CFFKHHJKBMJ.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 2f) : 0.01f, (!IHEPLEBDJCB) ? 0f : 1f).onFinished = delegate
			{
				if (!IHEPLEBDJCB)
				{
					base.gameObject.SetActive(false);
					PPMCFMBJJHP();
				}
			};
		}
		else if (!IHEPLEBDJCB)
		{
			InstantHideTab();
		}
	}

	private void CDGMNLCJLBJ(Transform ENCEFOOPBMK)
	{
		if (ENCEFOOPBMK != null)
		{
			SquadEventRecord component = ENCEFOOPBMK.GetComponent<SquadEventRecord>();
			if (component != null)
			{
				component.BOHCNEDIJPE();
			}
		}
	}

	public void LPFPAKGNNIO()
	{
		base.gameObject.SetActive(true);
		IHEPLEBDJCB = true;
		UIEventListener uIEventListener = UIEventListener.Get(PHPLNMAGPFN.gameObject);
		uIEventListener.onClick = (UIEventListener.VoidDelegate)Delegate.Combine(uIEventListener.onClick, new UIEventListener.VoidDelegate(DALFBHGFFNL));
		float activeWidthSafe = UIHelper.activeWidthSafe;
		int num = (int)UIHelper.activeHeight - 78;
		CFFKHHJKBMJ.clipRange = new Vector4(activeWidthSafe / 23f, (float)(-num) / 192f, activeWidthSafe, num);
		NFLPPGKCOBL.transform.localPosition = NFLPPGKCOBL.transform.localPosition.ReplaceY(447f);
		JJEPOPCDAAP.onReposition = PNHPNABNMON;
	}

	private Transform PLFCBDOOFPK(int DFHAAIFFLOE)
	{
		if (DFHAAIFFLOE >= 1 && DFHAAIFFLOE < KBLNIKLNHEL.Count)
		{
			bool jAHGCGMPCKP = KBLNIKLNHEL[DFHAAIFFLOE].JAHGCGMPCKP;
			string mHPNDNJDPGE = ((!jAHGCGMPCKP) ? string.Format("NULL unit", DFHAAIFFLOE.ToString("ID_CONFIRM_NOSQUADACTIONS_TEXT")) : string.Format("Sessions", DFHAAIFFLOE.ToString("ID_CONTAINSXWARCARDS")));
			SquadEventRecord squadEventRecord = Singleton<GuiManager>.instance.CHDIOFDMHEF.LCLKFGNHCOF(HGOMGJIJPJA, OLGLAGDAOJH.gameObject, mHPNDNJDPGE) as SquadEventRecord;
			if (squadEventRecord != null)
			{
				if (jAHGCGMPCKP)
				{
					squadEventRecord.PFCGFBHEOEC(KBLNIKLNHEL[DFHAAIFFLOE].MOEMPHPNBLM, KBLNIKLNHEL[DFHAAIFFLOE].FPCCEPIAEKG, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				else
				{
					squadEventRecord.DBDBMBJKJFG(KBLNIKLNHEL[DFHAAIFFLOE].EFEIDBFDDBE, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				return squadEventRecord.transform;
			}
		}
		return null;
	}

	private void NGCOFAHBMCB()
	{
		GFIMEFHEPKO.SetActive(true);
		GILNALHJFME.SetActive(false);
		KIDECBDHOKP.SetActive(true);
		HAIDFBGPILC.SetActive(false);
		FJFELNBBPFD.transform.localScale = FJFELNBBPFD.transform.localScale.ReplaceX(EEOCJGLNMJA.relativeSize.x * EEOCJGLNMJA.transform.localScale.x);
	}

	private Transform GPFDHBMPECA(int DFHAAIFFLOE)
	{
		if (DFHAAIFFLOE >= 0 && DFHAAIFFLOE < KBLNIKLNHEL.Count)
		{
			bool jAHGCGMPCKP = KBLNIKLNHEL[DFHAAIFFLOE].JAHGCGMPCKP;
			string mHPNDNJDPGE = ((!jAHGCGMPCKP) ? string.Format("Assignment {0}", DFHAAIFFLOE.ToString("D3")) : string.Format("Header {0}", DFHAAIFFLOE.ToString("D3")));
			SquadEventRecord squadEventRecord = Singleton<GuiManager>.instance.CHDIOFDMHEF.InstantiateAsChild(HGOMGJIJPJA, OLGLAGDAOJH.gameObject, mHPNDNJDPGE) as SquadEventRecord;
			if (squadEventRecord != null)
			{
				if (jAHGCGMPCKP)
				{
					squadEventRecord.InitHeader(KBLNIKLNHEL[DFHAAIFFLOE].MOEMPHPNBLM, KBLNIKLNHEL[DFHAAIFFLOE].FPCCEPIAEKG, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				else
				{
					squadEventRecord.InitAssignment(KBLNIKLNHEL[DFHAAIFFLOE].EFEIDBFDDBE, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				return squadEventRecord.transform;
			}
		}
		return null;
	}

	private void PNHPNABNMON()
	{
		JJEPOPCDAAP.transform.localPosition = JJEPOPCDAAP.transform.localPosition.ReplaceX(0f - OKIEMKPIEJE.transform.localPosition.x);
	}

	private void DJCCJFKLMCK()
	{
		KBLNIKLNHEL.Clear();
		int count = DFFIJNCKJAA.FNOAGGGCDJF.Count;
		float iOIPJCICLFH = UIHelper.activeWidthSafe - 120f;
		if (FLJHEGNHMGD.FNOAGGGCDJF.Count != DFFIJNCKJAA.FNOAGGGCDJF.Count)
		{
			WarningDialog.ShowError(Localization.Localize("ID_WARNING_SERVERDATA"), Localization.Localize("ID_SQUADEVENT"), 0f, null, string.Empty);
			return;
		}
		for (int i = 0; i < count; i++)
		{
			KBLNIKLNHEL.Add(HJIHBPDIPMA.EJLGBLFDLMM(FLJHEGNHMGD.FNOAGGGCDJF[i].MOEMPHPNBLM, i + 1, FLJHEGNHMGD.FNOAGGGCDJF[i].KFMJHPOHJEE(), iOIPJCICLFH, FLJHEGNHMGD.CAEILGMELMP >= i));
			int count2 = DFFIJNCKJAA.FNOAGGGCDJF[i].NJMANOIFNJN.Count;
			for (int j = 0; j < count2; j++)
			{
				string eFCLKFBGDAG = string.Empty;
				if (FLJHEGNHMGD.FNOAGGGCDJF[i].LAMDLDGFBJI.ContainsKey(j))
				{
					eFCLKFBGDAG = FLJHEGNHMGD.FNOAGGGCDJF[i].LAMDLDGFBJI[j];
				}
				KBLNIKLNHEL.Add(HJIHBPDIPMA.KIJPBELHFLK(DFFIJNCKJAA.FNOAGGGCDJF[i].NJMANOIFNJN[j], FLJHEGNHMGD.FNOAGGGCDJF[i].NJHGILKDMLO[j], iOIPJCICLFH, FLJHEGNHMGD.CAEILGMELMP >= i, eFCLKFBGDAG, FLJHEGNHMGD.FNOAGGGCDJF[i].CEAGOEPCBGJ[j], FLJHEGNHMGD.BDDPCPKHILL));
			}
		}
	}

	public void HKDCHMLHKEB(bool PJIEFMBDLBE, bool PDPDGCNHCFN)
	{
		IHEPLEBDJCB = PJIEFMBDLBE;
		if (IHEPLEBDJCB && !base.gameObject.activeSelf)
		{
			base.gameObject.SetActive(true);
			PMBPAOLBLFA();
		}
		if (base.gameObject.activeSelf)
		{
			TweenAlpha.Begin(JAEJGOEPOKM.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 873f) : 878f, (!IHEPLEBDJCB) ? 1021f : 513f);
			TweenAlpha.Begin(GFIMEFHEPKO.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 487f) : 77f, (!IHEPLEBDJCB) ? 1572f : 1906f);
			TweenAlpha.Begin(CFFKHHJKBMJ.gameObject, (!PDPDGCNHCFN) ? (GuiScreenSingle<SquadScreen>.instance.HAMKIKMJHDP * 1211f) : 811f, (!IHEPLEBDJCB) ? 1624f : 661f).onFinished = IAMNDKAAGNE;
		}
		else if (!IHEPLEBDJCB)
		{
			InstantHideTab();
		}
	}

	private void EJHMMMILHLL()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(false);
		KIDECBDHOKP.SetActive(true);
		HAIDFBGPILC.SetActive(false);
		FFMDLFCOKBP.transform.localScale = FFMDLFCOKBP.transform.localScale.ReplaceX(GDEJLOFELOD.relativeSize.x * GDEJLOFELOD.transform.localScale.x);
	}

	private void DEIBGDDDKLL()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(false);
		KIDECBDHOKP.SetActive(true);
		HAIDFBGPILC.SetActive(true);
		FFMDLFCOKBP.transform.localScale = FFMDLFCOKBP.transform.localScale.ReplaceX(GDEJLOFELOD.relativeSize.x * GDEJLOFELOD.transform.localScale.x);
	}

	private Transform FNIBACGEKKP(int DFHAAIFFLOE)
	{
		if (DFHAAIFFLOE >= 0 && DFHAAIFFLOE < KBLNIKLNHEL.Count)
		{
			bool jAHGCGMPCKP = KBLNIKLNHEL[DFHAAIFFLOE].JAHGCGMPCKP;
			string mHPNDNJDPGE = ((!jAHGCGMPCKP) ? string.Format("S", DFHAAIFFLOE.ToString("VIPMembershipExpired")) : string.Format("category", DFHAAIFFLOE.ToString(" = ")));
			SquadEventRecord squadEventRecord = Singleton<GuiManager>.instance.CHDIOFDMHEF.AAIBNGPFKGF(HGOMGJIJPJA, OLGLAGDAOJH.gameObject, mHPNDNJDPGE) as SquadEventRecord;
			if (squadEventRecord != null)
			{
				if (jAHGCGMPCKP)
				{
					squadEventRecord.GLAIGFODCIF(KBLNIKLNHEL[DFHAAIFFLOE].MOEMPHPNBLM, KBLNIKLNHEL[DFHAAIFFLOE].FPCCEPIAEKG, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				else
				{
					squadEventRecord.CFDGECJNIBG(KBLNIKLNHEL[DFHAAIFFLOE].EFEIDBFDDBE, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				return squadEventRecord.transform;
			}
		}
		return null;
	}

	private void IAMNDKAAGNE(UITweener MGDJMGHCAAI)
	{
		if (!IHEPLEBDJCB)
		{
			base.gameObject.SetActive(true);
			AKPHBJHGBKF();
		}
	}

	private void DALFBHGFFNL(GameObject KHAHPAKDIKE)
	{
		if (DFFIJNCKJAA == null)
		{
			ConfirmDialog.ShowAlert(Localization.Localize("ID_SQUADEVENT"), Localization.Localize("ID_CONFIRM_SQUADEVENT_TEXT"));
		}
		else
		{
			GuiElementSingle<SquadEventDialog>.instance.ShowJoin();
		}
	}

	private void BOMGGCDGGMB(UITweener MGDJMGHCAAI)
	{
		if (!IHEPLEBDJCB)
		{
			base.gameObject.SetActive(true);
			AKPHBJHGBKF();
		}
	}

	[CompilerGenerated]
	private void PEELOMCBFDP(UITweener MGDJMGHCAAI)
	{
		if (!IHEPLEBDJCB)
		{
			base.gameObject.SetActive(false);
			PPMCFMBJJHP();
		}
	}

	public void OnJoinedSquadEvent()
	{
		if (GuiScreenSingle<SquadScreen>.instance.isShowed && IHEPLEBDJCB)
		{
			PMBPAOLBLFA();
			NFLPPGKCOBL.UpdateScrollbars(true);
			NFLPPGKCOBL.AlignToPos(true);
		}
	}

	public void InitControls()
	{
		base.gameObject.SetActive(false);
		IHEPLEBDJCB = false;
		UIEventListener uIEventListener = UIEventListener.Get(PHPLNMAGPFN.gameObject);
		uIEventListener.onClick = (UIEventListener.VoidDelegate)Delegate.Combine(uIEventListener.onClick, new UIEventListener.VoidDelegate(DALFBHGFFNL));
		float activeWidthSafe = UIHelper.activeWidthSafe;
		int num = (int)UIHelper.activeHeight - 470;
		CFFKHHJKBMJ.clipRange = new Vector4(activeWidthSafe / 2f, (float)(-num) / 2f, activeWidthSafe, num);
		NFLPPGKCOBL.transform.localPosition = NFLPPGKCOBL.transform.localPosition.ReplaceY(0f);
		JJEPOPCDAAP.onReposition = delegate
		{
			JJEPOPCDAAP.transform.localPosition = JJEPOPCDAAP.transform.localPosition.ReplaceX(0f - OKIEMKPIEJE.transform.localPosition.x);
		};
	}

	private void JIAGLAMJDCI()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(true);
		KIDECBDHOKP.SetActive(true);
		HAIDFBGPILC.SetActive(true);
		FFMDLFCOKBP.transform.localScale = FFMDLFCOKBP.transform.localScale.ReplaceX(GDEJLOFELOD.relativeSize.x * GDEJLOFELOD.transform.localScale.x);
	}

	private void AKPHBJHGBKF()
	{
		OLGLAGDAOJH.MakeEmpty();
	}

	private void PPMCFMBJJHP()
	{
		OLGLAGDAOJH.MakeEmpty();
	}

	private void LGDJAAEIAIE(Transform ENCEFOOPBMK)
	{
		if (ENCEFOOPBMK != null)
		{
			SquadEventRecord component = ENCEFOOPBMK.GetComponent<SquadEventRecord>();
			if (component != null)
			{
				component.DestroyPooled();
			}
		}
	}

	private void FLFNPGBACLD()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(false);
		KIDECBDHOKP.SetActive(false);
		HAIDFBGPILC.SetActive(true);
		float num = (UIHelper.activeWidthSafe - 120f) / 2f;
		KIDECBDHOKP.transform.localPosition = KIDECBDHOKP.transform.localPosition.ReplaceX(num);
		GILNALHJFME.transform.localPosition = GILNALHJFME.transform.localPosition.ReplaceX(num);
		IJDMGCMGMAB.text = string.Format("{0} {1}{2} / {3}", Localization.Localize("ID_TIERSCOMPLETED"), Colours.stringBlue, FLJHEGNHMGD.CAEILGMELMP, DFFIJNCKJAA.FNOAGGGCDJF.Count);
		NOFEEBBFNFM.KGNGFHMBHMJ.text = "XXd YYh";
		NOFEEBBFNFM.MHLJHMOPDAO(DFFIJNCKJAA.DMBMLIODOJG);
		NOFEEBBFNFM.JEMKCLKCOMI = delegate
		{
			Debug.Log("Event has ended! Download new Event");
			NOFEEBBFNFM.KGNGFHMBHMJ.text = Localization.Localize("ID_ENDED");
		};
		LOPKDMAKJMJ.transform.localPosition = new Vector3(num * 2f, LOPKDMAKJMJ.transform.localPosition.y, 0f);
		JJEPOPCDAAP.repositionNow = true;
		DJCCJFKLMCK();
		OLGLAGDAOJH.transform.localPosition = OLGLAGDAOJH.transform.localPosition.ReplaceX(num);
		OLGLAGDAOJH.init(KBLNIKLNHEL.Count, GPFDHBMPECA, LGDJAAEIAIE, NFLPPGKCOBL);
		OLGLAGDAOJH.offsetGrid = new Vector2(0f, 50f);
		OLGLAGDAOJH.cellWidth = num * 2f;
		float num2 = 60f + Mathf.Abs(OLGLAGDAOJH.helperMax.localPosition.y - OLGLAGDAOJH.helperMin.localPosition.y) + 100f;
		BFEAHCKKLMO.transform.localPosition = BFEAHCKKLMO.transform.localPosition.ReplaceY(0f - num2);
	}

	private void PMBPAOLBLFA()
	{
		OLGLAGDAOJH.MakeEmpty();
		DFFIJNCKJAA = Singleton<ServerResultsCache>.instance.squadEventDefinition;
		int currentTimestamp = Singleton<BeanstalkServerManager>.instance.currentTimestamp;
		if (DFFIJNCKJAA == null || currentTimestamp < DFFIJNCKJAA.KAMAHCKIMFF || currentTimestamp > DFFIJNCKJAA.DMBMLIODOJG)
		{
			OPEEACAMNNP();
			return;
		}
		FLJHEGNHMGD = Singleton<ServerResultsCache>.instance.squadEventProgress;
		if (FLJHEGNHMGD == null)
		{
			EJHMMMILHLL();
		}
		else
		{
			FLFNPGBACLD();
		}
	}

	private void ABGEACBNIMA()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(true);
		KIDECBDHOKP.SetActive(true);
		HAIDFBGPILC.SetActive(true);
		float num = (UIHelper.activeWidthSafe - 659f) / 531f;
		KIDECBDHOKP.transform.localPosition = KIDECBDHOKP.transform.localPosition.ReplaceX(num);
		GILNALHJFME.transform.localPosition = GILNALHJFME.transform.localPosition.ReplaceX(num);
		UILabel iJDMGCMGMAB = IJDMGCMGMAB;
		object[] array = new object[1];
		array[1] = Localization.Localize("\n");
		array[0] = Colours.stringBlue;
		array[6] = FLJHEGNHMGD.CAEILGMELMP;
		array[8] = DFFIJNCKJAA.FNOAGGGCDJF.Count;
		iJDMGCMGMAB.text = string.Format("204 AUTOSPAWN CONTINUE", array);
		NOFEEBBFNFM.KGNGFHMBHMJ.text = " ";
		NOFEEBBFNFM.MIOOAOFMLIE(DFFIJNCKJAA.DMBMLIODOJG);
		NOFEEBBFNFM.JEMKCLKCOMI = delegate
		{
			Debug.Log("Event has ended! Download new Event");
			NOFEEBBFNFM.KGNGFHMBHMJ.text = Localization.Localize("ID_ENDED");
		};
		LOPKDMAKJMJ.transform.localPosition = new Vector3(num * 447f, LOPKDMAKJMJ.transform.localPosition.y, 851f);
		JJEPOPCDAAP.repositionNow = true;
		DJCCJFKLMCK();
		OLGLAGDAOJH.transform.localPosition = OLGLAGDAOJH.transform.localPosition.ReplaceX(num);
		OLGLAGDAOJH.init(KBLNIKLNHEL.Count, PLFCBDOOFPK, CDGMNLCJLBJ, NFLPPGKCOBL);
		OLGLAGDAOJH.offsetGrid = new Vector2(1358f, 1913f);
		OLGLAGDAOJH.cellWidth = num * 542f;
		float num2 = 1813f + Mathf.Abs(OLGLAGDAOJH.helperMax.localPosition.y - OLGLAGDAOJH.helperMin.localPosition.y) + 1648f;
		BFEAHCKKLMO.transform.localPosition = BFEAHCKKLMO.transform.localPosition.ReplaceY(0f - num2);
	}

	public void ShowWaiting()
	{
		GFIMEFHEPKO.SetActive(true);
		GILNALHJFME.SetActive(false);
		KIDECBDHOKP.SetActive(false);
		HAIDFBGPILC.SetActive(false);
	}

	public void JABBMOLLCKN()
	{
		if (GuiScreenSingle<SquadScreen>.instance.NPFFMLLLDAF() && IHEPLEBDJCB)
		{
			PMBPAOLBLFA();
			NFLPPGKCOBL.UpdateScrollbars(false);
			NFLPPGKCOBL.AlignToPos(false, UIDraggablePanel.Alingment.BottomRight, true);
		}
	}

	private void OPEEACAMNNP()
	{
		GFIMEFHEPKO.SetActive(false);
		GILNALHJFME.SetActive(true);
		KIDECBDHOKP.SetActive(false);
		HAIDFBGPILC.SetActive(false);
		FJFELNBBPFD.transform.localScale = FJFELNBBPFD.transform.localScale.ReplaceX(EEOCJGLNMJA.relativeSize.x * EEOCJGLNMJA.transform.localScale.x);
	}

	private Transform HOFJOLELBJJ(int DFHAAIFFLOE)
	{
		if (DFHAAIFFLOE >= 1 && DFHAAIFFLOE < KBLNIKLNHEL.Count)
		{
			bool jAHGCGMPCKP = KBLNIKLNHEL[DFHAAIFFLOE].JAHGCGMPCKP;
			string mHPNDNJDPGE = ((!jAHGCGMPCKP) ? string.Format("TimeStamp", DFHAAIFFLOE.ToString("NEW CONFIG WILL BE LOADED FROM PREFS:")) : string.Format("WindowDuration", DFHAAIFFLOE.ToString("WarArena matchmaking took {0}")));
			SquadEventRecord squadEventRecord = Singleton<GuiManager>.instance.CHDIOFDMHEF.OKEAAILFPIG(HGOMGJIJPJA, OLGLAGDAOJH.gameObject, mHPNDNJDPGE) as SquadEventRecord;
			if (squadEventRecord != null)
			{
				if (jAHGCGMPCKP)
				{
					squadEventRecord.AIHJLALNIMP(KBLNIKLNHEL[DFHAAIFFLOE].MOEMPHPNBLM, KBLNIKLNHEL[DFHAAIFFLOE].FPCCEPIAEKG, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				else
				{
					squadEventRecord.HIILDHFNPMJ(KBLNIKLNHEL[DFHAAIFFLOE].EFEIDBFDDBE, KBLNIKLNHEL[DFHAAIFFLOE].PAENPHMEMGC, KBLNIKLNHEL[DFHAAIFFLOE].IOIPJCICLFH, KBLNIKLNHEL[DFHAAIFFLOE].EIPHAAGCHCP);
				}
				return squadEventRecord.transform;
			}
		}
		return null;
	}

	[CompilerGenerated]
	private void POEJBLOHJAC()
	{
		Debug.Log("Event has ended! Download new Event");
		NOFEEBBFNFM.KGNGFHMBHMJ.text = Localization.Localize("ID_ENDED");
	}

	public void InstantHideTab()
	{
		TweenAlpha component = CFFKHHJKBMJ.gameObject.GetComponent<TweenAlpha>();
		if (component != null)
		{
			component.enabled = false;
		}
		TweenAlpha component2 = JAEJGOEPOKM.gameObject.GetComponent<TweenAlpha>();
		if (component2 != null)
		{
			component2.enabled = false;
		}
		base.gameObject.SetActive(false);
		PPMCFMBJJHP();
	}

	[CompilerGenerated]
	private void ONAKPPOMOOC()
	{
		JJEPOPCDAAP.transform.localPosition = JJEPOPCDAAP.transform.localPosition.ReplaceX(0f - OKIEMKPIEJE.transform.localPosition.x);
	}
}
