using System;

public interface PJHAKBEHAGF
{
	bool EJGFFDLAJOK { get; }

	void LNKHEKNFMPL(Action<JCEIPOHJCIE> ENBGNHDOGDH, Action<FAGPEFLHJJC> ANFPHJLJIFP);

	void IHLCBGGOEAB(HBMIGBHPLOK PCLCLMMNIFK, Action<JCEIPOHJCIE> ENBGNHDOGDH, Action<FAGPEFLHJJC> ANFPHJLJIFP);

	void LNGNMFKAPML(string NLKAAAOICNO, Action<PHLLNOOPHAG> ENBGNHDOGDH, Action<FAGPEFLHJJC> ANFPHJLJIFP);

	void FGCLMPHKNLK(Action<string> NBJLOCGNOOA);
}
