using System;
using System.Text;
using UnityEngine;

namespace FuseMisc
{
	public struct KIDFEANMAKJ
	{
		public int DHOMHJBNEIF;

		public string FMOPAEAPFBL;

		public float FNPCHNALNPL;

		public int LOADAJMDAMF;

		public string EJAOIMDLKDO;

		public int OAIIBKKCLLO;

		public DateTime DAIOILGOBGP;

		public DateTime CNGDKFPFCDC;

		public string IFFJPCHLIDG;

		public string ONLNILBHKJJ()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JHGBHIJBGKK("Game_type", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("com/google/android/gms/games/Games", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("menu-gold", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("CharacterClass", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("Device UNPAUSED at {0}", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_MISSION_UNITS_HUD", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF(" (#", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("{0} {1}{2}", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("Application paused", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("tierCount", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EKOEIMEMCGH()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.JHGBHIJBGKK("Sniper_Tutorial_Played", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("Count", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("WarFriends necessita di un permesso per accedere alla memoria e scaricare importanti dati di gioco.Senza questo permesso, il gioco non può funzionare e verrà chiuso. Riprova o esci da WarFriends.", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("URL", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("registerCustomProfileDate", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_CONFIRM_SQUADALREADYEXISTS", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("subscription_tab_displayed", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("BonusDamage", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("ChangeWeightForDestroyablePartRPC", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("Wrong_Weapon", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string GIOJAGFALPL()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("N", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("Flawless", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("special", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("-VIP", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_TUTORIAL_UPGRADEWEAPON_6", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("MachineGunner", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("{0}", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_SQUADEVENT_TEXT", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_NA", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF(" ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string GDDFCENINBB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JHGBHIJBGKK("Wrong_Weapon", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB(" x ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("BESTÄTIGEN", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("Parts", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("game-ico-poison", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_YOUNEEDMONEYTODELIVER", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("FB: FacebookLogout - RemoveFacebook - 1", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_FEATURE_RATE-WEAPONPREFIX", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("testingPlayerId", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("MasterId", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BICEOOCDGBD()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.IHCNGGHNALF("roomName", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("Cards", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_READYTIME", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_DEBUG_EVENTASSIGNMENTUPDATE", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("Yes_Clicked", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("country-canada", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("StepId", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("SessionManager: Send OnApplicationResumed to Managers !!!", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ExplodeDamageMax", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("AmmoPool", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string PKECMHAGOLI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.JHGBHIJBGKK("PlayerLeaguesId", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_DELIVEREDTIME", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_LEAGUESTAYHINT2", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("]", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("Different names \"{0}\" and \"{1}\"\n", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("shotReal", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("OneDogTagRefillRate", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("p0lski", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("Cards_Owned_Silver", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CDFCDJNCADE()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_TUTORIAL_TAPON", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("withAttribute5", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("LT", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("EUId", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("D6", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK(" ", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Error Handler: Player si vybral starsi account!", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("DailyMission", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Sniper_Tutorial_Duration", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP(", ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string HHGEAHJAFBK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_GETFORNUMBERONE1", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_WARNING_PURCHASEERROR_TEXT", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("FuseSDK", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONTAINSXWARCARDS", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_CONFIRM_PROMOTEDEMOTEERROR", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ShotFrequencyMin", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("YES", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("-", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("PlayCardRPC", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_MIN", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MBHMDIIIIHA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_NA", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ARENA SCREEN CLOSED with mode: ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("USPECH POKUSU O LOGIN NA FB!!!", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_ELITEPACK_VIPDESCRIPTION", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("Deploys_Count", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_HINT", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_STAT_TIMEPLAYED", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("getSystemService", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("YES", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP(".", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string AOAKECEMMBA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JHGBHIJBGKK("Joined room: {0}, name: {1},  userId: {2}, allConnected: {3}", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB(", mis = ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_OPENLOOTBOX", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("Squad", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF(",", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("Different squads \"{0}\" and \"{1}\"\n", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_REMINDER_GETCARDPACKS", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Play_Card_Tutorial_Duration", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("ArmyPower", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("ID_GOLD", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BOHPMCOKKPJ()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.JHGBHIJBGKK("Play_Card_Tutorial_Duration", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("px :\n ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("null", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("buddy card excel doesnt contain {0}", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("FontSize", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("gold", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("MaintenanceMessage", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CLOSESIN", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("{0}\u00a0{1}", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("Have discount {0} to upgrade {1}", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CNAMFAJIMEK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.JHGBHIJBGKK("Inactive player disconnected: ", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_TUTORIAL_UPGRADEWEAPON_4", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SLOTUPGRADE_DAMAGE", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("x", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("Wrong_Category", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("OK", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ammo", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Reward", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("PrepareBotForDeathMatch 3", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_READYTIME", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string KDLGINIJCID()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("Damage", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("SpecialOfferSuffix", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("BS: On In App Bought ", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("173432c2", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF(" failure. Server response = ", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("WarFriends requires permission to access your media storage in order to download critical game data.Without this permission the game cannot function and will be closed. Please retry or quit WarFriends.", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Fb_login", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Show starter pack: {0}\tConfiguration time: {1}\tTime till end time: {2}\tLast shown: {3}", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("\"", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MHCGFLMKBHO()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.JHGBHIJBGKK("getGameConfigurationKeys", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_ARENARULES_RANDOMWEAPONS", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SQUADEMPTYTEXT-FIGHT", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("Returning null weapon for category: {0} level: {1}, minPower: {2}, maxPower: {3}", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_UNIT2UPGRADEABILITY_UNIT1ABILITYUPGRADE", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_NOTIFICATION_DAILYREWARD_CARDPACK", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SILVERPACK", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("withEventItems", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("Manual_Unit_Spawn", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_CONFIRM_LOGGEDOUT_TEXT", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EEPNEAHHICA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("dailyRewardData", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("WithdrawerId", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_UNLOCKEDATTIER", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("[", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("_", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("Pack_Id", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Out|In|Sum:\t{0,4} | {1,4} | {2,4}", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("response contain VipReward", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("1", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("shootAdditive", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OENLNDACNCI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JHGBHIJBGKK("\t\"FALSE\"", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_GETSP", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("added", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_EMPTYARENAHEROESCURRENT", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("game-card-ico-bg-silver", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CATEGORY_LOW_SG_LMG", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("127 NEXT TUTORIAL STARTING", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("IsVip", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_CONFIRM_JOINSQUADEVENT", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("ID_CONGRATULATIONSMOVEDTO", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string HANBPIENBMA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_CREATESQUADNOTENOUGH", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("category", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_GUI_EQUIPPED", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("N", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("seconds", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_READYTIME", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_MACHINEGUNNERS_UP", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("WarBucks", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("Warbucks_Balance", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("ID_GUI_LEAGUEBONUS", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MKCKMHOMECK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.JHGBHIJBGKK("weapon", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("Beanstalk: ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("+0", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_EVENTENDSINSMALL", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("OnConnectionFailed: ", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("HeartDialogShown", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Country", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("()I", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("menu-close", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("run_grenadelauncher", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CCONMNOONFF()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.IHCNGGHNALF("warbucks", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("rookie2", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("IdOfPlayer", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_BUFF", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("Buy_", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("DeathEventPlayerShoot", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SALEPERCENT", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("x", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("PrepareBotForDeathMatch 8", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("ShootBatchRPC", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string NJOBOGIBCFL()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.IHCNGGHNALF("URL", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("Unit delivery was : ", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("subscription", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("Buy_Army_Unit_Gold", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("PlayerName", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("auto", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CLAIMTODAY", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("HELMETS_CROWNSILVER", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("reached max depth!", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("AndroidID", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public override string ToString()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("CurrencyID", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("PurchaseCurrency", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("PurchasePrice", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("VirtualGoodID", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("ItemName", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ItemAmount", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("StartTime", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("EndTime", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Metadata", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("VGOfferInfo", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string ILDBFCIMIPI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("com.tune.TuneGender", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("\n\t", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("Assets", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_WARNING_FAILDOWNLOADINGASSET", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("\nCPAPI:{\"cmd\":\"Watch\" \"name\":\"", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK(" (#", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_UPGRADEUNIT_8", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("_New_User", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("No original weapon set for blackmarket weapon: ", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("menu-weapon-benelli-starterpack", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string NIPJIAHENOC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.IHCNGGHNALF("squadMembers", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("FacebookId", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("DepositedCards", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("DEPOSIT WARCARDS MESSAGE!!!", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ProductId", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_WINSTREAK", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Hearts", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_STAT_SQUADTOTAL", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("attrValue23", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("{0} {1}", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EAJBHIFDNIM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.IHCNGGHNALF("BoughtIndex", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("menu-arena-ticket", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("#AccoutCheck# GoogleLoggedIn tutorial - ALL OK - logged to gpgs connectet to this account", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("UsedGold", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("menu-gold", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("squadMembers", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("startResolutionForResult", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("{0} {1}{2}", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("OnOffersReleased", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("Achievement_page_accessed", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string FOOMIBECINC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_ARENALOSSREWARD", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("Overtime_Was_Already_Explained", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("601 TUTORIAL STARTED", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("bronze", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("Unkown Lootbox Button ", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("-----BEGIN CERTIFICATE-----MIIDwDCCAqgCCQCAhUcHjX7uoDANBgkqhkiG9w0BAQUFADCBoTELMAkGA1UEBhMCQ1oxDzANBgNVBAgMBlByYWd1ZTEPMA0GA1UEBwwGUHJhZ3VlMRIwEAYDVQQKDAlBYm91dCBGdW4xCzAJBgNVBAsMAklUMSswKQYDVQQDDCJ3YXJmcmllbmRzLWV1LmVsYXN0aWNiZWFuc3RhbGsuY29tMSIwIAY", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("PhotonConnectionManager: ConnectToPhotonSafe ", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("BESTÄTIGEN", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("MaintenanceMessage", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BBNHEKLGNIC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("WarFriends funktioniert ohne diese zusätzlichen Daten nicht. Möchtest du WarFriends wirklich VERLASSEN oder möchtest du die Daten herunterladen?", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("menu-info-close-ico", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("InfluencerAlias", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("global", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("setAppAdTrackingEnabled", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_BATTLEWINBONUSFALLSTO", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Ending TimeLock: ", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("GooglePlay", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_ERROR", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_LOADING", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public KIDFEANMAKJ(string HHLLCFBCONC)
		{
			this = default(KIDFEANMAKJ);
			if (string.IsNullOrEmpty(HHLLCFBCONC))
			{
				return;
			}
			try
			{
				string[] array = HHLLCFBCONC.Split(',');
				FMOPAEAPFBL = Encoding.UTF8.GetString(Convert.FromBase64String(array[0]));
				float result;
				FNPCHNALNPL = ((!float.TryParse(array[1], out result)) ? 0f : result);
				EJAOIMDLKDO = Encoding.UTF8.GetString(Convert.FromBase64String(array[2]));
				int result2;
				OAIIBKKCLLO = (int.TryParse(array[3], out result2) ? result2 : 0);
				long result3;
				DAIOILGOBGP = ((!long.TryParse(array[4], out result3)) ? 0 : result3).JHHJCIOHPAD();
				long result4;
				CNGDKFPFCDC = ((!long.TryParse(array[5], out result4)) ? 0 : result4).JHHJCIOHPAD();
				int result5;
				DHOMHJBNEIF = (int.TryParse(array[6], out result5) ? result5 : 0);
				int result6;
				LOADAJMDAMF = (int.TryParse(array[7], out result6) ? result6 : 0);
				IFFJPCHLIDG = Encoding.UTF8.GetString(Convert.FromBase64String(array[8]));
				Debug.LogFormat("fuse offer: {0}", HHLLCFBCONC);
			}
			catch (Exception exception)
			{
				Debug.LogError("FuseSDK: Error parsing VGOfferInfo. Returning default value.");
				Debug.LogException(exception);
			}
		}

		public string FFMAAHMHCAM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.IHCNGGHNALF(", response: ", DHOMHJBNEIF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("menu-army-power-ico", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("qbz2_reload", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("Region: {0} with ping {1}, IP: {2} \n", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SILVERWARCARDS", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("GetRewardedInfoForZoneID", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Rule Record For Height", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("OnOffersReleased", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("#AccoutCheck# GoogleLoggedIn tutorial - Check current gpgs on server : {0}", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CIJPPHFEBNI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_WARNING_CANNOTINVITE", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("DailyMissionsCompletionRewardGold", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("+", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("MachineGunLevelSetup needs PlayerBurstWeapon", LOADAJMDAMF);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_MEDALSTOJOINBIG", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_ARENAEVENTSTARTSIN", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("NetworkDamage damage Error new HP is {0} and {1} should NOT be DEAD, damage: {2}, damage owner {3}", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ShowEngineerBuildingIndicator", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("SetGameData(", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_WAITINGFOROPPONENTCARDS", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BJKPFIAJCMJ()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("null", DHOMHJBNEIF);
			fPPNAOFJOCF2.IHCNGGHNALF("NULL WARCARD", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_REMINDER_SUITUPSOLDIER", FNPCHNALNPL);
			fPPNAOFJOCF2.JHGBHIJBGKK("menu-assignments-bar-blue", LOADAJMDAMF);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_ISALREADYMEMBEROFANOTHERSQUAD", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_RENTAL_ROCKETLAUNCHER", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_FIGHT", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("\t", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("Cant fing player", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("DogTagCap", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string LIKPNODLLEC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.JHGBHIJBGKK("menu-assignments-type-kill", DHOMHJBNEIF);
			fPPNAOFJOCF2.OFHNEHKHELB("isRandomMap", FMOPAEAPFBL);
			fPPNAOFJOCF2.IHCNGGHNALF("#PETER# Weapon Screen - LEFT BUTTON - weapon state: OTHER\t\tbutton type: EMPTY", FNPCHNALNPL);
			fPPNAOFJOCF2.IHCNGGHNALF("Animating claiming cardpack end", LOADAJMDAMF);
			fPPNAOFJOCF2.OFHNEHKHELB("resizing texture ", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_CONFIRM_NOSKIRMISHAVAILABLE", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("eventEnd", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("setListener", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("Total_Transactions", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("isPayingUser = ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}
	}
}
