namespace FuseMisc
{
	public struct BFBLJPDGMHH
	{
		public string MDMLKBEGCGN;

		public float GIFAJAMKBLM;

		public string DOOGLANJOFJ;

		public string BICEOOCDGBD()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_GUI_BRONZE", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Pack: Gold Cards ", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_TAPON", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("USD", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string ILDBFCIMIPI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.JLCCDEMIPGB("Awake '{0}'", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("+{0}", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_ERROR", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("Deploys_Count", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OFEOHDIAIJA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("\"{0}\"\t", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF(" - ", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("-1", DOOGLANJOFJ);
			fPPNAOFJOCF.OLJECDCJHIP("nextGenerate", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MAJKLAFDDON()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.JLCCDEMIPGB("You probably assigned bad type of AmmoSetup to gun", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Shotgunner", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("inappId", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("I Got New Squad Messages", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OPAAIPALNKI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.OFHNEHKHELB("Completed", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("(Ljava/lang/Object;)Z", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("RETRY", DOOGLANJOFJ);
			fPPNAOFJOCF.OLJECDCJHIP("Landroid/os/Parcelable$Creator;", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string IKFDIDOAFKA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("AmmoPool", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_NOTIFICATION_DAILYREWARD_CARDS", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("Weapon", DOOGLANJOFJ);
			fPPNAOFJOCF.OLJECDCJHIP("Player_Avoided_Grenade_On_First_Try", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string ONLNILBHKJJ()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.OFHNEHKHELB("Directory \"{0}\" does not exists", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("()Z", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("GameGold", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("showedOffers", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string FFMAAHMHCAM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JLCCDEMIPGB("UsedCards", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("DOWNLOADBTN", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_BRONZEPACK", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("GOT MAINTENANCE MESSAGE IN CREATE ACCOUNT", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EFHCEGDBCJH()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.JLCCDEMIPGB("()I", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("changing moneypack to B variant withoud data from fuseboxx", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("GetOriginalAccountAlias()", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("0.#", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string NLAKJODBJOB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("BS: Remove Google Play", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF(", on server = ", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("IsGold", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("N", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MKCKMHOMECK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("isConnected", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("VIP active: {0}\tConfiguration time: {1}\tTime till end time: {2}\tLast shown: {3}", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_CONFIRM_ERRORCLAIMREWARD_TEXT", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("Squad Emblem ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public override string ToString()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("ProductId", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Price", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("PriceLocale", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("Product", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OENLNDACNCI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_YOUNEEDMONEYTOTRAINSPECIAL", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Icon", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("unit", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("ID_LEAVE_SPECTATE", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string GDDFCENINBB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.OFHNEHKHELB("Input turned on completely: ", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_DELIVER", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("SquadIcon", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("+", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string DMEOPDDGKKH()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("Buy_Weapons", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF(",", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("Notification_MaintenanceInformation", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("something is wrong - time == 0", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string LHPJMKEPKDN()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.IHCNGGHNALF("Gold", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("#PETER# Weapon Screen - LEFT BUTTON - weapon state: SLOT DELIVERED\t\tbutton type: ACTIVATE", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_NOTIFICATION_DAILYREWARD_VIP", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("ID_RELOG_TO_WRONG_FB_DIALOG_TEXT2", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CIJPPHFEBNI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("ammo", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_GUI_REPORTABUSE_LISTITEM7", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("WarFriends necesita permiso para acceder a tu almacenamiento de medios para descargar datos esenciales del juego.Por favor, acepta el cuadro de solicitud de permisos que aparece a continuación; nunca utilizaremos este permiso para ningún otro fin.", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("ID_FEATURE_RATE-DESCRIPTION", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MBHMDIIIIHA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.IHCNGGHNALF("Name", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("menu-warbucks", GIFAJAMKBLM);
			fPPNAOFJOCF2.OFHNEHKHELB("facebook get me data, but still is logged in, logout manualy", DOOGLANJOFJ);
			fPPNAOFJOCF.CHNMAKKEKLL("Try out: Equipping visual \"{0}\" instead of visual \"{1}\"", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string FOOMIBECINC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.OFHNEHKHELB("Google Play Time out", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("/Player_", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("Card_2_Played", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("AddAmmoRPC", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EAJBHIFDNIM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_WEAPON2UPGRADE_WEAPON1UPGRADE", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("IT IS", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("?", DOOGLANJOFJ);
			fPPNAOFJOCF.OLJECDCJHIP("ID_INMASTER1", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string PJLHMOIHPGG()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.OFHNEHKHELB("Ignore_Text_{0}{1}", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("D2", GIFAJAMKBLM);
			fPPNAOFJOCF2.IHCNGGHNALF("S", DOOGLANJOFJ);
			fPPNAOFJOCF.OLJECDCJHIP("is-IS", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string CCONMNOONFF()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.OFHNEHKHELB("C5", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("\n", GIFAJAMKBLM);
			fPPNAOFJOCF2.JLCCDEMIPGB("Rank", DOOGLANJOFJ);
			fPPNAOFJOCF.IHCNGGHNALF("setGender", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}
	}
}
