using System;
using System.Text;
using UnityEngine;

namespace FuseMisc
{
	public struct CKIENDMMJOG
	{
		public string MGFPKCKMOHM;

		public string AGPANDBMDLC;

		public string MALFKFCFECD;

		public int KOHNHGIABIH;

		public int ALEHOMNMLJF;

		public string BICEOOCDGBD()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("Wave Out of range. #DAN#", MGFPKCKMOHM);
			fPPNAOFJOCF2.OFHNEHKHELB("menu-gold", AGPANDBMDLC);
			fPPNAOFJOCF2.JLCCDEMIPGB("setCustomProfileNumber", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("New Assignments!", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("Card withdrawn", ALEHOMNMLJF);
			fPPNAOFJOCF.IHCNGGHNALF("BoughtIndex", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OENLNDACNCI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_STAT_SHOTGUNKILLS", MGFPKCKMOHM);
			fPPNAOFJOCF2.OFHNEHKHELB("false", AGPANDBMDLC);
			fPPNAOFJOCF2.OFHNEHKHELB("WarBucks", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("DailyMissionsCompletionRewardTickets", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("VipReward1", ALEHOMNMLJF);
			fPPNAOFJOCF.OLJECDCJHIP("Warbucks_Balance", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public CKIENDMMJOG(string HHLLCFBCONC)
		{
			this = default(CKIENDMMJOG);
			if (string.IsNullOrEmpty(HHLLCFBCONC))
			{
				return;
			}
			try
			{
				string[] array = HHLLCFBCONC.Split(',');
				MGFPKCKMOHM = Encoding.UTF8.GetString(Convert.FromBase64String(array[0]));
				AGPANDBMDLC = Encoding.UTF8.GetString(Convert.FromBase64String(array[1]));
				MALFKFCFECD = Encoding.UTF8.GetString(Convert.FromBase64String(array[2]));
				ALEHOMNMLJF = (int.TryParse(array[3], out var result) ? result : 0);
				KOHNHGIABIH = (int.TryParse(array[4], out var result2) ? result2 : 0);
			}
			catch (Exception exception)
			{
				Debug.LogError("FuseSDK: Error parsing RewardInfo. Returning default value.");
				Debug.LogException(exception);
			}
		}

		public string FOOMIBECINC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.IHCNGGHNALF("0", MGFPKCKMOHM);
			fPPNAOFJOCF2.IHCNGGHNALF("WarFriends precisa da sua permissão para acessar sua mídia para carregar informações adicionais.Favor aceitar o diálogo de permissão a seguir, saiba que não será utilizada para nenhum outro propósito.", AGPANDBMDLC);
			fPPNAOFJOCF2.OFHNEHKHELB("ExplodeNetwork", MALFKFCFECD);
			fPPNAOFJOCF2.JHGBHIJBGKK("{0} 1 / 3", KOHNHGIABIH);
			fPPNAOFJOCF2.JHGBHIJBGKK("DailyMissionsCompletionRewardTickets", ALEHOMNMLJF);
			fPPNAOFJOCF.OLJECDCJHIP("TEXTURE SIZE IS: ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MKCKMHOMECK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_DELIVERED_WEAPON", MGFPKCKMOHM);
			fPPNAOFJOCF2.OFHNEHKHELB("#PETER# League Arc - stop ignore on ", AGPANDBMDLC);
			fPPNAOFJOCF2.JLCCDEMIPGB("DevSettings", MALFKFCFECD);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_HEYDEPOSITSOMEWARCARDS", KOHNHGIABIH);
			fPPNAOFJOCF2.JHGBHIJBGKK("ID_SHOTDAMAGE", ALEHOMNMLJF);
			fPPNAOFJOCF.IHCNGGHNALF("207 STAGE 7 SNIPER", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public override string ToString()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("PreRollMessage", MGFPKCKMOHM);
			fPPNAOFJOCF2.IHCNGGHNALF("RewardMessage", AGPANDBMDLC);
			fPPNAOFJOCF2.IHCNGGHNALF("RewardItem", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("RewardItemId", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("RewardAmount", ALEHOMNMLJF);
			fPPNAOFJOCF.IHCNGGHNALF("RewardedInfo", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MAJKLAFDDON()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.OFHNEHKHELB("Called InitGuiValues in Member Content.", MGFPKCKMOHM);
			fPPNAOFJOCF2.OFHNEHKHELB("Flawless", AGPANDBMDLC);
			fPPNAOFJOCF2.IHCNGGHNALF("1", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("dailyRewardData", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_VIPLOOTBOXREWARDED", ALEHOMNMLJF);
			fPPNAOFJOCF.IHCNGGHNALF("(Landroid/os/Parcel;I)V", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string FFMAAHMHCAM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_ERROR", MGFPKCKMOHM);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_TUTORIAL_UPGRADEUNIT_4", AGPANDBMDLC);
			fPPNAOFJOCF2.OFHNEHKHELB("cards", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_BUTTON_YOU", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_YOURREWARDS", ALEHOMNMLJF);
			fPPNAOFJOCF.OLJECDCJHIP("hiding dialog............", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string NLAKJODBJOB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.OFHNEHKHELB("Total_Warbucks_Spent", MGFPKCKMOHM);
			fPPNAOFJOCF2.JLCCDEMIPGB("x{0}", AGPANDBMDLC);
			fPPNAOFJOCF2.IHCNGGHNALF("VGOfferInfo", MALFKFCFECD);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_STAT_ASSIGNMENTSDONE", KOHNHGIABIH);
			fPPNAOFJOCF2.IHCNGGHNALF("vip", ALEHOMNMLJF);
			fPPNAOFJOCF.CHNMAKKEKLL("ID_LEAGUE2", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}
	}
}
