namespace FuseMisc
{
	public struct EBDBJAKJNLD
	{
		public string OAKIALCHAIG;

		public string DPDEIHFAPJP;

		public string IEKIGEMEECE;

		public bool HELOLIKHOCB;

		public string FFMAAHMHCAM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JLCCDEMIPGB("001 LOADING ASSETS STARTED", OAKIALCHAIG);
			fPPNAOFJOCF2.JLCCDEMIPGB("MainScene*.unity", DPDEIHFAPJP);
			fPPNAOFJOCF2.IHCNGGHNALF("AmmoPool", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("VideoFeed", HELOLIKHOCB);
			fPPNAOFJOCF.OLJECDCJHIP("bazooka_shot_barrier", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OPAAIPALNKI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_GETSP", OAKIALCHAIG);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_STATE_SEARCHINGFOROPPONENT", DPDEIHFAPJP);
			fPPNAOFJOCF2.JLCCDEMIPGB("HeartPrice", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF(" OK!", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("LeagueId", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OENLNDACNCI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.IHCNGGHNALF("AccountType", OAKIALCHAIG);
			fPPNAOFJOCF2.OFHNEHKHELB("Category ", DPDEIHFAPJP);
			fPPNAOFJOCF2.JLCCDEMIPGB("shield_shot", IEKIGEMEECE);
			fPPNAOFJOCF2.MDJCMBBOADP("FinishedBeginnersLeague", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("com/google/android/gms/common/ConnectionResult", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public override string ToString()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("FuseId", OAKIALCHAIG);
			fPPNAOFJOCF2.IHCNGGHNALF("AccountId", DPDEIHFAPJP);
			fPPNAOFJOCF2.IHCNGGHNALF("Alias", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("Pending", HELOLIKHOCB);
			fPPNAOFJOCF.IHCNGGHNALF("Friend", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MAJKLAFDDON()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("deliveryReduce", OAKIALCHAIG);
			fPPNAOFJOCF2.OFHNEHKHELB("doesnt exist", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("0", IEKIGEMEECE);
			fPPNAOFJOCF2.MDJCMBBOADP("DogtagsRefillRankUp", HELOLIKHOCB);
			fPPNAOFJOCF.OLJECDCJHIP("Physical ammo is null !!!", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BICEOOCDGBD()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.OFHNEHKHELB("Humvee", OAKIALCHAIG);
			fPPNAOFJOCF2.JLCCDEMIPGB("ReputationPointsAdded", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_BUYVALUEPACK", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("Mission", HELOLIKHOCB);
			fPPNAOFJOCF.OLJECDCJHIP("ID_NAMECHARACTER", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string NLAKJODBJOB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("country-china", OAKIALCHAIG);
			fPPNAOFJOCF2.IHCNGGHNALF("_DESC", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("menu-health-ico", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("Failed to join room during or after match and MatchManager.isReconnect = FALSE", HELOLIKHOCB);
			fPPNAOFJOCF.OLJECDCJHIP("Vip status changed!", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string IKFDIDOAFKA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)8);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_EMPTYUNITTRAIN", OAKIALCHAIG);
			fPPNAOFJOCF2.IHCNGGHNALF("SetBeepRPC", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("SquadEventProgress", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("<", HELOLIKHOCB);
			fPPNAOFJOCF.IHCNGGHNALF("ID_UNITCANBEPROMOTEDTOTIER", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string FOOMIBECINC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JLCCDEMIPGB("\t\"TRUE\"", OAKIALCHAIG);
			fPPNAOFJOCF2.OFHNEHKHELB("android.os.Build$VERSION", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_PARSING_CONFIGURATIONS", IEKIGEMEECE);
			fPPNAOFJOCF2.MDJCMBBOADP("com/google/android/gms/common/api/Status", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("GB", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string DMEOPDDGKKH()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_MOREXP", OAKIALCHAIG);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_ERROR", DPDEIHFAPJP);
			fPPNAOFJOCF2.IHCNGGHNALF("AtlasPreparer.LoadCommonCoroutine", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_GETSP", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("BS: On add video reward success!", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string ILDBFCIMIPI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_SQUADMEDALSSMALL", OAKIALCHAIG);
			fPPNAOFJOCF2.JLCCDEMIPGB(" ", DPDEIHFAPJP);
			fPPNAOFJOCF2.JLCCDEMIPGB("DogTagCap", IEKIGEMEECE);
			fPPNAOFJOCF2.MDJCMBBOADP("()Landroid/app/PendingIntent;", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("Mouse Y", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MBHMDIIIIHA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.JLCCDEMIPGB("AssignemntId", OAKIALCHAIG);
			fPPNAOFJOCF2.OFHNEHKHELB("hookId", DPDEIHFAPJP);
			fPPNAOFJOCF2.OFHNEHKHELB("customDouble", IEKIGEMEECE);
			fPPNAOFJOCF2.IHCNGGHNALF("qbz2_idle", HELOLIKHOCB);
			fPPNAOFJOCF.CHNMAKKEKLL("HeroicPoints", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OFEOHDIAIJA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_YOUHAVENOGOLDWARCARDSAVAILABLE", OAKIALCHAIG);
			fPPNAOFJOCF2.JLCCDEMIPGB("S", DPDEIHFAPJP);
			fPPNAOFJOCF2.IHCNGGHNALF("S", IEKIGEMEECE);
			fPPNAOFJOCF2.MDJCMBBOADP("SquadPromoteMessage {0}", HELOLIKHOCB);
			fPPNAOFJOCF.IHCNGGHNALF("ID_NOTINLEAGUETEXT", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}
	}
}
