using System;
using System.Text;
using UnityEngine;

namespace FuseMisc
{
	public struct MFJJLPLILJF
	{
		public string MDMLKBEGCGN;

		public float GICDFLDICNG;

		public string EJAOIMDLKDO;

		public int OAIIBKKCLLO;

		public DateTime DAIOILGOBGP;

		public DateTime CNGDKFPFCDC;

		public string IFFJPCHLIDG;

		public string BBNHEKLGNIC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF((FPPNAOFJOCF.NKHJBLBAAEB)7);
			fPPNAOFJOCF2.IHCNGGHNALF("XP", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("idle", GICDFLDICNG);
			fPPNAOFJOCF2.OFHNEHKHELB("-", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("FuseSDK: ", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ArmyPower", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_GO_TO_ARMORY_3", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_WARBUCKS", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("warbucks", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string GDDFCENINBB()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.OFHNEHKHELB("right", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("LevelName", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_SECONDWEAPONDAMAGE", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("Amount", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("/PC/", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF(", exception = ", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_FRIENDINSQUAD_TEXT", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("jp", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string KJELICIGHML()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.IHCNGGHNALF("Legacy Shaders/Transparent/DiffuseNew", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("WarbuckRewardWin", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_YOUNEEDMONEYTOTRAINSPECIAL", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("GooglePlayName", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("DpsCoef", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("122 MENU WEAPON SCREEN TUTORIAL WEAPON SELECTED", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("Emblem updated!", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF(", result = ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EFHCEGDBCJH()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.OFHNEHKHELB("ShotFrequencyMaxCannon", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Player", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("next", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("{0}{1}[-] {2}/[-] {3}", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Friends", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Have discount {0} to upgrade {1}", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("RewardItem", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("ID_VETERANPACKDESCRIPTION", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string LIKPNODLLEC()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.OFHNEHKHELB("{0} {1}{2}", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("AdminName", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("en", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("account", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("<", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF(" (FREE)", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB(".", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("WarBucks", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string PGBHLHDMEIA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.JLCCDEMIPGB("DailyMissionsCompletionRewardScraps", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Other Player Cards -> Card Manager -> does not contain id: ", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB(" ", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("UIReflectionEffect reference missing for index ", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("GLM: RegisterOrLogin -  5", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("special", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("{0} Empty", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("ID_TUTORIAL_UPGRADEUNIT_3", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string JPHKHJGKLJD()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_CONFIRM_NOTACTIVEEVENT", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("WarBucks", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("SquadMembers", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("LoadingFinishedRPC", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("{0} {1}", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ItemRarity_4", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("ShotFrequencyMinCannon", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("Chat Tab: PUBLIC BUTTON clicked on ", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public override string ToString()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			fPPNAOFJOCF2.IHCNGGHNALF("ProductId", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("ProductPrice", GICDFLDICNG);
			fPPNAOFJOCF2.IHCNGGHNALF("ItemName", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ItemAmount", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("StartTime", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("EndTime", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Metadata", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("IAPOfferInfo", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string MKCKMHOMECK()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.IHCNGGHNALF("Skill", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("relog OK", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("CONTENTS_FILE_DESCRIPTOR", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("AddGameCenter with ", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("gold", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("menu-weapon-mp5-elite", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Player wants to join squad, name =", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("ID_CREATE", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string KDLGINIJCID()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JLCCDEMIPGB("damage", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("OK", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("(Lcom/google/android/gms/common/api/Api;)Lcom/google/android/gms/common/ConnectionResult;", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_PLAYERALREADYEXISTS", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("CONFERMA", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Checker", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("java.lang.Double", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("Claim Assignment success!", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string GIOJAGFALPL()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BAKED);
			fPPNAOFJOCF2.OFHNEHKHELB("ADDED WB ", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Friend", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB(" (FREE)", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("ShootFromBazookaFromCover", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("AttributionData", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("fr", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ArenaPoorConnection", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP("DemoteOrKickPlayer {0}", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OFEOHDIAIJA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.IHCNGGHNALF("Recieved {0} memory warnings in last 10 seconds", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("()F", GICDFLDICNG);
			fPPNAOFJOCF2.OFHNEHKHELB("{0} {1}{2}", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_ARENARULES_DEFENDERSPROHIBITED", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("subscription_tab_displayed", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("N", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_DAILYMISSIONSUNLOCKEDHINT3TITLE", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("FacebookName", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public MFJJLPLILJF(string HHLLCFBCONC)
		{
			this = default(MFJJLPLILJF);
			if (string.IsNullOrEmpty(HHLLCFBCONC))
			{
				return;
			}
			try
			{
				string[] array = HHLLCFBCONC.Split(',');
				MDMLKBEGCGN = Encoding.UTF8.GetString(Convert.FromBase64String(array[0]));
				GICDFLDICNG = ((!float.TryParse(array[1], out var result)) ? 0f : result);
				EJAOIMDLKDO = Encoding.UTF8.GetString(Convert.FromBase64String(array[2]));
				OAIIBKKCLLO = (int.TryParse(array[3], out var result2) ? result2 : 0);
				DAIOILGOBGP = ((!long.TryParse(array[4], out var result3)) ? 0 : result3).JHHJCIOHPAD();
				CNGDKFPFCDC = ((!long.TryParse(array[5], out var result4)) ? 0 : result4).JHHJCIOHPAD();
				IFFJPCHLIDG = Encoding.UTF8.GetString(Convert.FromBase64String(array[6]));
			}
			catch (Exception exception)
			{
				Debug.LogError("FuseSDK: Error parsing IAPOfferInfo. Returning default value.");
				Debug.LogException(exception);
			}
		}

		public string CIJPPHFEBNI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.OFHNEHKHELB("jp", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Changed country to {0} from {1}.", GICDFLDICNG);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_YOUNEEDMONEYTOBUY", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF(" (#", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("Have discount {0} to buy {1}", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("VipRewardForDay", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("setResultCallback", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("InApp_ID", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string PJLHMOIHPGG()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.JLCCDEMIPGB("currentDogtags: ", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("key= ", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("Wrong_Category", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("menu-dailyrewards-vip-ico", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("GameControllerCoop.StartGame START", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_SILVERARENACROWN", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("idle", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("ID_ERROR_SQUADNAMENOTUNIQUE", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string LHPJMKEPKDN()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			fPPNAOFJOCF2.OFHNEHKHELB("Warbucks", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Arena Lost - Scraps received = ", GICDFLDICNG);
			fPPNAOFJOCF2.IHCNGGHNALF("Display_Rental", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("Awake called: ", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("S", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Play_Card_Tutorial_Duration", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("Fuseboxx: No Dictionary with configuration found!", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("ID_SILVERARENACROWN", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string BOHPMCOKKPJ()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.STRING);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NUMBER);
			fPPNAOFJOCF2.OFHNEHKHELB("ID_CONFIRM_CONNECTTOGOOGLENAME", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("N", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("PT", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("Is_Overtime", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("RUN ON CHILDREN OF OBJECT \"", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("ID_CONFIRM_SERVERCOULDNOTCOMPLETED", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("303 STAGE 9 STARTED", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.CHNMAKKEKLL("Squad Wars Data {0}", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string EAJBHIFDNIM()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_TUTORIAL_SWIPE_UP", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Xp", GICDFLDICNG);
			fPPNAOFJOCF2.IHCNGGHNALF("InAppHandlerIos: restore transactions", EJAOIMDLKDO);
			fPPNAOFJOCF2.IHCNGGHNALF("isInterrupted", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("WarFriends benötigt deine Genehmigung zum Zugriff auf deinen Medienspeicher, um wichtige Spieldaten herunterladen zu können.Bitte bestätige die folgende Genehmigungsanfrage. Wir werden diese Genehmigung nicht für andere Zwecke verwenden.", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("com/google/android/gms/common/api/Status", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("flamethrower_run", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("S", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string IKFDIDOAFKA()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.OBJECT);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.ARRAY);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_WARNING_BADVERSIONERROR_TEXT", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("No Offer Available (has all already)", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("BS: Remove Google Play", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("BattleId", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("GrenadeExplodeDamage", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("expiresOn", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.OFHNEHKHELB("Arena Lost - Scraps received = ", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.IHCNGGHNALF("ID_GETITCHEAPERNOW", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}

		public string OPAAIPALNKI()
		{
			FPPNAOFJOCF fPPNAOFJOCF = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.BOOL);
			FPPNAOFJOCF fPPNAOFJOCF2 = new FPPNAOFJOCF(FPPNAOFJOCF.NKHJBLBAAEB.NULL);
			fPPNAOFJOCF2.OFHNEHKHELB("com/google/android/gms/games/Games", MDMLKBEGCGN);
			fPPNAOFJOCF2.IHCNGGHNALF("Tutorial_Step_Complete", GICDFLDICNG);
			fPPNAOFJOCF2.JLCCDEMIPGB("ID_TUTORIAL_PLAY_CARD_DOWN", EJAOIMDLKDO);
			fPPNAOFJOCF2.JHGBHIJBGKK("BatchSizeMax", OAIIBKKCLLO);
			fPPNAOFJOCF2.IHCNGGHNALF("ID_TUTORIAL_START_PHASE2", DAIOILGOBGP.FJOPPAABFPB());
			fPPNAOFJOCF2.IHCNGGHNALF("com/google/android/gms/common/ConnectionResult", CNGDKFPFCDC.FJOPPAABFPB());
			fPPNAOFJOCF2.JLCCDEMIPGB("remainingTimeForNextDogtag", Convert.ToBase64String(Encoding.UTF8.GetBytes(IFFJPCHLIDG)));
			fPPNAOFJOCF.OLJECDCJHIP(",", fPPNAOFJOCF2);
			return fPPNAOFJOCF.ToString();
		}
	}
}
