namespace TuneSDK
{
	internal struct HENFBBGJCMK
	{
		public string MHPNDNJDPGE;

		public double CCDOJLFMPCN;

		public int GHJBDNGEJIM;

		public double LPMMABJCMOB;

		public string HENAJIMFKEG;

		public string CHFKJGEKNCL;

		public string HAJIBLIIBFB;

		public string JBLMNGCGCEH;

		public string NIJPEPNLEDJ;

		public HENFBBGJCMK(string MHPNDNJDPGE)
		{
			this.MHPNDNJDPGE = MHPNDNJDPGE;
			CCDOJLFMPCN = 0.0;
			GHJBDNGEJIM = 0;
			LPMMABJCMOB = 0.0;
			HENAJIMFKEG = null;
			CHFKJGEKNCL = null;
			HAJIBLIIBFB = null;
			JBLMNGCGCEH = null;
			NIJPEPNLEDJ = null;
		}

		public HENFBBGJCMK(NDMMHFNNODA PDAHBILDJPA)
		{
			MHPNDNJDPGE = PDAHBILDJPA.MHPNDNJDPGE;
			double? cCDOJLFMPCN = PDAHBILDJPA.CCDOJLFMPCN;
			CCDOJLFMPCN = ((!cCDOJLFMPCN.HasValue) ? 0.0 : cCDOJLFMPCN.Value);
			int? gHJBDNGEJIM = PDAHBILDJPA.GHJBDNGEJIM;
			GHJBDNGEJIM = (gHJBDNGEJIM.HasValue ? gHJBDNGEJIM.Value : 0);
			double? lPMMABJCMOB = PDAHBILDJPA.LPMMABJCMOB;
			LPMMABJCMOB = ((!lPMMABJCMOB.HasValue) ? 0.0 : lPMMABJCMOB.Value);
			HENAJIMFKEG = PDAHBILDJPA.HENAJIMFKEG;
			CHFKJGEKNCL = PDAHBILDJPA.CHFKJGEKNCL;
			HAJIBLIIBFB = PDAHBILDJPA.HAJIBLIIBFB;
			JBLMNGCGCEH = PDAHBILDJPA.JBLMNGCGCEH;
			NIJPEPNLEDJ = PDAHBILDJPA.NIJPEPNLEDJ;
		}
	}
}
