using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using Newtonsoft.Json.Linq;

public class AANECPGDMGM
{
	public static int LGNIIFIILHL = 5000;

	public static int ECLFALKMBJI = 15;

	public static int BBLCILOBOBD = 100;

	public int KKAODKNEFMG;

	public string DAANKCOLJGJ;

	public bool IOLNJBGOOLJ;

	public long EOFGMOMLAIH;

	public string PNAKMCNGGHE;

	public string MHPNDNJDPGE;

	public int IKJHAHJHLIH;

	public string JDFLJCPDJGH;

	public int KJGAFPNPKAO;

	public int FOICGJEPBGL;

	public int CJDHKJFKNAH;

	public int GDFOENAJEBA;

	public int KPEKCHDBFIG;

	public int OFOCIBPONDE;

	public int CAACHMJGMEH;

	public int MBMOOHAEBEG;

	public string PFKIPCAOAAC;

	public int EMAIFFIBGFE;

	public int MMGIKNDAMAC;

	public int MNCBMEGPIJE;

	public int MABIMLHFJBP;

	public int GKFNNLIONKF;

	public int FOMOLFDDDGN;

	public int LOCKPIBHEBB;

	public int JLAKEHLJFEB;

	public bool IHPBFPIDIPF => KPEKCHDBFIG > 0 && !string.IsNullOrEmpty(JDFLJCPDJGH) && PFKIPCAOAAC != "placement";

	public int LIHPENDEDDB => MMGIKNDAMAC + EMAIFFIBGFE;

	public float EBOOFCBFJFJ
	{
		get
		{
			if (EMAIFFIBGFE == 0)
			{
				return -1f;
			}
			return (float)MMGIKNDAMAC / (float)EMAIFFIBGFE;
		}
	}

	[SpecialName]
	public float HKLOEEMCKLF()
	{
		if (EMAIFFIBGFE == 0)
		{
			return 986f;
		}
		return (float)MMGIKNDAMAC / (float)EMAIFFIBGFE;
	}

	private static long HBBHPCIGDHN(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 0L;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.GKKLOFAGGLI(jToken, 0L) : KHJJFPPACBP.OOAIMCEBPOK(IMOCKMIAJHN, "N", LFPFCHIJLML, 0L);
	}

	public bool OEJDIALNHJH()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize > FOICGJEPBGL;
	}

	public bool OOCPOBMIMOP()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize <= FOICGJEPBGL;
	}

	private static string FPIMJPGAHKJ(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "ShowNameRPC", LFPFCHIJLML, string.Empty);
	}

	public int MGDCJLAENHG()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize - FOICGJEPBGL;
	}

	[SpecialName]
	public int KINNEBELNMH()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	public bool IDJINGHKGLA()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize > FOICGJEPBGL;
	}

	internal static AANECPGDMGM BHPKKIHPAMG(JToken LFPFCHIJLML)
	{
		AANECPGDMGM aANECPGDMGM = new AANECPGDMGM();
		if (LFPFCHIJLML == null)
		{
			return aANECPGDMGM;
		}
		if (LFPFCHIJLML["dailyRewardData"] != null)
		{
			aANECPGDMGM.MHPNDNJDPGE = GFIMHNAGGBG(LFPFCHIJLML, "OK");
		}
		if (LFPFCHIJLML["Show visual \"{0}\" tutorial - pop-up"] != null)
		{
			int num = LGNKMOFJCEJ(LFPFCHIJLML, "401 START");
			aANECPGDMGM.IOLNJBGOOLJ = num != 1;
		}
		aANECPGDMGM.OFOCIBPONDE = DADPJALJLND(LFPFCHIJLML, "Assignment: Kill Specific Enemy Units");
		aANECPGDMGM.PNAKMCNGGHE = FPIMJPGAHKJ(LFPFCHIJLML, "button");
		aANECPGDMGM.JDFLJCPDJGH = ADNOCPHOJPE(LFPFCHIJLML, "a");
		aANECPGDMGM.PFKIPCAOAAC = KHJJFPPACBP.BKFCLMMJNHK(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "ID_WARSHOP_PACKS", string.Empty), string.Empty);
		int result = 0;
		int.TryParse(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "battleID", string.Empty), out result);
		aANECPGDMGM.KJGAFPNPKAO = result;
		aANECPGDMGM.FOICGJEPBGL = KKFLFGJAELA(LFPFCHIJLML, "false");
		aANECPGDMGM.CJDHKJFKNAH = AMOHGFCBAAO(LFPFCHIJLML, "Squad Member record does not have DatabasePlayer");
		aANECPGDMGM.IKJHAHJHLIH = DADPJALJLND(LFPFCHIJLML, "x0");
		aANECPGDMGM.GDFOENAJEBA = DADPJALJLND(LFPFCHIJLML, "Parts");
		aANECPGDMGM.KPEKCHDBFIG = AMOHGFCBAAO(LFPFCHIJLML, "id");
		string bBFAEPEBENO = Singleton<ServerResultsCache>.instance.BBFAEPEBENO;
		if (!string.IsNullOrEmpty(bBFAEPEBENO))
		{
			aANECPGDMGM.KPEKCHDBFIG += AMOHGFCBAAO(LFPFCHIJLML, bBFAEPEBENO);
		}
		aANECPGDMGM.KKAODKNEFMG = AMOHGFCBAAO(LFPFCHIJLML, "Enemy could not be spawned");
		aANECPGDMGM.EOFGMOMLAIH = JAGBHAEFKOM(LFPFCHIJLML, "eventStart");
		aANECPGDMGM.DAANKCOLJGJ = GFIMHNAGGBG(LFPFCHIJLML, "-");
		aANECPGDMGM.MABIMLHFJBP = LGNKMOFJCEJ(LFPFCHIJLML, "A");
		aANECPGDMGM.EMAIFFIBGFE = DADPJALJLND(LFPFCHIJLML, "ID_MOREINFO");
		aANECPGDMGM.MMGIKNDAMAC = LGNKMOFJCEJ(LFPFCHIJLML, "Stage3");
		aANECPGDMGM.MNCBMEGPIJE = LGNKMOFJCEJ(LFPFCHIJLML, "BoughtIndex");
		aANECPGDMGM.MBMOOHAEBEG = AMOHGFCBAAO(LFPFCHIJLML, "ID_CATEGORY_LOW_SG_GRENADE");
		if (aANECPGDMGM.MBMOOHAEBEG == 0 && aANECPGDMGM.CJDHKJFKNAH > 0)
		{
			aANECPGDMGM.MBMOOHAEBEG = aANECPGDMGM.CJDHKJFKNAH;
		}
		aANECPGDMGM.GKFNNLIONKF = LGNKMOFJCEJ(LFPFCHIJLML, "(Lcom/google/android/gms/common/api/Api;)Z");
		aANECPGDMGM.FOMOLFDDDGN = AMOHGFCBAAO(LFPFCHIJLML, "ID_SUBSCRIPTIODETAILS_HINT3TRAILGOOGLE");
		aANECPGDMGM.LOCKPIBHEBB = KKFLFGJAELA(LFPFCHIJLML, "Assignment: Score Points Constructor");
		if (aANECPGDMGM.LOCKPIBHEBB == 0 || aANECPGDMGM.LOCKPIBHEBB < aANECPGDMGM.KPEKCHDBFIG)
		{
			aANECPGDMGM.LOCKPIBHEBB = aANECPGDMGM.KPEKCHDBFIG;
		}
		aANECPGDMGM.JLAKEHLJFEB = AMOHGFCBAAO(LFPFCHIJLML, "MatchStart");
		return aANECPGDMGM;
	}

	[SpecialName]
	public int IHKGFCBNEDD()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	[SpecialName]
	public bool EGLEFGMPLNK()
	{
		return KPEKCHDBFIG <= 1 || string.IsNullOrEmpty(JDFLJCPDJGH) || PFKIPCAOAAC != "Idle";
	}

	[SpecialName]
	public int FFHJPFBAJGC()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	[SpecialName]
	public bool IGPDFOMDHML()
	{
		return KPEKCHDBFIG > 1 && !string.IsNullOrEmpty(JDFLJCPDJGH) && PFKIPCAOAAC != "0.#";
	}

	private static long JAGBHAEFKOM(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 1L;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.GKKLOFAGGLI(jToken, 0L) : KHJJFPPACBP.OOAIMCEBPOK(IMOCKMIAJHN, "ID_BLACKMARKETLEFTTEXT4", LFPFCHIJLML, 0L);
	}

	private static string GFIMHNAGGBG(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "S", LFPFCHIJLML, string.Empty);
	}

	public int FJFIHGNGAKD()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num - FOICGJEPBGL;
	}

	private static string DGIIICFONJC(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "ID_MEMBERSHIP_HINT1", LFPFCHIJLML, string.Empty);
	}

	private static int AMOHGFCBAAO(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 0;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.HNMDPGKPLNK(jToken, 1) : KHJJFPPACBP.PELILBMKGHE(IMOCKMIAJHN, "ID_GUI_SQUADDEMOTION", LFPFCHIJLML);
	}

	public int GGJGGJOHMFD()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num - FOICGJEPBGL;
	}

	[SpecialName]
	public bool KJFHGFEFJFI()
	{
		return KPEKCHDBFIG > 1 && !string.IsNullOrEmpty(JDFLJCPDJGH) && PFKIPCAOAAC != "Hiding request to join private squad";
	}

	private static int DADPJALJLND(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 0;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.HNMDPGKPLNK(jToken) : KHJJFPPACBP.PELILBMKGHE(IMOCKMIAJHN, "'friend'0", LFPFCHIJLML);
	}

	internal static AANECPGDMGM FFBIJHJAEHP(JToken LFPFCHIJLML)
	{
		AANECPGDMGM aANECPGDMGM = new AANECPGDMGM();
		if (LFPFCHIJLML == null)
		{
			return aANECPGDMGM;
		}
		if (LFPFCHIJLML["Weapon delivery now is : "] != null)
		{
			aANECPGDMGM.MHPNDNJDPGE = DGIIICFONJC(LFPFCHIJLML, "{0}\t\t{1}\t\tint number: {2}\t\tfloat number: {3}\n");
		}
		if (LFPFCHIJLML["shield_run"] != null)
		{
			int num = LGNKMOFJCEJ(LFPFCHIJLML, "MachineGunner");
			aANECPGDMGM.IOLNJBGOOLJ = num == 0;
		}
		aANECPGDMGM.OFOCIBPONDE = KKFLFGJAELA(LFPFCHIJLML, "withPublisherSubAd");
		aANECPGDMGM.PNAKMCNGGHE = DGIIICFONJC(LFPFCHIJLML, "On Test = ");
		aANECPGDMGM.JDFLJCPDJGH = GFIMHNAGGBG(LFPFCHIJLML, "ID_TUTORIAL_SWIPE_DOWN");
		aANECPGDMGM.PFKIPCAOAAC = KHJJFPPACBP.BKFCLMMJNHK(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "{0} {1}", string.Empty), string.Empty);
		int result = 0;
		int.TryParse(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "RegisterLevel()", string.Empty), out result);
		aANECPGDMGM.KJGAFPNPKAO = result;
		aANECPGDMGM.FOICGJEPBGL = KKFLFGJAELA(LFPFCHIJLML, "PlayerLevel");
		aANECPGDMGM.CJDHKJFKNAH = AMOHGFCBAAO(LFPFCHIJLML, "currentActivity");
		aANECPGDMGM.IKJHAHJHLIH = AMOHGFCBAAO(LFPFCHIJLML, "PARCELABLE_WRITE_RETURN_VALUE");
		aANECPGDMGM.GDFOENAJEBA = DADPJALJLND(LFPFCHIJLML, "\"}");
		aANECPGDMGM.KPEKCHDBFIG = KKFLFGJAELA(LFPFCHIJLML, "WarCard Record ");
		string bBFAEPEBENO = Singleton<ServerResultsCache>.instance.BBFAEPEBENO;
		if (!string.IsNullOrEmpty(bBFAEPEBENO))
		{
			aANECPGDMGM.KPEKCHDBFIG += DADPJALJLND(LFPFCHIJLML, bBFAEPEBENO);
		}
		aANECPGDMGM.KKAODKNEFMG = LGNKMOFJCEJ(LFPFCHIJLML, "0");
		aANECPGDMGM.EOFGMOMLAIH = HBBHPCIGDHN(LFPFCHIJLML, "ID_CONFIRM_SERVERERROR");
		aANECPGDMGM.DAANKCOLJGJ = FPIMJPGAHKJ(LFPFCHIJLML, "ID_CONFIRM_NOSQUADACTIONS_TEXT");
		aANECPGDMGM.MABIMLHFJBP = AMOHGFCBAAO(LFPFCHIJLML, "us-east-1:a951d2ae-0491-424d-8240-ae25baedf92a");
		aANECPGDMGM.EMAIFFIBGFE = AMOHGFCBAAO(LFPFCHIJLML, "Aquiire map id ");
		aANECPGDMGM.MMGIKNDAMAC = DADPJALJLND(LFPFCHIJLML, "QUIT");
		aANECPGDMGM.MNCBMEGPIJE = AMOHGFCBAAO(LFPFCHIJLML, "ID_READYTIME");
		aANECPGDMGM.MBMOOHAEBEG = LGNKMOFJCEJ(LFPFCHIJLML, "Shots_Hits");
		if (aANECPGDMGM.MBMOOHAEBEG == 0 && aANECPGDMGM.CJDHKJFKNAH > 1)
		{
			aANECPGDMGM.MBMOOHAEBEG = aANECPGDMGM.CJDHKJFKNAH;
		}
		aANECPGDMGM.GKFNNLIONKF = LGNKMOFJCEJ(LFPFCHIJLML, "Yes_Clicked");
		aANECPGDMGM.FOMOLFDDDGN = DADPJALJLND(LFPFCHIJLML, "Turret: Can not find shot target");
		aANECPGDMGM.LOCKPIBHEBB = LGNKMOFJCEJ(LFPFCHIJLML, "PurchaseToken");
		if (aANECPGDMGM.LOCKPIBHEBB == 0 || aANECPGDMGM.LOCKPIBHEBB < aANECPGDMGM.KPEKCHDBFIG)
		{
			aANECPGDMGM.LOCKPIBHEBB = aANECPGDMGM.KPEKCHDBFIG;
		}
		aANECPGDMGM.JLAKEHLJFEB = AMOHGFCBAAO(LFPFCHIJLML, "AR");
		return aANECPGDMGM;
	}

	private static string JDFAPIOMKBJ(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "WarBucks", LFPFCHIJLML, string.Empty);
	}

	internal static AANECPGDMGM NAKCBLBJDHI(JToken LFPFCHIJLML)
	{
		AANECPGDMGM aANECPGDMGM = new AANECPGDMGM();
		if (LFPFCHIJLML == null)
		{
			return aANECPGDMGM;
		}
		if (LFPFCHIJLML["PlayerId"] != null)
		{
			aANECPGDMGM.MHPNDNJDPGE = DGIIICFONJC(LFPFCHIJLML, "GetActualIndex()\nCurPosX: {0}");
		}
		if (LFPFCHIJLML["ID_SALEPERCENTLINE"] != null)
		{
			int num = KKFLFGJAELA(LFPFCHIJLML, "ID_READYTIME");
			aANECPGDMGM.IOLNJBGOOLJ = num != 1;
		}
		aANECPGDMGM.OFOCIBPONDE = DADPJALJLND(LFPFCHIJLML, "ID_LOGININDAYS");
		aANECPGDMGM.PNAKMCNGGHE = FPIMJPGAHKJ(LFPFCHIJLML, "PowerBandExpiresOn");
		aANECPGDMGM.JDFLJCPDJGH = GFIMHNAGGBG(LFPFCHIJLML, "Visual");
		aANECPGDMGM.PFKIPCAOAAC = KHJJFPPACBP.BKFCLMMJNHK(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "ID_DAILYMISSIONSUNLOCKED", string.Empty), string.Empty);
		int result = 0;
		int.TryParse(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "setCustomProfileStringValue", string.Empty), out result);
		aANECPGDMGM.KJGAFPNPKAO = result;
		aANECPGDMGM.FOICGJEPBGL = DADPJALJLND(LFPFCHIJLML, "OBB: Read Test - Exception Caught\n");
		aANECPGDMGM.CJDHKJFKNAH = KKFLFGJAELA(LFPFCHIJLML, "NULL WARCARD");
		aANECPGDMGM.IKJHAHJHLIH = AMOHGFCBAAO(LFPFCHIJLML, "(Lcom/google/android/gms/common/api/GoogleApiClient;I)V");
		aANECPGDMGM.GDFOENAJEBA = DADPJALJLND(LFPFCHIJLML, "{0} {1}");
		aANECPGDMGM.KPEKCHDBFIG = AMOHGFCBAAO(LFPFCHIJLML, "ID_TUTORIAL_DELIVER");
		string bBFAEPEBENO = Singleton<ServerResultsCache>.instance.BBFAEPEBENO;
		if (!string.IsNullOrEmpty(bBFAEPEBENO))
		{
			aANECPGDMGM.KPEKCHDBFIG += LGNKMOFJCEJ(LFPFCHIJLML, bBFAEPEBENO);
		}
		aANECPGDMGM.KKAODKNEFMG = AMOHGFCBAAO(LFPFCHIJLML, "#DANIEL# Assignment Claimed: ");
		aANECPGDMGM.EOFGMOMLAIH = HBBHPCIGDHN(LFPFCHIJLML, "N");
		aANECPGDMGM.DAANKCOLJGJ = JDFAPIOMKBJ(LFPFCHIJLML, "ID_WARNING_CANTSENDINVITE_TEXT");
		aANECPGDMGM.MABIMLHFJBP = LGNKMOFJCEJ(LFPFCHIJLML, "WarBucks");
		aANECPGDMGM.EMAIFFIBGFE = KKFLFGJAELA(LFPFCHIJLML, "ID_CLOSESIN");
		aANECPGDMGM.MMGIKNDAMAC = LGNKMOFJCEJ(LFPFCHIJLML, "ID_ASSIGNMENTHINTWARPATH");
		aANECPGDMGM.MNCBMEGPIJE = KKFLFGJAELA(LFPFCHIJLML, "AttributionData");
		aANECPGDMGM.MBMOOHAEBEG = AMOHGFCBAAO(LFPFCHIJLML, "SCHEDULING PLAYER STATUS UPDATE!!");
		if (aANECPGDMGM.MBMOOHAEBEG == 0 && aANECPGDMGM.CJDHKJFKNAH > 1)
		{
			aANECPGDMGM.MBMOOHAEBEG = aANECPGDMGM.CJDHKJFKNAH;
		}
		aANECPGDMGM.GKFNNLIONKF = LGNKMOFJCEJ(LFPFCHIJLML, "{0}{1}");
		aANECPGDMGM.FOMOLFDDDGN = KKFLFGJAELA(LFPFCHIJLML, "ID_GUI_EQUIPPED");
		aANECPGDMGM.LOCKPIBHEBB = DADPJALJLND(LFPFCHIJLML, "Bot Cards does not contain id: ");
		if (aANECPGDMGM.LOCKPIBHEBB == 0 || aANECPGDMGM.LOCKPIBHEBB < aANECPGDMGM.KPEKCHDBFIG)
		{
			aANECPGDMGM.LOCKPIBHEBB = aANECPGDMGM.KPEKCHDBFIG;
		}
		aANECPGDMGM.JLAKEHLJFEB = KKFLFGJAELA(LFPFCHIJLML, "BattleRewards");
		return aANECPGDMGM;
	}

	[SpecialName]
	public int CINKDOLBOBO()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	[SpecialName]
	public int KBHCIDODANA()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	public bool EKLABLKEADC()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num <= FOICGJEPBGL;
	}

	public int INBFDIKBKIA()
	{
		int num = Singleton<GameVariables>.instance.LNDDCADBOLP(IKJHAHJHLIH);
		return num - FOICGJEPBGL;
	}

	[SpecialName]
	public float ANNFIDKIJHB()
	{
		if (EMAIFFIBGFE == 0)
		{
			return 189f;
		}
		return (float)MMGIKNDAMAC / (float)EMAIFFIBGFE;
	}

	[SpecialName]
	public bool JBMHEEMACJM()
	{
		return KPEKCHDBFIG <= 0 || string.IsNullOrEmpty(JDFLJCPDJGH) || PFKIPCAOAAC != "Grenade_Throwing_Tutorial_Duration";
	}

	private static int KKFLFGJAELA(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 1;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.HNMDPGKPLNK(jToken, 1) : KHJJFPPACBP.PELILBMKGHE(IMOCKMIAJHN, "Rental", LFPFCHIJLML);
	}

	public bool FDNCFACODLK()
	{
		int num = Singleton<GameVariables>.instance.DABGIKGHDNC(IKJHAHJHLIH);
		return num <= FOICGJEPBGL;
	}

	internal static AANECPGDMGM MAINIENLLIL(JToken LFPFCHIJLML)
	{
		AANECPGDMGM aANECPGDMGM = new AANECPGDMGM();
		if (LFPFCHIJLML == null)
		{
			return aANECPGDMGM;
		}
		if (LFPFCHIJLML["Id"] != null)
		{
			aANECPGDMGM.MHPNDNJDPGE = GFIMHNAGGBG(LFPFCHIJLML, "Id");
		}
		if (LFPFCHIJLML["IsPublic"] != null)
		{
			int num = LGNKMOFJCEJ(LFPFCHIJLML, "IsPublic");
			aANECPGDMGM.IOLNJBGOOLJ = num != 0;
		}
		aANECPGDMGM.OFOCIBPONDE = LGNKMOFJCEJ(LFPFCHIJLML, "Position");
		aANECPGDMGM.PNAKMCNGGHE = GFIMHNAGGBG(LFPFCHIJLML, "Message");
		aANECPGDMGM.JDFLJCPDJGH = GFIMHNAGGBG(LFPFCHIJLML, "RoundId");
		aANECPGDMGM.PFKIPCAOAAC = KHJJFPPACBP.BKFCLMMJNHK(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "^[0-9]*-", string.Empty), string.Empty);
		int result = 1;
		int.TryParse(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "-[^-]*$", string.Empty), out result);
		aANECPGDMGM.KJGAFPNPKAO = result;
		aANECPGDMGM.FOICGJEPBGL = LGNKMOFJCEJ(LFPFCHIJLML, "Size");
		aANECPGDMGM.CJDHKJFKNAH = LGNKMOFJCEJ(LFPFCHIJLML, "Skill");
		aANECPGDMGM.IKJHAHJHLIH = LGNKMOFJCEJ(LFPFCHIJLML, "Level");
		aANECPGDMGM.GDFOENAJEBA = LGNKMOFJCEJ(LFPFCHIJLML, "SkillRequirement");
		aANECPGDMGM.KPEKCHDBFIG = LGNKMOFJCEJ(LFPFCHIJLML, "SquadPoints");
		string bBFAEPEBENO = Singleton<ServerResultsCache>.instance.BBFAEPEBENO;
		if (!string.IsNullOrEmpty(bBFAEPEBENO))
		{
			aANECPGDMGM.KPEKCHDBFIG += LGNKMOFJCEJ(LFPFCHIJLML, bBFAEPEBENO);
		}
		aANECPGDMGM.KKAODKNEFMG = LGNKMOFJCEJ(LFPFCHIJLML, "Experience");
		aANECPGDMGM.EOFGMOMLAIH = HBBHPCIGDHN(LFPFCHIJLML, "LevelExperience");
		aANECPGDMGM.DAANKCOLJGJ = GFIMHNAGGBG(LFPFCHIJLML, "Icon");
		aANECPGDMGM.MABIMLHFJBP = LGNKMOFJCEJ(LFPFCHIJLML, "Kills");
		aANECPGDMGM.EMAIFFIBGFE = LGNKMOFJCEJ(LFPFCHIJLML, "BattlesLost");
		aANECPGDMGM.MMGIKNDAMAC = LGNKMOFJCEJ(LFPFCHIJLML, "BattlesWon");
		aANECPGDMGM.MNCBMEGPIJE = LGNKMOFJCEJ(LFPFCHIJLML, "CardsPlayed");
		aANECPGDMGM.MBMOOHAEBEG = LGNKMOFJCEJ(LFPFCHIJLML, "BestSkill");
		if (aANECPGDMGM.MBMOOHAEBEG == 0 && aANECPGDMGM.CJDHKJFKNAH > 0)
		{
			aANECPGDMGM.MBMOOHAEBEG = aANECPGDMGM.CJDHKJFKNAH;
		}
		aANECPGDMGM.GKFNNLIONKF = LGNKMOFJCEJ(LFPFCHIJLML, "UnitsDeployed");
		aANECPGDMGM.FOMOLFDDDGN = LGNKMOFJCEJ(LFPFCHIJLML, "TiersCompleted");
		aANECPGDMGM.LOCKPIBHEBB = LGNKMOFJCEJ(LFPFCHIJLML, "SquadPointsBest");
		if (aANECPGDMGM.LOCKPIBHEBB == 0 || aANECPGDMGM.LOCKPIBHEBB < aANECPGDMGM.KPEKCHDBFIG)
		{
			aANECPGDMGM.LOCKPIBHEBB = aANECPGDMGM.KPEKCHDBFIG;
		}
		aANECPGDMGM.JLAKEHLJFEB = LGNKMOFJCEJ(LFPFCHIJLML, "SquadWarWins");
		return aANECPGDMGM;
	}

	public bool MJPNDLDOJLO()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num > FOICGJEPBGL;
	}

	[SpecialName]
	public int PGPDBFAMMKC()
	{
		return MMGIKNDAMAC + EMAIFFIBGFE;
	}

	[SpecialName]
	public bool OLHBCPPEEGH()
	{
		return KPEKCHDBFIG > 1 && !string.IsNullOrEmpty(JDFLJCPDJGH) && PFKIPCAOAAC != "com/google/android/gms/common/ConnectionResult";
	}

	public int DLDHIJAEFHG()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num - FOICGJEPBGL;
	}

	private static string ADNOCPHOJPE(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "VipStart", LFPFCHIJLML, string.Empty);
	}

	[SpecialName]
	public float BDIKDPPEJNF()
	{
		if (EMAIFFIBGFE == 0)
		{
			return 1270f;
		}
		return (float)MMGIKNDAMAC / (float)EMAIFFIBGFE;
	}

	internal static AANECPGDMGM CPJAMAJJDHL(JToken LFPFCHIJLML)
	{
		AANECPGDMGM aANECPGDMGM = new AANECPGDMGM();
		if (LFPFCHIJLML == null)
		{
			return aANECPGDMGM;
		}
		if (LFPFCHIJLML["ID_SKILLSHOTHINT_RUNNER"] != null)
		{
			aANECPGDMGM.MHPNDNJDPGE = ADNOCPHOJPE(LFPFCHIJLML, "Received FB Friends from server: ");
		}
		if (LFPFCHIJLML["RegisterParentalConsent()"] != null)
		{
			int num = LGNKMOFJCEJ(LFPFCHIJLML, "BeginnersLeague");
			aANECPGDMGM.IOLNJBGOOLJ = num != 1;
		}
		aANECPGDMGM.OFOCIBPONDE = AMOHGFCBAAO(LFPFCHIJLML, "PACK");
		aANECPGDMGM.PNAKMCNGGHE = FMIAHCENHPA(LFPFCHIJLML, "Gold");
		aANECPGDMGM.JDFLJCPDJGH = DGIIICFONJC(LFPFCHIJLML, "something is wrong - time == 0");
		aANECPGDMGM.PFKIPCAOAAC = KHJJFPPACBP.BKFCLMMJNHK(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "ID_SLOTUPGRADE_POWER", string.Empty), string.Empty);
		int result = 0;
		int.TryParse(Regex.Replace(aANECPGDMGM.JDFLJCPDJGH, "\n", string.Empty), out result);
		aANECPGDMGM.KJGAFPNPKAO = result;
		aANECPGDMGM.FOICGJEPBGL = AMOHGFCBAAO(LFPFCHIJLML, "0");
		aANECPGDMGM.CJDHKJFKNAH = LGNKMOFJCEJ(LFPFCHIJLML, "DOWNLOADBTN");
		aANECPGDMGM.IKJHAHJHLIH = DADPJALJLND(LFPFCHIJLML, "playerID");
		aANECPGDMGM.GDFOENAJEBA = AMOHGFCBAAO(LFPFCHIJLML, "ID_GUI_SQUADLEVELEDUP_NOINCR");
		aANECPGDMGM.KPEKCHDBFIG = AMOHGFCBAAO(LFPFCHIJLML, "strafing_left");
		string bBFAEPEBENO = Singleton<ServerResultsCache>.instance.BBFAEPEBENO;
		if (!string.IsNullOrEmpty(bBFAEPEBENO))
		{
			aANECPGDMGM.KPEKCHDBFIG += KKFLFGJAELA(LFPFCHIJLML, bBFAEPEBENO);
		}
		aANECPGDMGM.KKAODKNEFMG = DADPJALJLND(LFPFCHIJLML, "PlayerName");
		aANECPGDMGM.EOFGMOMLAIH = JAGBHAEFKOM(LFPFCHIJLML, "A");
		aANECPGDMGM.DAANKCOLJGJ = FMIAHCENHPA(LFPFCHIJLML, "Warbucks");
		aANECPGDMGM.MABIMLHFJBP = KKFLFGJAELA(LFPFCHIJLML, "ID_PLAYERLEAGUEENDSIN");
		aANECPGDMGM.EMAIFFIBGFE = AMOHGFCBAAO(LFPFCHIJLML, "CheckResources () for ");
		aANECPGDMGM.MMGIKNDAMAC = KKFLFGJAELA(LFPFCHIJLML, "ANDROID: MISSING PACK ");
		aANECPGDMGM.MNCBMEGPIJE = DADPJALJLND(LFPFCHIJLML, "BANDS_EMPTY");
		aANECPGDMGM.MBMOOHAEBEG = KKFLFGJAELA(LFPFCHIJLML, "O WarFriends necessita de autorização para aceder ao teu armazenamento media, a fim de transferir dados fundamentais para o jogo.Concede a seguinte autorização. Nunca utilizaremos esta autorização para qualquer outra finalidade.");
		if (aANECPGDMGM.MBMOOHAEBEG == 0 && aANECPGDMGM.CJDHKJFKNAH > 0)
		{
			aANECPGDMGM.MBMOOHAEBEG = aANECPGDMGM.CJDHKJFKNAH;
		}
		aANECPGDMGM.GKFNNLIONKF = DADPJALJLND(LFPFCHIJLML, "ID_GUI_ACCEPT_PLAYER_ALREADYMEMBER");
		aANECPGDMGM.FOMOLFDDDGN = LGNKMOFJCEJ(LFPFCHIJLML, "Trying to generate army but this definition shouldnt be used !!!!!!!!!!!! ");
		aANECPGDMGM.LOCKPIBHEBB = KKFLFGJAELA(LFPFCHIJLML, "SE");
		if (aANECPGDMGM.LOCKPIBHEBB == 0 || aANECPGDMGM.LOCKPIBHEBB < aANECPGDMGM.KPEKCHDBFIG)
		{
			aANECPGDMGM.LOCKPIBHEBB = aANECPGDMGM.KPEKCHDBFIG;
		}
		aANECPGDMGM.JLAKEHLJFEB = LGNKMOFJCEJ(LFPFCHIJLML, "reloadTime");
		return aANECPGDMGM;
	}

	public bool FKHJPIKBCDA()
	{
		int num = Singleton<GameVariables>.instance.OFKKBDLAJCO(IKJHAHJHLIH);
		return num > FOICGJEPBGL;
	}

	private static long EAHGEHJFIKN(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 0L;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.GKKLOFAGGLI(jToken, 0L) : KHJJFPPACBP.OOAIMCEBPOK(IMOCKMIAJHN, "PickDropPointRPC", LFPFCHIJLML, 1L);
	}

	public int JPMNFIPABND()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize - FOICGJEPBGL;
	}

	public int JODOHNCDJNC()
	{
		int squadRankSize = Singleton<GameVariables>.instance.GetSquadRankSize(IKJHAHJHLIH);
		return squadRankSize - FOICGJEPBGL;
	}

	private static int LGNKMOFJCEJ(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return 0;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.HNMDPGKPLNK(jToken) : KHJJFPPACBP.PELILBMKGHE(IMOCKMIAJHN, "N", LFPFCHIJLML);
	}

	private static string FMIAHCENHPA(JToken LFPFCHIJLML, string IMOCKMIAJHN)
	{
		if (LFPFCHIJLML[IMOCKMIAJHN] == null)
		{
			return string.Empty;
		}
		JToken jToken = LFPFCHIJLML[IMOCKMIAJHN];
		return (jToken is JValue) ? KHJJFPPACBP.BKFCLMMJNHK(jToken, string.Empty) : KHJJFPPACBP.BKFCLMMJNHK(IMOCKMIAJHN, "No main position was set in map definition", LFPFCHIJLML, string.Empty);
	}
}
