using UnityEngine;
using UnityEngine.Serialization;

public class CardRocketTiming : Card
{
	[FormerlySerializedAs("NIMEEPHLAEA")]
	public float HMDBMGCHIJO;

	private PlayerWeapon FFHMECBFJMH;

	private float JFFIKONBHLG;

	private bool NNDMKIACBBM;

	private bool DJNINJLMMAA;

	private bool AIKJBNODBNI;

	private GDCLLGDCODD ALNFGGOGFOO;

	private PlayerController MBIAKMPDOPG;

	public const string EJLCMBEKFFN = "game-card-ico-explosivetiming";

	public virtual void NIODJFGIJNN(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[4];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.LJLDJOHAAMC("These IDs have different translations:\n", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += OKIJBHOFFML;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void LECNFJGCDLC()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= KNLCGAHONCI;
			AIKJBNODBNI = true;
		}
	}

	private void KNLCGAHONCI(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= KKKGEEAPMBJ;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.LDGKPCDJPLA("Sniper_Tutorial_Played", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void HPFMMIJJFBJ()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= OGNKPBIKGFP;
			AIKJBNODBNI = false;
		}
	}

	private void GDEHEKKDANN(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= KKKGEEAPMBJ;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.NNPILDOKNJO("ID_LOADING", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void MCMGMPAFPLK()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= JJLNMMLALGK;
			AIKJBNODBNI = true;
		}
	}

	public virtual void EDLIKPAHGPH()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= OGNKPBIKGFP;
			AIKJBNODBNI = true;
		}
	}

	private void DHFKEIPHKKD(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= GDEHEKKDANN;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.GGHDIAFACAH("{0} Empty", NABOFKMBMKH: false, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void NLPMJPNEEOM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[6];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.LDGKPCDJPLA("ID_CATEGORY_GRENADE", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += AMEOCPAOGJH;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JCFIFGAJKCB()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= JJLNMMLALGK;
			AIKJBNODBNI = false;
		}
	}

	private void OGNKPBIKGFP(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= IDOIMOCJNPC;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF(" NOT OK!\t\t\t\t\t\t", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	private void PELHDJIOFBF(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= DHGMHCGOMLF;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.GKAOMCGCDGE("twitter_user_id", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public override void DisconnectEvents()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= CKKGLFOJMGJ;
			AIKJBNODBNI = false;
		}
	}

	private void OKJCAJONOAE(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= ADDJMGJGHBH;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.GGHDIAFACAH("\t\"FALSE\"", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	private void CKKGLFOJMGJ(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= CKKGLFOJMGJ;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.Show("game-card-ico-explosivetiming", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void JIDDCBAEAGC()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= OKIJBHOFFML;
			AIKJBNODBNI = false;
		}
	}

	private void ODEEEIINAFL(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= DHFKEIPHKKD;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("ID_COMPLETED", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void EBOJNIKJKPG()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= OKIJBHOFFML;
			AIKJBNODBNI = true;
		}
	}

	public virtual void POLFFIJKMNA(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[6];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.LJLDJOHAAMC("ID_HEALTH", NABOFKMBMKH: true, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += OKIJBHOFFML;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void IDAFLCICMKD(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("$0", NABOFKMBMKH: true, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += PELHDJIOFBF;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void PLJOBLELPAJ()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= AEFAAHMIJFM;
			AIKJBNODBNI = false;
		}
	}

	private void IDOIMOCJNPC(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= ODEEEIINAFL;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("DogTagRefillTime", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void IDLKDDEEALI(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[0];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.PEBHGOMEKME("ID_BECOMEAVIP", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += AMEOCPAOGJH;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JCCNJNMBKBO(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[6];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.GGHDIAFACAH("ID_OVERTIME", NABOFKMBMKH: true, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += JJLNMMLALGK;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void CKLOEEJCAOH()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= IDOIMOCJNPC;
			AIKJBNODBNI = true;
		}
	}

	public virtual void JDMHDLOCMPO()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= FMIEOOKPFLM;
			AIKJBNODBNI = true;
		}
	}

	public virtual void BKNCKLLMJHI()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= JJLNMMLALGK;
			AIKJBNODBNI = false;
		}
	}

	public virtual void AKEJOLCFDJI(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[1];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.Show("{0} {1}", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHFKEIPHKKD;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void CMGCBIANBAG(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[1];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("{0}{1}", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ADDJMGJGHBH;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void GAGEHEGFGOA(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[7];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.NNPILDOKNJO("IsNotificationAvailable()", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += PELHDJIOFBF;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JIAIAPAHOII()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= OGNKPBIKGFP;
			AIKJBNODBNI = true;
		}
	}

	private void NINIOPMNDKC(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= OGNKPBIKGFP;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("menu-info-ico", NABOFKMBMKH: false, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	private void JJLNMMLALGK(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= AEFAAHMIJFM;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("TEXTURE SIZE IS: ", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void KKEPLAFJKOO(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[8];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.JCJFMHGNIOF("ID_CONFIRM_NOTENOUGHMEDALSTOJOIN", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ODEEEIINAFL;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void GBFGPFAFPKH()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= PELHDJIOFBF;
			AIKJBNODBNI = true;
		}
	}

	public virtual void NLGPBNBAPIN(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[0];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("-VIP", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHGMHCGOMLF;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void KDPEOGLJPOB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BIIHCAEKCOD("Camo load error: {0}", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ADDJMGJGHBH;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void NPGNJOGAEMK(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[1];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("USPECH POKUSU O LOGIN NA FB!!!", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += AMEOCPAOGJH;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void IGLGKCMAEEE()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= AEFAAHMIJFM;
			AIKJBNODBNI = true;
		}
	}

	private void KKKGEEAPMBJ(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= KNLCGAHONCI;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.GGHDIAFACAH("REMOVING CURRENT PLAYER FROM SQUAD ", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	private void BKFFCKKJFNN(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= AEFAAHMIJFM;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.EOEDEJKJKMN("subscription1", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	private void AMEOCPAOGJH(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= AEFAAHMIJFM;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.NNPILDOKNJO("C5", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void BJCODKFDGIH()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= DHFKEIPHKKD;
			AIKJBNODBNI = false;
		}
	}

	public virtual void ILGMMCAGIIM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[8];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BIIHCAEKCOD("ID_GUI_UNLOCKEDAT", NABOFKMBMKH: true, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHFKEIPHKKD;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void BECBKICGOKB()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= AEFAAHMIJFM;
			AIKJBNODBNI = true;
		}
	}

	public override void UseCard(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.Show("game-card-ico-explosivetiming", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += CKKGLFOJMGJ;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void EHFIHPJILMG()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= AMEOCPAOGJH;
			AIKJBNODBNI = false;
		}
	}

	public virtual void AFAKDALHMDK()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= GDEHEKKDANN;
			AIKJBNODBNI = true;
		}
	}

	public virtual void LMJPLJMABEF()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= FMIEOOKPFLM;
			AIKJBNODBNI = false;
		}
	}

	private void FJNPKPHIDBJ(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= CBIJFOBNJKO;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("ID_WARNING_DUPLICATEDVIDEOFEED", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	private void CEDMLDJELDE(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= OGNKPBIKGFP;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.LDGKPCDJPLA("SkillDifference", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void DHMNAJKOGIM()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= KJKKKAOINNH;
			AIKJBNODBNI = false;
		}
	}

	private void OKIJBHOFFML(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= OGNKPBIKGFP;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.GGHDIAFACAH("ID_BEGINNERSLEAGUE2", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void EKFKAICCHLI(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[4];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.JCJFMHGNIOF("goldenSuitcase", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += OKIJBHOFFML;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void CFIKIKCBGKI()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= IDOIMOCJNPC;
			AIKJBNODBNI = false;
		}
	}

	public virtual void NPNDHFIMPHE(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.EOEDEJKJKMN("EUId", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += KJKKKAOINNH;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	private void CPAOIKMPCOI(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= JPFGLHALKCD;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.BIIHCAEKCOD("ID_NOTIFICATION_DAILYREWARD_GOLD", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void FEJKPDNPNOA(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[0];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.GCLFBCIKNAH("id", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += CKKGLFOJMGJ;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	private void KJKKKAOINNH(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= PELHDJIOFBF;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.OFPAGLLFPPK("Too few containers!!!!", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void CCODFGNHBOJ(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[0];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("ETM: Show Rewarded Video", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ADDJMGJGHBH;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JDECOEIBHBP()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= OGNKPBIKGFP;
			AIKJBNODBNI = false;
		}
	}

	public virtual void GDEHLDBGNHB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[8];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.PEBHGOMEKME("ID_CONFIRM_ERROR", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ADDJMGJGHBH;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void AGMKIMGHPAL(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[8];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.PEBHGOMEKME("game-card-ico-headsup", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += INJNAKPOPFG;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JIHLMCGMAMO(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[4];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.GKAOMCGCDGE("Player_Avoided_Grenade_On_First_Try", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHFKEIPHKKD;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void BLDICPPHHPA()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= DHGMHCGOMLF;
			AIKJBNODBNI = true;
		}
	}

	public virtual void DMHDDHILDJK()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= CEDMLDJELDE;
			AIKJBNODBNI = false;
		}
	}

	public virtual void EEJJPCKLAMB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BIIHCAEKCOD("menu-assignments-type-crate", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += PELHDJIOFBF;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void JGNBFCJFAHM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("_TintColor", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += PELHDJIOFBF;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void OGCHJPKOLPK()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= FMIEOOKPFLM;
			AIKJBNODBNI = false;
		}
	}

	public virtual void EGHLIEEBAHJ(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.DLNGGGOEDLL("WarBucks", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHFKEIPHKKD;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void LMPJIPAFBDE(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.JLMDEMFIHCA().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.JCJFMHGNIOF("ID_ARENAPROMOSTARTSIN", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += AEFAAHMIJFM;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void NDPOMFABJLM()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= INJNAKPOPFG;
			AIKJBNODBNI = true;
		}
	}

	public virtual void ECJGKKEGCGA(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[8];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.JCJFMHGNIOF("D6", NABOFKMBMKH: false, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += CBIJFOBNJKO;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	private void CBIJFOBNJKO(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= FMIEOOKPFLM;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.GCLFBCIKNAH("CreationTime", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void JMNNGMOAMEO()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= DHGMHCGOMLF;
			AIKJBNODBNI = true;
		}
	}

	private void ADDJMGJGHBH(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= AEFAAHMIJFM;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("PowerBandId", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void NPODFBNDOAK(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[1];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("menu-powerband-damage-ico", NABOFKMBMKH: true, HGNIGKCLLHM: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += FMIEOOKPFLM;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void CHOEJKFNLLC()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= PELHDJIOFBF;
			AIKJBNODBNI = true;
		}
	}

	private void AEFAAHMIJFM(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= PELHDJIOFBF;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = false;
			MBIAKMPDOPG.cardIconIndicator.Show("leagueMembers", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	private void DHGMHCGOMLF(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= GDEHEKKDANN;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("WENEEDTO", NABOFKMBMKH: false);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void JIHHEBGMCBB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[1];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.GCLFBCIKNAH("League: {0}  LeagueId: {1}  LeagueDivision: {2}  WeeklyMedals: {3}  GLobalMedals: {4}", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += AEFAAHMIJFM;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void CPALNIACCKB()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= BKFFCKKJFNN;
			AIKJBNODBNI = false;
		}
	}

	public virtual void JCHICJBOCFA(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.DLNGGGOEDLL("CURRENT PLAYER - REMOVE CARD FROM DEPOSITED CARDS - card id is null", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += BKFFCKKJFNN;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void MPFCLCJMDCJ(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[7];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("ID_COLLECTELITEPARTSFROMARENALOOTBOXES", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += ADDJMGJGHBH;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void LAHPKDOAAAM()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
			Weapon.OnShotFired -= FJNPKPHIDBJ;
			AIKJBNODBNI = false;
		}
	}

	public virtual void HGINJJNEEDB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.FMKGGADDHJK().LAGONJMBJMM[5];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.GCLFBCIKNAH(" AND ", NABOFKMBMKH: true);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += OKJCAJONOAE;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	private void JPFGLHALKCD(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = true;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= OGNKPBIKGFP;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.FJILILFMPIF("D2", NABOFKMBMKH: false, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
	}

	public virtual void OJLEHLGEMLI(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
		}
		FFHMECBFJMH = MBIAKMPDOPG.BEIIOAIJMFK().LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.NNPILDOKNJO("OnPauseDrawing", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = true;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += KNLCGAHONCI;
		AIKJBNODBNI = true;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void MEMDELDKFJI(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[7];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.LJLDJOHAAMC("experiment name is ", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = true;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += NINIOPMNDKC;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.weapon.JMDLKIAKOIE;
		NNDMKIACBBM = false;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	private void INJNAKPOPFG(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.HFNAMMBPJAJ()) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = false;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= NINIOPMNDKC;
				AIKJBNODBNI = true;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.BBJADAJPJHH("Version", NABOFKMBMKH: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void KMPPOGGNJPC()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= AEFAAHMIJFM;
			AIKJBNODBNI = false;
		}
	}

	private void FMIEOOKPFLM(Weapon ENCEFOOPBMK, Vector3 MDOPFNNFLFB)
	{
		if (!(ENCEFOOPBMK == FFHMECBFJMH.weapon) || !NNDMKIACBBM)
		{
			return;
		}
		if (DJNINJLMMAA)
		{
			FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE = JFFIKONBHLG;
			NNDMKIACBBM = true;
			DJNINJLMMAA = false;
			if (AIKJBNODBNI)
			{
				Weapon.OnShotFired -= KNLCGAHONCI;
				AIKJBNODBNI = false;
			}
		}
		else
		{
			FFHMECBFJMH.weapon.JMDLKIAKOIE = JFFIKONBHLG * HMDBMGCHIJO;
			DJNINJLMMAA = true;
			MBIAKMPDOPG.cardIconIndicator.LDGKPCDJPLA("Xp", NABOFKMBMKH: true, HGNIGKCLLHM: true);
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
	}

	public virtual void APHGOCOMCAJ(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		if (AIKJBNODBNI && FFHMECBFJMH != null)
		{
			FFHMECBFJMH.KLBAKPENKMM = false;
		}
		FFHMECBFJMH = MBIAKMPDOPG.weaponInventory.LAGONJMBJMM[2];
		ALNFGGOGFOO = MNBIOCOAJHK;
		MBIAKMPDOPG.cardIconIndicator.NNPILDOKNJO("ID_STATE_OPPONENTISREADYTOBATTLE", NABOFKMBMKH: false);
		FFHMECBFJMH.KLBAKPENKMM = false;
		DJNINJLMMAA = false;
		if (AIKJBNODBNI)
		{
			MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
			return;
		}
		Weapon.OnShotFired += DHGMHCGOMLF;
		AIKJBNODBNI = false;
		JFFIKONBHLG = FFHMECBFJMH.HFNAMMBPJAJ().JMDLKIAKOIE;
		NNDMKIACBBM = true;
		MNBIOCOAJHK.CardWasUsed(this, MBIAKMPDOPG.fraction);
	}

	public virtual void DOLJLBIGBHK()
	{
		if (AIKJBNODBNI)
		{
			FFHMECBFJMH.KLBAKPENKMM = true;
			Weapon.OnShotFired -= ADDJMGJGHBH;
			AIKJBNODBNI = true;
		}
	}
}
