public class CardFriendlyFireOff : Card
{
	private PlayerController MBIAKMPDOPG;

	private bool NNDMKIACBBM;

	private float BHABHIDDBLH;

	public virtual void HGINJJNEEDB(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = true;
	}

	public virtual void INPLMEOCGKE(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = true;
	}

	public virtual void DBAPEPJHJMH(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = false;
	}

	public override void UseCard(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = true;
	}

	public virtual void NEPIKOKDBHP(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		NNDMKIACBBM = false;
		MBIAKMPDOPG.COHFDCGJECK = true;
	}

	public virtual void AIBAOLCOMBM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.MAJOCMGOFII(CIOPAKLHFIL);
		NNDMKIACBBM = false;
		MBIAKMPDOPG.COHFDCGJECK = false;
	}

	public virtual void OFNENBNMMOO(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.HEAGPACBLJA(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = false;
	}

	public virtual void HOBNOKFFHCM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.CCPHMCAIJNA(CIOPAKLHFIL);
		NNDMKIACBBM = true;
		MBIAKMPDOPG.COHFDCGJECK = true;
	}

	public virtual void NLPMJPNEEOM(GDCLLGDCODD MNBIOCOAJHK, GHPGNELIDBM CIOPAKLHFIL)
	{
		MNBIOCOAJHK.CardWasUsed(this, CIOPAKLHFIL);
		MBIAKMPDOPG = PlayerController.GetPlayerOld(CIOPAKLHFIL);
		NNDMKIACBBM = false;
		MBIAKMPDOPG.COHFDCGJECK = false;
	}
}
