public class CDACJEGCGLB
{
	public PNFCNJHKBBN GGIOEPBPMHF;

	public int IEALLELGOBM;

	public LevelBehaviour IKILOKMAGJJ;

	public static CDACJEGCGLB MJGNIAFBMNF(int HAFMGCFMCPC)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = HAFMGCFMCPC;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.Gold;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB FOFHNFNLOEL(int FMCANDNKEKC)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = FMCANDNKEKC;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.ArenaTickets;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB OFBDBPEDKCF(int HAFMGCFMCPC)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = HAFMGCFMCPC;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.EliteParts;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB KMIDDBEAEKG(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)41;
		return cDACJEGCGLB;
	}

	public static int AJOFNDDBHFL(CDACJEGCGLB JPMFEINCHNP, CDACJEGCGLB HKDPDFLOEDK)
	{
		int gGIOEPBPMHF = (int)JPMFEINCHNP.GGIOEPBPMHF;
		return gGIOEPBPMHF.CompareTo((int)HKDPDFLOEDK.GGIOEPBPMHF);
	}

	public static CDACJEGCGLB OFBODECLPBC()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.BronzeCardpack;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB HHGMPOJKDJL(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)(-55);
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB BFHEOFFKAMI()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.SilverCardpack;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB NGABPAOFOCM(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.SilverWarCards;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB OJEKBPGDCFL(int AIFBEPDEHHA)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = AIFBEPDEHHA;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.SilverCardpack;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB DNHKCKIAMMP()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.GoldCardpack;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB CIMGPHBGOCH()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.Scraps;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB HMGDGHAIDJA(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)55;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB ONCBFMEFMKJ(int AIFBEPDEHHA)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = AIFBEPDEHHA;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.XP;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB ALGPCNPCPOL(int PDMGPGEHLNM, LevelBehaviour IOIKKIIFOCB = null)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.IKILOKMAGJJ = IOIKKIIFOCB;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.EliteParts;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB JKNGDHGEMPK(int HAFMGCFMCPC)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = HAFMGCFMCPC;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.EliteParts;
		return cDACJEGCGLB;
	}

	public static int GIDMKBGKDNF(CDACJEGCGLB JPMFEINCHNP, CDACJEGCGLB HKDPDFLOEDK)
	{
		int gGIOEPBPMHF = (int)JPMFEINCHNP.GGIOEPBPMHF;
		return gGIOEPBPMHF.CompareTo((int)HKDPDFLOEDK.GGIOEPBPMHF);
	}

	public static CDACJEGCGLB DCBDNIJAHEB(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.BronzeWarCards;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB FCFOLGKLHCP(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)(-120);
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB KHBBIJFAGNC(int FPMJEDOCJKE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = FPMJEDOCJKE;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.WarBucks;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB OBKKOGALKNI(int FPMJEDOCJKE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = FPMJEDOCJKE;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.Scraps;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB FKCPDGIJODO(int MDOHMDGAHDD)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = MDOHMDGAHDD;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.Scraps;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB LEGIDPOHIHH(int AIFBEPDEHHA)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = AIFBEPDEHHA;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.BronzeCardpack;
		return cDACJEGCGLB;
	}

	public static int IKFDKDDMCHO(CDACJEGCGLB JPMFEINCHNP, CDACJEGCGLB HKDPDFLOEDK)
	{
		int gGIOEPBPMHF = (int)JPMFEINCHNP.GGIOEPBPMHF;
		return gGIOEPBPMHF.CompareTo((int)HKDPDFLOEDK.GGIOEPBPMHF);
	}

	public static CDACJEGCGLB HECPHABDFEP(int FPMJEDOCJKE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = FPMJEDOCJKE;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.WarBucks;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB MHIONBHIOOE(int CJMKHJELGIE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = CJMKHJELGIE;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.HeroicPoints;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB HAONOLJLGON(int CJMKHJELGIE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = CJMKHJELGIE;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)(-111);
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB GBOKHPDPIIO(int HAFMGCFMCPC)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = HAFMGCFMCPC;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.EliteParts;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB NBFEIJBLKKA(int CJMKHJELGIE)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = CJMKHJELGIE;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)(-100);
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB GFDGABAKKNP(int AIFBEPDEHHA)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = AIFBEPDEHHA;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.ArenaTickets;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB OLKHLHODELD()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.WarBucks;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB GKCAHKJPPAE()
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = 1;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.GoldCardpack;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB NLHHPGBAOMP(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = (PNFCNJHKBBN)91;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB PPBJIGHKCNO(int MDOHMDGAHDD)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = MDOHMDGAHDD;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.Scraps;
		return cDACJEGCGLB;
	}

	public static CDACJEGCGLB IJJAKOJNEPA(int PDMGPGEHLNM)
	{
		CDACJEGCGLB cDACJEGCGLB = new CDACJEGCGLB();
		cDACJEGCGLB.IEALLELGOBM = PDMGPGEHLNM;
		cDACJEGCGLB.GGIOEPBPMHF = PNFCNJHKBBN.GoldWarCards;
		return cDACJEGCGLB;
	}
}
