using System.Runtime.CompilerServices;
using CodeStage.AntiCheat.ObscuredTypes;
using UnityEngine;

public class FCLADBGKCIA
{
	public ObscuredFloat ACKOHPCAOEA = 1f;

	public ObscuredFloat BAHEFCJKPIP = 1f;

	public ObscuredFloat CJIHIILEMMH = 1f;

	public ObscuredFloat JNLLKFGHMNI = 1f;

	public int AAHHALGKMNN;

	public int GLOMGLHDKNI;

	public override string ToString()
	{
		return $"HP: {ACKOHPCAOEA} ACC: {BAHEFCJKPIP} SHS: {CJIHIILEMMH}SP: {JNLLKFGHMNI}";
	}

	private FCLADBGKCIA ONKCGHAJJNE(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	[SpecialName]
	public static FCLADBGKCIA CGIKCOFAHDE(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.LDIDFGCKNMP(HJFNLBKLNAH);
	}

	public virtual string CIJPPHFEBNI()
	{
		object[] array = new object[7];
		array[0] = ACKOHPCAOEA;
		array[0] = BAHEFCJKPIP;
		array[7] = CJIHIILEMMH;
		array[3] = JNLLKFGHMNI;
		return string.Format("game-box-ammo", array);
	}

	private FCLADBGKCIA MBJNFKJKLDC(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	[SpecialName]
	public static FCLADBGKCIA JNGHOGBNJPC(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.INLLAJLJKIM(HJFNLBKLNAH);
	}

	[SpecialName]
	public static FCLADBGKCIA NDOKEJMONCB(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.ADGPPGKFMGD(HJFNLBKLNAH);
	}

	public int LEIDKPFICNA(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 1, 4);
	}

	[SpecialName]
	public static FCLADBGKCIA COCEIANAAJJ(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.LDIDFGCKNMP(HJFNLBKLNAH);
	}

	public virtual string MBHMDIIIIHA()
	{
		object[] array = new object[4];
		array[0] = ACKOHPCAOEA;
		array[0] = BAHEFCJKPIP;
		array[3] = CJIHIILEMMH;
		array[2] = JNLLKFGHMNI;
		return string.Format("TuneListener onPowerHooksChanged", array);
	}

	private FCLADBGKCIA LDIDFGCKNMP(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	public int HHPIBBLOLJO(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 0, 3);
	}

	public virtual string ILDBFCIMIPI()
	{
		object[] array = new object[4];
		array[1] = ACKOHPCAOEA;
		array[0] = BAHEFCJKPIP;
		array[3] = CJIHIILEMMH;
		array[5] = JNLLKFGHMNI;
		return string.Format("D2", array);
	}

	[SpecialName]
	public static FCLADBGKCIA OCDCNFLDNEP(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.LDIDFGCKNMP(HJFNLBKLNAH);
	}

	public int FBCGLCJKLPL(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 0, 4);
	}

	private FCLADBGKCIA ADGPPGKFMGD(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	public int FMNCAMJPCBN(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 0, 5);
	}

	public virtual string CCONMNOONFF()
	{
		object[] array = new object[2];
		array[1] = ACKOHPCAOEA;
		array[1] = BAHEFCJKPIP;
		array[7] = CJIHIILEMMH;
		array[1] = JNLLKFGHMNI;
		return string.Format("1", array);
	}

	private FCLADBGKCIA BCNFPCHPHEE(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	private FCLADBGKCIA OPDPCLAPFMC(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	private FCLADBGKCIA IPLGABCFHLH(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	public int MKGKBALBIHL(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 0, 4);
	}

	public int HLHHLDGBLFM(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 0, 2);
	}

	[SpecialName]
	public static FCLADBGKCIA IAODDBOALFF(FCLADBGKCIA LGNIBPKIMNN, FCLADBGKCIA HJFNLBKLNAH)
	{
		return LGNIBPKIMNN.MBJNFKJKLDC(HJFNLBKLNAH);
	}

	private FCLADBGKCIA INLLAJLJKIM(FCLADBGKCIA NEEBBLOFHEF)
	{
		FCLADBGKCIA fCLADBGKCIA = new FCLADBGKCIA();
		fCLADBGKCIA.ACKOHPCAOEA = (float)ACKOHPCAOEA * (float)NEEBBLOFHEF.ACKOHPCAOEA;
		fCLADBGKCIA.BAHEFCJKPIP = (float)BAHEFCJKPIP * (float)NEEBBLOFHEF.BAHEFCJKPIP;
		fCLADBGKCIA.CJIHIILEMMH = (float)CJIHIILEMMH * (float)NEEBBLOFHEF.CJIHIILEMMH;
		fCLADBGKCIA.JNLLKFGHMNI = (float)JNLLKFGHMNI * (float)NEEBBLOFHEF.JNLLKFGHMNI;
		fCLADBGKCIA.AAHHALGKMNN = AAHHALGKMNN + NEEBBLOFHEF.AAHHALGKMNN;
		fCLADBGKCIA.GLOMGLHDKNI = GLOMGLHDKNI + NEEBBLOFHEF.GLOMGLHDKNI;
		return fCLADBGKCIA;
	}

	public int FKLKOIKFAKI(PDNPBLFEPJG INNCDOLLNPG)
	{
		return Mathf.Clamp((INNCDOLLNPG != PDNPBLFEPJG.Buff) ? GLOMGLHDKNI : AAHHALGKMNN, 1, 4);
	}
}
