public static class FIDIMECCNLP
{
	public static float GHBCLBPPDMI(float IDEBKDPMPGM, float GAFMOFFOBAK, float DMEHGIDJEBD)
	{
		return (IDEBKDPMPGM - GAFMOFFOBAK) * 1f / (DMEHGIDJEBD - GAFMOFFOBAK);
	}

	public static float IDGNBOADDAI(float IDEBKDPMPGM, float GKIGHIBHOMG, float BJDEODDLCDN, float MDEAJFONJLE, float FIPCDKMDEEL)
	{
		return MDEAJFONJLE + (IDEBKDPMPGM - GKIGHIBHOMG) * (FIPCDKMDEEL - MDEAJFONJLE) / (BJDEODDLCDN - GKIGHIBHOMG);
	}
}
