using UnityEngine;

public class GrenadeAmmo : GrenadeAmmoContent
{
	public virtual void KFNMNPEJHIK(Vector3 MPHCNMDIPAI)
	{
		base.INABHIGCAGL(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = CCDHMLCIBOG(MPHCNMDIPAI);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(94f);
	}

	public virtual void CGGEBOHENHG(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = GHHFMOCMLKB(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1935f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC MEGLHDOJEAC(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		bool flag = KPJKKODEODO() is Grenade && ((Grenade)HPCHGPPCBNE()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Flash;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGEHCNJEJJK();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 716f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)8) : ((DFHALNOAGGC.PEBLJIFMBGC)7));
		return pKDCCCNJIEC;
	}

	private DFHALNOAGGC.PKDCCCNJIEC JDKDCFKLEJJ(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		bool flag = MNOCEAENIKP() is Grenade && ((Grenade)PAIKDEPMONH()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)5;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1860f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)7));
		return pKDCCCNJIEC;
	}

	public virtual void PKMFMKOPLJF(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeRPCImplementation(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = COALKKLBJCF(MPHCNMDIPAI);
		DFHALNOAGGC.IPEDNMPJOOO(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(851f);
	}

	public virtual void GGKMNFEGJBL(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LKHJMFIJIDJ(MPHCNMDIPAI);
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1352f, ENGGOAPADCP: true);
	}

	public virtual void KKONANJNNBP(Vector3 MPHCNMDIPAI)
	{
		base.NPOCOJIDBPN(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LHNNCMMDANO(MPHCNMDIPAI);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(586f, ENGGOAPADCP: true);
	}

	public virtual void NEHPAOKBAAE(Vector3 MPHCNMDIPAI)
	{
		base.INABHIGCAGL(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = KNGBHBACKIN(MPHCNMDIPAI);
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1709f);
	}

	public virtual void GOKKFFIJEAI(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = ANPFNJFKDIM(MPHCNMDIPAI);
		DFHALNOAGGC.JLJNJFJCJMH(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1257f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC COALKKLBJCF(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		bool flag = base.JMMJHCOKCGG is Grenade && ((Grenade)HPCHGPPCBNE()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Molotov;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 648f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)8) : DFHALNOAGGC.PEBLJIFMBGC.Barel);
		return pKDCCCNJIEC;
	}

	public virtual void IPNFDEDGFBD(Vector3 MPHCNMDIPAI)
	{
		base.BLJPLCFILOF(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = PDFLODALBOJ(MPHCNMDIPAI);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1914f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC DDHCKDLCKLP(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = KNLBEJDDGML() as GrenadeAmmoSetup;
		bool flag = !(HPCHGPPCBNE() is Grenade) || ((Grenade)MNOCEAENIKP()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Poison;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1715f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Big : DFHALNOAGGC.PEBLJIFMBGC.Small);
		return pKDCCCNJIEC;
	}

	public virtual void INJIBFNCJFI(Vector3 MPHCNMDIPAI)
	{
		base.JLBLOHJNAAG(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DMNGKJOKAIG(MPHCNMDIPAI);
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1490f);
	}

	public virtual void ABLKNCLKJDG(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DMNGKJOKAIG(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(626f, ENGGOAPADCP: true);
	}

	public virtual void PLIJJCHDIGM(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MAJHBDMIHCE(MPHCNMDIPAI);
		DFHALNOAGGC.EDLKNHCMHJF(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(764f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC DMNGKJOKAIG(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		bool flag = HPCHGPPCBNE() is Grenade && ((Grenade)base.JMMJHCOKCGG).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)5;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 980f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)5) : DFHALNOAGGC.PEBLJIFMBGC.Molotov);
		return pKDCCCNJIEC;
	}

	public virtual void MMNMCEHEGME(Vector3 MPHCNMDIPAI)
	{
		base.INABHIGCAGL(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DMNGKJOKAIG(MPHCNMDIPAI);
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1621f);
	}

	public virtual void AENFHBIMJOD(Vector3 MPHCNMDIPAI)
	{
		base.DOPNJAIJKLJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = PDFLODALBOJ(MPHCNMDIPAI);
		DFHALNOAGGC.DCKBBBOHNFK(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(1847f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC APKDABHODIO(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		bool flag = PAIKDEPMONH() is Grenade && ((Grenade)KPJKKODEODO()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Flash;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1287f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Medium : DFHALNOAGGC.PEBLJIFMBGC.Barel);
		return pKDCCCNJIEC;
	}

	private DFHALNOAGGC.PKDCCCNJIEC NFKPLIDKDKG(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		bool flag = !(MABMFNCDEMG() is Grenade) || ((Grenade)DOLNDGCPEKH()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)8;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1657f;
		pKDCCCNJIEC.FJLBLLLEELD = (flag ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)5));
		return pKDCCCNJIEC;
	}

	public virtual void CBKAFECJMDJ(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeRPCImplementation(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DMNGKJOKAIG(MPHCNMDIPAI);
		DFHALNOAGGC.BPOCFDOIHPG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(644f, ENGGOAPADCP: true);
	}

	public virtual void AJEAAGFOCAN(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DDHCKDLCKLP(MPHCNMDIPAI);
		DFHALNOAGGC.GPOCAHICFDH(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1505f, ENGGOAPADCP: true);
	}

	public virtual void CKOMABNMJPE(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = CCDHMLCIBOG(MPHCNMDIPAI);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1220f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC LAFBBAAFHIJ(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		bool flag = MNOCEAENIKP() is Grenade && ((Grenade)PAIKDEPMONH()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)5;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = HPCHGPPCBNE();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 648f;
		pKDCCCNJIEC.FJLBLLLEELD = (flag ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)7));
		return pKDCCCNJIEC;
	}

	public virtual void CCHINPKCNFN(Vector3 MPHCNMDIPAI)
	{
		base.ECBPMJGHHAJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = APKDABHODIO(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1079f);
	}

	public virtual void HCMGOHNEJPA(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = ANPFNJFKDIM(MPHCNMDIPAI);
		DFHALNOAGGC.JLJNJFJCJMH(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1978f, ENGGOAPADCP: true);
	}

	public override void NLCMFKBPCGJ(Vector3 MPHCNMDIPAI)
	{
		base.ECBPMJGHHAJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DDHCKDLCKLP(MPHCNMDIPAI);
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1582f, ENGGOAPADCP: true);
	}

	public virtual void IDHKEMALIEN(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MEGLHDOJEAC(MPHCNMDIPAI);
		DFHALNOAGGC.LHKLMDDPLHE(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1990f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC ANPFNJFKDIM(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		bool flag = !(base.JMMJHCOKCGG is Grenade) || ((Grenade)HPCHGPPCBNE()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Frag;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 912f;
		pKDCCCNJIEC.FJLBLLLEELD = (flag ? DFHALNOAGGC.PEBLJIFMBGC.Big : DFHALNOAGGC.PEBLJIFMBGC.Molotov);
		return pKDCCCNJIEC;
	}

	public virtual void PGCDKFPIODI(Vector3 MPHCNMDIPAI)
	{
		base.MBOCMMBCPEF(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = KOCDNKAGGEA(MPHCNMDIPAI);
		DFHALNOAGGC.LCDHLOOGLAD(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1896f, ENGGOAPADCP: true);
	}

	public virtual void BGJHLMOBFPP(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MAJHBDMIHCE(MPHCNMDIPAI);
		DFHALNOAGGC.LCDHLOOGLAD(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(756f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC ABEOHOHNCGB(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		bool flag = base.JMMJHCOKCGG is Grenade && ((Grenade)MNOCEAENIKP()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)7;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1207f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Molotov : ((DFHALNOAGGC.PEBLJIFMBGC)8));
		return pKDCCCNJIEC;
	}

	public virtual void CILAGLOOJBF(Vector3 MPHCNMDIPAI)
	{
		base.IDIKOOOGBJG(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = AGDBOBLDOOP(MPHCNMDIPAI);
		DFHALNOAGGC.CKHDGLLABNA(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(370f, ENGGOAPADCP: true);
	}

	public virtual void GHHILKKNHIM(Vector3 MPHCNMDIPAI)
	{
		base.MBDCLNNFCKC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = GHHFMOCMLKB(MPHCNMDIPAI);
		DFHALNOAGGC.MKOEENAEACP(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(72f, ENGGOAPADCP: true);
	}

	public virtual void GKKDLPAIIIC(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = GHHFMOCMLKB(MPHCNMDIPAI);
		DFHALNOAGGC.LCDHLOOGLAD(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(299f);
	}

	public override void ExplodeImplementation(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeImplementation(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MAJHBDMIHCE(MPHCNMDIPAI);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(0.15f);
	}

	public override void JLBLOHJNAAG(Vector3 MPHCNMDIPAI)
	{
		base.DOPNJAIJKLJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = GHHFMOCMLKB(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(547f);
	}

	public virtual void ACFKLINFPHB(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = APKDABHODIO(MPHCNMDIPAI);
		DFHALNOAGGC.LGIKNJJDGGF(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1083f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC LHNNCMMDANO(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		bool flag = !(HPCHGPPCBNE() is Grenade) || ((Grenade)KPJKKODEODO()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)7;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 623f;
		pKDCCCNJIEC.FJLBLLLEELD = (flag ? DFHALNOAGGC.PEBLJIFMBGC.Big : DFHALNOAGGC.PEBLJIFMBGC.Molotov);
		return pKDCCCNJIEC;
	}

	public virtual void DOIPPKKGEMI(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = ENPAAOAKLGC(MPHCNMDIPAI);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1475f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC LKHJMFIJIDJ(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		bool flag = DOLNDGCPEKH() is Grenade && ((Grenade)HPCHGPPCBNE()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Poison;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = PAIKDEPMONH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 12f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)7) : DFHALNOAGGC.PEBLJIFMBGC.Medium);
		return pKDCCCNJIEC;
	}

	private DFHALNOAGGC.PKDCCCNJIEC PPJHLAHOKAC(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		bool flag = MABMFNCDEMG() is Grenade && ((Grenade)HPCHGPPCBNE()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Frag;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = HINMGJGCOJC();
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 304f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)8) : ((DFHALNOAGGC.PEBLJIFMBGC)5));
		return pKDCCCNJIEC;
	}

	private DFHALNOAGGC.PKDCCCNJIEC KOCDNKAGGEA(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		bool flag = !(MNOCEAENIKP() is Grenade) || ((Grenade)MNOCEAENIKP()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)6;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1564f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)5) : ((DFHALNOAGGC.PEBLJIFMBGC)7));
		return pKDCCCNJIEC;
	}

	public virtual void EMCLKCLFFIH(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = COALKKLBJCF(MPHCNMDIPAI);
		DFHALNOAGGC.DMGILJJODLE(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(820f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC GHHFMOCMLKB(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = PEDNMLDCPNL() as GrenadeAmmoSetup;
		bool flag = !(KPJKKODEODO() is Grenade) || ((Grenade)MABMFNCDEMG()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Flash;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 111f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Molotov : ((DFHALNOAGGC.PEBLJIFMBGC)6));
		return pKDCCCNJIEC;
	}

	public virtual void MPEBHEODHFF(Vector3 MPHCNMDIPAI)
	{
		base.IDIKOOOGBJG(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = PPJHLAHOKAC(MPHCNMDIPAI);
		DFHALNOAGGC.IPEDNMPJOOO(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1595f);
	}

	public override void ExplodeRPCImplementation(Vector3 MPHCNMDIPAI)
	{
		base.ExplodeRPCImplementation(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MAJHBDMIHCE(MPHCNMDIPAI);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(0.1f);
	}

	public virtual void NHILEKBDBKH(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = BFIKLDHFBDN(MPHCNMDIPAI);
		DFHALNOAGGC.GKBHNGLILLM(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1338f);
	}

	public virtual void ONAOKOGIEMC(Vector3 MPHCNMDIPAI)
	{
		base.MBOCMMBCPEF(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = ABEOHOHNCGB(MPHCNMDIPAI);
		DFHALNOAGGC.DCKBBBOHNFK(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1110f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC ENPAAOAKLGC(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = EBJGPMCLNAI() as GrenadeAmmoSetup;
		bool flag = !(HPCHGPPCBNE() is Grenade) || ((Grenade)PAIKDEPMONH()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Molotov;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = KECCEOEBJNM();
		pKDCCCNJIEC.JMMJHCOKCGG = DOLNDGCPEKH();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OMKDGIPFMDF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 574f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)8) : DFHALNOAGGC.PEBLJIFMBGC.Small);
		return pKDCCCNJIEC;
	}

	public virtual void OINGAJOOILA(Vector3 MPHCNMDIPAI)
	{
		base.JLBLOHJNAAG(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = ENPAAOAKLGC(MPHCNMDIPAI);
		DFHALNOAGGC.INCNNACKAOO(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(994f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC KIFPAINPKKG(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JAIJGJNKNFB() as GrenadeAmmoSetup;
		bool flag = !(KPJKKODEODO() is Grenade) || ((Grenade)base.JMMJHCOKCGG).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)8;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = OGONCEGFDPB();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1563f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Molotov : ((DFHALNOAGGC.PEBLJIFMBGC)6));
		return pKDCCCNJIEC;
	}

	public virtual void AOFJCJNOEEN(Vector3 MPHCNMDIPAI)
	{
		base.HMCHBIFGONC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = APKDABHODIO(MPHCNMDIPAI);
		DFHALNOAGGC.HELCGODGBJG(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(334f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC MAJHBDMIHCE(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = base.EIIMIEGIOPN as GrenadeAmmoSetup;
		bool flag = base.JMMJHCOKCGG is Grenade && ((Grenade)base.JMMJHCOKCGG).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Molotov;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 0.7f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Medium : DFHALNOAGGC.PEBLJIFMBGC.Molotov);
		return pKDCCCNJIEC;
	}

	public virtual void FPNFIBLGCFA(Vector3 MPHCNMDIPAI)
	{
		base.JMNFDCOFBFB(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LHNNCMMDANO(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1478f);
	}

	public override void IDIKOOOGBJG(Vector3 MPHCNMDIPAI)
	{
		base.NPOCOJIDBPN(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = BFIKLDHFBDN(MPHCNMDIPAI);
		DFHALNOAGGC.MKOEENAEACP(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(883f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC CCDHMLCIBOG(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		bool flag = PAIKDEPMONH() is Grenade && ((Grenade)PAIKDEPMONH()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)8;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = base.CAKABHIPCDF;
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 636f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? ((DFHALNOAGGC.PEBLJIFMBGC)7) : ((DFHALNOAGGC.PEBLJIFMBGC)5));
		return pKDCCCNJIEC;
	}

	public virtual void KEBGIAAFFLI(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = JDKDCFKLEJJ(MPHCNMDIPAI);
		DFHALNOAGGC.NNKPEIEABPA(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1373f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC KNGBHBACKIN(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		bool flag = !(base.JMMJHCOKCGG is Grenade) || ((Grenade)MABMFNCDEMG()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Smoke;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = base.MHAMIMGNJND;
		pKDCCCNJIEC.JMMJHCOKCGG = KPJKKODEODO();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1513f;
		pKDCCCNJIEC.FJLBLLLEELD = (flag ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)5));
		return pKDCCCNJIEC;
	}

	public virtual void GAMPHKBAFJH(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = KNGBHBACKIN(MPHCNMDIPAI);
		DFHALNOAGGC.OIIMCCDGFIL(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1879f);
	}

	public virtual void FKCNPCOFNEG(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LAFBBAAFHIJ(MPHCNMDIPAI);
		DFHALNOAGGC.IMCGCAHFJLP(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(691f);
	}

	public virtual void BBOHBMPDEFJ(Vector3 MPHCNMDIPAI)
	{
		base.MBDCLNNFCKC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = KOCDNKAGGEA(MPHCNMDIPAI);
		DFHALNOAGGC.HELCGODGBJG(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1566f, ENGGOAPADCP: true);
	}

	public virtual void DEHMFNOEPIH(Vector3 MPHCNMDIPAI)
	{
		base.INABHIGCAGL(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = PDFLODALBOJ(MPHCNMDIPAI);
		DFHALNOAGGC.KNEPFMFFOOG(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1548f, ENGGOAPADCP: true);
	}

	public virtual void MONNDAOHCIJ(Vector3 MPHCNMDIPAI)
	{
		base.ECBPMJGHHAJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LHNNCMMDANO(MPHCNMDIPAI);
		DFHALNOAGGC.CKNBNIPDOLH(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1323f);
	}

	public virtual void GDLFBDGDMOM(Vector3 MPHCNMDIPAI)
	{
		base.IDIKOOOGBJG(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = GHHFMOCMLKB(MPHCNMDIPAI);
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
		GBJKONGOBBO.MIDOLDHLMAF(1179f, ENGGOAPADCP: true);
	}

	public virtual void BOHGFBPCNBM(Vector3 MPHCNMDIPAI)
	{
		base.DOPNJAIJKLJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = CCDHMLCIBOG(MPHCNMDIPAI);
		DFHALNOAGGC.GPOCAHICFDH(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1515f, ENGGOAPADCP: true);
	}

	public virtual void PCECEEJGCNB(Vector3 MPHCNMDIPAI)
	{
		base.ELEMJPNEMFC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = MAJHBDMIHCE(MPHCNMDIPAI);
		DFHALNOAGGC.LNHKKEAJBED(nOCEDALFEJM);
		GBJKONGOBBO.AEHFNIMENDJ(1522f);
	}

	public virtual void IFIOMKFEKJM(Vector3 MPHCNMDIPAI)
	{
		base.PMIBMDFFKHE(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = KOCDNKAGGEA(MPHCNMDIPAI);
		DFHALNOAGGC.GNPJIPAKCJL(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(470f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC DBHDKDBBPNL(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		bool flag = !(MABMFNCDEMG() is Grenade) || ((Grenade)MNOCEAENIKP()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Frag;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MABMFNCDEMG();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = PFPKMFLANKO();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1442f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)7));
		return pKDCCCNJIEC;
	}

	public virtual void KDKBMIJECPJ(Vector3 MPHCNMDIPAI)
	{
		base.MBDCLNNFCKC(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = NFKPLIDKDKG(MPHCNMDIPAI);
		DFHALNOAGGC.JPJBPDICFGO(nOCEDALFEJM);
		GBJKONGOBBO.NFJEOLKAONC(798f);
	}

	public virtual void FBHDGMIAEGA(Vector3 MPHCNMDIPAI)
	{
		base.LPIOCLILCFK(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = DDHCKDLCKLP(MPHCNMDIPAI);
		DFHALNOAGGC.CJAKPBGJKAF(nOCEDALFEJM);
		GBJKONGOBBO.DestroyPooled(1189f, ENGGOAPADCP: true);
	}

	private DFHALNOAGGC.PKDCCCNJIEC PDFLODALBOJ(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = ENPNKGNPEHL() as GrenadeAmmoSetup;
		bool flag = MNOCEAENIKP() is Grenade && ((Grenade)MABMFNCDEMG()).CPBDKPFPAND == (GrenadeAmmoBase.LNOCLBOKLBN)6;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = FKMMDFBHHIA();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = GGJHMGFEONI();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 993f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Molotov : DFHALNOAGGC.PEBLJIFMBGC.Small);
		return pKDCCCNJIEC;
	}

	private DFHALNOAGGC.PKDCCCNJIEC BFIKLDHFBDN(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JEFLHHOPLFH() as GrenadeAmmoSetup;
		bool flag = PAIKDEPMONH() is Grenade && ((Grenade)DOLNDGCPEKH()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Flash;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = base.JMMJHCOKCGG;
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = CEINMDAAIHL();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 467f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Big : ((DFHALNOAGGC.PEBLJIFMBGC)8));
		return pKDCCCNJIEC;
	}

	public override void BLJPLCFILOF(Vector3 MPHCNMDIPAI)
	{
		base.DOPNJAIJKLJ(MPHCNMDIPAI);
		DFHALNOAGGC.PKDCCCNJIEC nOCEDALFEJM = LKHJMFIJIDJ(MPHCNMDIPAI);
		DFHALNOAGGC.IPEDNMPJOOO(nOCEDALFEJM);
		GBJKONGOBBO.DCFHLIDIDMN(1520f);
	}

	private DFHALNOAGGC.PKDCCCNJIEC AGDBOBLDOOP(Vector3 MPHCNMDIPAI)
	{
		GrenadeAmmoSetup grenadeAmmoSetup = JGAEFCIINCA() as GrenadeAmmoSetup;
		bool flag = base.JMMJHCOKCGG is Grenade && ((Grenade)DOLNDGCPEKH()).CPBDKPFPAND == GrenadeAmmoBase.LNOCLBOKLBN.Frag;
		DFHALNOAGGC.PKDCCCNJIEC pKDCCCNJIEC = new DFHALNOAGGC.PKDCCCNJIEC();
		pKDCCCNJIEC.MPHCNMDIPAI = MPHCNMDIPAI;
		pKDCCCNJIEC.JHGHGAFBDFG = grenadeAmmoSetup.ABFGHBDEBAN;
		pKDCCCNJIEC.EPDELOGPNAC = grenadeAmmoSetup.EPDELOGPNAC;
		pKDCCCNJIEC.HNFNINFCBEJ = IFDEKAFNIIF();
		pKDCCCNJIEC.JMMJHCOKCGG = MNOCEAENIKP();
		pKDCCCNJIEC.INIBDNGHLPN = grenadeAmmoSetup.INIBDNGHLPN;
		pKDCCCNJIEC.LIEABAMBOMG = grenadeAmmoSetup.LIEABAMBOMG;
		pKDCCCNJIEC.ELMEIGEABIK = grenadeAmmoSetup.ELMEIGEABIK;
		pKDCCCNJIEC.CPBCADFLPMO = grenadeAmmoSetup.CPBCADFLPMO;
		pKDCCCNJIEC.CAKABHIPCDF = ADMOFJHMFCF();
		pKDCCCNJIEC.MAOPCAMOEEK = grenadeAmmoSetup.MAOPCAMOEEK;
		pKDCCCNJIEC.AJMLFHFPMPO = 1657f;
		pKDCCCNJIEC.FJLBLLLEELD = ((!flag) ? DFHALNOAGGC.PEBLJIFMBGC.Big : DFHALNOAGGC.PEBLJIFMBGC.Medium);
		return pKDCCCNJIEC;
	}
}
