using System.Collections;
using System.Collections.Specialized;
using UnityEngine;
using UnityEngine.Serialization;

[RequireComponent(typeof(PoolableObject))]
public class HudObjectIndicator : Core_BaseScript
{
	public enum NPPEJJKFCON
	{
		CardIco,
		InfoIco,
		EngineerIco,
		None
	}

	private sealed class FHOJNIDPDPP
	{
		internal HudObjectIndicator2D JPDFMABBKDI;

		internal string JLEJGKJBDNC;
	}

	private sealed class OJJPMIGPFCE
	{
		internal Vector3 MPHCNMDIPAI;
	}

	private sealed class BKPMPBDJBDJ
	{
		internal Vector3 GPGMBCEEGEL;

		internal FHOJNIDPDPP MMALFGIGIPL;

		internal OJJPMIGPFCE ALIKEGIJIHD;

		internal void FIBGJHCGHJH(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1905f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1151f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_INELITE2");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 76;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void OABFAOLFMMJ(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 763f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1032f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Id");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -112;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void MCFGAFBEJDK(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1155f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 231f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Got ");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 31;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void FDKMOFHAEFN(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 957f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1803f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_NA");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 84;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void CHDOECNGOPM(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1148f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 852f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("menu-button-promote-ico");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -98;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void GGJDILDIFPJ(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 946f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 913f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Wrong_Unit");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 96;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void BBPKDMPNEDG(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1342f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1008f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite(" does not have defined look!!!!!!");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -94;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void EMKPBGFBPFI(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 262f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1128f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Player was removed from db!");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 103;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void KJIFNOJILDB(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1527f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1876f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Assignment: DestroyEnemyCratesAssignment Constructor");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -19;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void OHLGKFGIPCC(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1692f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 600f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Deploys_Count");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 22;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void KPHEPHDFCKK(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 676f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1882f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("{0} {1}");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -30;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void GMFJFMHNDMC(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1482f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1684f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Found labels with original font in children:\n");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 98;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void HHLMDAKDHFK(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1527f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 220f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Error Deserializing JSON for ");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -110;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void DGELDDJAEEF(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 61f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1023f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_GOLDC");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -52;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void OKNCFDMEFGJ(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1279f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 653f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_ENDED");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 96;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void CMDLGJKIBLL(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1168f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 286f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_WARNING_CANTSENDINVITE_TEXT");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -44;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void POGLHCIAAGH(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1803f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 499f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("writeToParcel");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 26;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void POGDLLFCOKO(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1384f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1243f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Squad");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 67;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void KNJBDOADLDO(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 252f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1647f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_GUI_CHEATINGMESSAGE");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 0;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void BDCAFHOHEGM(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 780f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 477f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("reloadTime");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 35;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void MFCNOIDCJME(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 381f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 270f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ShootAdditive");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -90;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void NCLMPCCHDAM(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 855f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 693f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("BANDS_EMPTY");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -82;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void NNIJEDKBPGJ(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1142f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1019f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("1");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -39;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void HOMIPBFODIC(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 880f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 1810f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Action ");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 23;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void LHPPLGOOLEC(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1423f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 522f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("large_icon");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -115;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void NNFHNIMCBLH(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1805f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 738f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("C3");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -36;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void BMCMDMKGHHO(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 898f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1013f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite(">");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -56;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void PANKBNOCEAM(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 281f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1920f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Font problems with labels");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -15;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void INFLOOLPOBK(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 801f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 619f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("LevelName");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 87;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void MAKLHLCDIKD(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 75f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 415f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Resource: {0} loaded {1} times\n");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -52;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}

		internal void EOHOLKEGGLH(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1236f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 727f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Visual {0}, overcount {1}, duplicate wb {2}\n");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -13;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void LJCDGJKCNEC(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 0.2f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 0f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("game-card-ico-stroke");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 20;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void ILNPANOCHIH(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1193f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1395f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("S");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -66;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void ABNGKEJNLJO(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 230f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI).delay = 427f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("Show: ");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 97;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void LGJCNCHBFDA(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 1274f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1069f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ReportedPlayerId");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -30;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: true);
		}

		internal void CFJHDIHLIML(UITweener ALOMHALCMNH)
		{
			TweenPosition.Begin(MMALFGIGIPL.JPDFMABBKDI.gameObject, 120f, GPGMBCEEGEL, ALIKEGIJIHD.MPHCNMDIPAI, useLocal: false).delay = 1049f;
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.SetSprite(MMALFGIGIPL.JLEJGKJBDNC);
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SetSprite("ID_AWESOME");
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.SortingOrder = 98;
			MMALFGIGIPL.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
			MMALFGIGIPL.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		}
	}

	private sealed class OCNCLOOPFNE
	{
		internal HudObjectIndicator2D JPDFMABBKDI;
	}

	private sealed class MPCMGIMIFBK
	{
		internal TweenAlphaTk2d JNIJCLMBAMP;

		internal OCNCLOOPFNE BLDPJKHMBKA;

		internal void JEGPCHMCABF(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1253f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1668f, 765f);
			JNIJCLMBAMP.onFinished = KNPFPEKILPK;
		}

		internal void LJMPKFLPDNK(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1274f, 266f);
			JNIJCLMBAMP.onFinished = LINFPCHJDJM;
		}

		internal void BNEEECLGJME(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1617f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 313f, 1827f);
			JNIJCLMBAMP.onFinished = JEKOCFKHBKH;
		}

		internal void GLPMMHODCOG(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 545f, 1623f);
		}

		internal void MNHAOLHNNIF(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1245f, 668f);
			JNIJCLMBAMP.onFinished = ODNCMGOFKOO;
		}

		internal void KGMKJFBPLCC(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1941f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 976f, 1591f);
			JNIJCLMBAMP.onFinished = BMONIBOJLJF;
		}

		internal void ECPMEMNKMCB(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 266f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 981f, 1748f);
			JNIJCLMBAMP.onFinished = AKCPOJMIBOG;
		}

		internal void MHADHBLEAHJ(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1690f, 934f);
			JNIJCLMBAMP.onFinished = GFCCOPBJDBM;
		}

		internal void CDFAIFAHJLN(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1433f, 1502f);
			JNIJCLMBAMP.onFinished = MNHAOLHNNIF;
		}

		internal void EHDOLLODEAH(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 737f, 621f);
		}

		internal void EFFNMHECDDI(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 38f, 1245f);
			JNIJCLMBAMP.onFinished = FINDAJGNBDJ;
		}

		internal void DGELDDJAEEF(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 371f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1820f, 1687f);
			JNIJCLMBAMP.onFinished = BMONIBOJLJF;
		}

		internal void POFEBBEMKLN(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 101f, 1172f);
			JNIJCLMBAMP.onFinished = DJDFHAGLOBD;
		}

		internal void OABFAOLFMMJ(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 792f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 317f, 411f);
			JNIJCLMBAMP.onFinished = KNPFPEKILPK;
		}

		internal void CHDOECNGOPM(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 162f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 626f, 620f);
			JNIJCLMBAMP.onFinished = ENOBKGECBGB;
		}

		internal void LKPBPIFKFKN(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1768f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1613f, 360f);
			JNIJCLMBAMP.onFinished = ENOBKGECBGB;
		}

		internal void FINDAJGNBDJ(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 705f, 1159f);
			JNIJCLMBAMP.onFinished = JINCDMIIJJK;
		}

		internal void DEJJPKJEOFD(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1816f, 1606f);
			JNIJCLMBAMP.onFinished = EHDOLLODEAH;
		}

		internal void PKCGGMPIPDL(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1866f, 1350f);
			JNIJCLMBAMP.onFinished = HONCMBHEKDP;
		}

		internal void JHDEKOKOLPG(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 409f, 1039f);
			JNIJCLMBAMP.onFinished = KPNGMLMINJL;
		}

		internal void JEKOCFKHBKH(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1898f, 1399f);
			JNIJCLMBAMP.onFinished = BDEGOKBJGFK;
		}

		internal void EIGOHMKAMGI(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 345f, 1675f);
			JNIJCLMBAMP.onFinished = LJMPKFLPDNK;
		}

		internal void LJCDGJKCNEC(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.08f, 1f);
			JNIJCLMBAMP.onFinished = EJLGBICBIFK;
		}

		internal void FFFMHMKJBFG(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1581f, 761f);
			JNIJCLMBAMP.onFinished = LJMPKFLPDNK;
		}

		internal void KCOOCOMPHEF(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 652f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1376f, 929f);
			JNIJCLMBAMP.onFinished = DFOJLAFDBHO;
		}

		internal void ODNCMGOFKOO(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1193f, 1224f);
		}

		internal void ENOBKGECBGB(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 195f, 1240f);
			JNIJCLMBAMP.onFinished = FFGOEHLBPHP;
		}

		internal void OKFINGDLMJP(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 717f, 1706f);
			JNIJCLMBAMP.onFinished = LJMPKFLPDNK;
		}

		internal void KPNGMLMINJL(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 672f, 1948f);
			JNIJCLMBAMP.onFinished = BHEEPMPEMOJ;
		}

		internal void LBPGIEANDDL(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1534f, 1434f);
		}

		internal void FFGOEHLBPHP(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1970f, 1426f);
			JNIJCLMBAMP.onFinished = EODJHIOCFAG;
		}

		internal void PEFOCGECECP(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1095f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1175f, 695f);
			JNIJCLMBAMP.onFinished = ENOBKGECBGB;
		}

		internal void LCEMKGDLGCB(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1047f, 529f);
			JNIJCLMBAMP.onFinished = EPEIPBKIFOF;
		}

		internal void HONCMBHEKDP(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.08f, 1f);
			JNIJCLMBAMP.onFinished = BIGNHFCNJLL;
		}

		internal void HKNCGEMENDB(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1670f, 1996f);
		}

		internal void OHHBONPGLGJ(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 584f, 345f);
			JNIJCLMBAMP.onFinished = BIGNHFCNJLL;
		}

		internal void JGKCIFDJIPB(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 890f, 365f);
			JNIJCLMBAMP.onFinished = EMHFHNLEFGN;
		}

		internal void AMIJFGBOCLC(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 234f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1939f, 1904f);
			JNIJCLMBAMP.onFinished = DNILGLLHHPG;
		}

		internal void OFCOFDILHHH(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1302f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1072f, 1250f);
			JNIJCLMBAMP.onFinished = PKCGGMPIPDL;
		}

		internal void JKDLDKOKLNH(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 172f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 183f, 1943f);
			JNIJCLMBAMP.onFinished = DFOJLAFDBHO;
		}

		internal void OKBIKLGPNKI(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 528f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1175f, 1356f);
			JNIJCLMBAMP.onFinished = KNPFPEKILPK;
		}

		internal void MAKLHLCDIKD(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 84f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 171f, 1743f);
			JNIJCLMBAMP.onFinished = OKFINGDLMJP;
		}

		internal void EIHHMNDHDHL(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 166f, 293f);
			JNIJCLMBAMP.onFinished = MNHAOLHNNIF;
		}

		internal void DNILGLLHHPG(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 266f, 1949f);
			JNIJCLMBAMP.onFinished = IKOBFNFAFFL;
		}

		internal void CFDNMILGDLG(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1063f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1243f, 1685f);
			JNIJCLMBAMP.onFinished = OEKMGACNPJM;
		}

		internal void NHLKEBGODKG(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1393f, 1659f);
		}

		internal void BMONIBOJLJF(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1063f, 323f);
			JNIJCLMBAMP.onFinished = GFCCOPBJDBM;
		}

		internal void BLEMBJFNOGA(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1384f, 1779f);
			JNIJCLMBAMP.onFinished = BHEEPMPEMOJ;
		}

		internal void IKOBFNFAFFL(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1350f, 467f);
			JNIJCLMBAMP.onFinished = ALBGCHOONIM;
		}

		internal void CGGCDFGJBII(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 439f, 1529f);
			JNIJCLMBAMP.onFinished = GKCCIMLNGCF;
		}

		internal void AFKHHFPMJOF(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1059f, 1614f);
		}

		internal void LINFPCHJDJM(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 737f, 989f);
		}

		internal void HHNEBNHCGMO(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 704f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1621f, 1153f);
			JNIJCLMBAMP.onFinished = CGGCDFGJBII;
		}

		internal void OBBNKPLABKG(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 559f, 1387f);
		}

		internal void JNPPAGHIMDJ(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 644f, 429f);
			JNIJCLMBAMP.onFinished = BHEEPMPEMOJ;
		}

		internal void JGEMIBIJMJC(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 62f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 941f, 337f);
			JNIJCLMBAMP.onFinished = CGGCDFGJBII;
		}

		internal void BIGNHFCNJLL(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.08f, 0f);
		}

		internal void JBDJIDBNKIO(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1784f, 1736f);
			JNIJCLMBAMP.onFinished = JNPPAGHIMDJ;
		}

		internal void AKCPOJMIBOG(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 232f, 1833f);
			JNIJCLMBAMP.onFinished = JNPPAGHIMDJ;
		}

		internal void FIKKCJKBMHG(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1756f, 215f);
			JNIJCLMBAMP.onFinished = NFOCBJHGGCM;
		}

		internal void JINCDMIIJJK(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 713f, 1426f);
		}

		internal void GFCCOPBJDBM(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 587f, 10f);
			JNIJCLMBAMP.onFinished = NFOCBJHGGCM;
		}

		internal void GKCCIMLNGCF(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1578f, 1227f);
			JNIJCLMBAMP.onFinished = LBPGIEANDDL;
		}

		internal void GDJIAPHLGOA(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1852f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 971f, 661f);
			JNIJCLMBAMP.onFinished = JHPEFFLPHCF;
		}

		internal void OMEBEADFFBI(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 844f, 1595f);
		}

		internal void MCFGAFBEJDK(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 101f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1932f, 776f);
			JNIJCLMBAMP.onFinished = DFOJLAFDBHO;
		}

		internal void DJDFHAGLOBD(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 161f, 54f);
		}

		internal void FICGLJJELPM(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1887f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 894f, 474f);
			JNIJCLMBAMP.onFinished = PKCGGMPIPDL;
		}

		internal void OAAHKJBCNBO(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1973f, 507f);
		}

		internal void FNILDOLEBGG(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1095f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 46f, 439f);
			JNIJCLMBAMP.onFinished = MHADHBLEAHJ;
		}

		internal void MJLPMDLMCLH(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 953f, 363f);
			JNIJCLMBAMP.onFinished = NHLKEBGODKG;
		}

		internal void OEKMGACNPJM(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 255f, 543f);
			JNIJCLMBAMP.onFinished = POFEBBEMKLN;
		}

		internal void EPEIPBKIFOF(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 802f, 1564f);
		}

		internal void EODJHIOCFAG(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1493f, 344f);
		}

		internal void HCDHHJONPLF(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 150f, 1605f);
			JNIJCLMBAMP.onFinished = BLBAPKLOBKD;
		}

		internal void INFLOOLPOBK(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1279f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1801f, 1500f);
			JNIJCLMBAMP.onFinished = PKCGGMPIPDL;
		}

		internal void BLBAPKLOBKD(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1508f, 1942f);
		}

		internal void EJLGBICBIFK(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.08f, 0f);
			JNIJCLMBAMP.onFinished = HONCMBHEKDP;
		}

		internal void DKNJHLBJKKD(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1640f, 1100f);
			JNIJCLMBAMP.onFinished = DEJJPKJEOFD;
		}

		internal void FKIBFHGKMFJ(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1202f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1014f, 180f);
			JNIJCLMBAMP.onFinished = EIHHMNDHDHL;
		}

		internal void BHEEPMPEMOJ(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 567f, 1880f);
		}

		internal void EMHFHNLEFGN(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1594f, 556f);
			JNIJCLMBAMP.onFinished = HFMCNPDCJAM;
		}

		internal void HFPEMDEMNLP(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1264f, 1956f);
			JNIJCLMBAMP.onFinished = DJDFHAGLOBD;
		}

		internal void HEOOALAELMD(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1215f, 1872f);
			JNIJCLMBAMP.onFinished = OMEBEADFFBI;
		}

		internal void NFFJEOEKJNG(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1898f, 445f);
			JNIJCLMBAMP.onFinished = DJDFHAGLOBD;
		}

		internal void IBOOIIJAHMC(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 954f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 130f, 832f);
			JNIJCLMBAMP.onFinished = JBDJIDBNKIO;
		}

		internal void OLOJCIHEKOB(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1897f, 489f);
			JNIJCLMBAMP.onFinished = HKNCGEMENDB;
		}

		internal void BEIGOGFHJIB(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 126f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1664f, 318f);
			JNIJCLMBAMP.onFinished = CGGCDFGJBII;
		}

		internal void ALFPMCHHIMH(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 151f, 1519f);
			JNIJCLMBAMP.onFinished = LJMPKFLPDNK;
		}

		internal void HPJCBDDALHB(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1960f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 216f, 1651f);
			JNIJCLMBAMP.onFinished = DNILGLLHHPG;
		}

		internal void GFBPCKDLGMM(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 1404f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1486f, 1803f);
			JNIJCLMBAMP.onFinished = MHADHBLEAHJ;
		}

		internal void HKOHIJPFLJC(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1124f, 365f);
			JNIJCLMBAMP.onFinished = JNPPAGHIMDJ;
		}

		internal void CDFJFDAKEAL(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 635f, 388f);
			JNIJCLMBAMP.onFinished = LJMPKFLPDNK;
		}

		internal void NMOEHJHCEGD(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1991f, 1065f);
			JNIJCLMBAMP.onFinished = EMHFHNLEFGN;
		}

		internal void JHPEFFLPHCF(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1923f, 1198f);
			JNIJCLMBAMP.onFinished = MNPKIAGIBLF;
		}

		internal void KNPFPEKILPK(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 787f, 471f);
			JNIJCLMBAMP.onFinished = HFPEMDEMNLP;
		}

		internal void BDEGOKBJGFK(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1424f, 1632f);
			JNIJCLMBAMP.onFinished = AFKHHFPMJOF;
		}

		internal void DJLGPGPAHCD(UITweener ALOMHALCMNH)
		{
			BLDPJKHMBKA.JPDFMABBKDI.progress = 873f;
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 846f, 759f);
			JNIJCLMBAMP.onFinished = JEKOCFKHBKH;
		}

		internal void HFMCNPDCJAM(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 239f, 1938f);
		}

		internal void DFOJLAFDBHO(UITweener BLILJAEBIDF)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 767f, 1031f);
			JNIJCLMBAMP.onFinished = GKCCIMLNGCF;
		}

		internal void ALBGCHOONIM(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 961f, 1150f);
		}

		internal void NFOCBJHGGCM(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 469f, 1681f);
		}

		internal void LKFEAEFEIBG(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 71f, 876f);
			JNIJCLMBAMP.onFinished = OMEBEADFFBI;
		}

		internal void CBEOACBBEKN(UITweener OHADJLPCKBA)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 266f, 386f);
		}

		internal void MNPKIAGIBLF(UITweener CJIEGIOBBDH)
		{
			JNIJCLMBAMP = TweenAlphaTk2d.Begin(BLDPJKHMBKA.JPDFMABBKDI.GMPADNOGGNL.gameObject, 1602f, 1376f);
			JNIJCLMBAMP.onFinished = HFMCNPDCJAM;
		}
	}

	private Transform NGCDDPCAGJB;

	private Transform OFGNACJLCPK;

	private Transform LJGGEMAGMHI;

	[FormerlySerializedAs("DDGFDCBJJOA")]
	public Transform JHNFPPDCBDK;

	[FormerlySerializedAs("FDADEAHAIKP")]
	public bool NABOFKMBMKH = true;

	[FormerlySerializedAs("HEEIBFCEOLC")]
	public string KCHMDALPMBN;

	private OrderedDictionary FDFLHDPCHCN = new OrderedDictionary();

	private Transform IHOHMIAONEF;

	private float JIIKOENDJAF;

	[FormerlySerializedAs("CCOJKJDDIKB")]
	public Vector3 IFANIMJLAGF;

	[FormerlySerializedAs("KNPMDMBFIGP")]
	public bool CACFIJJILFP;

	[FormerlySerializedAs("JMAHLKBOOKH")]
	public bool BNKCCJEMIAM;

	private Vector3 HFMLDDCPOLH;

	public void IJHCIJLDKHK()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.DestroyPooled(DCDEEADIGEH: true);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 1032f;
	}

	public void IJPAEHAGPFK(bool IDEBKDPMPGM)
	{
		GGHDIAFACAH(KCHMDALPMBN, IDEBKDPMPGM, NPPEJJKFCON.InfoIco);
		NABOFKMBMKH = IDEBKDPMPGM;
	}

	public void GNOLGJMNLAK()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	protected override void Awake()
	{
		base.Awake();
		NGCDDPCAGJB = base.transform;
		LJGGEMAGMHI = HealthBarManager.instance.KPDAPFBIPAI.transform;
		OFGNACJLCPK = Singleton<GameCamera>.instance.transform;
		GameObject gameObject = new GameObject("iconParent");
		gameObject.transform.parent = Singleton<GameCamera>.instance.FKFDNNPBOFI.transform;
		IHOHMIAONEF = gameObject.transform;
		if (NABOFKMBMKH)
		{
			KLALIIMABIA(KCHMDALPMBN, Color.white);
		}
	}

	public int BMGFLMDEOGE(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	public void KKLJIFDFIJF()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public void FHEMMACIODD()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public void NGAGGCFIEGJ()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.DestroyPooled(DCDEEADIGEH: false);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 1959f;
	}

	protected void NKGLGNEJIOA()
	{
		if (IHOHMIAONEF.gameObject.activeInHierarchy)
		{
			if (BNKCCJEMIAM)
			{
				float num = Vector3.Distance(NGCDDPCAGJB.position, OFGNACJLCPK.position);
				Vector3 vector = new Vector3(1791f / num, 544f / num, 1035f / num);
				vector = Vector3.ClampMagnitude(vector, 249f);
				IHOHMIAONEF.localScale = vector;
				HFMLDDCPOLH = Vector3.Scale(IFANIMJLAGF, vector);
			}
			if (CACFIJJILFP)
			{
				Vector3 vector2 = LJGGEMAGMHI.position + new Vector3(1833f, 597f, HealthBarManager.BCDJJBAFLLG().KPDAPFBIPAI.nearClipPlane + 567f);
				Vector3 point = Singleton<GameCamera>.instance.CAGAKKADGDG().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				point = HealthBarManager.ALODNGEMIMO().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point);
				point.z = vector2.z;
				IHOHMIAONEF.position = point + HFMLDDCPOLH;
			}
			else
			{
				Vector3 point2 = Singleton<GameCamera>.instance.LBBFBJMLEJB().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				IHOHMIAONEF.position = HealthBarManager.IPAFHDNJIJP().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point2) + HFMLDDCPOLH;
			}
		}
		HFMLDDCPOLH = IFANIMJLAGF;
	}

	private int OEBENBJKEEI(string JLEJGKJBDNC, NPPEJJKFCON AGMEHGCOPBM = NPPEJJKFCON.InfoIco, float JLHNLGCHKME = 0.5f)
	{
		OCNCLOOPFNE oCNCLOOPFNE = new OCNCLOOPFNE();
		float delay = ((AGMEHGCOPBM != NPPEJJKFCON.CardIco) ? 1939f : 1839f);
		int result = -1;
		if (FDFLHDPCHCN.Contains(JLEJGKJBDNC))
		{
			oCNCLOOPFNE.JPDFMABBKDI = (HudObjectIndicator2D)FDFLHDPCHCN[JLEJGKJBDNC];
			FDFLHDPCHCN.Remove(JLEJGKJBDNC);
			result = oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.spriteId;
			Bounds bounds = oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.GetBounds();
			JIIKOENDJAF -= bounds.size.x;
			Vector3 vector = new Vector3(997f - JIIKOENDJAF * 291f, 723f, 1458f);
			IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
			while (enumerator.MoveNext())
			{
				HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
				Bounds bounds2 = hudObjectIndicator2D.GMPADNOGGNL.GetBounds();
				Vector3 pos = vector + new Vector3(bounds2.size.x * 1388f, 525f, 582f);
				TweenPosition.Begin(hudObjectIndicator2D.gameObject, 1232f, pos, useLocal: false).delay = delay;
				vector += new Vector3(bounds2.size.x, 1074f, 1284f);
			}
			switch (AGMEHGCOPBM)
			{
			case NPPEJJKFCON.CardIco:
			{
				MPCMGIMIFBK mPCMGIMIFBK = new MPCMGIMIFBK();
				mPCMGIMIFBK.BLDPJKHMBKA = oCNCLOOPFNE;
				mPCMGIMIFBK.JNIJCLMBAMP = TweenAlphaTk2d.Begin(oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.gameObject, 21f, 112f);
				mPCMGIMIFBK.JNIJCLMBAMP.delay = 440f;
				mPCMGIMIFBK.JNIJCLMBAMP.onFinished = mPCMGIMIFBK.HPJCBDDALHB;
				break;
			}
			case (NPPEJJKFCON)6:
				TweenPosition.Begin(oCNCLOOPFNE.JPDFMABBKDI.gameObject, 276f, oCNCLOOPFNE.JPDFMABBKDI.gameObject.transform.localPosition - new Vector3(356f, bounds.size.y * 298f, 914f), useLocal: false).delay = 386f;
				break;
			default:
				TweenPosition.Begin(oCNCLOOPFNE.JPDFMABBKDI.gameObject, 1028f, oCNCLOOPFNE.JPDFMABBKDI.gameObject.transform.localPosition - new Vector3(84f, bounds.size.y * 1901f, 132f)).delay = 1453f;
				TweenAlphaTk2d.Begin(oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.gameObject, 317f, 749f).delay = 233f;
				break;
			}
			oCNCLOOPFNE.JPDFMABBKDI.NFJEOLKAONC(JLHNLGCHKME);
		}
		return result;
	}

	protected void Update()
	{
		if (IHOHMIAONEF.gameObject.activeInHierarchy)
		{
			if (BNKCCJEMIAM)
			{
				float num = Vector3.Distance(NGCDDPCAGJB.position, OFGNACJLCPK.position);
				Vector3 vector = new Vector3(5.5f / num, 5.5f / num, 5.5f / num);
				vector = Vector3.ClampMagnitude(vector, 2.3f);
				IHOHMIAONEF.localScale = vector;
				HFMLDDCPOLH = Vector3.Scale(IFANIMJLAGF, vector);
			}
			if (CACFIJJILFP)
			{
				Vector3 vector2 = LJGGEMAGMHI.position + new Vector3(0f, 0f, HealthBarManager.instance.KPDAPFBIPAI.nearClipPlane + 3f);
				Vector3 point = Singleton<GameCamera>.instance.camera.WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				point = HealthBarManager.instance.KPDAPFBIPAI.NormalizedViewportToWorldPoint(point);
				point.z = vector2.z;
				IHOHMIAONEF.position = point + HFMLDDCPOLH;
			}
			else
			{
				Vector3 point2 = Singleton<GameCamera>.instance.camera.WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				IHOHMIAONEF.position = HealthBarManager.instance.KPDAPFBIPAI.NormalizedViewportToWorldPoint(point2) + HFMLDDCPOLH;
			}
		}
		HFMLDDCPOLH = IFANIMJLAGF;
	}

	public void NLEKBKHPEJI(string KCHMDALPMBN, float JLHNLGCHKME = 0.5f)
	{
		MGPHEHEAEPA(KCHMDALPMBN, (NPPEJJKFCON)6, JLHNLGCHKME);
	}

	public int BAECLGNMHIO(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	public void IACPOBGHDCA()
	{
		object[] array = new object[FDFLHDPCHCN.Count];
		FDFLHDPCHCN.Keys.CopyTo(array, 0);
		for (int i = 0; i < array.Length; i++)
		{
			if (array[i] is string && array[i] as string != "BattleRewards")
			{
				MGPHEHEAEPA(array[i] as string, NPPEJJKFCON.CardIco, 1923f);
			}
		}
	}

	public void JOENJIPGGEK(string KCHMDALPMBN, float JLHNLGCHKME = 0.5f)
	{
		MGPHEHEAEPA(KCHMDALPMBN, (NPPEJJKFCON)6, JLHNLGCHKME);
	}

	public int AAHJOEILKNG(string KCHMDALPMBN, bool IDEBKDPMPGM, NPPEJJKFCON AGMEHGCOPBM, Color PIOLPEIPAEI)
	{
		if (IDEBKDPMPGM)
		{
			IHOHMIAONEF.gameObject.SetActive(IDEBKDPMPGM);
		}
		HudObjectIndicator2D hudObjectIndicator2D = null;
		if (IDEBKDPMPGM)
		{
			hudObjectIndicator2D = KLALIIMABIA(KCHMDALPMBN, PIOLPEIPAEI, AGMEHGCOPBM);
			if (hudObjectIndicator2D != null)
			{
				return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
			}
			return -1;
		}
		return OEBENBJKEEI(KCHMDALPMBN, AGMEHGCOPBM, 155f);
	}

	public void EPHMECKBGAA(bool IDEBKDPMPGM)
	{
		Show(KCHMDALPMBN, IDEBKDPMPGM, NPPEJJKFCON.CardIco);
		NABOFKMBMKH = IDEBKDPMPGM;
	}

	public void BCKMHLBBBCK()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.CADILLCGODA(DCDEEADIGEH: false);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 673f;
	}

	private void JCNCGJPJDAC()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	public void LICALBFPBLL()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.CADILLCGODA(DCDEEADIGEH: true);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 1246f;
	}

	protected virtual void KECNIEGEDBP()
	{
		base.Awake();
		NGCDDPCAGJB = base.transform;
		LJGGEMAGMHI = HealthBarManager.IPAFHDNJIJP().KPDAPFBIPAI.transform;
		OFGNACJLCPK = Singleton<GameCamera>.instance.transform;
		GameObject gameObject = new GameObject("0.#");
		gameObject.transform.parent = Singleton<GameCamera>.instance.FKFDNNPBOFI.transform;
		IHOHMIAONEF = gameObject.transform;
		if (NABOFKMBMKH)
		{
			KLALIIMABIA(KCHMDALPMBN, Color.white, NPPEJJKFCON.CardIco);
		}
	}

	public void NFBALBAIGJO()
	{
		object[] array = new object[FDFLHDPCHCN.Count];
		FDFLHDPCHCN.Keys.CopyTo(array, 1);
		for (int i = 1; i < array.Length; i++)
		{
			if (array[i] is string && array[i] as string != "ID_GUI_BRONZE")
			{
				OEBENBJKEEI(array[i] as string, NPPEJJKFCON.CardIco, 1730f);
			}
		}
	}

	public int Show(string KCHMDALPMBN, bool IDEBKDPMPGM, NPPEJJKFCON AGMEHGCOPBM)
	{
		if (IDEBKDPMPGM)
		{
			IHOHMIAONEF.gameObject.SetActive(IDEBKDPMPGM);
		}
		HudObjectIndicator2D hudObjectIndicator2D = null;
		if (IDEBKDPMPGM)
		{
			hudObjectIndicator2D = KLALIIMABIA(KCHMDALPMBN, Color.white, AGMEHGCOPBM);
			if (hudObjectIndicator2D != null)
			{
				return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
			}
			return -1;
		}
		return MGPHEHEAEPA(KCHMDALPMBN, AGMEHGCOPBM);
	}

	public int HENDNELEOJD(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	private int MGPHEHEAEPA(string JLEJGKJBDNC, NPPEJJKFCON AGMEHGCOPBM = NPPEJJKFCON.InfoIco, float JLHNLGCHKME = 0.5f)
	{
		OCNCLOOPFNE oCNCLOOPFNE = new OCNCLOOPFNE();
		float delay = ((AGMEHGCOPBM != NPPEJJKFCON.CardIco) ? 0f : 0.1f);
		int result = -1;
		if (FDFLHDPCHCN.Contains(JLEJGKJBDNC))
		{
			oCNCLOOPFNE.JPDFMABBKDI = (HudObjectIndicator2D)FDFLHDPCHCN[JLEJGKJBDNC];
			FDFLHDPCHCN.Remove(JLEJGKJBDNC);
			result = oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.spriteId;
			Bounds bounds = oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.GetBounds();
			JIIKOENDJAF -= bounds.size.x;
			Vector3 vector = new Vector3(0f - JIIKOENDJAF * 0.5f, 0f, 0f);
			IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
			while (enumerator.MoveNext())
			{
				HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
				Bounds bounds2 = hudObjectIndicator2D.GMPADNOGGNL.GetBounds();
				Vector3 pos = vector + new Vector3(bounds2.size.x * 0.5f, 0f, 0f);
				TweenPosition.Begin(hudObjectIndicator2D.gameObject, 0.3f, pos).delay = delay;
				vector += new Vector3(bounds2.size.x, 0f, 0f);
			}
			switch (AGMEHGCOPBM)
			{
			case NPPEJJKFCON.CardIco:
			{
				MPCMGIMIFBK mPCMGIMIFBK = new MPCMGIMIFBK();
				mPCMGIMIFBK.BLDPJKHMBKA = oCNCLOOPFNE;
				mPCMGIMIFBK.JNIJCLMBAMP = TweenAlphaTk2d.Begin(oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.08f, 0f);
				mPCMGIMIFBK.JNIJCLMBAMP.delay = 0f;
				mPCMGIMIFBK.JNIJCLMBAMP.onFinished = mPCMGIMIFBK.LJCDGJKCNEC;
				break;
			}
			case NPPEJJKFCON.EngineerIco:
				TweenPosition.Begin(oCNCLOOPFNE.JPDFMABBKDI.gameObject, 0.2f, oCNCLOOPFNE.JPDFMABBKDI.gameObject.transform.localPosition - new Vector3(0f, bounds.size.y * -0.25f, 0f)).delay = 0f;
				break;
			default:
				TweenPosition.Begin(oCNCLOOPFNE.JPDFMABBKDI.gameObject, 0.2f, oCNCLOOPFNE.JPDFMABBKDI.gameObject.transform.localPosition - new Vector3(0f, bounds.size.y * 6f, 0f)).delay = 0f;
				TweenAlphaTk2d.Begin(oCNCLOOPFNE.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.2f, 0f).delay = 0f;
				break;
			}
			oCNCLOOPFNE.JPDFMABBKDI.DestroyPooled(JLHNLGCHKME, ENGGOAPADCP: true);
		}
		return result;
	}

	private void OnEnable()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	public void Reset()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.DestroyPooled(DCDEEADIGEH: true);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 0f;
	}

	public void RemoveAllIconExceptDeathIco()
	{
		object[] array = new object[FDFLHDPCHCN.Count];
		FDFLHDPCHCN.Keys.CopyTo(array, 0);
		for (int i = 0; i < array.Length; i++)
		{
			if (array[i] is string && array[i] as string != "game-card-ico-backstab")
			{
				MGPHEHEAEPA(array[i] as string);
			}
		}
	}

	public string ConvertSpriteIDtoSpriteName(int INFLHPGMEOB)
	{
		tk2dSpriteDefinition[] spriteDefinitions = Singleton<ObjectPoolDatabase>.instance.JPDFMABBKDI.GMPADNOGGNL.Collection.spriteDefinitions;
		if (INFLHPGMEOB >= 0 && INFLHPGMEOB < spriteDefinitions.Length)
		{
			return spriteDefinitions[INFLHPGMEOB].name;
		}
		return string.Empty;
	}

	private void ODAKCFDIDBM()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	public void DMHHFFJDABC()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public string GHEJGLDHNDD(int INFLHPGMEOB)
	{
		tk2dSpriteDefinition[] spriteDefinitions = Singleton<ObjectPoolDatabase>.instance.JPDFMABBKDI.GMPADNOGGNL.Collection.spriteDefinitions;
		if (INFLHPGMEOB >= 1 && INFLHPGMEOB < spriteDefinitions.Length)
		{
			return spriteDefinitions[INFLHPGMEOB].name;
		}
		return string.Empty;
	}

	public void DJNMPLKPENF(bool IDEBKDPMPGM)
	{
		Show(KCHMDALPMBN, IDEBKDPMPGM, NPPEJJKFCON.InfoIco);
		NABOFKMBMKH = IDEBKDPMPGM;
	}

	public void GLMKGLKCDAL(bool IDEBKDPMPGM)
	{
		Show(KCHMDALPMBN, IDEBKDPMPGM, NPPEJJKFCON.CardIco);
		NABOFKMBMKH = IDEBKDPMPGM;
	}

	private void OMFEMBPCLFK()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	public int Show(string KCHMDALPMBN, bool IDEBKDPMPGM, NPPEJJKFCON AGMEHGCOPBM, Color PIOLPEIPAEI)
	{
		if (IDEBKDPMPGM)
		{
			IHOHMIAONEF.gameObject.SetActive(IDEBKDPMPGM);
		}
		HudObjectIndicator2D hudObjectIndicator2D = null;
		if (IDEBKDPMPGM)
		{
			hudObjectIndicator2D = KLALIIMABIA(KCHMDALPMBN, PIOLPEIPAEI, AGMEHGCOPBM);
			if (hudObjectIndicator2D != null)
			{
				return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
			}
			return -1;
		}
		return MGPHEHEAEPA(KCHMDALPMBN, AGMEHGCOPBM);
	}

	public void KCHOLCGBMBJ()
	{
		if (IHOHMIAONEF != null)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			hudObjectIndicator2D.CADILLCGODA(DCDEEADIGEH: true);
		}
		FDFLHDPCHCN.Clear();
		JIIKOENDJAF = 1823f;
	}

	public void IAHFKGJBNNJ(string KCHMDALPMBN, float JLHNLGCHKME = 0.5f)
	{
		OEBENBJKEEI(KCHMDALPMBN, (NPPEJJKFCON)4, JLHNLGCHKME);
	}

	private void EFADFEJNAEE()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	public int DOLMDMBJJEK(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	public void Hide(string KCHMDALPMBN, float JLHNLGCHKME = 0.5f)
	{
		MGPHEHEAEPA(KCHMDALPMBN, NPPEJJKFCON.None, JLHNLGCHKME);
	}

	private void OnDisable()
	{
		Reset();
	}

	public void ADHKMPOPKBN()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public void LIKJHKNOPEN()
	{
		object[] array = new object[FDFLHDPCHCN.Count];
		FDFLHDPCHCN.Keys.CopyTo(array, 1);
		for (int i = 1; i < array.Length; i++)
		{
			if (array[i] is string && array[i] as string != "ID_CONFIRM_NOTFORQUESTACCOUNTS")
			{
				MGPHEHEAEPA(array[i] as string, NPPEJJKFCON.CardIco, 1390f);
			}
		}
	}

	private void EILGMIPKHEC()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
	}

	private void IPIAJBBBAMJ()
	{
		LICALBFPBLL();
	}

	private HudObjectIndicator2D KLALIIMABIA(string JLEJGKJBDNC, Color PIOLPEIPAEI, NPPEJJKFCON AGMEHGCOPBM = NPPEJJKFCON.InfoIco)
	{
		FHOJNIDPDPP fHOJNIDPDPP = new FHOJNIDPDPP();
		fHOJNIDPDPP.JLEJGKJBDNC = JLEJGKJBDNC;
		if (string.IsNullOrEmpty(fHOJNIDPDPP.JLEJGKJBDNC))
		{
			Debug.Log("trying to add emty indicator " + base.gameObject.name);
		}
		if (FDFLHDPCHCN.Contains(fHOJNIDPDPP.JLEJGKJBDNC))
		{
			fHOJNIDPDPP.JPDFMABBKDI = (HudObjectIndicator2D)FDFLHDPCHCN[fHOJNIDPDPP.JLEJGKJBDNC];
			return fHOJNIDPDPP.JPDFMABBKDI;
		}
		fHOJNIDPDPP.JPDFMABBKDI = (HudObjectIndicator2D)Singleton<ObjectPoolDatabase>.instance.GHGMIFHAOMI.Instantiate(Singleton<ObjectPoolDatabase>.instance.JPDFMABBKDI);
		if (fHOJNIDPDPP.JPDFMABBKDI == null)
		{
			return null;
		}
		fHOJNIDPDPP.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: false);
		fHOJNIDPDPP.JPDFMABBKDI.IGLDDJNNEHE.gameObject.SetActive(value: false);
		fHOJNIDPDPP.JPDFMABBKDI.transform.parent = IHOHMIAONEF;
		fHOJNIDPDPP.JPDFMABBKDI.transform.localScale = Vector3.one;
		fHOJNIDPDPP.JPDFMABBKDI.progress = 1f;
		FDFLHDPCHCN.Add(fHOJNIDPDPP.JLEJGKJBDNC, fHOJNIDPDPP.JPDFMABBKDI);
		fHOJNIDPDPP.JPDFMABBKDI.colour = PIOLPEIPAEI;
		fHOJNIDPDPP.JPDFMABBKDI.SetSprite(fHOJNIDPDPP.JLEJGKJBDNC);
		JIIKOENDJAF += fHOJNIDPDPP.JPDFMABBKDI.GMPADNOGGNL.GetBounds().size.x;
		Vector3 vector = new Vector3(0f - JIIKOENDJAF * 0.5f, 0f, 0f);
		IDictionaryEnumerator enumerator = FDFLHDPCHCN.GetEnumerator();
		while (enumerator.MoveNext())
		{
			OJJPMIGPFCE oJJPMIGPFCE = new OJJPMIGPFCE();
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)enumerator.Value;
			Bounds bounds = hudObjectIndicator2D.GMPADNOGGNL.GetBounds();
			oJJPMIGPFCE.MPHCNMDIPAI = vector + new Vector3(bounds.size.x * 0.5f, 0f, 0f);
			if (hudObjectIndicator2D == fHOJNIDPDPP.JPDFMABBKDI)
			{
				switch (AGMEHGCOPBM)
				{
				case NPPEJJKFCON.CardIco:
				{
					BKPMPBDJBDJ bKPMPBDJBDJ = new BKPMPBDJBDJ();
					bKPMPBDJBDJ.MMALFGIGIPL = fHOJNIDPDPP;
					bKPMPBDJBDJ.ALIKEGIJIHD = oJJPMIGPFCE;
					bKPMPBDJBDJ.GPGMBCEEGEL = oJJPMIGPFCE.MPHCNMDIPAI + new Vector3(0f, 5f, 0f);
					fHOJNIDPDPP.JPDFMABBKDI.transform.localPosition = vector;
					TweenPosition tweenPosition = TweenPosition.Begin(fHOJNIDPDPP.JPDFMABBKDI.gameObject, 0.2f, oJJPMIGPFCE.MPHCNMDIPAI, bKPMPBDJBDJ.GPGMBCEEGEL);
					tweenPosition.delay = 0.23f;
					tweenPosition.onFinished = bKPMPBDJBDJ.LJCDGJKCNEC;
					break;
				}
				case NPPEJJKFCON.EngineerIco:
				{
					Vector3 vector3 = oJJPMIGPFCE.MPHCNMDIPAI + new Vector3(0f, bounds.size.y * -0.25f, 0f);
					fHOJNIDPDPP.JPDFMABBKDI.transform.localPosition = vector3;
					TweenPosition.Begin(fHOJNIDPDPP.JPDFMABBKDI.gameObject, 0.2f, vector3, oJJPMIGPFCE.MPHCNMDIPAI).delay = 0.2f;
					fHOJNIDPDPP.JPDFMABBKDI.MBMIOELEAND.SetSprite("game-engi-progress-bg");
					fHOJNIDPDPP.JPDFMABBKDI.MBMIOELEAND.SortingOrder = -1;
					fHOJNIDPDPP.JPDFMABBKDI.MBMIOELEAND.gameObject.SetActive(value: true);
					break;
				}
				default:
				{
					Vector3 vector2 = oJJPMIGPFCE.MPHCNMDIPAI + new Vector3(0f, bounds.size.y * 6f, 0f);
					fHOJNIDPDPP.JPDFMABBKDI.transform.localPosition = vector2;
					TweenPosition.Begin(fHOJNIDPDPP.JPDFMABBKDI.gameObject, 0.2f, vector2, oJJPMIGPFCE.MPHCNMDIPAI).delay = 0.2f;
					break;
				}
				}
				Color color = fHOJNIDPDPP.JPDFMABBKDI.GMPADNOGGNL.color;
				color.a = 0f;
				fHOJNIDPDPP.JPDFMABBKDI.GMPADNOGGNL.color = color;
				TweenAlphaTk2d.Begin(fHOJNIDPDPP.JPDFMABBKDI.GMPADNOGGNL.gameObject, 0.2f, 1f).delay = 0.2f;
			}
			else
			{
				TweenPosition.Begin(hudObjectIndicator2D.gameObject, 0.2f, oJJPMIGPFCE.MPHCNMDIPAI).delay = 0f;
			}
			vector += new Vector3(bounds.size.x, 0f, 0f);
		}
		return fHOJNIDPDPP.JPDFMABBKDI;
	}

	protected virtual void FGOGGLDAKHL()
	{
		base.Awake();
		NGCDDPCAGJB = base.transform;
		LJGGEMAGMHI = HealthBarManager.OGBIHEFNJGO().KPDAPFBIPAI.transform;
		OFGNACJLCPK = Singleton<GameCamera>.instance.transform;
		GameObject gameObject = new GameObject("ID_CONFIRM_ERROR");
		gameObject.transform.parent = Singleton<GameCamera>.instance.FKFDNNPBOFI.transform;
		IHOHMIAONEF = gameObject.transform;
		if (NABOFKMBMKH)
		{
			KLALIIMABIA(KCHMDALPMBN, Color.white);
		}
	}

	public void GPLDABNOFPM()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public int GGHDIAFACAH(string KCHMDALPMBN, bool IDEBKDPMPGM, NPPEJJKFCON AGMEHGCOPBM)
	{
		if (IDEBKDPMPGM)
		{
			IHOHMIAONEF.gameObject.SetActive(IDEBKDPMPGM);
		}
		HudObjectIndicator2D hudObjectIndicator2D = null;
		if (IDEBKDPMPGM)
		{
			hudObjectIndicator2D = KLALIIMABIA(KCHMDALPMBN, Color.white, AGMEHGCOPBM);
			if (hudObjectIndicator2D != null)
			{
				return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
			}
			return -1;
		}
		return MGPHEHEAEPA(KCHMDALPMBN, AGMEHGCOPBM, 995f);
	}

	protected void CJAHPFMAMKK()
	{
		if (IHOHMIAONEF.gameObject.activeInHierarchy)
		{
			if (BNKCCJEMIAM)
			{
				float num = Vector3.Distance(NGCDDPCAGJB.position, OFGNACJLCPK.position);
				Vector3 vector = new Vector3(776f / num, 921f / num, 1181f / num);
				vector = Vector3.ClampMagnitude(vector, 799f);
				IHOHMIAONEF.localScale = vector;
				HFMLDDCPOLH = Vector3.Scale(IFANIMJLAGF, vector);
			}
			if (CACFIJJILFP)
			{
				Vector3 vector2 = LJGGEMAGMHI.position + new Vector3(1283f, 1504f, HealthBarManager.MCJOOEEIIHI().KPDAPFBIPAI.nearClipPlane + 337f);
				Vector3 point = Singleton<GameCamera>.instance.HEANFGONCBJ().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				point = HealthBarManager.BNDNFHKPDLM().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point);
				point.z = vector2.z;
				IHOHMIAONEF.position = point + HFMLDDCPOLH;
			}
			else
			{
				Vector3 point2 = Singleton<GameCamera>.instance.HEANFGONCBJ().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				IHOHMIAONEF.position = HealthBarManager.KPCLHHDMNDD().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point2) + HFMLDDCPOLH;
			}
		}
		HFMLDDCPOLH = IFANIMJLAGF;
	}

	public int KOIHOMHNFJO(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	private void ENNFAAHDFFA()
	{
		if (NABOFKMBMKH)
		{
			IHOHMIAONEF.gameObject.SetActive(value: true);
		}
		else
		{
			IHOHMIAONEF.gameObject.SetActive(value: false);
		}
	}

	private void NEMBOADCDBK()
	{
		BCKMHLBBBCK();
	}

	protected void JBGDAOIDBGF()
	{
		if (IHOHMIAONEF.gameObject.activeInHierarchy)
		{
			if (BNKCCJEMIAM)
			{
				float num = Vector3.Distance(NGCDDPCAGJB.position, OFGNACJLCPK.position);
				Vector3 vector = new Vector3(874f / num, 104f / num, 1664f / num);
				vector = Vector3.ClampMagnitude(vector, 170f);
				IHOHMIAONEF.localScale = vector;
				HFMLDDCPOLH = Vector3.Scale(IFANIMJLAGF, vector);
			}
			if (CACFIJJILFP)
			{
				Vector3 vector2 = LJGGEMAGMHI.position + new Vector3(1707f, 36f, HealthBarManager.KHMBHIINOFD().KPDAPFBIPAI.nearClipPlane + 1753f);
				Vector3 point = Singleton<GameCamera>.instance.HEANFGONCBJ().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				point = HealthBarManager.KHMBHIINOFD().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point);
				point.z = vector2.z;
				IHOHMIAONEF.position = point + HFMLDDCPOLH;
			}
			else
			{
				Vector3 point2 = Singleton<GameCamera>.instance.HEANFGONCBJ().WorldToNormalizedViewportPoint((!(JHNFPPDCBDK != null)) ? NGCDDPCAGJB.position : JHNFPPDCBDK.position);
				IHOHMIAONEF.position = HealthBarManager.BNDNFHKPDLM().KPDAPFBIPAI.NormalizedViewportToWorldPoint(point2) + HFMLDDCPOLH;
			}
		}
		HFMLDDCPOLH = IFANIMJLAGF;
	}

	public void Disable()
	{
		IHOHMIAONEF.gameObject.SetActive(value: false);
	}

	public int SetProgress(string KCHMDALPMBN, float IDEBKDPMPGM)
	{
		if (FDFLHDPCHCN.Contains(KCHMDALPMBN))
		{
			HudObjectIndicator2D hudObjectIndicator2D = (HudObjectIndicator2D)FDFLHDPCHCN[KCHMDALPMBN];
			hudObjectIndicator2D.progress = IDEBKDPMPGM;
			return hudObjectIndicator2D.GMPADNOGGNL.spriteId;
		}
		return -1;
	}

	public void Show(bool IDEBKDPMPGM)
	{
		Show(KCHMDALPMBN, IDEBKDPMPGM, NPPEJJKFCON.InfoIco);
		NABOFKMBMKH = IDEBKDPMPGM;
	}

	public void IJJKPNLCOIE()
	{
		object[] array = new object[FDFLHDPCHCN.Count];
		FDFLHDPCHCN.Keys.CopyTo(array, 0);
		for (int i = 1; i < array.Length; i++)
		{
			if (array[i] is string && array[i] as string != "FuseSDK: Parsing error in _FriendAdded")
			{
				MGPHEHEAEPA(array[i] as string, NPPEJJKFCON.CardIco, 1806f);
			}
		}
	}

	public void AGJFMINNOBH(string KCHMDALPMBN, float JLHNLGCHKME = 0.5f)
	{
		MGPHEHEAEPA(KCHMDALPMBN, (NPPEJJKFCON)4, JLHNLGCHKME);
	}
}
