public class KIPCEIMNKIK
{
	public enum NEDLKCPPPPC
	{
		None,
		UnitUnlock,
		WeaponUnlock,
		MapUnlock,
		DailyMissionUnlock,
		JoinSquadUnlock,
		CreateSquadUnlock,
		WarCardsUnlock,
		DogTagRefill,
		GoldReceived,
		InstantBattleUnlock,
		WarArenaUnlock
	}

	public NEDLKCPPPPC FJLBLLLEELD;

	public LevelBehaviour IOIKKIIFOCB;

	public WeaponLevelsSetup JMMJHCOKCGG;

	public MapManager.MapEntry JHENMFHHHHC;

	public int EOHOJBOGNAO;

	public static KIPCEIMNKIK LDCCMIIDJML()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK HIKHMFLPKDG()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-51);
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NKCIOMBOFNB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PLPLDGDFNPJ(int HAFMGCFMCPC)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-72);
		kIPCEIMNKIK.EOHOJBOGNAO = HAFMGCFMCPC;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK KNOJMDBHHKA()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK HNBNHEOGACH()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.CreateSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PHCOIIPBHDP()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-22);
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK KOHGICBMLPF()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-81);
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PKHLAAFJKAB(int HAFMGCFMCPC)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)50;
		kIPCEIMNKIK.EOHOJBOGNAO = HAFMGCFMCPC;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PGLKJEOIKCM(int HAFMGCFMCPC)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)100;
		kIPCEIMNKIK.EOHOJBOGNAO = HAFMGCFMCPC;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK KGJHLMHEFJN(WeaponLevelsSetup MBNLFKHLDBH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WeaponUnlock;
		kIPCEIMNKIK.JMMJHCOKCGG = MBNLFKHLDBH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NODEOPGACHL()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WeaponUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NCOEJJIPFEL(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FMICDGPEAJD(int HAFMGCFMCPC)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-107);
		kIPCEIMNKIK.EOHOJBOGNAO = HAFMGCFMCPC;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK IKGNAIDDDFA()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK OIOGHEEIKBB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK JONBEONIIKJ()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DogTagRefill;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NNHBKKDADHB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DailyMissionUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK CIHKHBHPGMH()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)61;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FPMNAKKGOCI()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK JNKPAJHDCIF()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)116;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FKIGCIKCALI()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DailyMissionUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FOOBBGBOFFI()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PIJAAOHOMNE(WeaponLevelsSetup MBNLFKHLDBH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		kIPCEIMNKIK.JMMJHCOKCGG = MBNLFKHLDBH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FJHAAKBODNL(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NONKFDGKBEK(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NGEPMGDDLEC(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK EGEJHDPDGJG()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WeaponUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK GBOGBAGGJME()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarArenaUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK BIMMBOOHMOC(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK JGLMNACNIPI(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK ELEHPJCNFMB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WeaponUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PNJCBLGGJKJ()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.JoinSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK BDNFBLMMADH()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK DBALFHMFJDK(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK HJCLPFEHJGL(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK EBHMGAHJBKB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DailyMissionUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK GHEFJBMMIDE()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.InstantBattleUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK MOLAOFEDMNC()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.JoinSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK IHEOFABOEEH()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DogTagRefill;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK AFMEAFIHGNO(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WarCardsUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK HOEONIOPEOL()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK PCMLHIFBLAP(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.JoinSquadUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK DBIPDGNBEOB(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK CLJHBIJCJJF()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-29);
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK ADDPLMENEEL(MapManager.MapEntry EJPAFCIPDOJ)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.CreateSquadUnlock;
		kIPCEIMNKIK.JHENMFHHHHC = EJPAFCIPDOJ;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK IJAJIOBLNKO()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK MOPBDIKMKHP()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NIIAMBLJLCB(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FJGOKCDLENF()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DailyMissionUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK JGDFKGELMJL()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.WeaponUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK CFNAIOLIKMK()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK EIKEKHEFLBN()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.JoinSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK ELDHJLGKLPB()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)(-122);
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK EFFPPNACHKJ(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK DLJGOJPDLKH(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK HAOAPGMBMFD()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK KHGPDHGJOCO()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = (NEDLKCPPPPC)119;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK OECNMOMEEEL()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.DogTagRefill;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK FDDJAPFGEJA(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK KFNPJGJFFCH()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.MapUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK MJGNIAFBMNF(int HAFMGCFMCPC)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.GoldReceived;
		kIPCEIMNKIK.EOHOJBOGNAO = HAFMGCFMCPC;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK NKCAFKHBANH(LevelBehaviour MIGFKJJIDJH)
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.None;
		kIPCEIMNKIK.IOIKKIIFOCB = MIGFKJJIDJH;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK OIKJBKFJFOJ()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.CreateSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK EFMILALCLFC()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.CreateSquadUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK IKIDLLGCALP()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.UnitUnlock;
		return kIPCEIMNKIK;
	}

	public static KIPCEIMNKIK MGDDFCEJKEP()
	{
		KIPCEIMNKIK kIPCEIMNKIK = new KIPCEIMNKIK();
		kIPCEIMNKIK.FJLBLLLEELD = NEDLKCPPPPC.CreateSquadUnlock;
		return kIPCEIMNKIK;
	}
}
