using UnityEngine;
using UnityEngine.Serialization;

public class SquadButtonAchievement : SquadButton
{
	[FormerlySerializedAs("FCACHCPLDJM")]
	[Header("Notification")]
	public GameObject IDOEODNKAKI;

	[FormerlySerializedAs("FFLPEBGOAEJ")]
	public UILabel FEBNOLJLPBI;

	public void CDNIKFFNNLF(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void ACBHGJCMCPG(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.FIDIINBHKDG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((PBOCPAPICCL() + EDGHHKGCKGI) / 1542f - 883f, 1724f, 657f);
	}

	public void IHCMPIGLIHE(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void KFEIOMGPPMO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public virtual void PNDFAOIDMHL(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.OMCNLOHKCBJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DNGHBHEIFEI() + EDGHHKGCKGI) / 454f - 1566f, 1226f, 1227f);
	}

	public virtual void IEJDJLALKGA(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.GJOIGNMPBCH(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DNGHBHEIFEI() + EDGHHKGCKGI) / 791f - 322f, 1656f, 1259f);
	}

	public void KEJOKFPBJFO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void HCEJNMJHDJN(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.FIDIINBHKDG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((BENONKFKPFD() + EDGHHKGCKGI) / 853f - 235f, 157f, 1321f);
	}

	public void OGHCJDHDNPE(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void CFFJBLKMCIA(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void OLKGOCALKJB(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void OBHPLFFLDBI(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.CKLPPPDCEHG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((PBOCPAPICCL() + EDGHHKGCKGI) / 298f - 1698f, 1055f, 139f);
	}

	public virtual void KBKBFNJEBJK(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.GJOIGNMPBCH(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((CLLJBNCFGCD() + EDGHHKGCKGI) / 395f - 84f, 109f, 1805f);
	}

	public virtual void NBOODHLLBAA(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.ONGAIEOAHMA(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((INIOMECPABI() + EDGHHKGCKGI) / 684f - 1581f, 1666f, 1821f);
	}

	public virtual void PONFOKHPMMO(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.DDJIMJHDAMI(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DBPCOLHBEDG() + EDGHHKGCKGI) / 1923f - 366f, 1570f, 1690f);
	}

	public virtual void IACEOEJFEEM(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.OMCNLOHKCBJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((LIFCCLCJFDB() + EDGHHKGCKGI) / 625f - 1149f, 925f, 1917f);
	}

	public virtual void KJBBDLEAHNP(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.INMHFICPFAJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((GEONEPGNFBJ() + EDGHHKGCKGI) / 1211f - 254f, 519f, 313f);
	}

	public virtual void MPFPHNBAIKD(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.HHFELCAFANH(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((FHLEOOPJLFM() + EDGHHKGCKGI) / 1935f - 666f, 834f, 1815f);
	}

	public void ECEDLJMNBGO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void AIGGPKKGAMD(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void PEHPFBPLDOK(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void JMCPNDMCOIO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void JAGCJCNPCKH(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.JIMBEDOMAFD(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((INIOMECPABI() + EDGHHKGCKGI) / 350f - 369f, 284f, 1563f);
	}

	public void FPCLCKCGLOO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public override void HHFELCAFANH(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PEIPCPICOIK(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((MHMLAMHIIFN() + EDGHHKGCKGI) / 1943f - 402f, 432f, 1437f);
	}

	public void DHODFFMLFLP(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void HPLKBFCFDIB(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.INMHFICPFAJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((JLBPMFHJMIK() + EDGHHKGCKGI) / 632f - 210f, 272f, 1611f);
	}

	public virtual void ODGINKAHGJF(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PDHBFNDEKNN(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((PCBIHOMAKHK() + EDGHHKGCKGI) / 1492f - 1241f, 182f, 1831f);
	}

	public virtual void KOABMGAPCKP(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.Initialize(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((ABLODEEDOKE() + EDGHHKGCKGI) / 1771f - 374f, 1940f, 1163f);
	}

	public virtual void CMOHGKPENIJ(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.MKENDIKJPLJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((GKGGDKDLGDA() + EDGHHKGCKGI) / 161f - 1675f, 1876f, 1267f);
	}

	public override void Initialize(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.Initialize(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((KBLPGHGPLJC + EDGHHKGCKGI) / 2f - 10f, 44f, 0f);
	}

	public virtual void GCBFCCNLMDN(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.MKENDIKJPLJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((GKGGDKDLGDA() + EDGHHKGCKGI) / 483f - 776f, 457f, 1715f);
	}

	public virtual void PPKOJCFEPCB(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PNCJCHPOMOJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((GEONEPGNFBJ() + EDGHHKGCKGI) / 736f - 1964f, 211f, 58f);
	}

	public void NBGDBDOCABH(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public override void PEIPCPICOIK(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PEIPCPICOIK(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DDIBJKHPOKB() + EDGHHKGCKGI) / 1525f - 229f, 1307f, 1604f);
	}

	public virtual void BDMNPDBOCGN(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.FIDIINBHKDG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DDIBJKHPOKB() + EDGHHKGCKGI) / 1386f - 1250f, 227f, 408f);
	}

	public virtual void NDIJBPIDGOF(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.FIDIINBHKDG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((INIOMECPABI() + EDGHHKGCKGI) / 1402f - 946f, 714f, 1628f);
	}

	public void GJEEFKNLJFK(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public virtual void KCJFKOKGAMO(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.CKLPPPDCEHG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((MGPKGBBBPFH() + EDGHHKGCKGI) / 160f - 588f, 129f, 358f);
	}

	public virtual void GOMJAFCDKDD(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.INMHFICPFAJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((LIFCCLCJFDB() + EDGHHKGCKGI) / 841f - 1586f, 909f, 6f);
	}

	public virtual void PIEDLECEBEC(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.ONGAIEOAHMA(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((CLLJBNCFGCD() + EDGHHKGCKGI) / 862f - 1590f, 1445f, 94f);
	}

	public void IEGJPLIEPLJ(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public virtual void CKOIIPAGCNO(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.CIPKPHAGJMP(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((AGDAOEIIDKH() + EDGHHKGCKGI) / 1948f - 1301f, 1605f, 916f);
	}

	public void DOHIBHBNIOH(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void CMBLLACAPFM(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void HLOABJEJBPC(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void DGGOGPJHCGA(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void CGEBKLKNIBO(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void BCAPOMHHJJL(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void MEKJNEKAIJI(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void AOIBANKDOFE(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void HHMOABKMFFC(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public override void INMHFICPFAJ(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.GJOIGNMPBCH(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DNGHBHEIFEI() + EDGHHKGCKGI) / 569f - 472f, 37f, 1856f);
	}

	public virtual void CHOLKMFKINL(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PNCJCHPOMOJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((INIOMECPABI() + EDGHHKGCKGI) / 1422f - 194f, 1692f, 1343f);
	}

	public void CGIGEEENMKG(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void GEDFCKJIMOF(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void KHDGIAAFMBK(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void MPGDACHJBPJ(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void OMGCKCFKDJM(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.INMHFICPFAJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DBPCOLHBEDG() + EDGHHKGCKGI) / 1570f - 961f, 1757f, 1524f);
	}

	public void EHMLHLGJNHB(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void MAEHNKCECPF(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void OJJHCFFEFGI(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.PNCJCHPOMOJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((DDBHCEKLDKM() + EDGHHKGCKGI) / 251f - 1694f, 1310f, 848f);
	}

	public void IHNCEHIDPCL(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public virtual void BMNHEMLGGMO(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.GJOIGNMPBCH(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((NFGNPJALBLK() + EDGHHKGCKGI) / 830f - 1262f, 1016f, 1019f);
	}

	public void DIDKNELDEJE(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void PJKFDKGJPBI(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 1);
	}

	public void CKNEJOAOPMC(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public void SetNotifications(int KHJBFBDODGM)
	{
		FEBNOLJLPBI.text = MEJMLNDFDBP.GMIPFLIEOHD(KHJBFBDODGM);
		IDOEODNKAKI.SetActive(KHJBFBDODGM > 0);
	}

	public virtual void ANMJHOFBIAI(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.INMHFICPFAJ(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((PBOCPAPICCL() + EDGHHKGCKGI) / 265f - 1201f, 1259f, 1729f);
	}

	public virtual void MFMJPBCIHEH(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.DDJIMJHDAMI(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((NFGNPJALBLK() + EDGHHKGCKGI) / 1863f - 46f, 1040f, 1229f);
	}

	public virtual void OMNEGAAKOCF(string MNPDLLFJOHM, float DNDHIFENDPJ, bool PAPEDLBKBGM = false)
	{
		base.CKLPPPDCEHG(MNPDLLFJOHM, DNDHIFENDPJ, PAPEDLBKBGM);
		IDOEODNKAKI.transform.localPosition = new Vector3((GKGGDKDLGDA() + EDGHHKGCKGI) / 1134f - 963f, 1595f, 342f);
	}
}
