using UnityEngine;

public class TweenLeague : UITweener
{
	public MAPGBEOOFLL OEIICEJPGKI;

	public MAPGBEOOFLL IIMDKHJAJGO;

	private LeagueArcGuiElement DHKEDJEKJPN;

	protected virtual void PBDFKCLOAKC(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void LFJGEEDJGME(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void AKKKDIBLICM()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void PJEMCLFLGBL()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague HBHMEFGMNNN(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 352f)
		{
			tweenLeague.Sample(333f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague MKFDJJCJMPN(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 498f)
		{
			tweenLeague.Sample(1111f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague NFCEEJODFMO(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 214f)
		{
			tweenLeague.Sample(868f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void Awake()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague HEOAOMCHOJG(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 26f)
		{
			tweenLeague.Sample(1936f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague OBHFCFEKAPG(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 533f)
		{
			tweenLeague.Sample(255f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void PDLNCCFMDFG()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague FMGPCIGJIBP(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 341f)
		{
			tweenLeague.Sample(1398f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void KKBCJKEDJBL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague AHHCDBHEBEF(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 939f)
		{
			tweenLeague.Sample(1601f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void FHHHBLCNGKE(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void EJNJCILPBEC()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void PHGKLGLOLPL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague LMNBPJEACEA(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 948f)
		{
			tweenLeague.Sample(1700f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague FOPAOKJDKJP(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1972f)
		{
			tweenLeague.Sample(781f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void EJDGJGHOFHK(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void AKHKMOOJOGC()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void CADJAJCEFCF()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague FFIHIGPINBB(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1092f)
		{
			tweenLeague.Sample(1096f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague OHHMFLKGKBP(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 562f)
		{
			tweenLeague.Sample(1647f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague HGBKLMHAGBF(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 835f)
		{
			tweenLeague.Sample(1565f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague CPHOAGPKAMB(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 968f)
		{
			tweenLeague.Sample(923f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void BGMHIBPMEBP(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void CALILPEEAMB()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void EGMBELHFNMO(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague HNEAGHHABGL(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 575f)
		{
			tweenLeague.Sample(649f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void NMHFGMNKLPG(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void EOKFCPBJHFC(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void IEOCAOCKMGB(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague EBHBONAFMLA(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 259f)
		{
			tweenLeague.Sample(1178f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague AJJFGBOKPOL(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 444f)
		{
			tweenLeague.Sample(584f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void LMNINFNNGKL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void AKPDFHFHGEJ(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void OMLINILCBDL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void EBPDPEOHPOB(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void FIGOGIMJIIN()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague KKIGNHJHLGD(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 678f)
		{
			tweenLeague.Sample(669f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void EEDOMDHMGLA(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected override void OnUpdate(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void AKHJEGBPEDN(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague BIMCIIOMBMB(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 169f)
		{
			tweenLeague.Sample(542f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void DOGHJOONHLD(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void OMDILMPFKII()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void OAFGNHCMJMB(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague JCLGAFGBMDC(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 621f)
		{
			tweenLeague.Sample(696f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague IPAMGPAPCMA(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1380f)
		{
			tweenLeague.Sample(1958f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague ALCKOMNFIFH(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 215f)
		{
			tweenLeague.Sample(1609f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague JPJPAJEBNPK(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1892f)
		{
			tweenLeague.Sample(131f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void EEDNGNLEMAO(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void IFLMKBDLENF(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague MDBMAINKPKG(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 126f)
		{
			tweenLeague.Sample(397f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	private void DCKJHAILENK()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague KAEBPEJBJCI(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1180f)
		{
			tweenLeague.Sample(1926f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void PKJFBGDNKLB(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void IOAEHDJGBJC()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague IAGLEIPAIOB(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1191f)
		{
			tweenLeague.Sample(1647f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void AJIGPEGLLLF(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void PIIFEPFCOJF()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void POCCFAMHECP(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void CMJLPFKEEIJ(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void CEHHMFLDANA(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void PBIJLBHDFOK()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void HMBBGNKFNCK()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague CHFFALDIKCI(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 283f)
		{
			tweenLeague.Sample(1168f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void OHHLNKPIHBH()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague IPOEOHBLGMJ(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 744f)
		{
			tweenLeague.Sample(1842f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void FFBBKELEEIF()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void GEPHFAECCII()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague LJBDCPDBOMM(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 10f)
		{
			tweenLeague.Sample(1391f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague DEPELDAKMAJ(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 723f)
		{
			tweenLeague.Sample(1313f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void MIKACHBFCGF(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague IECHDKECJAB(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 316f)
		{
			tweenLeague.Sample(1520f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void KKPDLAPBPHG(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void NOOLAIEENFB()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague AKNNLALFDIJ(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 613f)
		{
			tweenLeague.Sample(1817f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague OGHELDLHAMK(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1008f)
		{
			tweenLeague.Sample(880f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague CABGNGMLIEK(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 67f)
		{
			tweenLeague.Sample(524f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	private void MEBEHLLPMPK()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	public static TweenLeague PMLCBMLFOAF(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 301f)
		{
			tweenLeague.Sample(1714f, isFinished: true);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	protected virtual void AJKJBMHEPDM(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague DBPOCEIDEAE(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1807f)
		{
			tweenLeague.Sample(559f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void KODJIPJGFPB()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void KIBMKFGELKG(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void CHLPJOCMMPD()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void BNJBFLPBONL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void OJODNDNPLBL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void FLAFCDGMJCP(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague FFEEMJJIMOE(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1563f)
		{
			tweenLeague.Sample(1227f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague IHIEDPNEJFE(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 185f)
		{
			tweenLeague.Sample(1253f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	public static TweenLeague LCBLJBAJGED(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 795f)
		{
			tweenLeague.Sample(541f, isFinished: false);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void JFNAAAFJDOF(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void GPENDOJKGKL(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = true;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	private void CFGDCEOLKJG()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void MLBAFICPECE()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	private void LLKBLBNEBPA()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}

	protected virtual void KEPEHFLOBPN(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague MDKDEJJDHKM(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 1610f)
		{
			tweenLeague.Sample(1742f, isFinished: false);
			tweenLeague.enabled = true;
		}
		return tweenLeague;
	}

	public static TweenLeague Begin(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 0f)
		{
			tweenLeague.Sample(1f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	protected virtual void HAFPIEANDHE(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.SetArrow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.EDNPIOIBFOJ(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE, AJNINHIKAFC: true);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	protected virtual void FEPCGPEOMAG(float KDJCCDGMEJL, bool DEHAOIKPFFA)
	{
		int cJLGKBLPDHI = (int)Mathf.Lerp(OEIICEJPGKI.MPHCNMDIPAI, IIMDKHJAJGO.MPHCNMDIPAI, KDJCCDGMEJL);
		int fFHHEHHFOKJ = (int)Mathf.Lerp(OEIICEJPGKI.GEIONCLKAGF, IIMDKHJAJGO.GEIONCLKAGF, KDJCCDGMEJL);
		DHKEDJEKJPN.KMEEGJFHJBB(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.SetGlow(cJLGKBLPDHI, OEIICEJPGKI.LHPLLCNGBBL, OEIICEJPGKI.BMNDININJCE);
		DHKEDJEKJPN.JDDDDOBAFEO.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ);
		if (DEHAOIKPFFA)
		{
			DHKEDJEKJPN.HCPFFMFGNEL.repositionNow = false;
		}
		if (OEIICEJPGKI.CIKCEPEFPFG)
		{
			int fFHHEHHFOKJ2 = (int)Mathf.Lerp(OEIICEJPGKI.HFGPOFPHFIL, IIMDKHJAJGO.HFGPOFPHFIL, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ2);
		}
		if (OEIICEJPGKI.CEHILCHIDJB)
		{
			int fFHHEHHFOKJ3 = (int)Mathf.Lerp(OEIICEJPGKI.OAEOOEPJCOG, IIMDKHJAJGO.OAEOOEPJCOG, KDJCCDGMEJL);
			DHKEDJEKJPN.HFGPOFPHFIL.text = MEJMLNDFDBP.GMIPFLIEOHD(fFHHEHHFOKJ3);
		}
	}

	public static TweenLeague OGOADPAGHJH(LeagueArcGuiElement PJFGCMCKMJF, float DNDHIFENDPJ, MAPGBEOOFLL FOKOHCIEPML, MAPGBEOOFLL KOPLEOAGNJC)
	{
		TweenLeague tweenLeague = UITweener.Begin<TweenLeague>(PJFGCMCKMJF.gameObject, DNDHIFENDPJ);
		tweenLeague.OEIICEJPGKI = FOKOHCIEPML;
		tweenLeague.IIMDKHJAJGO = KOPLEOAGNJC;
		tweenLeague.DHKEDJEKJPN = PJFGCMCKMJF;
		if (DNDHIFENDPJ <= 855f)
		{
			tweenLeague.Sample(959f, isFinished: true);
			tweenLeague.enabled = false;
		}
		return tweenLeague;
	}

	private void EALPHOPMAMP()
	{
		if (DHKEDJEKJPN == null)
		{
			DHKEDJEKJPN = GetComponent<LeagueArcGuiElement>();
		}
	}
}
