using System.Collections.Generic;

namespace Google2u
{
	public class PlayerVisuals : Google2uComponentBase, IGoogle2uDB
	{
		public enum rowIds
		{
			CAMOS_DEFAULT,
			CAMOS_MACHINEGUNNER,
			CAMOS_PARA,
			CAMOS_ALIEN,
			CAMOS_COWBOY,
			CAMOS_NINJA,
			CAMOS_SCIENTIST,
			CAMOS_SUITGUY,
			CAMOS_ZOMBIE,
			CAMOS_SARAH,
			CAMOS_OREN,
			CAMOS_RAPPER,
			CAMOS_RAMBO,
			CAMOS_SPECOPS,
			CAMOS_MADMAX,
			CAMOS_COMMANDO,
			CAMOS_DUSTY,
			BANDS_EMPTY,
			BANDS_CRITICAL_0,
			BANDS_CRITICAL_1,
			BANDS_DAMAGE_0,
			BANDS_DAMAGE_1,
			BANDS_HEALTH_0,
			BANDS_HEALTH_1,
			HEAD_EMPTY,
			HEAD_CIGAR,
			HEAD_SUNGLASSES,
			HEAD_MASK_ROCKET,
			HEAD_GLASSES_SNIPER,
			HEAD_BB_GLASSES,
			HEAD_BEARD,
			HEAD_SANTABEARD,
			HEAD_CLOWN,
			HEAD_EYE_PATCH,
			HEAD_GOOGLES,
			HEAD_LENNON,
			HEAD_LOS_SANTOS,
			HEAD_REBREATHER,
			HEAD_WEST,
			HEAD_ENGINEERELITEGLASSES,
			HEAD_GRENADIERELITEMASK,
			HEAD_GRENADIERMASK,
			HEAD_MACHINEGUNNERBAND,
			HEAD_MACHINEGUNNERGLASSES,
			HEAD_HIPSTERGLASSES,
			HEAD_STEAMPUNKGLASSES,
			HEAD_MADMAXGLASSES,
			HEAD_ROCKETLAUNCHERMASK,
			HEAD_SCIFIGRENADIERMASK,
			HEAD_SWATGLASSES,
			HEAD_BAND,
			HELMETS_SANTA,
			HELMETS_EMPTY,
			HELMETS_DEFAULT,
			HELMETS_BLUEBARRET,
			HELMETS_BLACKCAP,
			HELMETS_EAGLE,
			HELMETS_FOOTBALL,
			HELMETS_HAT,
			HELMETS_CYLINDER,
			HELMETS_MINIGUNHAT,
			HELMETS_HEADCOVER,
			HELMETS_HORNS,
			HELMETS_JASON,
			HELMETS_PUNK,
			HELMETS_SKULL,
			HELMETS_SPARTAN,
			HELMETS_ASSAULT,
			HELMETS_COWBOYHAT,
			HELMETS_ENGINEERELITE,
			HELMETS_ENGINEER,
			HELMETS_FLAMETHROWER,
			HELMETS_GRENADIERELITE,
			HELMETS_GRENADIER,
			HELMETS_MADMAX,
			HELMETS_ROCKETLAUNCHERELITE,
			HELMETS_ROCKETLAUNCHER,
			HELMETS_ELFHAT,
			HELMETS_SCIFIMINIGUNNER,
			HELMETS_SCIFIMINIGUNNERELITE,
			HELMETS_SHOTGUNNER,
			HELMETS_SWATELITE,
			HELMETS_SWATHAT,
			HELMETS_PROPHAT,
			CAMOS_BRUCELEE,
			CAMOS_ASSAULT,
			CAMOS_ELITEENGINEER,
			CAMOS_ELITEPARATROOPER,
			CAMOS_ROCKETLAUNCHER,
			CAMOS_SCIENTIST2,
			HELMETS_VIETNAM,
			HELMETS_CROWNBRONZE,
			HELMETS_CROWNSILVER,
			HELMETS_CROWNGOLD,
			HEAD_HANNIBAL,
			HEAD_PLAGUE,
			HELMETS_PAPERBAG,
			CAMOS_GIRLBLONDE,
			HELMETS_PICKELHAUBE,
			HEAD_GASMASK,
			HEAD_SAMURAIMASK,
			HELMETS_SAMURAI,
			HELMETS_AVIATOR,
			HEAD_GOOGLYEYES,
			HEAD_BUNNY,
			HEAD_VENETIANBUNNY,
			HELMETS_EGGSHELL,
			HELMETS_OFFICERCAP,
			HELMETS_SPECIALFORCES,
			HEAD_STEAMPUNK_EYE_PATCH,
			HEAD_SILLYFACE,
			HELMETS_SHERIFFHAT,
			HELMETS_PUMPKINJACK,
			HELMETS_SUGARSKULL,
			HEAD_MUSTACHE,
			HELMETS_TURKEYHAT,
			HELMETS_PILGRIMHAT,
			HELMETS_PARTYHAT,
			HELMETS_REINDEERSANTLERS,
			HELMETS_SNOWMANHAT,
			CAMOS_DUSTYSANTA,
			CAMOS_VIETNAMMACHINEGUNNER,
			HEAD_VALENTINESGLASSES,
			CAMOS_CHINESEGIRL,
			HEAD_CARNIVALMASK,
			HEAD_CANDY,
			HEAD_REINDEERGLASSES,
			HELMETS_DRAGONMASK,
			HELMETS_CAKEHAT,
			HELMETS_BACKBONE,
			HEAD_FACESHIELD,
			HEAD_INSTINCTVISOR,
			HELMETS_INSTINCTMASK,
			CAMOS_INSTINCTMALE,
			CAMOS_INSTINCTFEMALE,
			CAMOS_SILVERSTRIKEMALE,
			CAMOS_SILVERSTRIKEFEMALE,
			HELMETS_OXMASK,
			HELMETS_RIKOHELMET,
			HEAD_RIKOMASK,
			HELMETS_CZECH,
			HELMETS_SLOVAK,
			HEAD_SPECTERVISOR,
			HEAD_OVERSEERVISOR,
			HELMETS_TIGERMASK,
			HEAD_SURGEMASK,
			HEAD_SURGEMASKELITE
		}

		public string[] rowNames;

		public Dictionary<string, int> namesToIndex;

		public List<PlayerVisualsRow> Rows;

		public override bool haveDictionary => false;

		public override int getColumnCount => 0;

		public override int GetRowIndex(string rowID)
		{
			return 0;
		}

		public override void AddRowGeneric(List<string> input)
		{
		}

		public override int AddBlanckRowGeneric(string rowId)
		{
			return 0;
		}

		public override int AddRowGenericRealyAdd(List<string> input)
		{
			return 0;
		}

		public override void CheckRows(List<string> rowIds)
		{
		}

		public override void Clear()
		{
		}

		public IGoogle2uRow GetGenRow(string in_RowString)
		{
			return null;
		}

		public IGoogle2uRow GetGenRow(rowIds in_RowID)
		{
			return null;
		}

		public PlayerVisualsRow GetRow(rowIds in_RowID)
		{
			return null;
		}

		public PlayerVisualsRow GetRow(string in_RowString)
		{
			return null;
		}
	}
}
